### ISSUE TITLE
Converter auto-register itself to ConversionService [SPR-6415]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#11081]
**[Liu, Yinwei David](https://jira.spring.io/secure/ViewProfile.jspa?name=veaven)** opened **[SPR-6415](https://jira.spring.io/browse/SPR-6415?redirect=false)** and commented

Hi,
Currently, we can only register a CustomConverter by configuring it in Spring configuration file in Spring 3.0.0.RC2. However, we want the ability which allows all Converters to register themselves into the global ConversionService by default.

In Spring 3.0.RC2, we can use ConversionServiceFactoryBean to create a ConversionService in Spring config. If people have a lot of Converter in the infrastructure libraries, they need to register all customized converters by themself, so we think it would be good if Converter itself can register itself.

---

**Affects:** 3.0 RC1, 3.0 RC2

4 votes, 8 watchers

**Comment by bclozel** [comment]
This approach requires more fine-grained knowledge of the application.
I think this has been covered by Spring Boot for [configuration properties](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion) and [web data binding](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-web-applications.spring-mvc.auto-configuration).

This looks like a general auto-configuration feature rather than a Spring Framework concern. I'm closing this issue as a result.
