### ISSUE TITLE
@Async and @PostConstruct don't work in combination [SPR-7560]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#12217]
**[Joern Barthel](https://jira.spring.io/secure/ViewProfile.jspa?name=jbar)** opened **[SPR-7560](https://jira.spring.io/browse/SPR-7560?redirect=false)** and commented

## How to reproduce

Annotate a void public method with `@Async` and `@PostConstruct`. Setup an application context with the appropriate task:executor infrastructure to make `@Async` work.

### Excepted behavior

`@PostConstruct` method should a) be executed in a different thread and b) not block the initialization of the application context.

### Actual behaviour

`@PostConstruct` method is executed in main Thread and blocks. After method returns Spring bails with an exception:

```
NoSuchBeanDefinitionException: No matching bean of type [<omitted>] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {} 
```

## Workaround

Only known workaround atm. is to manually execute the logic in the `@PostConstruct` method in a `Thread`.

### Motivation

The application has quite a few state transfers which need to run initially and can easily be parallelized. Business logics accesses the result of those state transfers not necessarily immediately after initialization. Access to asynchronously generated values is easy using patterns such as Google Guava's `ValueFuture<T>`.

---

**Affects:** 3.0 GA

**Issue Links:**
- #12218 Document limitations of @Async annotation

3 votes, 8 watchers

**Comment by inad9300** [comment]
Could someone confirm whether this feature has been added or not? It is unclear why was the issue closed.

**Comment by sbrannen** [comment]
As stated in https://github.com/spring-projects/spring-framework/issues/12217#issuecomment-453715845, this issue was bulk closed as "outdated" and "unresolved", which means the requested feature was not implemented.

**Comment by inad9300** [comment]
It felt like an automatic comment, that's why I wasn't sure. Also, I thought it wasn't so unlikely that something had been done about this problem but wasn't linked to this GitHub issue, given that it was raised almost 10 years ago.

**Comment by baltiyskiy** [comment]
Can we please reopen it? @heanssgen-troy is right - there are cases where you want to load some data and consider bean constructed only when it's done., and after that use only synchronous API. Otherwise, asynchronicity "creeps" out into all the code that works with that bean, which is very intrusive.

**Comment by snicoll** [comment]
>  Otherwise, asynchronicity "creeps" out into all the code that works with that bean, which is very intrusive.

It doesn't have to be. You can have a separate component that calls this API from the same package for startup purposes or inject an `AsyncTaskExecutor` to execute your task asynchronously.

**Comment by baltiyskiy** [comment]
After some consideration, I don't agree with @ehanssgen-troy. In the example posted, you could simply replace return type of `@PostConstruct` method to `void` and everything would work. I think that `@Async @PostConstruct` should really postpone the creation of all dependent beans until the future is completed. 

@snicoll There should be a sync-async barrier somewhere anyway. And I think this is the case where Spring would be extremely useful by essentially hiding this barrier from the application code.

In our case, we have an important component (feature flags!) that reads these flags on startup. We want logic that depends on this flag to work only when the flags are loaded, in a synchronous and non-blocking manner. Almost all our code is in non-blocking context; sometimes it is asynchronous (Kotlin `suspend` functions or `CompletionStage`), but sometimes not, and I don't want the latter code to be forced to be asynchronous just because it needs to read a feature flag. 
Also, we don't really want to block inside `@PostConstruct` because it will postpone the initialization of other beans that do not depend on this bean, and also because sometimes we might be doing this in a non-blocking context (inside a ForkJoinPool).

So, it comes down to this:
- Initialization should be asynchronous and non-blocking,
- But we want to be able to use the results of the initialization in non-blocking, synchronous manner.

> So this might lead to situations where one can call ApplicationContext.getBean(…) getting a reference to a bean that is not completely initialized.

What happens when `@PostConstruct` blocks for a long period of time and one uses `getBean()` from another thread? I think the behaviour should be the same in this case too until the future is completed.
