### ISSUE TITLE
Clear AspectJExpressionPointcut cache when it is no longer used

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#12334]
**[Jon Seymour](https://jira.spring.io/secure/ViewProfile.jspa?name=jonseymour)** opened **[SPR-7678](https://jira.spring.io/browse/SPR-7678?redirect=false)** and commented

I have been doing a heap dump analysis of a 64bit JVM that uses Java5, Spring and AspectJ point cuts.

I have observed the following:

* the number of ReflectionWorlds in the JVM is ~= the number of PointCuts declared to Spring (P)
* the number of World.TypeMap entries (T) is proportional to the number of types reachable from declarations of beans that Spring can instantiate (T)
* the number of ReferenceType instances in the JVM is ~= k * the number of World.TypeMap entries

In my case, P is 15, k is observed to be 10 and T is around 4,500.

In other words, the JVM contains 15 * 10 * 5,000 ~ 675,000 ReferenceType objects!

Given that the system only has 4,500 types in it, it seems somewhat absurd that there should be 675,000 ReferenceType objects, but this is what the measurements show.

Is it really necessary that AspectJ creates 10 ReferenceType objects per type?

Is it really necessary that each PointCut introduced by Spring has its own ReflectionWorld?

If these two issues could be fixed, the number of ReferenceType objects consumed by this application could be reduced by a factor of 150 which is not an insignificant saving.

---

**Affects:** 3.0.5

**Attachments:**
- [issue-7678-2.5.6-0001.patch](https://jira.spring.io/secure/attachment/17300/issue-7678-2.5.6-0001.patch) (_9.69 kB_)
- [one-reflection-world-per-factory.patch](https://jira.spring.io/secure/attachment/17288/one-reflection-world-per-factory.patch) (_10.09 kB_)
- [spring.patch](https://jira.spring.io/secure/attachment/17268/spring.patch) (_5.90 kB_)

3 votes, 5 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by dmak** [comment]
I have discovered that `AspectJExpressionPointcut` holds thousands of entries in field `shadowMatchCache`. The given cache is not capped, so potentially (however highly unlikely) can cause OOM during startup. The possible improvement could be that `AspectJExpressionPointcut` listens on context events e.g. is `ApplicationListener` and empties the cache once the context is started.

![image](https://user-images.githubusercontent.com/366965/160114010-9440dc88-b706-4690-822b-557eef2339e3.png)

**Comment by heowc** [comment]
I'm writing a spring integration test, and during this process, as @dmak said, I could see that the `shadowMatchCache` is getting very large. Is there a fundamental solution? Or is there a way to initialize it in tests?

**Comment by sbrannen** [comment]
Reopening to investigate whether we can improve something here for Spring Framework 6.1.

**Comment by sbrannen** [comment]
> Or is there a way to initialize it in tests?

There is currently no API for resetting or clearing that cache.

However, if you have access to the instance of `AspectJExpressionPointcut` in question, you could use reflection to access the `shadowMatchCache` field and invoke `clear()` on it.

**Comment by heowc** [comment]
I've tried calling init in the form:

```java
public class ShadowMatchCacheCleanupExtension implements AfterAllCallback {
  @Override
  public void afterAll(ExtensionContext context) {
    final ApplicationContext applicationContext = SpringExtension.getApplicationContext(context);
    final AnnotationAwareAspectJAutoProxyCreator creator = applicationContext.getBean(AnnotationAwareAspectJAutoProxyCreator.class);
    final BeanFactoryAspectJAdvisorsBuilder builder = (BeanFactoryAspectJAdvisorsBuilder) ReflectionTestUtils.getField(creator, "aspectJAdvisorsBuilder");
    final Map<String, List<Advisor>> advisorsCache = (Map<String, List<Advisor>>) ReflectionTestUtils.getField(builder, "advisorsCache");
    advisorsCache.values()
                 .stream()
                 .flatMap(Collection::stream)
                 .filter(it -> it instanceof InstantiationModelAwarePointcutAdvisor)
                 .map(it -> (AspectJExpressionPointcut) ReflectionTestUtils.getField(it, "declaredPointcut"))
                 .map(it -> (Map<Method, ShadowMatch>) ReflectionTestUtils.getField(it, "shadowMatchCache"))
                 .forEach(Map::clear);
  }
}
````

This was pretty useful

**Comment by dmak** [comment]
> There is currently no API for resetting or clearing that cache.

Would it make more sense to reset the cache after Spring context is loaded? Or it is also used after all advisors are wired?

**Comment by sbrannen** [comment]
> This was pretty useful

@heowc, yes, I imagine that proved rather useful.

Kudos for figuring out how to jump through all of the reflection hoops to achieve that. 👍

**Comment by sbrannen** [comment]
> Would it make more sense to reset the cache after Spring context is loaded? Or it is also used after all advisors are wired?

@dmak, those are precisely some of the topics we will investigate in the 6.1 time frame.

**Comment by snicoll** [comment]
Based on the input of @heowc, I did look at making this available in one form or the other. This turns out to be quite complicated as there are several layers of indirection before hitting the instance that has the cache to clear. There is also a consideration of actually clearing the cache at the right time.

All this point in the direction of a first class concept in the `ApplicationContext`, available in `spring-beans` (since Spring AOP does not depend on the context). It could be an interface (name TBD) that a bean can implement to opt-in for being able to clear its cache once the context has refreshed. Ideally such interface would not be tied to the concept of bean so that non-beans can easily opt-in for it as well. Typically, `BeanFactoryAspectJAdvisorsBuilder` would implement it and cascade on its `advisorsCache`. And ditto for the `Advisor` that has a reference to a pointcut that needs its cache cleared.

Another reason for this to be a first class concept is that we may want to actually disable clearing the cache. I can see how Spring Boot Devtools would disable it to prevent advisors to be recomputed over and over again when the context restart.

Perhaps this could be a generalization of `AbstractApplicationContext#clearResourceCaches` that's currently invoked in `finishRefresh`?

paging @jhoeller for feedback.

**Comment by snicoll** [comment]
> Another reason for this to be a first class concept is that we may want to actually disable clearing the cache. I can see how Spring Boot Devtools would disable it to prevent advisors to be recomputed over and over again when the context restart.

This was a bogus analysis as the close of the context actually discards the cache anyway. 

We've brainstormed and it would nice if we could get away without a first class concept to it. We're considering to rather move AspectJExpressionPointcut's cache to a more central place that we can easily clear, and/or possibly make it static (additionally keyed by the expression) so that it can be cleared from anywhere.

**Comment by snicoll** [comment]
The cache has been rationalized in `ShadowMatchUtils` and is cleared automatically once the context has refreshed and on shutdown.

@heowc you should be able to remove that code there when upgrading to Spring Framework 6.2
