### ISSUE TITLE
Decide what to do with `@IfProfileValue` [SPR-7754]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#12410]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-7754](https://jira.spring.io/browse/SPR-7754?redirect=false)** and commented

Now that `@Profile` (and "profile" generally) has a meaning in the framework, the old test support for detecting system properties looks like it has an awkward name.  In Spring 3.1 terms, what `@IfProfileValue` does is detect key-value pairs in the Environment (not profiles).

One simple thing we should definitely do is add a ProfileValueSource that can pull values from the Environment.

More radically, maybe we could rename `@IfProfileValue`(name=,value=) to `@Environment`(key=,value=).

Another suggestion is that we could provide a way to activate profiles declaratively for tests or test classes.  Something I've been playing with is this (new components ProfileSuite and `@ActiveProfile`):

```java
@RunWith(Suite.class)
@SuiteClasses({ HsqlTest.class, DerbyTest.class })
public class JdbcDaoIntegrationTests {

	@RunWith(ProfileSuite.class)
	@SuiteClasses({ JdbcSearchableJobInstanceDaoTests.class, JdbcSearchableJobExecutionDaoTests.class,
			JdbcSearchableStepExecutionDaoTests.class })
	public static abstract class BaseTest {
	}

	@ActiveProfile("hsql")
	public static class HsqlTest extends BaseTest {
	}

	@ActiveProfile("derby")
	public static class DerbyTest extends BaseTest {
	}

}
```

It says: run these three test classes twice each, once with profile "hsql" and once with profile "derby".  This has the nice feature that `@EnvironmentValue` can still be honoured inside the individual tests (per method).

---

**Issue Links:**
- #13625 SystemProfileValueSource is not very compatible with the new 3.1 default system property profiles
- #12615 TestContext framework should support declarative configuration of bean definition profiles
- #13622 Allow overriding `@ActiveProfiles` in test classes with system property
- #16300 Introduce annotation to skip test based on active Spring profile

6 votes, 7 watchers

**Comment by sbrannen** [comment]
Since `@IfProfileValue` is specific to our JUnit 4 support and since JUnit 4 does not provide an extension mechanism for enabling/disabling tests, we have decided to leave the `@IfProfileValue` in place as-is as long as we continue to support JUnit 4.

Regarding other topics discussed in this issue, many of the requested features and/or proposals are already possible with JUnit Jupiter (in JUnit 5) and Spring's support for JUnit Jupiter.

- JUnit Jupiter provides numerous built-in annotations for [Conditional Test Execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution) such as `@DisabledIfSystemProperty`, `@EnabledIfEnvironmentVariable`, etc.
- Users can also implement their own custom `ExecutionCondition`.
- Spring provides [`@EnabledIf`](https://docs.spring.io/spring-framework/reference/testing/annotations/integration-junit-jupiter.html#integration-testing-annotations-junit-jupiter-enabledif) and [`@DisabledIf`](https://docs.spring.io/spring-framework/reference/testing/annotations/integration-junit-jupiter.html#integration-testing-annotations-junit-jupiter-disabledif) annotations that are based on SpEL expressions -- which can optionally access beans and the `Environment` in the `ApplicationContext`.

In light of the above, I am closing this issue.
