### ISSUE TITLE
Parallel bean initialization during startup [SPR-8767]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#13410]
**[Tomasz Nurkiewicz](https://jira.spring.io/secure/ViewProfile.jspa?name=nurkiewicz)** opened **[SPR-8767](https://jira.spring.io/browse/SPR-8767?redirect=false)** and commented

Spring should provide a way (possibly a `BeanFactory` with a different `ConfigurableListableBeanFactory#preInstantiateSingletons` implementation) to initialize singleton non-lazy beans on startup in parallel using a thread pool. This could significantly reduce startup (and maybe shutdown) time by creating and initializing independent beans concurrently.

The algorithm is pretty simple in principle. Whereas the normal bean factory creates beans in single thread in rather random order, this implementation should:

1. Find all bean definitions that don't have any unresolved dependencies.
2. Schedule creation of each bean found in 1. in a separate concurrent task to allow parallel creation
3. When any of the tasks scheduled in 2. is completed go to 1.

The algorithm stops when all beans are created.

Implementation notes:
* circular dependencies might require extra care
* bean factory should create a thread pool with configurable number of threads and shut it down after all beans are created

---

**Affects:** 3.1 RC1

**Reference URL:** http://forum.springsource.org/showthread.php?105896-Initialize-spring-beans-in-parallel-at-startup

**Issue Links:**
- #14520 Parallelize Component Scanning to Improve Spring Startup Time (_**"is duplicated by"**_)
- #10033 Threads bottlenecking in DefaultSingletonBeanRegistry when using Wicket's `@SpringBean` annotation for injection
- #14520 Parallelize Component Scanning to Improve Spring Startup Time
- #20904 Initialization blocked by multi-threaded event publishing
- #19487 Asynchronous initialization of beans during startup
- #18305 Background initialization option for JPA EntityManagerFactory / Hibernate SessionFactory
- #19398 Add a functional way to register a bean

80 votes, 77 watchers

**Comment by guanchao-yang** [comment]
Too much expectation!

**Comment by yiliaofan** [comment]
Hi, has this problem been solved?  @spring-issuemaster  thanks~
It takes 2 minutes for our database resources to load; the startup time is too long. . 
It takes 5 ~ 6 minutes to start the entire application. 

Is there any new progress? Thank you!

**Comment by fzyzcjy** [comment]
Hi is there any updates...? It has been **9 years** :( Spring is sooooo powerful and widely used so IMHO this feature can make thousands (if not millions) of developers and ops' life better!

**Comment by naakax** [comment]
please do this issue, it's really **important**!!

**Comment by guanchao-yang** [comment]
Parallel bean initialization  issue has bean 10 years!!!  Expecting [General Backlog](https://github.com/spring-projects/spring-framework/milestone/205) can be released as quickly as possible！！！ 👍  💯

**Comment by ofdata** [comment]
In the cloud native , parallel bean initialization is important, we need fast startup.

**Comment by maciekdragan** [comment]
The issue is 10 years old now. Happy birthday!!! 🎂 🎂 🎂

**Comment by mazingcai** [comment]
Watching

**Comment by abbothzhang** [comment]
Happy 11th birthday！

**Comment by hehuang139** [comment]
oh!, Is there any progress on this issue? It's so important

**Comment by aaronaxisa-ecabs** [comment]
The lack of this feature is what is making us move to frameworks like Quarkus who prioritises startup time. 
Spring applications are taking too long to start.

**Comment by mangusbrother** [comment]
Something like this is what is causing us to move to frameworks like Quarkus who give priority to startup time.

This would speed up the really slow startup of spring at a bare minimum.

**Comment by bclozel** [comment]
This issue is not scheduled for the upcoming 6.0 version, as it remains in the general backlog for now.

While working on real startup cases, we've often found that time is spent in a handful of specific beans that depend on each other. Introducing parallelization there would not save much in many cases as this doesn't speed up the critical path. This is often related to ORM setup and database migrations.

You can collect more information about this for your own application using the [application startup tracking](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.startup-tracking): you should see where and how startup time is being spent and whether parallelization would improve the situation.

For Spring Framework 6.0, we are focusing on Ahead Of Time features for both native use cases as well as startup time improvements.

**Comment by dikaewiwurae7** [comment]
today is 2022.11.18

**Comment by biuabiu** [comment]
I hope the spring team can take this issue seriously. My current project has an average startup time of over 5 minutes

**Comment by bclozel** [comment]
@biuabiu it's very unlikely that this feature would help in your case. A single component is probably responsible for most of the startup time.

Can you try measuring startup time with the tools we provide? See https://docs.spring.io/spring-framework/reference/core/beans/context-introduction.html#context-functionality-startup if your app is plain Spring or https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.startup-tracking if this is a Spring Boot app. You can send the data our way if you need help analyzing it.

**Comment by biuabiu** [comment]
> @biuabiu it's very unlikely that this feature would help in your case. A single component is probably responsible for most of the startup time.
> 
> Can you try measuring startup time with the tools we provide? See https://docs.spring.io/spring-framework/reference/core/beans/context-introduction.html#context-functionality-startup if your app is plain Spring or https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.startup-tracking if this is a Spring Boot app. You can send the data our way if you need help analyzing it.

ths for reply,in project,some bean initialization tasks,but there are dependencies some bean

**Comment by nicolasmafraintelipost** [comment]
Could the bean initialization approach be delegated to a library? In that case, most of the Spring application would continue to use the same initialization approach. Those who want parallel bean initialization can include library to override behavior.

**Comment by jhoeller** [comment]
Following up on the locking revision in #23501, we are introducing a `backgroundInit` flag on `AbstractBeanDefinition` and a corresponding `@Bean(bootstrap=BACKGROUND)` enum. This is still a bit hot from the oven, a first cut to be committed soon.

This new setting allows for singling out specific beans for background initialization, covering the entire `getBean` step for each such bean in `preInstantiateSingletons`. The corresponding `Future` is stored internally so that dependent beans automatically wait for the bean instance to be completed. Also, all regular background initializations are forced to complete at the end of `preInstantiateSingletons`; only for beans additionally marked as `@Lazy`, the completion is allowed to happen later (up until first actual access).

Note that this typically goes together with `@Lazy` (or `ObjectProvider<...>`) injection points, otherwise the main bootstrap thread is going to block when a background-initialized bean needs to be injected. Also, background initialization applies to individual beans: If such a bean depends on other beans, they need to have been initialized already, either simply through being declared earlier or through `@DependsOn` which is going to enforce initialization in the main bootstrap thread before background initialization for the affected bean is triggered.

Last but not least, a `bootstrapExecutor` needs to be specified on `DefaultListableBeanFactory` for this to be actually active. In an `ApplicationContext`, a bean of that name and of type ´Executor` will be automatically detected. I suppose that Spring Boot will set a corresponding alias for its application task executor by default, but there is also room for a custom executor with a maximum concurrency setting for bootstrapping to be configured - independent from a larger-scale thread pool for other purposes in the same application.
