### ISSUE TITLE
Document alternatives of using multiple `PropertyPlaceholderConfigurer`s [SPR-9989]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#14623]
**[Johann Vanackere](https://jira.spring.io/secure/ViewProfile.jspa?name=vanackej)** opened **[SPR-9989](https://jira.spring.io/browse/SPR-9989?redirect=false)** and commented

When using multiple `PropertyPlaceholderConfigurer` in conjunction with `@Value` annotation and default value for placeholders syntax (ie `${key:defaultValue}`), only the first `PropertyPlaceholderConfigurer` is used. If this configurer does not contain the desired value, it falls back to `@Value` default even if the second `PropertyPlaceholderConfigurer` contains the value.

You'll find attached a JUnit test case with Spring xml context to reproduce the issue.

---

**Affects:** 3.1.3

**Attachments:**
- [PropertyPlaceholderDefaultValueTest.java](https://jira.spring.io/secure/attachment/20689/PropertyPlaceholderDefaultValueTest.java) (_1010 bytes_)
- [propertyPlaceholder-test.xml](https://jira.spring.io/secure/attachment/20688/propertyPlaceholder-test.xml) (_1.31 kB_)
- [test-spring-placeholder.zip](https://jira.spring.io/secure/attachment/21949/test-spring-placeholder.zip) (_4.84 kB_)

**Issue Links:**
- #15247 Default resolved property value is not working properly (_**"is duplicated by"**_)
- #14873 Multiple PropertySourcesPlaceholderConfigurers do not work with placeholder defaults (_**"is duplicated by"**_)
- #15282 Improve property placeholder resolution when multiple configurers are declared (_**"is duplicated by"**_)

**Referenced from:** commits https://github.com/spring-projects/spring-framework-issues/commit/0017731fd9ebce43eaf304cfa0353ff54232cd23

41 votes, 43 watchers

**Comment by admoca60** [comment]
Dear family, I'm new in issue-following and I don't know exactly which is the right procedure to follow an issue. But in this case, I could see that it's closed without any solution. Am I wrong? Thank you!

**Comment by sbrannen** [comment]
@admoca60, your assessment is correct as per the comment above yours: https://github.com/spring-projects/spring-framework/issues/14623#issuecomment-453700023

**Comment by admoca60** [comment]
> your assessment is correct as per the comment above yours

so, in that case, the issue will be fixed or maybe the issue has been discarded?

**Comment by sbrannen** [comment]
It means the latter: the issue was closed without a fix, due to lack of recent community involvement, but it can be reopened for renewed discussion if the community wishes it.

**Comment by jprojas-tec** [comment]
Hello to all,

Just to let you know. We recently bumped against this problem: using default values in a multi PropertySourcePlaceholderConfigurer made our 'multilevel' imported context configurations behave erratically when trying to override these defaults.

The final solution we found was to remove all those defaults from the placeholder and declare them as local properties in the context declaring the PSPC  locations (the root of that context 'branch'). IMHO, its not the best approach and far from being the cleanest one but at lease it lets us combine components with their own placeholder definitions.

This approach still cannot solve importing 3rd party contexts 'as-is' but could help in some other scenarios.

Hope this helps anyone around!

Kind Regards!

JP

**Comment by luryson** [comment]
@jprojas-tec  we recently meet the same problem.

**Comment by AnthonyWhitakerJr** [comment]
I too am seeing this issue.
In the process of addressing a production failure because of it.
One of my dependencies has a property placeholder configurer and is causing other properties with default values to resolve incorrectly.

Please re-open this bug.

**Comment by yunfongloh** [comment]
Seeing this as well

**Comment by rs-dpatil** [comment]
facing the same issue please reopen

**Comment by guanth** [comment]
we are facing zhe same problem when we are trying to use multiple <context:property-placeholder/> labels to import different propertiess to our project. If this bug is fix or have a good solution to avoid this problem.

**Comment by guanth** [comment]
spring version: 5.2.12

we are facing zhe same problem when we are trying to use multiple context:property-placeholder/ labels to import different propertiess to our project. If this bug is fix or have a good solution to avoid this problem.

**Comment by robert-gdv** [comment]
@sbrannen : can you reopen the issue?

**Comment by WhiteFerrari666** [comment]
In the case that your project uses one single PSPC besides others that may exist in dependencies (as opposed to multiple ones in your own project), the following workaround may be applied: set the `order` property on your own PSPC with a low value (I have chosen 1) so that it is the first being asked by Spring. Most PSPCs seem to use the default value for `order`, which happens to be `Integer.MAX_VALUE`, so your chances are good that you can hook in here. 
Obviously this is rather hacky and will break as soon as there are other PSPCs that apply the same tactic.

You may have better luck by actually adding your properties to the Spring Environment, for example via the `PropertySource` mechanism instead of the PSPC `locations`. Please correct me if I'm wrong, but as far as I know any PSPC will always be aware of all the properties in the environment, thus being able to resolve them no matter where it was declared.

**Comment by snicoll** [comment]
This thread has several use cases and most of them are about modularization. Rather than creating multiple `context:property-placeholder` in the modules that need to source some properties, you should contribute a `PropertySource` in the `Environment`. Doing so is more consistent and will make sure the `Environment` has a unified view of the properties that are used.

If you want to apply the replacement against a set of well-defined keys, rather than using the full `Environment`, consider creating your own `PropertySourcesPlaceholderConfigurer` and gather the properties to use from a convention of your own in each module.

Configuring multiple configurers is still supported, but each should have a specific placeholder syntax (for example `${...}` vs. `@{...}`), to avoid the problem that has been described here.
