### ISSUE TITLE
Support correlation id header [SPR-12048]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#16664]
**[Alex](https://jira.spring.io/secure/ViewProfile.jspa?name=dusty)** opened **[SPR-12048](https://jira.spring.io/browse/SPR-12048?redirect=false)** and commented

The issue is described on StackOverflow (http://stackoverflow.com/questions/24991275/rpc-over-stomp-using-spring-and-correctly-handling-server-side-errors-propagate) but since it seems a general problem I hope it's ok to open a ticket for it.

While using `@MessageMapping` is fine for normal messaging, I find using `@SendToUser` quite limitating for implementing RPC because the client has an hard time to understand which reply is associated with which request in a scenario when multiple simultaneous requests are being made from the client.

Of course there is no problem when just only one request is made, and the client waits for its reply, but problems arise when the client has to keep track of multiple "open" rpc calls.

I've managed to make the system mostly fine by associating an ID with every request, i.e.: the client sends an id together with the message, and the server replies with a special message wrapper that contains this id, so the client is able to associate asynchronous replies with requests.

This works fine but has several limitations:

* I have to develop code that needs to understand this structure, and that defies the uitlity to have simple annotated methods

* when the server side code generates an Exception the Spring `@MessageExceptionHandler` get called and the correct Exception is returned to the client, but the request id is lost because the handler has no (easy) way to access it.

I know that with rabbitmq we can add "reply-to" header to every request that needs to be associated with a special reply (the rpc response), and this is implemented by creating a special temporary queue that the user is automatically subscribed to, but how may I use this scheme in Spring? Also, that would tie me a specific broker.

How may I elegantly implement a correct RPC call in Spring that correctly handles server side exceptions?

I find this a general problem and I think Spring could benefit greatly to implement it natively.

---

**Affects:** 4.0.6

1 votes, 7 watchers

**Comment by rstoyanchev** [comment]
One option for this is to inject the correlation header and use `SimpMessagingTemplate` to send the message with the correlation id set. Another option might be to make the destination unique, e.g. `/rpc/op1/{id}`.

**Comment by rstoyanchev** [comment]
Closing for now, but can be re-opened if needed.

**Comment by JohnHaze** [comment]
`org.springframework.messaging.simp.stomp.StompSession` can send receipt headers (see setAutoReceipt(boolean)) and returns `Receiptable` objects from send and subscribe methods. `Receiptable` is a handle to RECEIPT frames returned from the server/broker.

Unfortunately `org.springframework.messaging.simp.annotation.support.SendToMethodReturnValueHandler` strips incoming "receipt" headers. As Alex pointed out above.
It seems, that  SendToMethodReturnValueHandler should propagate the "receipt" headers, because otherwise the connected message broker is not able to send RECEIPT frames back and Spring's StompSession's receipt implementation is not backed by server-side header-integrity.

Tested both, with SimpleBroker and embedded Artemis Broker.
With a **changed** SendToMethodReturnValueHandler the embedded Artemis broker sends back RECEIPT frames and are received via `Receiptable`.
SimpleBroker is just a simple broker and does not send back RECEIPT frames although it could because "receipt" headers are propagated.

Further, the **changed** SendToMethodReturnValueHandler allows for sending back the "receipt" header as received from the client within the "response" message of the server, which comes in handy in terms with the `@SendTo` annotation, as Alex mentioned above.
With a **changed** SendToMethodReturnValueHandler the embedded Artemis broker and SimpleBroker send back the "receipt" header in the `@SendTo`-response-message, simply because it is not stripped by return value handler.

Therefore, also the function of a correlation-id-header is fulfilled by "receipt" header.


Conclusion:
If I am not missing something, I would agree with Alex and also propose a minor change in  `org.springframework.messaging.simp.annotation.support.SendToMethodReturnValueHandler`:
Propagate "receipt" header at least, if not all.

I guess other handlers may be updateable too (subscribe?)?

**Comment by rstoyanchev** [comment]
@JohnHaze I do see how copying all headers fits well for a controller method that intercepts a message before forwarding it to the broker, but I can also see a case where the controller method handles the message, and sends a new one. Therefore I'm not sure this should be done always, but it does make sense to provide control and allow you to do this.

Could you create a new issue, and we'll look for a way to make `SendToMethodReturnValueHandler` and `SubscriptionMethodReturnValueHandler` customizeable?

**Comment by JohnHaze** [comment]
@rstoyanchev yes I will create an issue, thank you!
pls see: https://github.com/spring-projects/spring-framework/issues/36168
