### ISSUE TITLE
Publish test execution events to the test ApplicationContext [SPR-13916]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18490]
**[Frank Scheffler](https://jira.spring.io/secure/ViewProfile.jspa?name=maverick1601)** opened **[SPR-13916](https://jira.spring.io/browse/SPR-13916?redirect=false)** and commented

We are using Mockito mocks quite often throughout our Spring-based integration tests, which leaves us with the problem of resetting them before/after each test method. While we can use some globally defined custom TestExecutionListener to reset all the mocks found within the ApplicationContext, it would be more practical to be able to define specific event-listeners within the application context itself. This would allow for more fine-grained control over which beans (i.e. mocks) should be reset.

## Deliverables

- [x] Implement `EventPublishingTestExecutionListener`.
- [x] Implement abstract `TestContextEvent` and all concrete subclasses.
- [x] Implement composed `@EventListener` annotations for all events.
- [x] Document exception handling and async support in Javadoc.
- [x] Document in the _Testing_ chapter of the reference manual.

---

**Issue Links:**

- #13352 Publish TestStarted and TestCompleted events in the TestContext framework
- #18606 Introduce support for test-scoped beans in the TestContext framework

2 votes, 6 watchers

**Comment by sbrannen** [comment]
This issue supersedes gh-13352.

**Comment by sbrannen** [comment]
Related [discussion on StackOverflow](https://stackoverflow.com/questions/54114640/how-to-register-spring-context-events-for-current-test-applicationcontext-at-run/54130273?stw=2#54130273)

**Comment by sbrannen** [comment]
Hi @maverick1601,

> I would like to proceed on finishing the code, if this is considered a useful enhancement to the TCF.

I took a glance at your draft, and it looks very similar to solutions I've implemented for clients.

Are you still interested in submitting a PR?

If so, feel free to simply submit your draft, and I'll take it from there. Otherwise, I'll likely just implement it from scratch.

I'm hoping to get this into Spring 5.2 M1, so I'd be grateful for prompt feedback.

Thanks,

Sam

**Comment by maverick1601** [comment]
I would do so. Since the issue is about 3 yrs old, I don't know how much I would have to rewrite. Back then we could not fully agree on the fact, that such a TestExecutionListener would be included in the list of default listeners, especially with respect to the fact that such an event publishing TestExecutionListener would trigger context initialization. What is your opinion on that?

**Comment by sbrannen** [comment]
> I would do so. 

I like to give credit where credit is due, so that would be great!

Can you provide an estimate of when you think you'll able to do that?

> Since the issue is about 3 yrs old, I don't know how much I would have to rewrite. 

I don't think you'd have to _rewrite_ much of anything. There are two new methods in the `TestExecutionListener` API, but I assume you'll make quick work of that. If you don't have time, don't worry: I can add the support for the new methods.

> Back then we could not fully agree on the fact, that such a TestExecutionListener would be included in the list of default listeners, especially with respect to the fact that such an event publishing TestExecutionListener would trigger context initialization. What is your opinion on that?

I'm currently inclined not to register this new listener by default. I think it's perhaps best to keep it as an opt-in feature. 

In any case, that can be decided later or changed before 5.2 GA is released.

My main objective right now is to get the feature in place in 5.2 M1 so that people can experiment with it and provide feedback.

Cheers,

Sam

p.s. don't worry so much about the documentation at this point unless you have time. If you don't have time, I'll pick up the documentation task after merging in your work.

**Comment by maverick1601** [comment]
Okay, I took a look at it and it seems the main work is to rebase my previous proposal against master branch and to cover those two new life-cycle methods. I'd say this is done by the end of this week.

**Comment by sbrannen** [comment]
Sounds good. 

Looking forward to your PR!

**Comment by maverick1601** [comment]
@sbrannen See: https://github.com/spring-projects/spring-framework/pull/22477

**Comment by sbrannen** [comment]
@maverick1601, thanks for the PR.

I'll take a look.

**Comment by sbrannen** [comment]
The work for this issue has been merged into `master` in 34fee867d2930ad102b94f193ff3a5d37712883c and refined in 2d6624de710b1b2383afa1ebf92b2cd1e69c56ab.

Reopening in order to add documentation to the _Testing_ chapter of the reference manual.

**Comment by sbrannen** [comment]
**Update**: commit e272e2e151b9995ef906f5ed0fc3206de22df1dc introduced support for conditional event processing in the built-in event listener annotations.

**Comment by sbrannen** [comment]
**Update**:

This new feature set is now documented in the Reference Manual.

In addition, the `EventPublishingTestExecutionListener` is now registered by default for 5.2 M1.

**Comment by sbrannen** [comment]
Reopening to sort out issues with having the new `EventPublishingTestExecutionListener` registered by default _and_ having a order of `HIGHEST_PRECEDENCE`.

The current state of affairs leads to undesirable side effects, such as:

- `@DirtiesContext` no longer works as expected: a context that is dirtied (and properly closed) after a test method or test class will be magically recreated by the `EventPublishingTestExecutionListener`, thus effectively breaking `@DirtiesContext` support.
- The test's `ApplicationContext` will be eagerly loaded before any other `TestExecutionListener` and before any _before all_ lifecycle methods in test classes (e.g., JUnit Jupiter's `@BeforeAll` and JUnit 4's `@BeforeClass`).

**Comment by sbrannen** [comment]
**Update**: the implementation of this feature has been revised. See 353e092bf6a71231d0e08d0127fe680462b583a7 for details.
