### ISSUE TITLE
Exclude an exception from @ExceptionHandler [SPR-13932]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18504]
**[Bill Chen](https://jira.spring.io/secure/ViewProfile.jspa?name=billc.cn)** opened **[SPR-13932](https://jira.spring.io/browse/SPR-13932?redirect=false)** and commented

As seen in the referenced SO question, if one wants a blanket handler for all Exceptions apart from a few, one will have to rethrow the unhandled exception in the `@ExceptionHandler` method, which causes a horrendous `ERROR` to be logged.

Can some facility be provided to statically (via the annotation) or, even better, dynamically skip an exception in a handler?

---

**Affects:** 4.2.4

**Reference URL:** http://stackoverflow.com/q/35267756/499922

**Issue Links:**
- #19473 ExceptionHandlerExceptionResolver should not log propagated exceptions at warn level
- #19427 Log exception from `@ExceptionHandler` at higher level than debug

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/cdfcc23b6f1424f04e8273b3aa69fe185fb73dde, https://github.com/spring-projects/spring-framework/commit/6ef2d827c67da49ba7751cae6b9bd9a6ec7f8fbc

**Comment by rstoyanchev** [comment]
Rather than an exclusion flag, it seems this could be done with two `@ExceptionHandler` methods, one for the more general exception and another for the more specific.

**Comment by yacota** [comment]
Hi @rstoyanchev, I hope you don't mind If I explain our use case in this closed issue

We have a globalErrorHandler with @ExceptionHandler(value = {Exception.class, Error.class}) that is catching every error in order to track them and check code regressions after each deployment.

We also have business exceptions (RedirectExceptions) that we'd like to handle in a custom HandleInterceptor, in its afterCompletion method. As you know this does not work because the exception has already been handled by our globalErrorHandler because we can not make it ignore these kind of business exceptions.
