### ISSUE TITLE
Consider target-class proxy mode by default [SPR-14515]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19084]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-14515](https://jira.spring.io/browse/SPR-14515?redirect=false)** and commented

Following up on #19047, we should once again consider changing the default proxy mode to target-class (CGLIB)...

---

**Affects:** 5.0 M1

**Issue Links:**
- #19047 Mis-proxying of Mockito mock and poor diagnostics for type mismatch on proxy injection
- #8346 Add support for mixed, fine-grained JDK- and CGLIB-based proxying
- #18894 CGLIB proxies should still consider `@Transactional` annotations on interface methods

**Comment by jhoeller** [comment]
Aside from Spring Boot's default target-class choice for high-level proxy functionality there, I don't see us ever changing this in the core framework facilities. At that level, this is effectively an independent setting for every proxy factory and would break many assumptions in scenarios that are hard to fix.

Also, in native images and similar scenarios, it actually turned out to be beneficial to aim for interface-based proxies wherever possible. Even for configuration classes, the "lite" mode (`proxyBeanMethods=false`) is rather recommendable for library components now, avoiding unnecessary class generation.
