### ISSUE TITLE
Allow declaring bean stereotypes using Java configuration [SPR-14677]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19241]
**[Behrang Saeedzadeh](https://jira.spring.io/secure/ViewProfile.jspa?name=behrangsa)** opened **[SPR-14677](https://jira.spring.io/browse/SPR-14677?redirect=false)** and commented

It would be nice if we could declare that a given bean has a particular stereotype using Java based configuration. For example:

```java
@Bean
@Service
public TwitterService twitterService() {
   // ...
}

@Bean
@Repository
public TweetRepository tweetRepository() {
   // ...
}
```

or

```java
@Service
public TwitterService twitterService() {
   // ...
}
```

or

```java
@Bean(stereotype = Service.class)
public TwitterService twitterService() {
   // ...
}
```

---

No further details from [SPR-14677](https://jira.spring.io/browse/SPR-14677?redirect=false)

**Comment by behrangsa** [comment]
Please reopen this issue.

**Comment by rstoyanchev** [comment]
**Team Decision:** We've discussed this, and don't see it as a good fit on, because it would make it possible to  declare multiple beans of the same type, with different stereotypes. A stereotype annotation really belonging on the class declaration where it's clear the a single class can only be one kind of component.

If this is for autowiring purposes, you could add `@Qualifier`. If not, please provide more details on how you use the stereotype metadata, so we can provide some further guidance.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
