### ISSUE TITLE
XpathExpectationsHelper should support Hamcrest matching against typed objects [SPR-14722]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19287]
**[Manuel Jordan](https://jira.spring.io/secure/ViewProfile.jspa?name=dr_pompeii)** opened **[SPR-14722](https://jira.spring.io/browse/SPR-14722?redirect=false)** and commented

I am working with:

* Spring Framework `4.3.2`

About `Spring MVC Test` for **Json** I have the following:

```java
.andExpect(jsonPath("$.id").exists())
.andExpect(jsonPath("$.id").value(is("100")))
.andExpect(jsonPath("$.id").value(is(persona.getId())))
.andExpect(jsonPath("$.nombre").exists())
.andExpect(jsonPath("$.nombre").value(is("Jesús Você")))
.andExpect(jsonPath("$.nombre").value(is(persona.getNombre())))
.andExpect(jsonPath("$.apellido").exists())
.andExpect(jsonPath("$.apellido").value(is("Mão Nuñez")))
.andExpect(jsonPath("$.apellido").value(is(persona.getApellido())))
....
```

now consider a more complex object, either _more fields_ or _relation with other objects_.
With the following I have a considerable reduction of code

```
.andExpect(jsonPath("$", is(persona)))
.andExpect(jsonPath("$").value(is(persona)))
```

Same thought for collections of data returned in JSON format. Here `jsonPath` works in peace with `Hamcrest`

The problem is with **XML**. I have the following:

```
.andExpect(xpath("persona/*").nodeCount(is(4)))
.andExpect(xpath("persona/id").exists())
.andExpect(xpath("persona/id").string(is("100")))
.andExpect(xpath("persona/id").string(is(persona.getId())))
.andExpect(xpath("persona/nombre").exists())
.andExpect(xpath("persona/nombre").string(is("Jesús Você")))
.andExpect(xpath("persona/nombre").string(is(persona.getNombre())))
.andExpect(xpath("persona/apellido").exists())
.andExpect(xpath("persona/apellido").string(is("Mão Nuñez")))
.andExpect(xpath("persona/apellido").string(is(persona.getApellido())))
```

The code works or pass, but again consider a more complex object, either _more fields_ or _relation with other objects_. Sadly `xpath` does not work with `Hamcrest`. So I am not able to do a reduction of code. Same problem for collections of data returned in XML format.

This problem has been discussed in some way in:
[SPR-13687 - Why MockMvcResultMatchers has not a xpath method with org.hamcrest.Matcher<T>?](#18262)
Pls. read the latest comment

Considering that Spring Framework 5 is coming, perhaps would have sense in re-consider in apply this improvement?

Thanks by your understanding.

---

**Affects:** 4.3 GA, 4.3.1, 4.3.2, 5.0 M1

**Issue Links:**
- #18262 Why MockMvcResultMatchers has not a xpath method with org.hamcrest.Matcher<T>?

**Backported to:** Contributions Welcome

**Comment by rstoyanchev** [comment]
Revisiting this issue, there are some things I overlooked. In order to compare to a higher level object, you need to specify a target class, so it should be this at least:
```java
.andExpect(jsonPath("$", is(persona), Persona.class))
```
Even then, unless JSONPath is configured with a `JsonProvider`, the `JsonSmartMappingProvider` used by default only decodes to maps of objects. This was raised in #31423 and #27486 recently. We do have an improvement planned with #31651 for `JsonPathExpectationsHelper` to expose JSONPath for configuration. However, the general challenge is that with static methods for `ResultMatcher` implementations, there is no way to have JSON or XML library configured during setup, and the config would have to be passed in every time or configured statically, neither of which is a good solution. 

This is why I don't think we can do do much more here. 

That said, I do actually have an alternative. If the goal is to compare higher level objects, you can use `WebTestClient`. Unlike MockMvc that does server side testing, `WebTestClient` is an actual test client that does encoding and decoding to higher level objects, and it can be used with any server, including MockMvc through `MockMvcWebTestClient`. You can use it to do something like:

```java
@Test
void xml() {
	MockMvcWebTestClient.bindToController(new PersonController()).build()
			.get()
			.uri("/person/Lee")
			.accept(MediaType.APPLICATION_XML)
			.exchange()
			.expectStatus().isOk()
			.expectHeader().contentType(MediaType.APPLICATION_XML)
			.expectBody(Person.class)
			.isEqualTo(person);
}

```
