### ISSUE TITLE
Common API for MockMvc tests and for real HTTP tests

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19647]
**[Neil S](https://jira.spring.io/secure/ViewProfile.jspa?name=neils)** opened **[SPR-15081](https://jira.spring.io/browse/SPR-15081?redirect=false)** and commented

There seems to be no common API which can be configure to do mock HTTP tests as well as real HTTP tests.

MockMvc tests suffice during development but for production deployment projects might like to do a complete end-to-end integration test by run real tests against a the (maybe embedded) container sever which will be used in production.

At the moment that means writing the same tests twice using the MockMvc and then TestRestTemplate+assert APIs.

IMHO MockMvc has the friendlier API which results in concise and easier to read test code.

---

**Affects:** 4.3.5

**Issue Links:**
- #18391 Extract MockHttp from MockMvc
- #20963 Support varargs for expectations in MockMvc

0 votes, 6 watchers

**Comment by inanemed** [comment]
Could you please confirm this is still an issue?

**Comment by molexx** [comment]
Yes.

@rstoyanchev 's experiment in https://github.com/spring-projects/spring-framework/issues/19647#issuecomment-453449879 looks to be a good solution.

**Comment by rstoyanchev** [comment]
I'll give this a try for 5.3 RC1.

**Comment by rstoyanchev** [comment]
After some more thought, while my earlier experiment in https://github.com/spring-projects/spring-framework/issues/19647#issuecomment-453449879 does work, it has a major issue in that `MockMvc` is for server tests and exposes lots of request inputs and response assertions that cannot be passed over HTTP such as request and session attributes, contextPath, servletPath, model attributes, and many others. It makes it a poor choice for a common API for both mock HTTP and real HTTP tests.

A better path is via `WebTestClient` which already supports a common API for mock HTTP tests (with WebFlux) and for real HTTP tests. We can add support for mock HTTP tests (with Spring MVC) targeting `MockMvc` as the server. That will expose equivalent `MockMvc` setup options, including setup extension hooks (e.g. Spring Security setup) but actual tests will be performed through the `WebTestClient`.

Among the benefits of this approach, as an actual HTTP client the `WebTestClient` provides encoding and decoding of request and response content (i.e. message conversion) which is convenient for assertions against higher level objects. For all other assertions in `MockMvc`, the `WebTestClient` offers equivalents but through a fluent API without static imports. Async requests will be a little easier because the asyncDispatch will be performed transparently.

I've experimented locally and it is fairly straight forward to do. I should have something concrete this week.

What does it mean for existing `MockMvc` tests and `MockMvc`? `WebTestClient` will use `MockMvc` to perform requests so `MockMvc` remains as the foundation for Spring MVC testing. I do expect however that a majority of tests will now be performed through the `WebTestClient`. Existing tests can remain as is, or it's easy to re-write them as well to `WebTestClient`.

**Comment by molexx** [comment]
Sounds fair to me, thanks.

I've not looked at `WebTestClient` so far because we don't use Webflux, looking forward to checking it out.

**Comment by rstoyanchev** [comment]
The new [MockMvcTestClient](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/web/servlet/client/MockMvcTestClient.java) is now available in master with 5.3 snapshots. I've ported all existing sample tests which can be used for comparison.

Before:
- [org/springframework/test/web/servlet/samples/standalone](https://github.com/spring-projects/spring-framework/tree/master/spring-test/src/test/java/org/springframework/test/web/servlet/samples/standalone)
- [org/springframework/test/web/servlet/samples/context](https://github.com/spring-projects/spring-framework/tree/master/spring-test/src/test/java/org/springframework/test/web/servlet/samples/context)

After
- [org/springframework/test/web/servlet/samples/client/standalone](https://github.com/spring-projects/spring-framework/tree/master/spring-test/src/test/java/org/springframework/test/web/servlet/samples/client/standalone)
- [org/springframework/test/web/servlet/samples/client/context](https://github.com/spring-projects/spring-framework/tree/master/spring-test/src/test/java/org/springframework/test/web/servlet/samples/client/context)

I am keeping the issue open until I've the documentation has been updated.

> I've not looked at WebTestClient so far because we don't use Webflux

Use of `WebTestClient` requires hardly any knowledge of WebFlux. You'll see from the before and after tests the experience is largely the same. I've even managed to keep the ability to perform MockMvc assertions on the server response for those extra things like model attributes, flash attributes, etc.

**Comment by molexx** [comment]
This looks great, thanks!

I think it would be useful to add an example that shows best practise to also run the tests from `WebAppResourceTests` in http mode please. 

I'm not sure what the neatest way is? Thinking aloud, perhaps the tests could be in an abstract class that is extended by two concrete test classes - one setting up the MockMVCTestClient as shown and the other starting the http server with `@SpringBootTest(webEnvironment=...)` and leaving the WebTestClient to be autoconfigured. Or maybe the same test class could configure itself differently depending on a property passed at test runtime?

**Comment by rstoyanchev** [comment]
> I think it would be useful to add an example that shows best practise to also run the tests from WebAppResourceTests in http mode please.

Replace the test [client initialization](https://github.com/spring-projects/spring-framework/blob/241afeb1b74be954ddb43b8faba70b956c6c021d/spring-test/src/test/java/org/springframework/test/web/servlet/samples/client/context/WebAppResourceTests.java#L60) with something like this (and you'll also need to run the server):
```java
this.testClient = WebTestClient.bindToServer().baseUrl("http://localhost:8080").build();
```

> perhaps the tests could be in an abstract class that is extended by two concrete test classes - one setting up the MockMVCTestClient as shown and the other starting the http server with @SpringBootTest(webEnvironment=...) and leaving the WebTestClient to be autoconfigured.

Yes that's one way to do it. I suppose it depends on whether you want to run both every time or selectively. It probably makes sense to run in MockMvc mode most often and in live server mode once in a while. If setting things up programmatically you could use JUnit's Assume or `@ParameterizedTest` or in a more declarative style with Boot's `@SpringBootTest(webEnvironment=...)`, I think JUnit's [@EnabledIfEnvironmentVariable](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-environment-variables) would be handy.

**Comment by molexx** [comment]
Great thanks.

I think it's worth mentioning this in the docs to make it clear how easy it is to do.

**Comment by nvora** [comment]
Do we have a reference project with an example of testing rest api with both and live server? if yes please share
