### ISSUE TITLE
Document LazyConnectionDataSourceProxy for IsolationLevelDataSourceRouter usage with DataSourceTransactionManager

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#19688]
**[springrain](https://jira.spring.io/secure/ViewProfile.jspa?name=springrain)** opened **[SPR-15121](https://jira.spring.io/browse/SPR-15121?redirect=false)** and commented

IsolationLevelDataSourceRouter.determineCurrentLookupKey returns the result was null, since AbstractPlatformTransactionManager.getTransaction (TransactionDefinition definition) before calling doBegin(Object transaction, TransactionDefinition definition), setCurrentTransactionIsolationLevel(Integer isolationLevel) is not set, but get a connection, it's bug.

---

**Affects:** 4.3.4

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1291

**Comment by andrei-ivanov** [comment]
I've hit a similar issue, where I'm trying to use the `readOnly` status of the transaction to determine which dataSource to use, just to see that `AbstractPlatformTransactionManager#prepareSynchronization` is invoked just after `doBegin`, which obtains the connection (using a `JpaTransactionManager`) 😥

**Comment by andrei-ivanov** [comment]
is there any chance that moving the [prepareSynchronization](https://github.com/spring-projects/spring-framework/blob/v5.2.9.RELEASE/spring-tx/src/main/java/org/springframework/transaction/support/AbstractPlatformTransactionManager.java#L401) call before `doBegin` might work?

**Comment by andrei-ivanov** [comment]
@jhoeller ?

**Comment by jhoeller** [comment]
Returning to DataSource setup issues for a bit of a JDBC theme in 6.1.2, including new sharding support and several refinements to Spring's DataSource adapters : see https://github.com/spring-projects/spring-framework/issues?q=is%3Aopen+milestone%3A6.1.2+label%3A%22in%3A+data%22+

I am inclined to address the isolation level scenario here through an extension of `SmartDataSource` with a dedicated `getConnection(int isolationLevel, boolean readOnly)` method that `DataSourceTransactionManager` can call if the target DataSource implements it. `IsolationLevelDataSourceRouter` and a similar routing DataSource based on `@Transactional(readOnly=...)` can then take this into account directly when specified. This would allow us to preserve the semantics of our existing transaction synchronization arrangement which we cannot easily bend towards earlier exposure.

As an alternative, `LazyConnectionDataSourceProxy` could be used to approach JTA-like late retrieval semantics which should make the existing transaction synchronization arrangement work with `IsolationLevelDataSourceRouter` as the target behind a `LazyConnectionDataSourceProxy`, since the actual target Connection will be retrieved after transaction begin then.
