### ISSUE TITLE
Open parameter autowiring utility for external use [SPR-17627]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19926]
**[Ledoyen Loïc](https://jira.spring.io/secure/ViewProfile.jspa?name=ledoyen)** opened **[SPR-17627](https://jira.spring.io/browse/SPR-17627?redirect=false)** and commented

## Proposal

Open autowiring utility methods in `ParameterAutowireUtils`, so they can be used by other testing frameworks.

## Deliverables

- Move functionality currently in `ParameterAutowireUtils` to a new location in the `spring-beans` module.
  - Actual destination: TBD
- Remove `ParameterAutowireUtils` from the `spring-test` module.

---

**Reference URL:** https://github.com/spring-projects/spring-framework/pull/2060

**Issue Links:**
- #18628 Introduce autowiring support for individual handler method parameters

**Comment by sbrannen** [comment]
If `org.springframework.beans.factory.support.AutowireUtils` were a `public` utility class, I would likely recommend that we move the functionality in `ParameterAutowireUtils` into `AutowireUtils`.

However, since `AutowireUtils` is not `public`, I propose that we simply relocate `ParameterAutowireUtils` to the `org.springframework.beans.factory.support` package alongside `AutowireUtils`.

@jhoeller, are you OK with the above proposal?

**Comment by sbrannen** [comment]
Now that we have migrated to GitHub issues, I'm closing this _issue_ in favor of the associated PR #2060.
