### ISSUE TITLE
Improve HandlerMappingIntrospector performance [SPR-16013]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20562]
**[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch)** opened **[SPR-16013](https://jira.spring.io/browse/SPR-16013?redirect=false)** and commented

Currently `HandlerMappingIntrospector` must iterate over all `HandlerMappings` to determine if a pattern matches. Then the `DispatcherServlet` must iterate over the same mappings to find a match. It would be nice if this could be optimized.

NOTE: This was originally reported by a user via email

---

**Affects:** 4.3.11, 5.0 RC4

**Issue Links:**
- #20094 AbstractHandlerMethodMapping should allow for customized bean retrieval

**Comment by rstoyanchev** [comment]
Superseded by #31588.

**Comment by tushar-meesho** [comment]
@rstoyanchev we have recently planning to migrate to spring-boot-3.0.1 version from spring-boot-2.7.10, Do we have to upgrade to Spring Boot 3.2.1-SNAPSHOT or later, so that we don't face any latency issues on production because of this caching isssue. Is this fix live on release version spring-boot - 3.2.5 ?
