### ISSUE TITLE
Failure to run second script as intended in @SQLGroup with multiple data sources and transaction managers on a JUnit test class [SPR-16153]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20701]
**[Eduardo Beja Martins](https://jira.spring.io/secure/ViewProfile.jspa?name=ebm)** opened **[SPR-16153](https://jira.spring.io/browse/SPR-16153?redirect=false)** and commented

On a JUnit Test configuration, with two data sources of different transaction managers, applied to the test class, the second is rerunned for each test.

Example:

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SqlGroup({
    @Sql(scripts = "script1.sql", config = @SqlConfig(dataSource = "dataSource1", transactionManager = "txMgr1")),
    @Sql(scripts = "script2.sql", config = @SqlConfig(dataSource = "dataSource2", transactionManager = "txMgr2"))
})
public class ExampleTest{
    @Test
    public test1() {
        // Some or no code here
    }

    @Test
    public test2() {
        // Some or no code here
    }
}
```

Between test1 and test2, errors will occur because script2.sql has insert statements, that will try to run for each test, and for the second time, registers with the same primary key will aready exist.

If the order of the '`@Sql`' statements is inverted, same problem will occur but for script1.sql.

The need for the persistence comes from the heavy load of JUnit tests for code pieces that only read and do not write to database..

---
No further details from [SPR-16153](https://jira.spring.io/browse/SPR-16153?redirect=false)

**Comment by sbrannen** [comment]
This is the expected behavior. `@Sql` scripts and statements configured at the class level will be executed for each test method in the test class -- unless a given test method is itself annotated with `@Sql` in which case the method-level configuration overrides the class-level configuration.

Issue gh-18929 will introduce support for class-level only configuration.

**Comment by sbrannen** [comment]
If you configure SQL scripts or statements that insert data into the database with predefined primary keys -- and if those SQL scripts or statements are executed outside of a test-managed transaction (i.e., if the changes are committed to the database), you will then have to clean up the changes after each test method. Otherwise you run into primary key constraint violations in the database as you have pointed out.

Luckily, `@Sql` provides support for executing "clean-up" scripts or statements after each test method.

I documented the available options in detail in this [StackOverflow question](https://stackoverflow.com/a/27156080/388980).

Here's an excerpt:

> ```java
> @Test
> @SqlGroup({
>     @Sql("create-tables.sql"),
>     @Sql(scripts = "clean-up.sql", executionPhase = AFTER_TEST_METHOD)
> })
> public void test() { /* ... */ }
> 
> ```
> 
> If your tests are `@Transactional` and you'd like to clean up committed database state, you can instruct Spring to execute your clean-up SQL script in a new transaction like this:
> 
> ```java
> @Test
> @Sql("insert-test-data.sql")
> @Sql(
>   scripts = "clean-up.sql",
>   executionPhase = AFTER_TEST_METHOD,
>   config = @SqlConfig(transactionMode = ISOLATED)
> )
> public void test() { /* ... */ }
> 
> ```

**Comment by sbrannen** [comment]
In light of the above, I am closing this issue as.
