### ISSUE TITLE
JDK 11 HttpClient integration with WebClient [SPR-16469]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21014]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-16469](https://jira.spring.io/browse/SPR-16469?redirect=false)** and commented

According to this [blog post](http://openjdk.java.net/groups/net/httpclient/intro.html) the HttpClient "handles request and response bodies as reactive-streams", and it is currently in [incubation status](http://http://openjdk.java.net/jeps/11), but will be made official in JDK 11 when it will switch to `java.net` from `jdk.incubator`.

Given the JDK 11 release dates, this is probably a 5.2 target. However, at present, we need to experiment with the proposed API to see if there any issues in adapting it through a `ClientHttpConnector`, and raise issues if necessary.

[JDK HTTP Client - JEP 321 - Update](http://mail.openjdk.java.net/pipermail/net-dev/2018-February/011155.html)

---

**Affects:** 5.0.3

**Issue Links:**
- #21016 JDK 11 WebSocket integration with WebSocketClient
- #19658 Jetty HTTP client integration with WebClient

0 votes, 6 watchers

**Comment by sdeleuze** [comment]
I have upgraded [the prototype](https://github.com/sdeleuze/jdk-http-webclient) to JDK 11 and Spring Framework 5.1, but it seems most tests are broken. Most significant change has been that we now leverage `BodyPublishers.fromPublisher`, so maybe the issue is on that part. I won't spend more time on that for now since this is not a Spring Framework 5.2 topic anymore, but we will have to fix that at some point.

**Comment by rstoyanchev** [comment]
I'm marking this superseded by #23432 which seems to be close enough to the [prototype](https://github.com/sdeleuze/jdk-http-webclient) here.
