### ISSUE TITLE
Use of ApplicationEventPublisher in a reactive call stack [SPR-16481]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21025]
**[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch)** opened **[SPR-16481](https://jira.spring.io/browse/SPR-16481?redirect=false)** and commented

Currently there is no equivalent of reactive `ApplicationEventPublisher` which means the only way to publish events is blocking and cannot be performed in a `WebFlux` application. This impacts Spring Security applications which currently cannot publish authentication events. See https://github.com/spring-projects/spring-security/issues/4961

---

**Affects:** 5.0.3

**Issue Links:**
- #21831 Support for non-blocking event listener methods

1 votes, 8 watchers

**Comment by jhoeller** [comment]
I've finally revised the javadoc on `publishEvent` accordingly, suggesting that no specific semantics are implied beyond a hand-off to the multicaster - and that event listeners are encouraged to individually use asynchronous execution for longer-running and potentially blocking operations. The latter has always been possible programmatically or with the use of `@Async`, and is now more sophisticated in 5.2 with reactive event listener methods (#21831).

For reactive event publication purposes, the best you can do to integrate the hand-off step into a reactive pipeline is `Mono.fromRunnable(() -> context.publishEvent(...))`, I suppose. Since we are not propagating anything other than the event itself between an event publisher and an event listener (as per the idea of decoupled events), we are currently unable to propagate a Reactor context as well, so a `publishEvent` variant with a `Mono` return type would arguably send a misleading signal at this point.

I'm moving this to the backlog for revisiting a fully Reactor-based multicaster with tighter publisher-listener interaction at a later point. For the time being, anything that the Reactor context could contain will have to be included in the event instance itself, including contextual transaction and security holders, so that a listener can independently operate on the complete specific context that it needs.

**Comment by codependent** [comment]
I found this issue after opening an [ticket](https://github.com/spring-projects/spring-framework/issues/25805) for failing to use a @TransactionalEventListener in a Webflux application.

At the moment it seems it can't be done. Are there any plans to provide a Reactor-based ApplicationEventMulticaster that would allow the transactional context to be propagated?

Regarding the suggested workaround:

_For the time being, anything that the Reactor context could contain will have to be included in the event instance itself, including contextual transaction and security holders, so that a listener can independently operate on the complete specific context that it needs._

Could you clear up how this could be done?

**Comment by jhoeller** [comment]
As of 6.1, `@TransactionalEventListener` can be triggered with reactive transactions through adding the transaction context as the event source: https://github.com/spring-projects/spring-framework/issues/27515#issuecomment-1660934318
