### ISSUE TITLE
Provide a mechanism to indicate that a WebFlux request mapping is blocking and should be called on a separate thread [SPR-16643]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21184]
**[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson)** opened **[SPR-16643](https://jira.spring.io/browse/SPR-16643?redirect=false)** and commented

Spring Boot's new Actuator endpoint model allows users to write endpoints with operations that may block. We need to adapt those operations to both WebMVC and WebFlux. When adapting to WebFlux, we identify operations that may block and use `publishOn` so that the work is performed on a different thread. We currently use the operation's return type to determine whether or not it will block, erring on the side of assuming that it will.

If Framework provided a mechanism for indicating whether or not a request mapping would block (an `@Blocking` annotation has been discussed) and automatically did the `publishOn`, we could adopt this approach in Spring Boot's Actuator and provide a consistent experience across Framework and Boot.

---

**Affects:** 5.0.4

**Comment by rstoyanchev** [comment]
**Team Attention:** with the team partially present, the following more current points came up.

After some time has passed, we now have R2DBC progressing, and removing a major reason for blocking methods. Project Loom is also likely to change calculations by making it less problematic to mix blocking and non-blocking. On the other hand at that point it might become less of an issue to automatically switch threads for controller methods with a blocking signature. 

We also have Blockhound to help detect issues with unintended mixing of blocking and non-blocking so we don't need to be as defensive.

For the time being we stick to the current behavior. One thing that we can do is provide some dedicated support to take a snippet of blocking code and run it off the Reactor thread so it's as easy as providing a lambda (e.g. not even having to call `publishOn`). This would also make it possible to do the same consistently in both annotated controllers and functional handlers, since otherwise there would be no answer for this in WebFlux.fn. To be decided if that belongs in Reactor or in the Spring Framework yet.

**Comment by rstoyanchev** [comment]
Closing for now as there is no intention to do this but can be re-opened.

**Comment by rstoyanchev** [comment]
This is now scheduled for 6.1 M2 in #30678.
