### ISSUE TITLE
Make WebFlux multipart support fully Reactive [SPR-17122]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21659]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[SPR-17122](https://jira.spring.io/browse/SPR-17122?redirect=false)** and commented

Spring Framework 5.0 and 5.1 provides support for reactive multipart leveraging [Synchronoss nio-multipart](https://github.com/synchronoss/nio-multipart) library which comes with several limitations. Spring WebFlux feeds data to the parser, which then provides a callback when the entire content for the part is ready, potentially creating temporary files when the content is too big to avoid consuming too much memory. These limitations mainly comes from the fact that their [StreamStorage abstraction](https://github.com/synchronoss/nio-stream-storage) is based on `InputStream` / `OutputStream`.

As proposed initially by [Arjen Poutsma](https://jira.spring.io/secure/ViewProfile.jspa?name=arjen.poutsma), we should probably write our own reactive multipart implementation to overcome these limitation and provide a fully reactive behavior where the content of the file is Reactive Streams compliant (bytes comes to the user as they are received) in order to give more control to the user. If we provide this, I tend to think that we don't have to create temporary files.

---

**Issue Links:**
- #21180 Race-Condition in Multipart upload proxy scenario

**Comment by thekalinga** [comment]
Can someone correct me if I am wrong

I see that the current implementation uses `bufferUntil` operator which will buffer all the data in memory till the end of each part. So, even if I use Flux<Part> variation, we are dealing with a faulty implementation

This means, if I am uploading a file of size 2GB, a proportional amount of RAM is used up by databuffers, which is a recipe for Out of memory errors

This is what I am referring to `DefaultMultipartMessageReader#read`

```java
DataBufferUtils.split(body, boundaryNeedle)
```

and the implementation of `split` is

```java
	public static Flux<DataBuffer> split(Publisher<DataBuffer> dataBuffers, byte[] delimiter,
///a lot
		return Flux.from(dataBuffers)
				.flatMap(buffer -> endFrameOnDelimiter(buffer, matcher))
				.bufferUntil(buffer -> buffer == END_FRAME)
// a lot more
	}
```

With this, users are forced to cache the whole file content (alteast one full part) in RAM before its consumed. What if I as a user dont want to cache/even write temporarily to disk by framework, but want to have backpressure (whole point of using reactive streams) & want the framework not to do pre read & cache everything in memory

Here are my two cents on how the implementation might needs to be changed to

`Part.content()` should be return `Flux<Flux<DataBuffer>>` instead of `Flux<DataBuffer>` & each of the top level `Flux` corresponds to the `Part` from http request

This way, you dont buffer the data in memory & allow the backpressure be properly cascaded

Please let me know your thoughts

**Comment by thekalinga** [comment]
Since my suggestion implies a breaking change, may be add a new another method

```java
public interface Part {
	String name();
	HttpHeaders headers();
        @Deprecated
	Flux<DataBuffer> content();
	Flux<Flux<DataBuffer>> contentStream(); // for true streaming
}
```

**Comment by thekalinga** [comment]
Also, why is `flatMap` used inside `split` method, when we care about the order. Since this is a synchronous operation, we are not seeing the issue of out of order packets

But we should use `concatMap` instead to make things explicit that we care about the order in which data is processed

**Comment by thekalinga** [comment]
Please note that these are my observations, which might/might not be correct. Appreciate if you can help me on this

**Comment by thekalinga** [comment]
Have deleted few comments & corrected few comments above as they were wrong/misleading

**Comment by thekalinga** [comment]
Please note that I dont have the complete understanding of the source. Its possible that I might have the incorrect understanding

**Comment by thekalinga** [comment]
If I am not wrong, we can add the following methods instead to have lazy reading & not buffer anything

```java
public static Flux<Flux<DataBuffer>> streamingSplit(Publisher<DataBuffer> dataBuffers, byte[] delimiter) {
    DataBufferUtils.Matcher matcher = matcher(delimiter);
    return Flux.from(dataBuffers)
        .concatMap(buffer -> {
          return endFrameOnDelimiter(buffer, matcher, delimiter.length)
              .windowWhile(bufferFragment -> bufferFragment == END_FRAME);
        })
        .doOnDiscard(PooledDataBuffer.class, DataBufferUtils::release);
  }

  private static Flux<DataBuffer> endFrameOnDelimiter(DataBuffer dataBuffer, DataBufferUtils.Matcher matcher, int delimiterLength) {
    List<DataBuffer> result = new ArrayList<>();
    do {
      int endIdx = matcher.match(dataBuffer);
      int readPosition = dataBuffer.readPosition();
      if (endIdx != -1) {
        int length = endIdx + 1 - readPosition ;
        result.add(dataBuffer.retainedSlice(readPosition, length));
        result.add(END_FRAME);
        dataBuffer.readPosition(endIdx + delimiterLength + 1); // lets skip delimiter length
      } else {
        result.add(retain(dataBuffer));
        break;
      }
    } while (dataBuffer.readableByteCount() > 0);

    DataBufferUtils.release(dataBuffer);
    return Flux.fromIterable(result);
  }
```

Please let me know what you think

**Comment by poutsma** [comment]
@thekalinga I think you are right, and have created #23184 to track this issue. Thank you for trying the 5.2 milestones and reporting bugs in them!

In the future, feel free to file an issue directly instead of commenting on a closed issue (though you might want to refer to your newly created issue in a comment, to get our attention).

**Comment by poutsma** [comment]
> ```java
> private static Flux<DataBuffer> endFrameOnDelimiter(DataBuffer dataBuffer, DataBufferUtils.Matcher matcher, int delimiterLength) {
>   ...
>       dataBuffer.readPosition(endIdx + delimiterLength + 1); // lets skip delimiter length
>   ...
> }
> ```

AFAICT, the only difference in your last snippet is the one that skips the delimiter length (shown above). But `endIdx` points to the index of the *last* byte of the delimiter, so there is no need to skip further ahead.

**Comment by poutsma** [comment]
The refactoring of the `DefaultMultipartParser` proved to be too ambitious for the 5.2 release deadline, so we are pushing this issue back to the next release.

**Comment by mdzhigarov** [comment]
Any update on this? Are there plans to move away from Synchronoss nio-multipart in one of the next releases?

**Comment by poutsma** [comment]
Yes, this planned for 5.3.
