### ISSUE TITLE
Document safe navigation semantics within compound expressions in SpEL

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21827]
**[Giulio Quaresima](https://jira.spring.io/secure/ViewProfile.jspa?name=giulio.quaresima)** opened **[SPR-17294](https://jira.spring.io/browse/SPR-17294?redirect=false)** and commented

When I use the [Safe Navigation operator](https://docs.spring.io/spring/docs/4.3.19.RELEASE/spring-framework-reference/html/expressions.html#expressions-operator-safe-navigation) my expectation is that it is always safe to evaluate an expression with null values. But in some contexts I get the SpelEvaluationException with the message "EL1012E:(pos 11): Cannot index into a null value".

See the example attached.

---

**Affects:** 4.3.19

**Attachments:**
- [SpringSpelBug.java](https://jira.spring.io/secure/attachment/26025/SpringSpelBug.java) (_1.74 kB_)

**Comment by aantono** [comment]
:bump  Any updates on fixing this?

**Comment by sbrannen** [comment]
@aclement, ping.

**Comment by sbrannen** [comment]
In order to avoid introducing additional complexity in the implementation of the Spring Expression Language, we have decided not to resolve an entire compound expression to `null` when the null-safe operator is used on a preceding node but not on subsequent nodes.

In other words, use of the null-safe navigation operator is required on all nodes in a compound expression, which aligns with the behavior of other languages such as Groovy.

I am therefore repurposing this ticket to document the current behavior.

Furthermore, please note that we will introduce a null-safe index operator in Spring Framework 6.2.

#### Related Issues

- #29847
- #32208
