### ISSUE TITLE
Asynchronous EntityManagerFactory bootstrapping to complete on context refresh completion [SPR-17334]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21868]
**[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson)** opened **[SPR-17334](https://jira.spring.io/browse/SPR-17334?redirect=false)** and commented

When a `LocalEntityManagerFactory` bean is configured with a bootstrap executor, there's a race between application context refresh and native entity manager factory bootstrapping. This makes things awkward for any logic that wants to run once bootstrapping has completed, for example something that relies on Hibernate DDL processing.

I've attached a small example that hopefully illustrates the problem. When imported into your IDE and run, `EmfBootstrappingRaceApplication` should thrown an exception when executing the `SELECT` query using `JdbcTemplate`. The failure will not occur if `factory.setBootstrapExecutor(executor);` is commented out. The failure will occur intermittently if the artificial delay introduced by the async executor is removed.

---

**Affects:** 4.3.19, 5.0.9, 5.1 GA

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/14658

**Attachments:**
- [emf-bootstrapping-race.zip](https://jira.spring.io/secure/attachment/26039/emf-bootstrapping-race.zip) (_49.57 kB_)

**Comment by jhoeller** [comment]
Revisiting this ticket in the backlog, I'm wondering what the current state of affairs is in Boot there.

Would a dedicated completion callback for EntityManagerFactory bootstrapping still be useful?

Should we consider introducing an option to wait for EntityManagerFactory completion at the end of context refresh, e.g. through joining the underlying Future on `ContextRefreshedEvent`? FWIW this can be externally accomplished already: through a custom `ContextRefreshedEvent` listener that casts the injected `EntityManagerFactory` handle to `EntityManagerFactoryInfo` and calls `getNativeEntityManagerFactory()` on it. This might be more natural to provide at Boot level than Framework level.

In any case, I'd like to close this ticket for good in the 6.1 timeframe.

**Comment by jhoeller** [comment]
Following up on our background initialization option for the core container (#13410) with its strict rules, it seems sensible to enforce completion of asynchronous EMF initialization before context refresh completion (just like we do for `@Bean(bootstrap=BACKGROUND)`). While the original motivation of letting the EMF initialize up until the first request tries to use it, the lack of predictability is an issue indeed. Also, most applications have some kind of startup-time database operations anyway, effectively - but not reliably - forcing EMF initialization to have completed then. We should align this for better predictability.

Unless there is a compelling case made, I do not intend to let users opt out of this in order to enforce the predictability for JPA/Hibernate initialization specifically. So the behavior will simply be stricter in 6.2, always completing in time for context refresh completion. This enables us to rely on `ContextRefreshedEvent` for post-initialization tasks that can reliably assume the database to have been initialized (as a solution for #26153, effectively turning it into a documentation task).
