### ISSUE TITLE
Provide additional debug information for memory leaks via ByteBuf.touch [SPR-17427]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21960]
**[Violeta Georgieva](https://jira.spring.io/secure/ViewProfile.jspa?name=violetagg)** opened **[SPR-17427](https://jira.spring.io/browse/SPR-17427?redirect=false)** and commented

Hi,

Netty provides the following API

```java
io.netty.buffer.ByteBuf.touch()


    /**
     * Records the current access location of this object for debugging purposes.
     * If this object is determined to be leaked, the information recorded by this operation will be provided to you
     * via {@link ResourceLeakDetector}.  This method is a shortcut to {@link #touch(Object) touch(null)}.
     */
    ReferenceCounted touch();
```

When the implementation does additional transformations of the content or buffers this object, please use this **touch()** functionality. If there is a memory leak, when Netty dumps the stack traces of the components that accessed this object, it will be easier to find where the buffer was leaked.

Thanks,
Violeta

 

---

**Affects:** 5.1.1

**Comment by rstoyanchev** [comment]
Adding a `touch` call here does make sense:
https://github.com/spring-projects/spring-framework/blob/57de2e09008e0bd80683df63b40f0748945e83aa/spring-core/src/main/java/org/springframework/core/io/buffer/NettyDataBufferFactory.java#L92-L94 because we're wrapping the buffer and keeping it. 

The constructor however is not suitable because that's also called from places that slice or retain and those Netty already records, so there is no need for us to do it too.
