### ISSUE TITLE
UserCredentialsDataSourceAdapter is not updating the credentials [SPR-17494]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22026]
**[Arunprasad](https://jira.spring.io/secure/ViewProfile.jspa?name=arunjumbo)** opened **[SPR-17494](https://jira.spring.io/browse/SPR-17494?redirect=false)** and commented

Hi Team,

I have a requirement like where I have a password to connect to database  which will be sent by different team through rest api. So in persistence context I connect to the service and get the password and create datasource object with the credentials, now since connection is made using persistence context it will create some active threads. But if suppose I am using the application and suddenly password changed and I have to get the updated password, since there is no functionality to check when the password is changed, I have to call the webservice before each database call in my application. If password is changed then I am using USerCredentialsDataSource Adaptor and setting the changed password, but issue here is even though password is changed the connections are still made with old password. So I am missing something in the code, please help. 

---

**Attachments:**
- [Spring case.docx](https://jira.spring.io/secure/attachment/26097/Spring+case.docx) (_43.23 kB_)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
