### ISSUE TITLE
Add unique number to WebFlux log prefix for Reactor Netty server

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22039]
**[Robbert van Waveren](https://jira.spring.io/secure/ViewProfile.jspa?name=robbert)** opened **[SPR-17507](https://jira.spring.io/browse/SPR-17507?redirect=false)** and commented

Expected behavior:
Every HTTP request is logged with a unique log prefix regardless of any tcp/ip connection or thread reuse.

Observed behavior:
Consecutive HTTP requests from Chrome (using keep-alive) that are handled by the same reactor-http-nio thread are logged with the same log prefix.

 

---

**Affects:** 5.1.2

**Attachments:**
- [issue-project.zip](https://jira.spring.io/secure/attachment/26100/issue-project.zip) (_9.08 kB_)

**Issue Links:**
- #22038 HTTP GET from Chrome with WebFlux Rest Controller never completes

**Comment by GwiYeong** [comment]
Hi. any update for this issue? 
i came from this [link](https://stackoverflow.com/questions/58500442/why-im-getting-same-logprefix-in-webfilter-between-different-requests) that i asked stackoverflow.

what is `status: blocked` means?  
any workaround to get unique string for each requests?

**Comment by snicoll** [comment]
@GwiYeong there is a description [for each label](https://github.com/spring-projects/spring-framework/labels):

> An issue that's blocked on an external project change

The [comment above yours](https://github.com/spring-projects/spring-framework/issues/22039#issuecomment-453479531) has a link to an unresolved issue in the `reactor-netty` project that we need to move further.

**Comment by rstoyanchev** [comment]
HTTP/2 streams should be addressed as part of https://github.com/reactor/reactor-netty/issues/549 and it looks like that will be transparent to us. In general where the underlying server exposes a connection id, we will use that, so if you need something further I believe that should be done at the Reactor Netty level. Otherwise the logs between Reactor Netty and WebFlux won't be entirely consistent.

**Comment by PyvesB** [comment]
We've enabled debug logging for incoming web server requests and have bumped into this issue as well. The Javadocs of ServerWebExchange suggest that the log prefix can be used to correlate messages for a given exchange:
https://github.com/spring-projects/spring-framework/blob/daa30a9f0b6bcc33cbb452e7a1df27776acfa935/spring-web/src/main/java/org/springframework/web/server/ServerWebExchange.java#L221

However, as the underlying channel id is being used (see [here](https://github.com/spring-projects/spring-framework/blob/9b30d46ff4653c411ee4c8edb89b9bafa11b2ee9/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpRequest.java#L185)), the same log prefix may be duplicated across different requests (for example if the connection is kept alive). Logs for different requests and responses will end up being mixed up together due to this.

@rstoyanchev suggestion about appending "-N" to the id where N is an incremental number to make it unique would be ideal, as it would prevent exchanges being mixed up together whilst still allowing to correlate with underlying reactor-netty log messages.

Could this issue please be reopened?

**Comment by PyvesB** [comment]
Thanks for working on this @rstoyanchev! 👍

**Comment by pdevalck** [comment]
I created issue #26430 for the Undertow reactive server
