### ISSUE TITLE
Possibly a wrong order of assertion in PayloadArgumentResolver [SPR-17503]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22035]
**[olegz](https://jira.spring.io/secure/ViewProfile.jspa?name=olegz)** opened **[SPR-17503](https://jira.spring.io/browse/SPR-17503?redirect=false)** and commented

While working on https://github.com/spring-cloud/spring-cloud-stream/issues/1527 I noticed that MessageConversion was not attempted on handler with signature `public Person echo(Object value)` where the payload was actually `byte[]`

 

I believe it is due to the following code on line 130. I believe the order of arguments should be different `if (ClassUtils.isAssignable(payloadClass, targetClass))`

 

---

**Affects:** 5.1.2

**Comment by rstoyanchev** [comment]
A problem with the suggestion I made previously is that with a `CompositeMessageConverter`, if the first one does not care about this issue, it would conclude that no conversion is required, and others will not get a chance.

@olegz looking at your changes, I'm not sure they make sense in the general case. What we want is to make sure is the payload can be assigned to the target type, i.e. it will not cause ClassCastException but otherwise can be more general. Not the other way around where if the payload type is more general than the target type, it would pass the check but fail with a ClassCastException.

The way you were describing it makes more sense:

> The argument I am making is that explicit definition of Object or ? as an input type could also mean "do not/can not use input type as a conversion driver, what is my content-type?" and if content-type is `text/**` what else can it be other then String regardless of what the input type is? This essentially puts CT `text/**` in a special category, but then again some may disagree.  

Specifically what I see here is a case where the target is `Object`, which is intentionally to general and not useful for conversion decisions. Something else needs to be used to choose a more specific target type, e.g. based on the media type.

What I can suggest is a method like this in PayloadArgumentResolver and also MessageMethodArgumentResolver:

```
protected Class<?> resolveTargetClass(MethodParameter parameter, Message<?> message) {
	return parameter.getParameterType();
}
```
Then SCS can override that and return `String.class` when the target is `Object.class` and media type is `text/*`. 

Another alternative would be to have special handling for target class of `Object.class`, i.e. in the resolvers allow it to be converted and then in converters like Jackson, return false for it.

**Comment by rstoyanchev** [comment]
I have gone ahead and added protected methods for resolving the target class.
