### ISSUE TITLE
Provide access to the WebSocket close status in WebFlux

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22079]
**[Sola](https://jira.spring.io/secure/ViewProfile.jspa?name=soladev)** opened **[SPR-17547](https://jira.spring.io/browse/SPR-17547?redirect=false)** and commented

Currently, both server-side and client-side on the Reactive stack cannot get CloseStatus when the other side actively closes the connection.

the CloseStatus can be useful when the remote closes with a reasonable reason.

---

**Affects:** 5.1.3

**Comment by unlimitedsola** [comment]
the original reporter here.

**Comment by rstoyanchev** [comment]
Looks like this is no longer blocked as of Reactor Netty 0.9.

**Comment by Fetsivalen** [comment]
Hi,
Is anyone working on this issue?

I'd like to contribute it to the ReactorNettyWebSocketSession,
but I wonder is this ticket is about ReactorNetty's implementation only, or it is about all implementations of the WebSocketSession (not sure that each implementation will give such a possibility)?

**Comment by rstoyanchev** [comment]
`ReactorNettyWebSocketSession` is the starting point but we'd want to expose it on `WebSocketSession` since that's what an application is typically using. From there it will need to be implemented across but all other servers make this available in their API.

Short answer is yes for all implementations.
