### ISSUE TITLE
Add String based URI template variants to RequestEntity  [SPR-17551]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22083]
**[Ryon Day](https://jira.spring.io/secure/ViewProfile.jspa?name=ryonday)** opened **[SPR-17551](https://jira.spring.io/browse/SPR-17551?redirect=false)** and commented

The `RestTemplateBuilder` documentation for the `rootUri()` method states:

"Set a root URL that should be applied to each request that starts with '/'."

However, the following code does not result in `RestTemplate` expanding the URI:

```java
UriTemplate template = new UriTemplate("/foo?bar={bar}");

this.restTemplate = restTemplateBuilder
 .rootUri(URI.create("http://foo.bar"))
 .build();

URI uri = template.expand("baz");
RequestEntity<Void> req = RequestEntity.get(uri)
 .accept(MediaType.APPLICATION_JSON)
 .header(accountLinkHeader, accountLinksHeader)
 .build();
String response = restTemplate.exchange(req, String.class);
```

 

Moreover, the exception received is EXTREMELY ambiguous when this doesn't work. In fact, the Spring exception thrown occludes the initial Apache exception (which states there's no host).

---

**Affects:** 5.1.3

**Comment by aberkecz** [comment]
Hi,

I would love to help out with this issue if it's up for grabs. I spent some time investigating it but got stuck a bit when trying to figure out a nice solution.

So far, I've created an example project to see if the issue is still valid and found out that it is. However, the Javadoc for `RestTemplateBuilder#rootUri` has been clarified to describe the above behaviour. 

 Now, I’m a bit confused because I’m not entirely sure what would be a nice way to do the expansion when a `RequestEntity` is used. (Do I extend the `RequestEntity` with new public methods expecting a String templateUri? But how do I expand it there when I only have the `rootUri` set in the `RestTemplate` instance?)

Would it be helpful if I tried and submitted a PR for this? If so, could you please help me with some guiding on how to get started?

Thanks!

**Comment by rstoyanchev** [comment]
@aberkecz thanks for considering this and yes this is marked "ideal-for-contribution".

For the implementation, I can suggest something like this:
1. Add extra static RequestEntity methods (per HTTP method) that accept a String-based URI template.
1. Add methods in the builder (`RequestEntity.HeadersBuilder` probably) that accept URI variables as either vararg or a Map.
1. Add private `RequestEntity` constructor that accepts `java.net.URI` and String-based URI template + varargs and store those are nullable fields (it's either-or).
1. Add overloaded `public URI getUrl(UriTemplateHandler)` method to `RequestEntity` which expands the URI template if it has one, or otherwise returns the `URI` it has.
1. Make use of this new method in `RestTemplate`.

**Comment by parviz-93** [comment]
HI.
Are work underway on this task?
Last comment was 12 days ago ... If activity does not go, I would like to take this task

**Comment by parviz-93** [comment]
opened Pull Request [24446](https://github.com/spring-projects/spring-framework/pull/24406)

**Comment by rstoyanchev** [comment]
Superseded by #24406.

**Comment by aberkecz** [comment]
@rstoyanchev : got my notifications and totally missed your reply. Sorry about that. :(

As I can see, there is already a PR open for that so I will look for a new issue and be careful with the notifications next time...
