### ISSUE TITLE
Upgrade Spring Context Support to Jakarta EE's com.sun.mail:jakarta.mail and com.sun.activation:jakarta.activation [SPR-17561]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22093]
**[Juergen Zimmermann](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.zimmermann)** opened **[SPR-17561](https://jira.spring.io/browse/SPR-17561?redirect=false)** and commented

Spring Context Support is using _javax.mail:javax.mail-api_ and _javax.activation:javax.activation-api_. Meanwhile there is _com.sun.mail:jakarta.mail_ and _com.sun.activation:jakarta.activation_.

---

**Affects:** 5.1.3

**Comment by pontello** [comment]
@spring-issuemaster , what is the correct way to tell spring CDI that `jakarta.inject.Inject` plays the same role as `javax.inject.Inject`?

I've researched a lot aboud this topic and haven't figured out an elegent solution for it. Please note that **@AliasFor** isn't an option because I can't annotate jakarta packages.
