### ISSUE TITLE
Support for Hibernate ORM 6.0/6.1 [SPR-17596]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22128]
**[Juergen Hoeller](https://jira.spring.io/secure/ViewProfile.jspa?name=juergen.hoeller)** opened **[SPR-17596](https://jira.spring.io/browse/SPR-17596?redirect=false)** and commented

Hibernate ORM 6.0 alpha 1 was recently released (in December 2018). Let's introduce a `org.springframework.orm.hibernate6` support package in the Spring Framework 5.2 timeframe, in parallel to our existing Hibernate ORM 5.x support.

---

**Issue Links:**
- #22049 Upgrade to Hibernate ORM 5.4

**Comment by jhoeller** [comment]
At this point, it looks like Hibernate ORM 6.0 won't be final in time for our 5.2 GA timeframe in June. While we're going to make sure that Spring's JPA support works fine against Hibernate ORM 6.0 pre-releases, a dedicated `orm.springframework.orm.hibernate6` package is probably better off in our next feature release.

**Comment by jhoeller** [comment]
On review, `HibernateTemplate` does not seem feasible to sustain anymore against Hibernate 6.0 since plenty of underlying API has changed or even been removed. We meant to phase out `HibernateTemplate` before, so this seems to be the definitive time for it. We can keep the Hibernate 5.x variant of `HibernateTemplate` around but won't introduce a dedicated 6.0 variant.

For all common purposes, our JPA support seems to be compatible with Hibernate 6.0 since #28007. From that perspective, there isn't much need for dedicated support for native Hibernate APIs from Spring's side. That said, let's keep this general support ticket open for the time being, to be revisited towards Spring Framework 6.0 GA for a final decision.

**Comment by jhoeller** [comment]
This is considered complete as of Spring Framework 6.0 RC1, as per the description above: support for Hibernate ORM 6.0/6.1 in a JPA setup, with `org.springframework.orm.hibernate5` remaining in place for native Hibernate based code for the time being. Support for Hibernate 5.x is limited to Hibernate ORM 5.6.x with JPA as well as the native Hibernate API.
