### ISSUE TITLE
DefaultCorsProcessor does not set "vary: Origin" if the request has no Cors header

### ISSUE THREAD

**Issue by Keroxo** [spring-projects/spring-framework#22273]
The DefaultCorsProcessor will not set the "vary: Origin" header in the response, if the request is not a cors request. 

Scenario: 
* The user visits the original page (without CORS).
* Some scripts are cached without CORS and vary headers
* The user visits page B which is using the same scripts. The browser wants to load them from the cache but get a CORS Error because of the missing CORS headers.

Discussions regarding this topic:
https://github.com/spring-projects/spring-framework/issues/18378 (especially the last comment)
https://stackoverflow.com/questions/25329405/why-isnt-vary-origin-response-set-on-a-cors-miss

I use Spring Boot 2.1.1.RELEASE

Are there any known workarounds?

**Comment by sdeleuze** [comment]
Did you manage to reproduce the issue without a CDN being involved (only browser cache)?

**Comment by Keroxo** [comment]
Here is a repo with a demo Spring application:
https://github.com/Keroxo/spring-cors-demo-backend

Here is a demo client:
https://github.com/Keroxo/spring-cors-demo-client

You should run both on a different server. The Spring Application should take the default port 8080. The client can run under any port. I used 8088 for testing. For running the client I used [http-server](https://www.npmjs.com/package/http-server).


1. Visit localhost:8088
 It will get the data from localhost:8080/data via xhr request. Take a look at the CORS-Headers like `vary:origin`
2. Reload localhost:8088
 See, that the data will be fetched from the disk cache
3. Visit localhost:8080/home 
Its also requesting localhost:8080/data and will not fetch from cache because of the vary:origin header of the cached version. Look at the CORS-Headers of the newly fetched data.json. There will be no CORS Headers at all.
4. Revisit localhost:8088
There will be an error when fetching the data json because the cached version has no cors Headers:
`Access to XMLHttpRequest at 'http://localhost:8080/data' from origin 'http://localhost:8088' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
 
I hope that helped to clarify the problem

**Comment by sdeleuze** [comment]
Thanks for the projects, I can indeed reproduce the issue with Chrome.

Currently what happens is that `CorsProcessor` is not used for non CORS requests ([see `AbstractHandlerMapping`](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerMapping.java#L423-L428)) so even if we modify `DefaultCorsProcessor` that will not solve this issue.

On the other side, setting `Vary: Origin` for every webapps, even those not using CORS, is probably not a good idea. 

A potential solution could be to determine at startup if CORS is configured by the user (globally or with annotation), and set `Vary: Origin` only if that's the case. The issue is that in `AbstractHandlerMapping` we can know if CORS has been globally configured, but I don't think we can easily detect if there are `@CrossOrigin` annotations. But that could be a potential evolution since it seems doable via `AbstractHandlerMethodMapping#mappingRegistry`.

I also tend to think we could use this kind of boolean status computed are startup to do some optimization like avoiding to check CORS headers for each request (even more useful since Chrome is sending `Origin` headers even for non CORS requests), avoiding to create `DefaultCorsProcessor` if not needed, etc.

Any thoughts @rstoyanchev?

**Comment by rstoyanchev** [comment]
@sdeleuze given that annotations allow fine-grained configuration, wouldn't we actually want to know more specifically if CORS is configured for a given endpoint? So while currently in `AbstractHandlerMapping` we check CORS config only if it is a CORS request but we could check also if it isn't. If we find CORS config but it's not a CORS request, set the Vary header only.

As for finding on startup if CORS is configured at all, and possible optimizations, I could see potentially a protected method in `AbstractHandlerMapping` that sub-classes can implement to indicate if they have any CORS config at all. `AbstractHandlerMethodMapping` can easily check its corsLookup. So for for any HandlerMapping it should be possible to determine if there is any CORS config at all (global or handler declared).

**Comment by sdeleuze** [comment]
@rstoyanchev I thought about checking CORS configuration for non CORS requests, but I don't think we should add this performance penalty that will impact also all the webapps that don't use CORS. The trade-off of setting `Vary: Origin` for all requests when CORS is enabled + the optimization it enables looks like a better alternative to me, especially given our current performance effort.

Given the required changes, I would be for making these changes part of Spring Framework 5.2 (we will of course discuss the PR before merging in `master`). Is it ok for you?

**Comment by rstoyanchev** [comment]
The `HandlerMethod` CORS lookup seems to be a straight-up lookup into a Map. Why would it add much overhead? If the concerns is creating objects, e.g. to combine global + local, we could optimize by including an extra protected method to check if there is CORS config for a given request (like the one to check globally on startup). At any rate let's set it for 5.2.

**Comment by johnou** [comment]
@sdeleuze shouldn't this be classed as a security fix? it could be used for cache poisoning attacks.
