### ISSUE TITLE
Got 404 with non-ASCII coded static resources in webflux

### ISSUE THREAD

**Issue by BiLuoHen** [spring-projects/spring-framework#22272]
![image](https://user-images.githubusercontent.com/12087354/51299309-0507ea00-1a63-11e9-95d7-87b78bbbd96b.png)
![image](https://user-images.githubusercontent.com/12087354/51299322-105b1580-1a63-11e9-9b2d-7448eb9ddcce.png)
I configed `spring.http.encoding.charset=UTF-8` and `spring.http.encoding.enabled=true` and `spring.http.encoding.force=true,` but webflux does't decoding the filename , so response me 404; PS: spring webmvc works fine

**Comment by BiLuoHen** [comment]
@Rossen Stoyanchev I find the problem is here:
![image](https://user-images.githubusercontent.com/12087354/51317166-d35a4780-1a91-11e9-8f64-ded47c114700.png)

this is the spring mvc:
![image](https://user-images.githubusercontent.com/12087354/51317265-11576b80-1a92-11e9-888a-15bb5549d239.png)

last: forgive my poor English^-^

**Comment by rstoyanchev** [comment]
Don't compare with Spring MVC in this regard. WebFlux uses a structured representation of the path, which contains the decoded value. Can you provide an isolated sample?

**Comment by BiLuoHen** [comment]
I know webflux uses the `PathContainer`, you get the path value in this way: `String path = processPath(pathWithinHandler.value());`, the `PathContainer.value()` just return the non-decoded path `@Override
	public String value() {
		return this.path;
	}` 
the `processPath()` method does't decode the path too.
this is the simple demo: [https://github.com/BiLuoHen/demo](url),
visit the [http://localhost:8080/pic.png](url) will get the pic resource, 
vist the [http://localhost:8080/图片.png](url) or [http://localhost:8080/%E5%9B%BE%E7%89%87.png](url) will got 404 response

**Comment by rstoyanchev** [comment]
Thanks for the sample. It confirms the issue. Basically `ResourceWebHandler` passes the undecoded String representation of the request path to the resource resolver chain which expects it to be decoded. The same needs to be fixed in `ResourceUrlProvider` even if that one is not used here.

The `PathContainer` provide a way to access to individual path segment values in decoded form but no way to get the full undecoded path. The latter is not necessary for path matching where we compare one segment at a time, but we'll need the former for resource paths.

**Comment by rstoyanchev** [comment]
This turned out to be more involved. 

The encoded path works as expected for `UrlResource` locations (e.g. file, HTTP url, etc) and is actually the preferred way to do it since it protects against traversal attacks or misinterpretation of encoded "/", "\", and others. On the Spring MVC side we even make an [extra effort](https://github.com/spring-projects/spring-framework/blob/0bdacddc53c576768151485055f739d606dd91f6/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/ResourceHandlerRegistration.java#L74-L77) to re-encode. So what we have in WebFlux is a good basis but we want to make sure it works for classpath and other non-URL resources too.

I'm moving to 5.2. In the mean time, you could access the `locations` property of `ResourceWebHandler` post initialization and decorate any `ClasspathResource` location to override the `createRelative` method in order to decode the relative path.

**Comment by BiLuoHen** [comment]
thanks a lot, I will try it.
