### ISSUE TITLE
HibernateTemplate.bulkUpdate deprecated but no replacement provided

### ISSUE THREAD

**Issue by djechelon** [spring-projects/spring-framework#22271]
I have noticed that during upgrade from Spring 4.3 to 5.1 HibernateTemplate.bulkUpdate has been deprecated

Source: https://docs.spring.io/spring-framework/docs/current/javadoc-api/deprecated-list.html
Source: https://github.com/spring-projects/spring-framework/blob/master/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTemplate.java#L1058

In the docs, it is not specified how to properly replace the handy `bulkUpdate` method.

Request here is to document how should one replace the deprecated bulkUpdate method in his/her code.

----
Comment:

I also have read #20972 but fail to understand why can lambdas be more elegant than a handy dirty method.

In my case, I am writing unit tests and I want a quick and _not-too-dirty-but-dirty-is-acceptable_ way to clear the database or do bulk operations.

In the past, I used

new HibernateTemplate(sessionFactory).bulkUpdate("delete from Entity");

Now I have to use
new HibernateTemplate(sessionFactory).execute(session->session.createQuery("delete from Entity").executeUpdate());

In my personal opinion, the second doesn't look so better than the first. And yes, bulkUpdate runs a lambda internally.

**Comment by rstoyanchev** [comment]
> In the docs, it is not specified how to properly replace the handy bulkUpdate method.

It is specified:
https://github.com/spring-projects/spring-framework/blob/ffe888ca1818f8e9901d3daeeb3dfb1464161d25/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateOperations.java#L42-L51

and here:
https://github.com/spring-projects/spring-framework/blob/ffe888ca1818f8e9901d3daeeb3dfb1464161d25/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateOperations.java#L851-L852

The underlying reason is is explained in the ticket you referenced:

> In anticipation of Hibernate ORM 5.3 (#20850) and for example **its removal of legacy positional parameters**, let's revisit HibernateTemplate and possibly deprecate affected operations upfront, allowing either for removal in Spring Framework 5.1/5.2 or at least for only supporting them against Hibernate ORM 5.0-5.2 but not 5.3.
