### ISSUE TITLE
Spring-Data- MongoDB MappingMongoConverter-- writeMapInternal() convertion issue with map value of List<LocalDate>s 

### ISSUE THREAD

**Issue by bsreddy125** [spring-projects/spring-framework#22312]
Map<String, List of LocalDate> is getting saved as as Map<String, List of String>.
Its Basically conversion issue with MAppingMongoConverter.writeMapInternal . While reading its throwing a conversion error like can't convert string to LocalDate.

Kindly suggest the workaround for this

**Comment by sdeleuze** [comment]
Thanks for getting in touch, but it feels like this is a question not related to Spring Framework and that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
