### ISSUE TITLE
ApplicationContext.refresh() causes stale listeners to be added to ApplicationEventMulticaster 

### ISSUE THREAD

**Issue by eknizat** [spring-projects/spring-framework#22325]
The problem is caused by the change in Spring AbstractApplicationContext, in particular how it handles the addition of ApplicationListener objects.
In short, all of the registered ApplicationListener objects are retained even after application context is refreshed, 
at which point the stale listeners become unusable as AbstractLifecycleBean(s) would have had their destroy methods invoked.

The change that caused this problem:
https://github.com/spring-projects/spring-framework/issues/21858
Commit:
https://github.com/spring-projects/spring-framework/commit/c8c0737ce712569a7e03a97dfe7ef11cbbc33e39

With this commit all listeners are added to AbstractApplicationContext's list applicationListeners instead of just adding them to an instance of ApplicationEventMulticaster.
This causes stale listeners to be added to a new instance of ApplicationEventMulticaster when the AbstractApplicationContext is refreshed via its refresh() method.
The refresh() method creates a new ApplicationEventMulticaster but then it adds all of the stale listeners (by registerListeners()) from its list of listeners.
Subsequently, when the refresh finishes (AbstractApplicationContext.finishRefresh()), a new instance of ApplicationEventMulticaster publishes the refresh event too all registered listeners, including the stale listeners whose destroy methods were called as part of the refresh.

**Comment by jhoeller** [comment]
@wilkinsona since this one addresses a side effect of #21858 which you requested, could you please double-check that the revision (in master and 5.1.x at this point) still works for your purposes, exposing all application listeners that you intend to see from `getApplicationListeners()`? I'll backport it to 5.0.x then where we backported the original change as well.

**Comment by wilkinsona** [comment]
This looks good to me with 5.1.5 snapshots. The sample provided with https://github.com/spring-projects/spring-boot/issues/14490 stops as expected.

**Comment by jhoeller** [comment]
Alright, good to hear. Thanks for the immediate feedback!

**Comment by jhoeller** [comment]
@eknizat since this is available in `5.1.5.BUILD-SNAPSHOT` from https://repo.spring.io/snapshot now, do you have a chance to give it an early try in your scenario before the official 5.1.5 release on Wednesday?

**Comment by eknizat** [comment]
The 5.1.5 snapshot works as expected. Thanks.

**Comment by rom16rus** [comment]
This issue is closed, but @jhoeller can you check this line, please [condition](https://github.com/spring-projects/spring-framework/blob/9689a59ab1b8432d8eba688247fc5cb86e602871/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L606)

I have the following problem: on the application startup there is a call of `prepareRefresh()`, so it works like that 

`this.earlyApplicationListeners = new LinkedHashSet<>(this.applicationListeners);` 

There are this.applicationListeners is an empty collection.
Then it's needed to refresh the Application Context, so it provokes the `refresh()` at AbstractApplicationContext, then goes to `prepareRefresh` and then checks 

`this.earlyApplicationListeners == null`, 

but it's an empty LinkedHashSet, not null, so then it comes to
`this.applicationListeners.clear();` 
and all the listeners are removed,  but this collection is not empty, so I'm loosing all of applicationListeners there.
Just FYI it was filled by CXF transports [here is the hack](https://github.com/apache/cxf/blob/ec4423437bd7d6b63e3464761394cfafb50cacfa/rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/CXFServlet.java#L90)

All in all, is there a reason to change the null checking to isEmpty? Or what will be the better decision?
Thank you in advance.
