### ISSUE TITLE
spring-context-indexer seems to do nothing

### ISSUE THREAD

**Issue by the4yeast** [spring-projects/spring-framework#22338]
I've included the dependency as per https://docs.spring.io/spring/docs/5.1.2.RELEASE/spring-framework-reference/core.html#beans-scanning-index into my Boot app. 

The app is fairly trivial, with one controller and one service.

When I build my fat jar and unpack it, I do not see the `spring.components` file in `META-INF`. 
Is there a way for me to get more insight into the process? How do I know the indexer is invoked?

**Comment by vpavic** [comment]
Are you using Gradle? If so, `annotationProcessor` configuration should be used to add `spring-context-indexer` dependency - I've opened #22339 to address this in reference manual.

**Comment by snicoll** [comment]
Thanks @vpavic, it could be related though I am quite surprised that Gradle stopped handling `compileOnly` in the `4.x` line. 

@the4yeast regardless of whether this is your problem or not, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted StackOverflow question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by the4yeast** [comment]
thanks @vpavic 

sorry @snicoll, I didn't realise that was the process. If/when I have the next question, I'll ask on SO.

This is the question in SO: https://stackoverflow.com/questions/54524942/spring-context-indexer-seems-to-do-nothing-on-gradle-4-6. I'll follow up there.
