### ISSUE TITLE
Webflux functional endpoints can't handle nesting and pathvariables

### ISSUE THREAD

**Issue by MOES-Media** [spring-projects/spring-framework#22399]
When I'm creating nested routes and have a pathVariable in the parent route, the root call to the nested paths goes to the handler in the parent route.

```
@Bean
    public RouterFunction<ServerResponse> testRoutes(){
        return nest(path("/test"),
                route(GET("/"), serverRequest -> ServerResponse.ok().syncBody("TEST"))
                        .andRoute(GET("/{id}"), serverRequest -> ServerResponse.ok().syncBody("TEST WITH ID"))
                        .andNest(path("/other"),
                                route(GET("/{id}"), serverRequest -> ServerResponse.ok().syncBody("OTHER WITH ID"))
                                        .andRoute(GET("/"), serverRequest -> ServerResponse.ok().syncBody("OTHER"))));
    }
```

I would expect a get call to "/test/other" would return "OTHER" instead it returns "TEST WITH ID"

**Comment by bclozel** [comment]
Hi @MOES-Media 

Thanks for reaching out after [our discussion on StackOverflow](https://stackoverflow.com/questions/54605469/webflux-nested-router-on-root-always-returns-404).

As mentioned in my latest comment on my answer, this is the expected behavior.

`RouterFunction` is a functional way of representing the routing process; unlike the annotation model, where all routes are considered and only the most specific one is selected for processing the request, `RouterFunction` is executing the `Predicate` against the incoming request and the first handler that matches is selected.

In your case, `"/test/other"` matches `"/test/{id}`. If you want a different behavior, then you need to order the routes accordingly.

For further questions, let's keep using StackOverflow. Thanks!
