### ISSUE TITLE
Add filter before RouterHandler in WebFlux

### ISSUE THREAD

**Issue by kkocel** [spring-projects/spring-framework#22408]
I have my app deployed behind load balancer and I take advantage of `ForwardedHeaderTransformer` to be able to have proper redirect urls (mostly for Spring Security OAuth) 

Then I have my router functions which need to have conext path prefix hardcoded (since `ForwardedHeaderTransformer` changed conextPath and uri). 

I would like not being forced to hard code context path into my router functions. Instead I would like to have such context path stripped out by filter before going to `RouterHandler`. Therefore I suggest adding a filter mechanism that would be used just before `RouterHandler`. I cannot use general purpose `WebFilter` because it will work also for requests that will be base for redirections.

**Comment by sdeleuze** [comment]
I am not sure to understand your use case, could you provide a focused repro project that implements it?

**Comment by kkocel** [comment]
In attachment you can find my repo (not a minimal case, but small though)

In `SecurityConfig` I register `ForwardedHeaderTransformer`

Then service routers is accessed with `X-Forwarded-Prefix: /api/ud/` header. 

Therefore I need to add path prefix ` router { "/api/ud".nest { devices() } }` in my router function.

I don't want to do that since my application should not be aware of exact path on which it was deployed behind load balancer. 

[user-and-device.zip](https://github.com/spring-projects/spring-framework/files/2865196/user-and-device-master.zip)

**Comment by rstoyanchev** [comment]
Context path is supposed to be handled at a lower level via `ContextPathCompositeHandler` which wraps one or more `HttpHandler` instances each mapped to a specific context path.

**Comment by kkocel** [comment]
@rstoyanchev I fully agree. My point is that later on (before going to router functions) I need some way to strip path prefix.

**Comment by rstoyanchev** [comment]
@kkocel, the idea of mutating the request only for the mapping phase of request handling is not one that we are likely to adopt. Besides being a potential source of confusion -- maybe not a concern for you, but if we accept the idea we have to support it more generally, the mismatch can lead to security issues due to the mismatch between security authorization mappings and application mappings. 

Further, you mention you don't want the application to be aware of the deployment prefix from the load balancer, but does removing it through a transformer/interceptor eliminate that awareness or just shift it? I imagine such a transformer would still have to know what the prefix. So can you explain again why is it an issue to have the prefix in the mappings?

I'll also add one extra idea. The `ForwardedHeaderTransformer` aims to ensure that the entire server (filters, controllers, etc.) sees the same request with forwarded headers absorbed, and that's considered a positive for consistency, performance, and for security reasons. Technically you might be able to avoid applying `ForwardedHeaderTransformer` at the start of request processing, and apply it more selectively in places where it's needed for redirecting.

**Comment by kkocel** [comment]
@rstoyanchev Thanks for replying. I understand your point about mismatch.

Regarding second paragraph - since my Spring application is behind load balancer I have to leak path prefix into my `RouterFunction` - and when path prefix changes I need to change it in two places - load balancer and `RouterFunction`. Also when I want to serve clean api I need to duplicate routes  and serve them with and without path prefix.

Regarding third paragraph - I use `ForwardedHeaderTransformer` for removing path prefix - but this breaks construction of Oauth2 links, so I abandoned using `ForwardedHeaderTransformer` but such approach leaves me with all inconveniences that I've mentioned in response to second paragraph.

**Comment by rstoyanchev** [comment]
Yes I see that it needs to change in two places but using the suggested `ServerRequestTransformer` doesn't change that. It only applies it to the application mappings in a different way.

For serving a clean API, it's quite straight forward to separate the routes into an independent method as you have already done, and layer the context path prefix on top. There isn't anything preventing re-use of the route with or without the prefix that I can see. This can be done in a conditional way, perhaps externalizing the prefix from the load balancer to a property, and then prepend the route mappings with it depending on whether it's present or not.

I'm not sure I follow the comment about using `ForwardedHeaderTransformer` to remove a path (it adds rather than remove), see [example test](https://github.com/spring-projects/spring-framework/blob/d1f544209eb31b1d03345c7df755f3fc9528ef58/spring-web/src/test/java/org/springframework/web/server/adapter/ForwardedHeaderTransformerTests.java#L89). Either way I'm not advocating removing the transformer.

**Comment by rstoyanchev** [comment]
I'm closing but feel free to comment.
