### ISSUE TITLE
are there APIs or documents about namespace of xml-based configuration?

### ISSUE THREAD

**Issue by XSun771** [spring-projects/spring-framework#22424]
it's useful and effective for me to use namespace in xml-based configurations, such as "xmlns:context="http://www.springframework.org/schema/context."" However, I can't find the documents and APIs about them. are there APIs or documents specifically for them?
Thanks.

**Comment by sdeleuze** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
