### ISSUE TITLE
5.1.5 webflux get request body failed

### ISSUE THREAD

**Issue by ColorfulWolf** [spring-projects/spring-framework#22446]
**Affects:** \<5.1.5>

---
when I want to get a json form request body with the following method `request.body(BodyExtractors.toFlux(HashMap.class)).subscribe(log::info)`
I get an empty flux
when I use 5.0.12(Springboot 2.0.8), it works.
so, what's wrong?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
