### ISSUE TITLE
Defining a bean that implements BeanFactoryPostProcessor via @Bean method will cause the Config Bean can't inject properties

### ISSUE THREAD

**Issue by xiaoyaofawai** [spring-projects/spring-framework#22455]
My code example is as follows :
```
@Configuration
public class TestConfig {
    @Autowired
    private Environment environment;
    
    @Bean
    public MapperScannerConfigurer mapperScannerConfigurer() {
        MapperScannerConfigurer mapperScannerConfigurer = new MapperScannerConfigurer();
        mapperScannerConfigurer.setBasePackage("com.example.demomybatis");
        return mapperScannerConfigurer;
    }
}
```
The `MapperScannerConfigurer`  class implements `BeanFactoryPostProcessor`, so `TestConfig` must be instantiated before the BeanFactoryPostProcessor‘s `postProcessBeanFactory` method is called. In other words, when `TestConfig` is instantiated, it will miss all methods of the `BeanPostProcessor` implementation class. So `@Autowired` will fail in class TestConfig.
Is this a problem?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
