### ISSUE TITLE
@async annocation queue

### ISSUE THREAD

**Issue by winston9527** [spring-projects/spring-framework#22454]
restart server when spring async queue has elements。 queue data will lost , how to resolve it?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
