### ISSUE TITLE
Ubuntu tomcat 9 application configuration file location?

### ISSUE THREAD

**Issue by khteh** [spring-projects/spring-framework#22460]
Spring Boot v2.1.2.RELEASE, Spring v5.1.4.RELEASE
tomcat 9.0.16
Ubuntu 18.10
Where is the location of application configuration yaml for spring-boot and tomcat started with systemctl? Thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
