### ISSUE TITLE
Get the integer type of HashMap from the long type of HashMap ?

### ISSUE THREAD

**Issue by wangnanyang** [spring-projects/spring-framework#22495]
I use the spring cloud framework, and the service provider interacts with consumers using the List < Map < String, Object > return value result set. The problem is that the long in map < String, Object > is converted to integer, that is, result. get (0). get ("count"). getClass () is the integer type from the long at the service provider to the service consumer. How can I solve this problem? Thank you!  

 @GetMapping("/report/common/data/search")
    public List<Map<String, Object>> searchSaleReport(@RequestParam("param") String param) {
        return saleReportService.searchSaleReport(param);
    }

@FeignClient("${sale.feign.name}")
public interface SaleReportService {
    @GetMapping("/report/common/data/search")
    List<Map<String, Object>> searchSaleReport(@RequestParam("param") String param);
}

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In addition, please note that this issue is for the Spring Framework and does not handle issues related to Spring Cloud.

**Comment by wangnanyang** [comment]
I opened a new problem in the Spring Framework, but was pointed out to repeat the problem here and turn it off directly. There is no solution there. It's a tough problem for me. Can you give me some advice on how to solve it?

**Comment by snicoll** [comment]
> I opened a new problem in the Spring Framework but was pointed out to repeat the problem here and turn it off directly

This is the issue tracker of the Spring Framework and we don't use it for questions. I don't see anywhere someone asking you to report the problem here. This doesn't look like a bug report but rather a question. Please take the time to read [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss) and ask questions on StackOverflow.
