### ISSUE TITLE
@ManyToMany not inserting into join table because of custom Hibernate Validator - Spring Data JPA 2.1.0.RELEASE 

### ISSUE THREAD

**Issue by tjhelmuth** [spring-projects/spring-framework#22533]
I have a ManyToMany relationship between User and Role. I have a custom hibernate validation constraint on my roles Set in User.

When I try to create a new user, the following happens:

- If I do not have my custom validation, the association is saved correctly and I see an entry in user_role join table. 

- If I include the constraint, the user is inserted without an entry into user_role table. The code is summarized below. I cannot understand how using the RoleRepo to fetch all of the roles in the validator could in any way break the save, but it does.

```java
class User {
  @Id
  String username;

  @ValidOption
  @ManyToMany(cascade = {CascadeType.ALL //for example}, fetch=FetchType.EAGER)
  Set<Role> roles;
}

class Role {
  @Id
  String name;
}

class CustomValidator implements ConstraintValidator<ValidOption, Object> {
  RoleRepository roleRepo; //injected by spring... have factory configured

  @Override
  public boolean isValid(Object value, ConstraintValidatorContext context){
    roleRepo.findAll() //<-------------- THIS CALL BREAKS THE SAVE
    return true;
  }
}

@Service
class UserService {
  UserRepository userRepo;

  @Transactional
  public void createUser(User user){
    //user has a transient instance of Role with the correct Id set
    if(userExists(user)) throw new ApiException();
    userRepo.save(user);
  }
}
```

This works 100% exactly the way I would expect if I remove the custom validator. Otherwise, no roles in the join table, **even though the entity returned by save has the role in the collection.**

Reproducible example project: https://github.com/tjhelmuth/SPR-22533/blob/master/src/test/java/spr22533/bug/BugExample.java

**Comment by sbrannen** [comment]
@odrotbohm, since this is related to Spring Data JPA, would you mind taking a look at this?

**Comment by odrotbohm** [comment]
This feels like a weird idea in the first place and probably is a limitation of Hibernate validator. I think it's fundamentally wrong to have fundamental domain validation be triggered by the persistence layer because if that kicks in to report a violation it means that you have passed *all layers of business functionality* with an invalid entity. I'd even extend that and would argue that JSR-303 validations are not a good match for domain model types as they insist on the object to be able to carry invalid data. It also means that a method that receives a type can never be sure that the validation has happened.

That said, IIRC the integration with Hibernate Validator is realized via JPA entity listeners, which are not allowed to trigger any additional database interaction in the first place. I'd love to see the stack trace you get to be more sure about the why, but essentially what you're trying is not actually supported. Not due anything Spring but the way JPA, JSR-303 and Hibernate work.

**Comment by tjhelmuth** [comment]
Hi, thanks for responding. I found out from Jens Schauder that this is failing because using the same EntityManager for any database access is not supported during a jpa lifecycle method.

Am I understanding correctly that your concern would be that I can get invalid values into an instantiated User object in any situation? Do you have any recommendations on how to go about that? I don't really want to lock creating every entity instance into its own factory and do validations by hand. Maybe I'm misunderstanding your point though.

My plan was not to only validate at the persistence layer, I have my resource at the api level validated (using this same custom constraint) and then I was planning on implementing this validation again at service level with a @Valid annotation in the method signatures. It would only make it to the validations in the persistence layer if the entity was already valid.

There is no stack trace or error message, fyi, hibernate seems to think the merge went successfully but it never triggers the save into the join table.

Anyways I will close this since it's clearly not a bug in spring or spring data.
