### ISSUE TITLE
component-scan exclude-filter org.springframework.stereotype.Component

### ISSUE THREAD

**Issue by kingrockw** [spring-projects/spring-framework#22551]
```xml
<context:component-scan base-package="cn.rock">
    <context:exclude-filter type="annotation" expression="org.springframework.stereotype.Component"></context:exclude-filter>
</context:component-scan>
```

Why can't the `DispatcherServlet` load the `@Controller` class in Spring MVC config according to the above configuration?

**Comment by sbrannen** [comment]
Although this kind of question is better suited for [Stack Overflow](https://stackoverflow.com/), I'll go ahead and answer your question here.

1. `@Controller` is meta-annotated with `@Component`. 
2. You have configured an exclude filter for classes annotated with `@Component`.
3. When specifying `type="annotation"` with `<context:exclude-filter ... />`, Spring creates an `org.springframework.core.type.filter.AnnotationTypeFilter` that by default considers annotations that are directly present or meta-present.

The net result is that you have instructed Spring to exclude from component scanning any classes that are directly annotated with `@Component` or meta-annotated with `@Component` (e.g., `@Controller`, `@Service`, `@Repository`, etc.). Thus, the `DispatcherServlet` does not see your `@Controller` class, because your `@Controller` class has been excluded from component scanning.

If you would like to exclude exactly classes annotated directly with `@Component`, you will need to implement a custom `org.springframework.core.type.filter.TypeFilter`. The easiest way would be to extend `AnnotationTypeFilter` and have the default constructor of your subclass delegate to the `AnnotationTypeFilter(Class<? extends Annotation>, boolean)` -- for example `super(Component.class, false)`.

You can then specify `type="custom"` and `expression="org.example.MyCustomComponentAnnotationTypeFilter"` in `<context:exclude-filter ... />`.

**Comment by sbrannen** [comment]
@kingrockw, thanks to your question I noticed that the documentation was not explicit with regard to the default support for meta-annotations. I have therefore updated the documentation in b109f140a7be2ccc6f7aad34a9bbe3d4b03da6d4.

Cheers!

**Comment by sbrannen** [comment]
As an alternative to my previous proposal to implement a custom `TypeFilter`, if you are activating the component scanning in an XML configuration file that is solely dedicated to loading web-related beans, you may wish to simply _include_ only classes annotated with `@Controller`, which you should be able to achieve as follows.

```xml
<context:component-scan base-package="cn.rock" use-default-filters="false">
    <context:include-filter type="annotation" expression="org.springframework.stereotype.Controller" />
</context:component-scan>
```

**Comment by kingrockw** [comment]
Thank you very much for your answer. @sbrannen
