### ISSUE TITLE
Wrong behavior in extended configuration class

### ISSUE THREAD

**Issue by bwaldvogel** [spring-projects/spring-framework#22558]
I’ve tried to create a minimal example that demonstrates an application context behavior that surprises me.

Given are the following configuration classes:
```java
class FirstServiceConfig
{
    @Value("${firstServiceUrl:url1}")
    private String firstServiceUrl;

    String getServiceUrl() {
        return firstServiceUrl;
    }

    @Bean
    Service firstService() {
        return new Service(getServiceUrl());
    }
}
```
```java
class SecondServiceConfig extends FirstServiceConfig
{
    @Value("${secondServiceUrl:url2}")
    private String secondServiceUrl;

    @Override
    String getServiceUrl() {
        return secondServiceUrl;
    }

    @Bean
    Service secondService() {
        return new Service(getServiceUrl());
    }
}
```
```java
class Service
{
    private final String url;

    Service(String url) {
        this.url = url;
    }

    String getUrl() {
        return url;
    }
}
```

The following example creates an application context and obtains both service beans:
```java
AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
context.register(FirstServiceConfig.class, SecondServiceConfig.class);
context.refresh();
Service firstService = context.getBean("firstService", Service.class);
Service secondService = context.getBean("secondService", Service.class);
System.out.println("firstService.url = " + firstService.getUrl());
System.out.println("secondService.url = " + secondService.getUrl());
```

I would expect the output
```
firstService.url = url1
firstService.url = url2
```

However, the actual output is
```
firstService.url = url2
firstService.url = url2
```

I can observe that behavior in various Spring versions: `4.3.5`, `5.0.0`, `5.1.5`

Interestingly, the behavior changes if the order of registration is changed:
```diff
- context.register(FirstServiceConfig.class, SecondServiceConfig.class);
+ context.register(SecondServiceConfig.class, FirstServiceConfig.class);
```

Is this behavior a bug or a feature? :slightly_smiling_face:

**Comment by jhoeller** [comment]
I'm afraid it's a feature :-)

Registration order is indeed significant here: Since `SecondServiceConfig` extends `FirstServiceConfig,` its base class part overrides the previously registered parts of `FirstServiceConfig.` And since it overrides `getServiceUrl()`, its `FirstServiceConfig` base class will use the overridden service URL as well.

Whereas if `SecondServiceConfig` is registered first, the subsequent `FirstServiceConfig` overrides the base class parts of `SecondServiceConfig`. As a consequence, its locally defined service URL for "firstService" will take effect, not the overridden one in `SecondServiceConfig`.

Note that the surprising effect comes from the fact that `FirstServiceConfig` is implicitly registered as a base class but also registered directly, with effectively different configuration values. I would try to avoid such a scenario to begin with.

**Comment by bwaldvogel** [comment]
Thanks for the explanation.

**Comment by bwaldvogel** [comment]
I’m glad to see that Spring Boot started to [prevent bean definition overriding in version 2.1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding).
This will help to reject bogus configurations as in my example.
