### ISSUE TITLE
Migrate CommonAnnotationBeanPostProcessor to MergedAnnotations

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#22585]
`CommonAnnotationBeanPostProcessor` would benefit from using the new `MergedAnnotations` API directly.

**Comment by jhoeller** [comment]
As mentioned in #22583, I'm reverting this one since it didn't actually replace `*Utils` calls but rather direct `AnnotatedElement.isAnnotationPresent` checks. The latter are preferable for plain annotation types where no merging is necessary, in particular for `javax` annotation lookups, due to the lean and GC-friendly presence check against internal JVM data structures (no arrays to clone for such checks etc).

The `MergedAnnotation` API is generally designed for sophisticated hierarchy searches and/or merged attribute processing. For straight lookups, per #22685, `AnnotationUtils` and `AnnotatedElementUtils` use direct `AnnotatedElement` access for plain local annotation types (and checks on types which are known to only contain plain annotation types) as well as the `MergedAnnotation` API for mergable annotation types. This also allows the `MergedAnnotation` implementation to internally optimize more aggressively, knowing that plain annotation types are always to be ignored for its purposes. All in all, callers should only choose the `MergedAnnotation` API if they are actually dealing with mergable annotation types.
