### ISSUE TITLE
DeferredResult didn't support 302 with response

### ISSUE THREAD

**Issue by pli2014** [spring-projects/spring-framework#22599]
I confused an issue that `DeferredResult` didn't support setting with 302 status of response, so I gave up this `DeferredResult` when returning response data,  how to resolve this? 

for example as below: 

```java
@Controller                      
@RequestMapping("/")  
public class SampleController{
@RequestMapping("/test")
  @ResponseBody  
  public DeferredResult<String> test( HttpServletResponse response){
     DeferredResult dr = new DeferredResult();
     //something to do 
     response.setStatus(302);
    response.setHeader("Location", xxxx);
     return dr;
  }
}
```

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
