### ISSUE TITLE
Documentation: Getting Started Guides. Please don't say: "Completed in 15 minutes"

### ISSUE THREAD

**Issue by molzb** [spring-projects/spring-framework#22601]
https://spring.io/guides

> Designed to be completed in 15-30 minutes.

Sorry to say that, this is not realistic. Better:

> Designed to be completed in around/under 1 hour by an experienced Java Programmer with a Spring background.

or

> Designed to be completed by a Spring committer in 15-30 minutes (that's a joke)

Please review all guides to provide a realistic time estimation.

Completing a tutorial means to me: Read all text, reproduce the 
example, going through it without getting stuck, understand the 
concepts, be able to transfer (only) those concepts to a real project, 
be able to communicate the concepts to colleagues.
Completing a tutorial doesn't mean to clone a repo and to compile it
or reading text without understanding.

Look at it from a manager perspective:
So that Spring stuff is so super simple, that you can complete
**32(!) guides within 1 work day** 
(ok, let's say 24, if you do 3 guides within an hour). Really? 
So let's move all development to some poor countries...

32 Guides is: 
 Building a RESTful Web Service
 Scheduling Tasks
 Consuming a RESTful Web Service
 Building Java Projects with Gradle
 Building Java Projects with Maven
 Accessing Relational Data using JDBC with Spring
 Uploading Files
 Authenticating a User with LDAP
 Messaging with Redis
 Messaging with RabbitMQ
 Accessing Data with Neo4j
 Validating Form Input
 Building a RESTful Web Service with Spring Boot Actuator
 Messaging with JMS
 Creating a Batch Service
 Securing a Web Application
 Building a Hypermedia-Driven RESTful Web Service
 Accessing Data in Pivotal GemFire
 Integrating Data
 Caching Data with Pivotal GemFire
 Managing Transactions
 Accessing Data with JPA
 Accessing Data with MongoDB
 Serving Web Content with Spring MVC
 Converting a Spring Boot JAR Application to a WAR
 Creating Asynchronous Methods
 Handling Form Submission
 Building an Application with Spring Boot
 Using WebSocket to build an interactive web application
 Working a Getting Started guide with STS
 Consuming a RESTful Web Service with AngularJS
 Consuming a RESTful Web Service with rest.js

I think, you get the point.

I'm currently here:
https://spring.io/guides/gs/securing-web/
"What you'll need: About 15 minutes"

OMG. If I look at my other colleague, who's a tester and writes Java code
from time to time, I would say, it takes 1 DAY. Yes, 1 day. If he gets
stuck somewhere or he has somebody to ask, he needs more time.
If I look at my colleague, who's an experienced Java backend guy with no
Spring experience, I would say, half a day. Not less.

Sorry about the rant.

**Comment by bclozel** [comment]
Hi @molzb 

This is the Spring Framework issue tracker, we're working here on enhancements and bugs for the Spring Framework project. You can submit feedback on the guides here: https://github.com/spring-guides/getting-started-guides (the organization itself hosts all the individual guides).

I agree that some guides are more involved and could be reworked into tutorials or topical guides ([see the bottom of this page](https://spring.io/guides)). The setup phase is common to all guides, so we're showing there the intent rather than the actual time it took to follow the guide.

On the other hand, the intended goal is not to understand all the concepts nor everything you listed in your issue description. What you're describing there is more in line with topical guides or tutorials.  The goal is to get your feet wet, maybe compare with another framework you've been using. I've been using similar content with students (with Java background, but no Spring background) and it worked pretty well.

We're thinking about improving those guides in many ways, and PRs are always welcome - that's why those guides are open source projects in the first place.

Thanks!
