### ISSUE TITLE
CssLinkResourceTransformer cannot process a blank value of a url() link

### ISSUE THREAD

**Issue by xzleah** [spring-projects/spring-framework#22602]
**Affects:** 5.0.10.RELEASE

---

I have some CSS files contain the following content:

```css
.csv-3 .csFilters {
  background: transparent url() no-repeat left top;
}
```

When a request for these files come in, the `CssLinkResourceTransformer` parses the `url()` to `ContentChunkInfo` instance (lines 85-87).

And then It processes each of the `ContentChunkInfo` instances by transforming the URL to a absolute path (line 103).

But the absolute path will be the location of a folder because the `link` parameter is a `null` value. 

And then it goes into the `resolveUrlPath` method and throws a `NullPointerException`, because the program tries to close a `FileInputStream` which refers to a folder and that is impossible.

This also suppresses the actual exception.

**Comment by sbrannen** [comment]
Does the CSS specification even support an _empty_ argument to the `url()` function?

I was under the impression that it must be a string.

What happens if you update your CSS to declare `url('')` instead of `url()`?

**Comment by xzleah** [comment]
The empty URL cause making a subsequent request by pointing back to the current page but it depends on the behavior of a browser.  Anyway, Spring should correct it if 'url()' is invalid.

**Comment by sbrannen** [comment]
> Anyway, Spring should correct it if 'url()' is invalid.

What do you mean by "it" in the previous sentence?

**Comment by xzleah** [comment]
I mean spring should just output the 'url()' even 'url()' is invalid rather than throw an NullPointerException.

**Comment by sbrannen** [comment]
> I mean spring should just output the 'url()' rather than throw an NullPointerException even 'url()' is invalid .

That sounds relatively pragmatic to me.

@rstoyanchev, WDYT?

**Comment by sbrannen** [comment]
@xzleah, can you please let me know which `CssLinkResourceTransformer` implementation you are referring it?

- `org.springframework.web.servlet.resource.CssLinkResourceTransformer`?
- `org.springframework.web.reactive.resource.CssLinkResourceTransformer`?
- or both?

**Comment by sbrannen** [comment]
> But the absolute path will be the location of a folder because the `link` parameter is a `null` value.

@xzleah, are you certain that you encountered this behavior using Spring Framework `5.0.10.RELEASE`?

I ask, because in the following code, the `link` variable can never be `null`.

https://github.com/spring-projects/spring-framework/blob/35d1a8b6b2af88ad10955d2e3eba6a4d2e134af1/spring-webmvc/src/main/java/org/springframework/web/servlet/resource/CssLinkResourceTransformer.java#L98-L116

**Comment by sbrannen** [comment]
@xzleah, in commit bcdc6e0581c787a7e526a0d51fa07fa68d83bb7a (against the `5.0.x` branch), I did my best to reproduce the scenario you have described, but I was unfortunately not able to reproduce the `NullPointerException`.

Can you please provide a simplified sample application that reproduces the behavior you have described?

**Comment by xzleah** [comment]
Hi @sbrannen , You are right.  I found that `link` is a empty string rather than a `null` value.

**Comment by sbrannen** [comment]
OK. Thanks for the feedback. We'll await your new sample.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by xzleah** [comment]
After my investigation, I found the NullPointerException is thrown in the specific JDK version with 1.8.0_66.
In other versions, the absolute path is transformed to a wrong path. The wrong path is such as below:
`background: transparent url(/css-d41d8cd98f00b204e9800998ecf8427e.null) no-repeat left top;`

You can find the bug in my demo: https://github.com/xzleah/CSS-file-bug-demo
I test it in the following restrictions：
1. run css-file-bug-demo-webapp in IDE(eclipse or IntelliJ IDEA)
2. I install the css-file-bug-demo-static-resource into maven repository rather than import the css-file-bug-demo-static-resource into IDE for resolving the depency.

**Comment by sbrannen** [comment]
@xzleah, thanks for the feedback and example projects.

After installing `css-file-bug-demo-static-resource` in my local maven repo and launching `css-file-bug-demo-webapp`, if I access http://localhost:8080/css/bug.css, I see the output you described.

```css
.abc {
	background: transparent url(/css-d41d8cd98f00b204e9800998ecf8427e.null) no-repeat left top;
}
```

We'll look into it.

**Comment by sbrannen** [comment]
Interestingly enough, if the `bug.css` file is served from within the `css-file-bug-demo-webapp` (i.e., with the `css-file-bug-demo-static-resource` dependency completely removed), I see the following as expected.

```css
.abc {
	background: transparent url() no-repeat left top;
}
```

**Comment by sbrannen** [comment]
If you upgrade to Spring 4.1.x, this problem disappears.

For example, I just tested with Spring Boot 2.1.4 which pulls in Spring Framework 5.1.6, and I get the expected output.

```css
.abc {
	background: transparent url() no-repeat left top;
}
```

So I'll see if I can figure out the difference in behavior between Spring Framework 5.0 and 5.1.

**Comment by sbrannen** [comment]
After extensive debugging and research, I have determined that this is a duplicate of #21372.

Specifically, `org.springframework.web.servlet.resource.PathResourceResolver.getResource(String, Resource)` considers the `/css/` folder in the `css-file-bug-demo-static-resource` JAR to be a "readable" file instead of a folder. This results in the `FileNameVersionPathStrategy` being applied to `"/css"` as the filename, which then results in `"/css-d41d8cd98f00b204e9800998ecf8427e.null"` as the versioned filename (with `null` for the non-existent extension).

As @jhoeller stated in https://github.com/spring-projects/spring-framework/issues/21372#issuecomment-453471833, the fix for this is "a 5.1 only revision since a complete fix incurs quite a bit of overhead in `isReadable()` ...".

In light of that, I'm afraid you'll have to upgrade to Spring Framework 5.1.x to get proper support for this use case.

In the interim, I will leave this issue open in order to allow @jhoeller to provide feedback.

**Comment by sbrannen** [comment]
After some further thought on the matter, `FileNameVersionPathStrategy` is intended for use with files and not folders. Thus, we might be able to _fix_ this issue in 5.0.x by reworking the logic in `FileNameVersionPathStrategy.addVersion(...)` so that it returns `null` if the supplied `requestPath` does not have an extension (i.e., does not look like a file).

A quick test with the following change in the `return` line actually results in the desired behavior for the use case in this GitHub issue, and the entire 5.0.x test suite passes as well.

```java
@Override
public String addVersion(String requestPath, String version) {
	String baseFilename = StringUtils.stripFilenameExtension(requestPath);
	String extension = StringUtils.getFilenameExtension(requestPath);
	return extension != null ? (baseFilename + '-' + version + '.' + extension) : null;
}
```

The above is admittedly a bit of a hack since it does not comply with the contract defined in `org.springframework.web.servlet.resource.VersionPathStrategy.addVersion(String, String)`, but it does seem to get the job done.

@rstoyanchev, what do you think about making the above change?

**Comment by rstoyanchev** [comment]
@sbrannen thanks for the investigation. We're pretty far in the 5.0.x timeline (5.0.14 to be the last one) and it's not worth taking the risk of regressions that could further extend its life.

@xzleah please upgrade to 5.1.x where this is no longer an issue. This is something you must do anyway because there will be no more 5.0.x updates and that could mean missing out on security fixes.

**Comment by xzleah** [comment]
Noted. I will upgrade to 5.1.x or remove the 'url()' to avoid the bug. Thank @sbrannen and @rstoyanchev  very much.
