### ISSUE TITLE
Spring should provide possibility to limit size of HTTP partial responses.

### ISSUE THREAD

**Issue by lkolek** [spring-projects/spring-framework#22604]
**Affects:** \5.*

---
As for now, spring web / reactive supports range requests (those containing Range header), returning full size of requested range. Some browsers (eg. Safari, Chrome) send first request (containing bytes=0-) just to check resource size. In this case, it is a waste of resources to try to return all that data - that transfer is interrupted one anyway.

Also, next requests (at least for eg. mp4 resources) will also be big anyway (for Chrome eg. 60M, Safari at start try to consume smaller chunks, like 60k, but after a while it try to get data to the end).

AFAIK it is completly OK according to standards to emit response with limited size. Browser will then issue next request, taking into account returned chunk.

It would be nice to have configuration options that allow two limits:
- first one for ranges bytes=0-  (ideally) or just for ranges starting from 0,
- second one for other ranges.

**Comment by rstoyanchev** [comment]
Couldn't browsers also request the full resource and check the content-length? In other words we can't prevent them from doing this and they might already have some such fallback if they can't find out the size otherwise. Also if the request is interrupted, then the full content is not served in any case. 

If you really want such a feature you could create a filter that decorates the request and overrides the range header for specific values.
