### ISSUE TITLE
Question about Spring Webflux: return type ResponseEntity<Mono<Foo>> vs Mono<ResponseEntity<Foo>> in Controller return type, follow up with Flux.

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-framework#22614]
Hello Spring Framework team,

Thank you for this amazing project, especially Spring Webflux.
I have a question to the community, could you please tell me what is the difference between ResponseEntity<Mono<Foo>> versus Mono<ResponseEntity<Foo>> as a return type of a rest controller? 
When is the most appropriate to what?
Following up on this question, let's say I need to return a list, or let's say several elements of Foo, there are many examples of returning Flux<Foo>.
Would it make sense to return ResponseEntity<Flux<Foo>> or Flux<ResponseEntity<Foo>>?

Thank you a lot for your help.
I am not trying to spam, just to learn something new, please don't "just close" this.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by opncow** [comment]
Any chance someone could answer the same question on SO: https://stackoverflow.com/q/57769190 ?

**Comment by sandyk1212** [comment]
Fala

Em seg, 11 de jan de 2021 21:36, Alexander Openkowski <
notifications@github.com> escreveu:

**Comment by rstoyanchev** [comment]
I've looked in our docs and indeed as the SO thread says, there is no good answer there. I'm re-opening in order to make a documentation improvement about this.

**Comment by opncow** [comment]
Thanks a lot for the super quick update!

**Comment by patpatpat123** [comment]
Many thanks
