### ISSUE TITLE
Add options.linksource to build.gradle javadoc

### ISSUE THREAD

**Issue by sdwarwick** [spring-projects/spring-framework#22636]
**Affects:**  Spring 5+

Adding this options.linksource to the javadoc configuration in  build.gradle would generate a very convenient link from javadoc entries to the underlying code. This would make it much easier to view the actual implementations rather than searching for the source by hand.   This option has been available in javadoc for a long time,  wondering why it is not used.

**Comment by sbrannen** [comment]
Resources:

- [Javadoc option](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDFBBID)
- [Gradle config](https://docs.gradle.org/current/javadoc/org/gradle/external/javadoc/StandardJavadocDocletOptions.html#isLinkSource--)

**Comment by sbrannen** [comment]
Hi @sdwarwick,

Thanks for making the suggestion.

Due to the fact that the source code is available online and in `source` JARs on Maven Central (which can be automatically downloaded for use in IDEs via build tools like Maven and Gradle), the team feels that adding this option does not provide much additional benefit.

**Comment by sdwarwick** [comment]
Thanks for your thoughtful consideration. Both options are certainly reasonable alternatives.
