### ISSUE TITLE
Expose Jaxb2Marshaller createMarshaller() and createUnmarshaller() methods

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-framework#22708]
**Affects:** 5.1.5

---
Having defined a `Jaxb2Marshaller` with some custom properties to be used with Spring AMQP, I'm trying now to re-use it and to use the JAXB `Marshaller`/`Unmarshaller` it can generate directly with a `javax.ws.rs.ext.ContextResolver<Marshaller>`, but those methods are protected so I can't invoke them directly.
As a temporary workaround, I've used reflection.

Please make them public.

**Comment by Kunxian615** [comment]
啊啊

**Comment by andrei-ivanov** [comment]
Thank you 🙂
Any chance of a backport to 5.1?

**Comment by jhoeller** [comment]
I'm afraid this isn't a backport candidate since such changes of visibility can break existing code extending `Jaxb2Marshaller.` For the time being, you could create such an extension yourself: overriding `createMarshaller` and `createUnmarshaller` with plain super delegation but public visibility at the subclass level.
