### ISSUE TITLE
why are @Configuration classes wraped by the cglib proxy with the ConfigurationClassEnhancer class

### ISSUE THREAD

**Issue by yaoyuanyy** [spring-projects/spring-framework#22714]
when i read and debug spring source, I find that the @Configuration classes are wraped by the cglib proxy with the ConfigurationClassEnhancer class, I don`t understand the reason of the design,, thanks

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by yaoyuanyy** [comment]
ok, thanks
