### ISSUE TITLE
MergedAnnotation.from(AnnotatedElement, SearchStrategy, …) skips annotations in org.springframework.lang

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#22743]
Using `MergedAnnotation` with an `AnnotatedElement` skips annotations such as `org.springframework.lang.NonNull`. 

A workaround is using `MergedAnnotations.from(Annotation)` to process each declared annotation individually.

**Comment by jhoeller** [comment]
This is intentional: Plain annotations (as per `AnnotationFilter.PLAIN`) are not considered searchable using the `MergedAnnotations` API. They aren't included in the internal caches to keep those smaller. This also allows for shortcutting meta-annotation searches at such lang-level annotations. Finally, we won't include such lang annotations in an annotation presence index either.

`AnnotationUtils` and `AnnotatedElementUtils` keep up support for direct retrieval of any annotations, for backwards compatibility. They would also still find lang-level declarations such as `NonNull`.

All in all, don't use the `MergedAnnotations` API for lang annotations. The JSR-305 arrangement might be a case where you'll have to resort to custom introspection since it's quite out of the ordinary for annotation types of that level, and it's beneficial to make hard assumptions about lang annotation exclusion at the  `MergedAnnotations` level.
