### ISSUE TITLE
Clarify Jackson2ObjectMapper.modulesToInstall override semantics

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-framework#22747]
When calling `Jackson2ObjectMapper.modulesToInstall` this overwrites the complete list of modules whereas methods like `serializers`, `deserializers` and `mixins` can be called multiple times and will append to their collections.

**Comment by sdeleuze** [comment]
If we do that change (I am not sure yet), we should do it for `modules` as well, and this should be done in 5.2 since it could break some applications that are expecting `modulesToInstall`/`modules` to work in override not append mode.

Any thoughts @bclozel @rstoyanchev?

**Comment by manderson23** [comment]
One further comment would be that if the behaviour if left as is then perhaps the javadoc could be updated to make it clearer that it overwrites all modules (similar to the javadoc for `modules()` which states is sets the complete list).

**Comment by sdeleuze** [comment]
I think I would favor a Javadoc update.

**Comment by rstoyanchev** [comment]
It's also not additive with (de)serializers and mixins strictly speaking since those are kept in a map new entries could replace existing ones.

I think improving the Javadoc is a good place to start. If necessary in the future we could provide method to modify the list of modules, e.g. via `Consumer<List<Module>>`.
