### ISSUE TITLE
Avoid MessageFormat processing for default @Pattern validation message

### ISSUE THREAD

**Issue by t-tera** [spring-projects/spring-framework#22761]
**Affects:** 5.1.5 RELEASE

**Example1**

Let's say a form bean has the following annotation:

<pre>
@Pattern(regexp = "[\\w.'-]{1,}@[\\w.'-]{1,}")
private String email;`
</pre>

If an invalid email is given, validation fails and the following error message is presented by form:errors tag.

<pre>... must match "[\w.-]{1,}@[\w.-][Ljavax.validation.constraints.Pattern$Flag;@4f413b2c"</pre>

Single quotes disappear and the second `{1,}` occurrence is replaced with `[Ljavax.validation.constraints.Pattern$Flag;@4f413b2c`.

**Example2:**

<pre>
private Integer age;
</pre>

Supply `age={0}aaa'bbb` then you get the following error message:

<pre>Failed to convert property value of type java.lang.String to required type java.lang.Integer 
for property age; nested exception is java.lang.NumberFormatException: For input string: 
"org.springframework.context.support.DefaultMessageSourceResolvable: codes formData.age,age]; 
arguments []; default message [age]aaabbb"</pre>

Again, `{0}` is replaced and single quote disappears.

The cause is that the values (the regexp in example1 and the user input in example2) are passed to `java.text.MessageFormat#applyPattern()` with no proper escaping.

It looks like the bug (example1) is similar to #11988.

**Comment by jhoeller** [comment]
Thanks for raising this! Our old fallback solution for MessageFormat mismatches isn't ideal there at all since it only catches invalid format syntax, not accidental matches with valid MessageFormat syntax.

As of 5.1.7, we generally don't apply MessageFormat rendering to Bean Validation default messages anymore, so any conflict with accidental placeholder or escaping syntax is avoided to begin with now.
