### ISSUE TITLE
Deprecate MediaType.APPLICATION_JSON_UTF8 in favor of APPLICATION_JSON

### ISSUE THREAD

**Issue by reschke** [spring-projects/spring-framework#22788]
In  spring-framework/spring-web/src/main/java/org/springframework/http/MediaType.java:

 	 * <p>This {@link MediaType#APPLICATION_JSON} variant should be used to set JSON
	 * content type because while
	 * <a href="https://tools.ietf.org/html/rfc7159#section-11">RFC7159</a>
	 * clearly states that "no charset parameter is defined for this registration", some
	 * browsers require it for interpreting correctly UTF-8 special characters

1. RFC 7159 has been obsoleted by RFC 8259
2. That states "No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients." (at the end of Section 11)
3. ...and browsers have indeed fixed their code.

So it would be best to clarify the text and deprecate the constant.

**Comment by sdeleuze** [comment]
Indeed, the related [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=438464) discussed in #18178 is fixed since September 2017, and I have been able to validate that UTF-8 characters are now rendered correctly with `Content-Type: application/json`, so I am ok to switch back to `MediaType.APPLICATION_JSON`, deprecate `MediaType.APPLICATION_JSON_UTF8` and update the documentation accordingly in Spring Framework 5.2.

**Comment by sdeleuze** [comment]
It is a shame, but Safari still has this bug so we should decide what to do ...

**Comment by sdeleuze** [comment]
I have created https://bugs.webkit.org/show_bug.cgi?id=197369 on Safari bugtracker, let's see what is their feedback.

**Comment by sdeleuze** [comment]
The Safari bug is only impacting the display in the main frame, not via `XMLHttpRequest`, so I think we can move forward and merge that in `master`.

**Comment by reschke** [comment]
> The Safari bug is only impacting the display in the main frame, not via XMLHttpRequest, ...

FWIW, I believe the same way true for the matching bugs in Chromium and Firefox.
