### ISSUE TITLE
Return value doesn't serialize to JSON when return type is Mono of Interface in WebFlux

### ISSUE THREAD

**Issue by freddieyyh** [spring-projects/spring-framework#22803]
In WebMVC type application, Spring's message converter can convert the return value to a proper message(like a JSON) when controller return type declared by interface.

But, Webflux's behavior is different.

For example, we have Car class that implements Vehicle interface.
```
public interface Vehicle {
}

public class Car implements Vehicle {
    private String gearType;
}
```
And then there is a controller method like that.
```
@GetMapping("vehicle")
public Vehicle getVehicle() {
    return new Car();
}
```
I can get a json response of Car class with `content-type: application/json` header.

But, webflux's result is defferent. 
```
@GetMapping("vehicle")
public Mono<Vehicle> getVehicle() {
    return Mono.just(new Car());
}
```
It only supports a 'content-type: text/event-stream' when return type is a mono of interface.
Is it a bug?

**Comment by rstoyanchev** [comment]
This odd. The signature with `Mono<Vehicle>` should work in both Spring MVC and WebFlux as expected. Do you have a sample?

**Comment by freddieyyh** [comment]
Here is my simple example.

Webflux : https://github.com/freddieyyh/demo/tree/webflux
WebMVC : https://github.com/freddieyyh/demo/tree/webmvc

Command `curl -X GET -H "Accept: application/json" "localhost:8080/interface-a"`
works on WebMVC demo, but doesn't work on  Webflux demo.

**Comment by rstoyanchev** [comment]
The `Result` interface from the sample has no methods, so Jackson returns false for `getObjectMapper().canSerialize(Result.class)`. Adding at least one accessor makes it work. 

Spring MVC works is because it uses the actual type `ResultA`. We can make an improvement in WebFlux so that a concrete return value works the same, but for `Mono<Result>` it would still rely on the declared type, so it's best to have some sort of accessor on the interface.
