### ISSUE TITLE
Does Spring-Ldap support integration to Oracle Unified Directory OUD

### ISSUE THREAD

**Issue by vsham5766** [spring-projects/spring-framework#22844]
Hello,
We would like to develop a java solution using Spring-Ldap to perform CRUD operation on Oracle Unified Directory (OUD) directory server in our enterprise. Would like to know if Spring-Ldap has been used to address this sort of problem prior.
If so, could you please direct us to a support forum that resembles this kind of a solution.
If not, would Spring forum address any issues the application run into after implementation.
Could you also please confirm if spring-ldap can be used for any directory server interactions.
Thank you,
Vijay

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
