### ISSUE TITLE
PathPattern with double-star(**) not works as expected

### ISSUE THREAD

**Issue by ronnin** [spring-projects/spring-framework#22847]
```java
public class SpringPathPatternTest {

    @Test
    public void testDoubleStar() {
        PathPattern pathPattern = new PathPatternParser().parse("/first/**/last");
        PathContainer path = PathContainer.parsePath("/first/a/b/c/last");

        assertTrue(pathPattern.matches(path)); // FAILED !!!
    }
}
```

tested on spring-web 5.1.5.RELEASE

**Comment by rstoyanchev** [comment]
This is expected behavior. As per the Javadoc of `PathPattern`, `**` is only supported at the end and not in the middle of a pattern. 

For extra context, we've seen countless issues with surprising behavior with `AntPathMatcher` in Spring MVC which does support `**` anywhere in a pattern, mostly as it relates to sorting patterns and deciding which one is the closest match.

I'm closing the issue but feel free to comment further.
