### ISSUE TITLE
Spring JMS Template Sync Receive on Non-Durable Subscriber Message Loss

### ISSUE THREAD

**Issue by zhvfeng** [spring-projects/spring-framework#22910]
Hello,

I call JMSTemplate.receive() in a loop on Non-Durable Subscriber, if I send many messages to the topic, some messages will be lost on receiver. The messages lost occurs after return of JMSTemplate.receive(), but before next call on JMSTemplate.receive().

Is it expected behaviour? or something is wrong with me?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
