### ISSUE TITLE
JDiff report does not contain HTML report anymore

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#22942]
Our release process includes a command to run to be able to generate the binary diff between two releases. 

First step is to get a repo with the previous release, e.g.

```shell
cd /tmp
mkdir spr-5.2.0.M1
cd spr-5.2.0.M1
git clone https://github.com/spring-projects/spring-framework/
cd spring-framework
git fetch origin --tags
git checkout v5.2.0.M1
```

Then, from the repo at the target (about to release version) we can run the following:

```shell
./gradlew jdiff -D OLD_VERSION=5.2.0.M1 -D OLD_VERSION_ROOT=/tmp/spr-5.2.0.M1
```

This generates a report with the diff (here's [an example for 5.1](https://docs.spring.io/spring-framework/docs/5.1.0.RC1_to_5.1.0.RC2/)). Running that command on `master` does not generate the `changes.html` file anymore.

**Comment by rustyTheClone** [comment]
After investigation, it seems to be from the signatures: 
  - `org.springframework.transaction.reactive.TransactionalOperator#transactional(Flux)`,
  - `org.springframework.transaction.reactive.TransactionalOperator#transactional(Mono)`.

JDiff doesn't figure out the difference because of the generic types of Flux and Mono arguments, and gives them the type `&lt;any&gt;` which ends up with a duplicate error and Jdiff does not create the report...

Logs:
```
[ant:Comparing versions] JDiff: reading the new API in from file '[...]/spring-framework/build/reports/jdiff/5.2.0.M1_to_5.2.0.BUILD-SNAPSHOT/Spring_Framework_5.2.0.BUILD-SNAPSHOT.xml'...Error: duplicate comment id: org.springframework.transaction.reactive.TransactionalOperator.transactional_changed(<any>)

> Task :jdiff
 Report location: [...]/spring-framework/build/reports/jdiff/5.2.0.M1_to_5.2.0.BUILD-SNAPSHOT/changes.html
```

As a workaround, you can (before generation) remove the generic types for Mono and Flux and rollback it later.

**Comment by snicoll** [comment]
Thanks for the investigation @fodil-a - JDiff is not maintained anymore so we're looking for an alternative now.

**Comment by bclozel** [comment]
I'm working on refactoring our Gradle build in #23282; in the process, I'm testing Japicmp.
The output format is not the same but at least it seems maintained and we wouldn't have to store binaries in our repo anymore...
I'll sync up with @snicoll to check whether the new output format works out for our needs.
