### ISSUE TITLE
How to connect authenticated service into admin server?

### ISSUE THREAD

**Issue by Nyamkhuub** [spring-projects/spring-framework#22970]
Hello developers!
I have several numbers of services in eureka. I want to monitor these services. So I decided to use Spring boot admin.  

I added that codes to my application yaml file.
> eureka:
    instance:
        metadata-map:
            user.name: eureka
            user.password: password

So, I can't solve that problem! How to solve ???
<img src="https://i.imgur.com/vOZ1aCC.png" />

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Side node: Spring Boot Admin is a Codecentric product and not maintained by the Spring team.
