### ISSUE TITLE
OncePerRequestFilter does not work properly on Error Dispatch on Jetty

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#22989]
Instances of `OncePerRequestFilter` do not get invoked for error dispatch types on Jetty (works on Tomcat) even when the following conditions are true:

- The Filter is configured to dispatch on error dispatch types
- The Filter returns `false` for `shouldNotFilterErrorDispatch`

# Sample

https://github.com/rwinch/onceperrequest-error-dispatch

**Comment by rstoyanchev** [comment]
The specific scenario is a call to `response.sendError(HttpServletResponse.SC_NOT_FOUND)` from `ResourceHttpRequestHandler`. Jetty does the ERROR dispatch within `sendError`, and that's why the  request attribute from `OncePerRequestFilter` is still set. Tomcat however sets the response, allows the REQUEST dispatch to exit, and then performs the ERROR dispatch.

@rwinch I presume you need this in 5.1.x?
