### ISSUE TITLE
DispatcherServlet reads request body while log request information

### ISSUE THREAD

**Issue by andreysubbotin** [spring-projects/spring-framework#22985]
**Affects** 5.1

---
`DispatcherServlet.logRequest` method reads input stream with request body while executing `request.getParameterMap()`. As soon as the input stream is read for the first time, it’s marked as consumed and cannot be read again.
So any MVC controller will not be able to read request body after the logging.  An exception appears in the log: 
```
[org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void com.haulmont.bpm.web.controller.ModelController.updateModel(java.lang.String,org.springframework.util.MultiValueMap<java.lang.String, java.lang.String>,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException]
```
Sample: 
Spring application with Spring MVC.
Controller that handles request body:
```
@Controller("ModelController")
@RequestMapping("/modeler/model")
public class ModelController {
 @RequestMapping(value = "/{actModelId}", method = RequestMethod.PUT)
    public void updateModel(@PathVariable String actModelId,
                            @RequestBody MultiValueMap<String, String> values,
                            HttpServletRequest request,
                            HttpServletResponse response) throws IOException {}
}
```

This works fine on Spring 4.3.18.

**Comment by rstoyanchev** [comment]
I assume this is "application/x-www-form-urlencoded"? Servlet API, section 3.1.1 says request params are parsed from form data only on HTTP POST. What's populating request parameters is the question then? Do you have `FormContentFilter` (or its predecessor `HttpPutFormContentFilter`)? If not, please confirm if it is the Servlet container doing it, despite the Servlet spec, and if yes what server and version is it? Perhaps the server has some option to enable or disable this since it's not per spec.

Note that we do [have something](https://github.com/spring-projects/spring-framework/blob/bd910fc62b87b052968cd5a52458159d9fb6333e/spring-web/src/main/java/org/springframework/http/server/ServletServerHttpRequest.java#L207-L209) that allows reconstructing the request body from parameters but that's only applied for HTTP POST. We might enhance need to enhance it so it also does it for PUT but otherwise falls back on `getInputStream()` if it finds no parameters.
