### ISSUE TITLE
validation error message {0} is not working

### ISSUE THREAD

**Issue by suzukitadashi** [spring-projects/spring-framework#23014]
# Application
* Spring boot 2.1.5.RELEASE
* Sample : https://github.com/suzukitadashi/validationMessageCheck
* Blog : http://tadashi.hatenablog.com/entry/2019/05/22/095656 (Sorry, Japanese only...)

# config

## ValidationMessages.properties 
```
javax.validation.constraints.NotEmpty.message={0} must not be empty
javax.validation.constraints.Size.message=size must be between {min} and {max},please.

value=value1111 
```

## Form

```
@Setter
@Getter
public class TestForm {

	@NotEmpty
	@Size(min=5, max=100)
	String value;
	
}
```

## run 

http://localhost:8080/test

Press the button without inserting anything.

# Result

## Spring boot 2.1.4

Error messages is no problem.

```
size must be between 5 and 100,please.

value1111 must not be empty
```

## Spring boot 2.1.5

Error message is...

```
size must be between 5 and 100,please.

{0} must not be empty
```

I want to set the value in the part of {0}.
Do you need to do something?

**Comment by jhoeller** [comment]
This seems to be caused by the recent changes behind #22761, taking native Bean Validation messages at face value and not applying `java.text.MessageFormat` to them if they are not expected to contain placeholders (avoiding unwanted side effects from `MessageFormat` escaping).

It looks like you are trying to use a `{0}` placeholder in the Bean Validation message format where it is not actually supported; it was rather just meant to work in Spring `MessageSource` resource bundles. I see that it would also have worked in a Spring integration scenario when defined in `ValidationMessages.properties`, so I'll try to make this a bit smarter again for 5.1.8.
