### ISSUE TITLE
Error in javadoc for o.s.web.servlet.function.ServerResponse

### ISSUE THREAD

**Issue by ah1508** [spring-projects/spring-framework#23075]
Javadoc for `writeTo` method of `org.springframework.web.servlet.function.ServerResponse` is not correct:

> Returns: Mono<Void> to indicate when writing is complete

**Comment by sbrannen** [comment]
Good catch.

The Javadoc should in fact look something more like the following, in order to align with `org.springframework.web.reactive.function.server.ServerResponse.writeTo(ServerWebExchange, Context)`.

```java
/**
 * Write this response to the given servlet response.
 * @param request the current request
 * @param response the response to write to
 * @param context the context to use when writing
 * @return a {@code ModelAndView} or {@code null}
 */
@Nullable
ModelAndView writeTo(HttpServletRequest request, HttpServletResponse response, Context context)
	throws ServletException, IOException;
```

@poutsma, can you elaborate on the intended semantics of the `@return` value, specifically when `null` is expected as a return value?
