### ISSUE TITLE
AntPathMatcher.getPatternComparator returns unexpected behaviour

### ISSUE THREAD

**Issue by robinvandenberg** [spring-projects/spring-framework#23125]
The `AntPathMatcher.getPatternComparator(String path)` javadoc states:

> ThisComparator will sort a list so that more specific patterns (without uri templates or wild cards) come before generic patterns. 

Given a url (for example, to stay close to the javadoc):

- `"/hotels/123/bookings/1/name"`

And the following paths:

- `"/hotels/**"`
- `"/hotels/*/bookings/**"`

I expect that `"/hotels/*/bookings/**"` will be more specific, thus, ends up in the list before the generic one. (i.e. it is 'smaller').

However, the following snippet prints:

> true
> true
> /hotels/** is smaller (more specific) than /hotels/*/bookings/**

```java
    public class Demo {
        public static void main(String[] args) {
    
            AntPathMatcher antPathMatcher = new AntPathMatcher();
    
            final String pathToTest = "/hotels/123/bookings/1/name";
            final String pattern1 = "/hotels/**";
            final String pattern2 = "/hotels/*/bookings/**";
    
            System.out.println(antPathMatcher.match(pattern1, pathToTest));
            System.out.println(antPathMatcher.match(pattern2, pathToTest));
    
            Comparator<String> patternComparator = antPathMatcher.getPatternComparator(pathToTest);
            int compare = patternComparator.compare(pattern1, pattern2);
            if (compare > 0) {
                System.out.println(pattern1 + " is larger (less specific) than " + pattern2);
            } else if (compare == 0) {
                System.out.println(pattern1 + " is equal to " + pattern2);
            } else {
                System.out.println(pattern1 + " is smaller (more specific) than " + pattern2);
    
            }
        }
    }
```

This is because eventually the `PatternInfo.getTotalCount()` evaluates to a higher number, because there are more wildcards.

However, the fact that there are more wildcards doesn't necessarily mean that it's less specific, right? Although I agree upfront that the word 'specific' is a bit vague and might be the cause of this issue/ wrong expectation.

**Comment by rstoyanchev** [comment]
For comparison, `PathPattern` prioritizes `"/hotels/*/bookings/**"` over `"/hotels/**"` [based on a rule](https://github.com/spring-projects/spring-framework/blob/e947e08638eaceab4bf70fb582df193c9ffc84be/spring-web/src/main/java/org/springframework/web/util/pattern/PathPattern.java#L90) where if both are prefix/catch-all patterns (e.g. `"/foo/**"`), it compares the pattern length.

`AntPathMatcher` does not have such a rule. It only [makes sure](https://github.com/spring-projects/spring-framework/blob/e947e08638eaceab4bf70fb582df193c9ffc84be/spring-core/src/main/java/org/springframework/util/AntPathMatcher.java#L779-L784) a prefix/catch-all pattern is after any other pattern as long as it doesn't have a `"**"` and otherwise compares scores.

I think we can update `AntPathMatcher` to have the same rule as `PathPattern`.

Thoughts?

**Comment by rstoyanchev** [comment]
**Team Decision:** go ahead with this change. Not only is `"/hotels/*/bookings/**"` more specific but it would also never be used, effectively a dead mapping.
