### ISSUE TITLE
method postForObject in RestTemplate causes NPE

### ISSUE THREAD

**Issue by TRockis** [spring-projects/spring-framework#23123]
**Affects:** \<4.3.13-RELEASE>
---
Hi, 
  When I was using postForObject method of RestTemplate, it may occur NPE. after debuggging, I found the exception was caused by 772 line in org.springframework.web.client.RestTemplate.java
```java
public void doWithRequest(ClientHttpRequest request) throws IOException {
    if (this.responseType != null) {
        Class<?> responseClass = null;
        if (this.responseType instanceof Class) {
            responseClass = (Class<?>) this.responseType;
        }
        List<MediaType> allSupportedMediaTypes = new ArrayList<MediaType>();
        for (HttpMessageConverter<?> converter : getMessageConverters()) {
            if (responseClass != null) {
                if (converter.canRead(responseClass, null)) {        //converter may be null, so NPE may occur. and I don't know why it may be null, and why not do something to prevent this exception occuring
                    allSupportedMediaTypes.addAll(getSupportedMediaTypes(converter));
                }
            }
            else if (converter instanceof GenericHttpMessageConverter) {
                GenericHttpMessageConverter<?> genericConverter = (GenericHttpMessageConverter<?>) converter;
                if (genericConverter.canRead(this.responseType, null, null)) {
                    allSupportedMediaTypes.addAll(getSupportedMediaTypes(converter));
                }
            }
        }
        if (!allSupportedMediaTypes.isEmpty()) {
            MediaType.sortBySpecificity(allSupportedMediaTypes);
            if (logger.isDebugEnabled()) {
                logger.debug("Setting request Accept header to " + allSupportedMediaTypes);
            }
            request.getHeaders().setAccept(allSupportedMediaTypes);
        }
    }
}
```
I don't know whether the exception occers because I used such expression such as 
```java
restTemplate.getMessageConverters().add(0,new StringHttpMessageConverter(Charset.forName("UTF-8")));
```
or
```java
rest = new RestTemplate();
rest.getMessageConverters().set(1, new StringHttpMessageConverter(StandardCharsets.UTF_8));
```
After the exception occured, I need restart my project, however, it may occur again after sometimes.
I do hope someone can give me some hints, thanks!

**Comment by rustyTheClone** [comment]
Hello,
I tried to reproduct this problem.
This NPE occurs if you have more than one message converter, plus `null` coming before.

One way to fix this is to check for the use of `null`-converters.

Another way (cleaner in my opinion) would be to prevent having `null` as a possible value for the converters, by encapsulating the messageConverters, but that's a breaking change and can introduce some regressions (for example, if the message converters are used with their index, not adding the null would break any mapping that considered it was added).

Since the RestTemplate's messageConverters list is exposed, I assume the first one is more protective but would make it less maintainable.

**Comment by sbrannen** [comment]
Superseded by #23132

**Comment by sbrannen** [comment]
Superseded by #23140

**Comment by sbrannen** [comment]
Superseded by #23151
