### ISSUE TITLE
I'm sorry I didn't describe my problem clearly。when i get the source code from github,and build from the command line,then import into my IDEA.the problem is that i create a spring demo module and when i build it,the error was occured: Error:(19, 28) Kotlin: Unresolved reference: core. (my kotlin version is 1.3, and java version is jdk1.8.0_161, gradle version: 5.4.1)

### ISSUE THREAD

**Issue by bai597030001** [spring-projects/spring-framework#23183]
I can't do much which no more detail provided. Please provide a repro project and check your configuration against the one generated from https://start.spring.io/?language=kotlin.

_Originally posted by @sdeleuze in https://github.com/spring-projects/spring-framework/issues/23161#issuecomment-503887201_

**Comment by John-Dormevil** [comment]
Please write your request in the description zone, and not in the title section.

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
