### ISSUE TITLE
bridgeMethod null check missing 

### ISSUE THREAD

**Issue by amozz** [spring-projects/spring-framework#23186]
https://github.com/spring-projects/spring-framework/blob/9239ab1891385a389a1dea68e703b153eb5d9a66/spring-core/src/main/java/org/springframework/core/BridgeMethodResolver.java#L69

in spring 4.x there is the bridgeMethod null check. 
https://github.com/spring-projects/spring-framework/blob/92abe2927ed8d272ba7fea0c76c7cd7016e44c9e/spring-core/src/main/java/org/springframework/core/BridgeMethodResolver.java#L59

Why this check is deleted in spring 5.x？

Thanks for any information.

**Comment by jhoeller** [comment]
This is simply a tightening of nullability as part of our general 5.0 null/non-null definitions through annotations (non-null semantics by default, otherwise there is an explicit `Nullable` annotation for affected arguments and return values).

In this particular case, we mean to enforce a non-null return value which is only really possible through enforcing a non-null argument value as well. If you happen to rely on a null value here, please add a check for null before caling `BridgeMethodResolver` (which is also going to work with 4.x).
