### ISSUE TITLE
why can't a bean being autowired

### ISSUE THREAD

**Issue by omobh** [spring-projects/spring-framework#23197]
I declare this class:

```java
@SpringBootApplication
public class ProgrammingTrading {
    @Bean
    public Logger logInit() {
        return LoggerFactory.getLogger(Logger.class);
    }
}
```

and want to use like this:

```java
@Service
public class MarketDataRobot extends Thread {
    @Autowired
    private Logger logger;
}
```

but always got null pointer exception, I just don't get it ...

thank you very much.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
