### ISSUE TITLE
Is the `volatile` valid ?

### ISSUE THREAD

**Issue by Runrioter** [spring-projects/spring-framework#23201]
https://github.com/spring-projects/spring-framework/blob/0b6239cecce110f5c660428f982758f57fd45f75/spring-core/src/main/java/org/springframework/core/io/FileUrlResource.java#L49

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by sbrannen** [comment]
In any case, yes, the use of `volatile` in that scenario is valid since the `file` instance field is mutable and lazily initialized in `getFile()`.

**Comment by Runrioter** [comment]
@sbrannen Thanks for your response. 

`getFile()` needs to be double-checked. Otherwise, it can cause repeated initialization. Right ?
