### ISSUE TITLE
Allow users to use existing PlatformTransactionManager with webflux

### ISSUE THREAD

**Issue by thekalinga** [spring-projects/spring-framework#23229]
**Affects:** 5.2.0.M2

I'm using the milestone version of `spring-tx` thru autoconfiguration. When I try to use `@Transactional` with jdbc apis within webflux, I get the following exception

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.transaction.ReactiveTransactionManager' available`

`TransactionAspectSupport#invokeWithinTransaction` is internally forcing users to use `ReactiveTransactionManager` just based on the fact that `org.reactivestreams.Publisher` is present in the classpath

This means, all users who have databases that dont have reactive drivers are forced to implement this interface. Users should be allowed to use blocking JDBC thru `PlatformTransactionManager` aswell as not every data store currently/will support reactive drivers

**Comment by jhoeller** [comment]
`TransactionAspectSupport` enforces a `ReactiveTransactionManager` if a particular method returns a reactive type; it's not based on plain classpath presence of the Reactive Streams API. Is this check misbehaving in your scenario?

Applying a `PlatformTransactionManager` to a method that builds a reactive pipeline (such as a WebFlux handler method) is usually pointless since it will wrap the execution of that particular pipeline-building method in a thread-bound transaction, whereas actual data access operations happen in the reactive pipeline that is being returned from that method - and selectively triggered later on when the original thread-bound transaction has completed already.

If you happen to have blocking operations in a WebFlux handler method, be aware that those execute in an event loop thread that generally must not be blocked. On the other hand, if you integrate your reactive pipeline with blocking JDBC operations on a separate worker thread, the latter won't participate in the thread-bound transaction for the original handler method either; a thread-bound transaction needs to be demarcated at the worker thread level there.

I see no valid scenario where a thread-bound `PlatformTransactionManager` transaction would add actual value to a WebFlux handler method. Am I missing something?

**Comment by thekalinga** [comment]
> TransactionAspectSupport enforces a ReactiveTransactionManager if a particular method returns a reactive type; it's not based on plain classpath presence of the Reactive Streams API. Is this check misbehaving in your scenario?

This is the code I see

```java
private static final boolean reactiveStreamsPresent = ClassUtils
    .isPresent("org.reactivestreams.Publisher", TransactionAspectSupport.class.getClassLoader());

protected TransactionAspectSupport() {
  if (reactiveStreamsPresent) {
    this.reactiveAdapterRegistry = ReactiveAdapterRegistry.getSharedInstance();
  }
  else {
    this.reactiveAdapterRegistry = null;
  }
}

@Nullable
protected Object invokeWithinTransaction(Method method, @Nullable Class<?> targetClass, final InvocationCallback invocation) throws Throwable {

  if (this.reactiveAdapterRegistry != null) {
    ReactiveAdapter adapter = this.reactiveAdapterRegistry.getAdapter(method.getReturnType());
    if (adapter != null) {
      return new ReactiveTransactionSupport(adapter).invokeWithinTransaction(method, targetClass, invocation);
    }
  }

  // lot more code

}
```

In essence, if `org.reactivestreams.Publisher` is in the classpath, user is forced to have `ReactiveTransactionManager` if he need to use `@Transactional`. Am I wrong?

> the latter won't participate in the thread-bound transaction for the original handler method either; a thread-bound transaction needs to be demarcated at the worker thread level there.

In this case, the thread bound transaction must be supported right

```java
upstream
  .flatMap(request -> {
      return Flux.fromCallable(() -> {
         return service.doThreadboundBlockingOp(request);
      }).subscribeOn(Schedulers.elastic());
  });

@Transactional
class Service {
  int doThreadboundBlockingOp(request) {
    // blocking operation
  }
}
```

**Comment by thekalinga** [comment]
You are right. I was switching from eventloop -> elastic scheduler in the service that was annotated with `@Transactional`, which means I was attempting to start the transaction in eventloop scheduler & the moving to elastic scheduler that did not have any transaction. So, bad things are bound to happen

This is what I had originally

```java
@Transactional
class Service {
  Mono<Response> doBlockingOp() {
    return Mono.fromCallable(() -> repo.blockingOp())
    .subscribeOn(Schedulers.elastic());
  }
}
```

Instead of doing this scheduler switch in `@Transactional` service, I now do it in the resource layer. Now, transactions work

```java
@Transactional
class Service {
  Response doBlockingOp() {
    return repo.blockingOp();
  }
}

class Controller {
  @GetMapping
  Mono<Response> doOp() {
    return Mono.fromCallable(() -> service.blockingOp())
        .subscribeOn(Schedulers.elastic());
  }
}
```

This way, I know that I am starting & ending my transaction on the elastic scheduler's thread

**Comment by thekalinga** [comment]
Looks like, this adapter being set to null since the return type is not a reactive type, which makes sense

```java
ReactiveAdapter adapter = this.reactiveAdapterRegistry.getAdapter(method.getReturnType());
```

**Comment by javolek** [comment]
> `TransactionAspectSupport` enforces a `ReactiveTransactionManager` if a particular method returns a reactive type; it's not based on plain classpath presence of the Reactive Streams API.

This actually does not seem to be true. `TransactionAspectSupport` decides which way to go according to `TransactionManager` implementation regardless methods return type. I would find better if the `TransactionAspectSupport` emits at least a warning when a `PlatformTransactionManager` is used for `@Trasnactional` method returning reactive type, because:
- it is easy to make such a mistake, since the documentation says it's fine to have `@Transactional` method returning reactive type 
- on the first glance it may look like everything is working fine
- would eventually produce inconsistence in the database, which cause would be later hard to identify
- is definitely not intended
