### ISSUE TITLE
@RequestBody when contentType="application/x-www-form-urlencoded" does not re-encode `*`

### ISSUE THREAD

**Issue by szatkus** [spring-projects/spring-framework#23238]
**Affects:** at least >= 5.0.4

---
Hi,

When I try to inject request body to a controller when content type is application/x-www-form-urlencoded and contains some encoded characters the result differs from the original body sent to the application.

I reproduced the bug with this case project https://github.com/szatkus/spring-bug (there is a test case, but the behaviour is the same both with MockMvc and real runtime)

I figured this is what happens:
1. A request is sent with body `fff=aaa%2Abbb`.
2. The body is converted to a parameters list (`fff = "aaa*bbb"`) because of `application/x-www-form-urlencoded` and POST method.
3. For injecting the request body, Spring reconstructs it from the parameters list (`ServletServerHttpRequest.getBodyFromServletRequestParameters`), but information about encoding is lost (so injected body is `fff=aaa*bbb`).

In case you'd be curious about my use case, [I need to verify Slack signature and I need full, unchanged body for that](https://api.slack.com/docs/verifying-requests-from-slack#how_to_make_a_request_signature_in_4_easy_steps__an_overview).

**Comment by yuequan1997** [comment]
The reason is that it was changed when the Mock request was constructed
The following is the implementation fragment：
MockHttpServletRequestBuilder#buildRequest:644
```java
if (this.content != null && this.content.length > 0) {
    String requestContentType = request.getContentType();
    if (requestContentType != null) {
        MediaType mediaType = MediaType.parseMediaType(requestContentType);
	if (MediaType.APPLICATION_FORM_URLENCODED.includes(mediaType)) {
	    addRequestParams(request, parseFormData(mediaType));
	}
    }
}
```
But it is correct，[Specific reference](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters)

When a character from the reserved set (a "reserved character") has special meaning (a "reserved purpose") in a certain context, and a URI scheme says that it is necessary to use that character for some other purpose, then the character must be percent-encoded. Percent-encoding a reserved character involves converting the character to its corresponding byte value in ASCII and then representing that value as a pair of hexadecimal digits. The digits, preceded by a percent sign (%) which is used as an escape character, are then used in the URI in place of the reserved character. (For a non-ASCII character, it is typically converted to its byte sequence in UTF-8, and then each byte value is represented as above.)

I recommend：Replace the ContenetType except  `application/x-www-form-urlencoded`

**Comment by rstoyanchev** [comment]
@szatkus, `ServletServerHttpRequest.getBodyFromServletRequestParameters` does do encoding via `java.net.URLEncoder` but `*` is not a character that needs to be encoded. Here are the [rules for encoding](https://url.spec.whatwg.org/#concept-urlencoded-serializer) form data. 

So why is that encoded in the first place? And why do you need it to be encoded, isn't `*` the actual content of the value? Even if you do need to post it to another server as form data, it shouldn't have to be encoded.

**Comment by szatkus** [comment]
It was quite a bit time ago, but AFAIR it was Slack API. You can create webhooks for Slack, so every time a user get into an interaction with your bot you can get a request from Slack. 

As you probably know Slack uses Markdown for message formatting. In Markdown asterisks are used for bold and we used it in a interactive message that was send to users. After a user clicks some of the buttons in the message we get a callback request from Slack. The request body includes the original message, but we didn't need that field and we didn't use it.

So what's the problem? Slack attaches a signature to every request. So I wanted to be a responsible citzen and implemented signature verification of that signature. As you can guess the signature is calculated basing on a request body. For some reasons asterisks in the body are encoded.

Of course Slack is out of my control, so I can't fix their behaviour. I already work-arouned the issue, but I filed a bug, because I think it's a weird thing that `@RequestBody` in some cases isn't an actual request body.

**Comment by rstoyanchev** [comment]
Thanks for elaborating. Unfortunately this is a bit outside of our control since the body can be parsed at any time as a result of access to request parameters, and all we can do is reconstruct it from request parameters that are already decoded. Obviously at that point we can't re-encode it to be exactly the same if the client encoded characters that didn't need to be encoded.

For more direct access to the body for a form data request, you can declare an `InputStream` argument in the controller, which should work assuming no code tries to access request parameters prior to that. Alternatively one could also use a `Filter`.
