### ISSUE TITLE
cannot find annotation

### ISSUE THREAD

**Issue by AcrazyDog** [spring-projects/spring-framework#23285]
**Version::5.1.7.RELEASE.**

when I use AOP like this: `@Around("@annotation(PulsarListener)")`, I cannot find  `PulsarListener` like this:  

```java
PulsarListener annotation = AnnotationUtils.getAnnotation(method, PulsarListener.class); 
```

I 'm not sure it's a bug or I use wrong, so I also ask on [stackoverflow](https://stackoverflow.com/questions/57000814/annotationutils-getannotationmethod-pulsarlistener-class-cannnot-work).

**Code:**

```java
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface PulsarListener {
    String[] topics() default {};
}

@Aspect
@Slf4j
@Component
@Order(0)
public class MDCAspect {
    @Around("@annotation(PulsarListener)")
    public Object around(ProceedingJoinPoint joinPoint) throws Throwable {
    ...
    }
}

@Slf4j
@Component
public class PulsarPostProcessor implements BeanPostProcessor {

    @Value("${pulsar.service.url}")
    private String pulsar_service_url;
    @Override
    public Object postProcessAfterInitialization(final Object bean, final String beanName) throws BeansException {

        Method[] methods = bean.getClass().getDeclaredMethods();

        for (Method method : methods) {
            //here  annotation is null;
            PulsarListener annotation = AnnotationUtils.getAnnotation(method, PulsarListener.class); 
         ...
```

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
