### ISSUE TITLE
Introduce SimpleUrlHandlerMapping constructor that accepts an order and a Map 

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-framework#23362]
I use `SimpleUrlHandlerMapping` for reactive websockets and I either end up instantiating the bean and then calling `.setUrlMap(...)` and `setOrder(...);` Or I create an anonymous subclass and call those setters in that. Either way, tedious. Please add a constructor so it can be a one-liner :-)

**Comment by sbrannen** [comment]
If we introduce explicit constructors for `org.springframework.web.reactive.handler.SimpleUrlHandlerMapping`, we should do the exact same for `org.springframework.web.servlet.handler.SimpleUrlHandlerMapping`.

**Comment by rstoyanchev** [comment]
The spring-webmvc variant has a lot more properties which makes picking urlMap and order out of all of them a bit more random. On the other hand if we were to pick one, urlMap does make sense on both sides. Maybe then order can be left to being expressed with `@Order`?

**Comment by sbrannen** [comment]
> The spring-webmvc variant has a lot more properties which makes picking urlMap and order out of all of them a bit more random. On the other hand if we were to pick one, urlMap does make sense on both sides. 

I agree that picking `urlMap` for both makes sense. Supporting `Properties` directly in the constructor probably doesn't make much sense for programmatic configuration (i.e., in `@Bean` methods), since properties are more often used with XML configuration where constructor arguments are likely not used.

> Maybe then order can be left to being expressed with `@Order` and just have a one-arg constructor on both sides with urlMap?

That unfortunately won't work since `AnnotationAwareOrderComparator` (which is used to sort the handler mappings in `DispatcherServlet#initHandlerMappings(ApplicationContext)`) gives `Ordered` precedence over `@Order`, effectively ignoring `@Order` for `AbstractHandlerMapping` implementations such as `SimpleUrlHandlerMapping`.

I think it would be OK to introduce the following constructors for both types.

- `SimpleUrlHandlerMapping()`
- `SimpleUrlHandlerMapping(Map<String, ?> urlMap)`
- `SimpleUrlHandlerMapping(Map<String, ?> urlMap, int order)`

Thoughts?

**Comment by joshlong** [comment]
I'd very much like that.

**Comment by sbrannen** [comment]
FWIW, `org.springframework.web.servlet.config.annotation.ViewControllerRegistry.buildHandlerMapping()` could also benefit from a `SimpleUrlHandlerMapping(Map<String, ?> urlMap, int order)` constructor.
