### ISSUE TITLE
Set up a server. The servlet. ContextPath = / my interceptor is based on the/my/began to intercept

### ISSUE THREAD

**Issue by 1346735074** [spring-projects/spring-framework#23373]
Mr Ma set up a server. The servlet. ContextPath = / my
The interceptor starts intercepting based on /my/
Such as:
Registry. AddRedirectViewController ("/", "/ my/index. The HTML")
SetStatusCode (HttpStatus. PERMANENT_REDIRECT);
Enter 127.0.0.1:8080/ cannot jump to /my/index.html properly

**Comment by 1346735074** [comment]
@sbrannen @jhoeller @rstoyanchev

**Comment by 1346735074** [comment]
@sbrannen Can you help me look over this problem

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by 1346735074** [comment]
@sbrannen You can help to look at this problem
https://stackoverflow.com/questions/57251849/set-up-a-server-the-servlet-contextpath-my-interceptor-is-based-on-the-my
