### ISSUE TITLE
Invalid using @EnableCaching(mode = AdviceMode.ASPECTJ)

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#23389]
i want use `@EnableCaching(mode = AdviceMode.ASPECTJ)` but it not work?

**Comment by snicoll** [comment]
@brucelwl thank you for the sample. It does not work either when I replace the use of Spring Boot with plain Spring framework code.

**Comment by philwebb** [comment]
@brucelwl We've transferred the issue to Spring Framework for that team to take a look at.

**Comment by brucelwl** [comment]
@sbrannen Please confirm this issue. you may need to roll back to the corresponding version of `cache-sapect`, **f5db13a5d7cb50ee6b173cc1f7cd8c76dbad5e80**

**Comment by philwebb** [comment]
@brucelwl I can't find a commit for f5db13a5d7cb50ee6b173cc1f7cd8c76dbad5e80, please can you provide a link so we know what you are referring to.

**Comment by brucelwl** [comment]
@philwebb  What i am referring to is https://github.com/brucelwl/demo, I used this project to submit other issue, but the demo for cache-aspect needs to be rolled back to the f5db13a5d7cb50ee6b173cc1f7cd8c76dbad5e80 version

**Comment by philwebb** [comment]
@brucelwl It's best if you create one sample per issue that you raise. To clarify, you're saying that [this commit](https://github.com/brucelwl/demo/commit/f5db13a5d7cb50ee6b173cc1f7cd8c76dbad5e80) needs to be reverted in order to trigger the issue?

> no confirmation information has been received

There's a lot of work on at the moment so it may take some time for someone from the framework team to triage the issue.

**Comment by brucelwl** [comment]
@philwebb Okay, I'll create branches for different issues later to demonstrate the problem.

**Comment by snicoll** [comment]
Closing due to the lack of feedback.
