### ISSUE TITLE
Annotations with @AliasFor are invalid in non-startup classes

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#23402]
I have a longer set of annotation attributes, so I use `@AliasFor` to set up a short annotation. If the new annotation is set on the boot class, the value of the annotation attributes can be obtained, but the value of the annotation attributes can not be obtained on the non-boot class
Maybe if you look at my demo, you can get a clearer understanding of what I mean.
https://github.com/brucelwl/demo

**Comment by sbrannen** [comment]
Thanks for raising the issue.

In your example, it turns out that `@AliasFor` is not honored for attribute override support in a meta-annotation when `AnnotationMetadataReadingVisitor` is the concrete implementation type for the `AnnotationMetadata importingClassMetadata` argument supplied to your `registerBeanDefinitions()` implementation.

In contrast, when the concrete implementation type is `StandardAnnotationMetadata`, your code works as expected.

So that at least explains what it is going on.

I don't yet have a workaround or solution to your problem, but we will continue to investigate.

**Comment by sbrannen** [comment]
@brucelwl, one way to circumvent the issue is to force the loading of `@Configuration` classes discovered via component scanning.

If you're OK with eagerly forcing the loading of such classes, the following should work for you. Basically, the goal in the following code is to:

1. retrieve the fully qualified class name of the `@Configuration` class from the supplied metadata
2. eagerly load the `@Configuration` class using reflection via `ClassUtils`
3. use `AnnotatedElementUtils` for full support of `@AliasFor`, including support for attribute overrides in meta-annotations.

```java
Class<?> clazz = null;
try {
	String className = importingClassMetadata.getClassName();
	clazz = ClassUtils.forName(className, getClass().getClassLoader());
}
catch (ClassNotFoundException ex) {
	throw new RuntimeException(ex);
}
EnableGitVersionControlConfig anno =
	AnnotatedElementUtils.findMergedAnnotation(clazz, EnableGitVersionControlConfig.class);

logger.info("*** serverAddress={}", anno.serverAddress());
logger.info("*** targetBranch={}", anno.targetBranch());
```

When I execute your tests with the above change, I see the expected log output.

Please let me know if this workaround works for you!

Thanks,

Sam

**Comment by brucelwl** [comment]
@sbrannen Thank you very much for your reply. Your solution can solve my problem. I have another similar solution.

```
public class GitConfigBeanDefinitionRegistrar implements ImportBeanDefinitionRegistrar {

    private static final Logger logger = LoggerFactory.getLogger(GitConfigBeanDefinitionRegistrar.class);

    @Override
    public void registerBeanDefinitions(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry) {
        String className = importingClassMetadata.getClassName();
        Class<?> aClass = null;
        try {
            aClass = ClassUtils.forName(className, null);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        StandardAnnotationMetadata metadata = new StandardAnnotationMetadata(aClass, true);
        AnnotationAttributes annotationAttributes = AnnotationAttributes.fromMap(
                metadata.getAnnotationAttributes(EnableGitVersionControlConfig.class.getName()));
        logger.info("serverAddress={}", annotationAttributes.getString("serverAddress"));
        logger.info("targetBranch={}", annotationAttributes.getString("targetBranch"));
    }
}

```

**Comment by sbrannen** [comment]
@brucelwl, thank you for the confirmation! I am glad to know that works for you.

FWIW, the behavior you described is a known deficiency.

Fortunately, @philwebb resolved this issue for the upcoming Spring Framework 5.2 release. This was achieved by the introduction of a new `SimpleAnnotationMetadata` class that is used behind the scenes for components picked up via component scanning. `SimpleAnnotationMetadata` uses the new `MergedAnnotations` API which provides full support for `@AliasFor` within annotation hierarchies, even for metadata sourced from ASM.

I have therefore changed the title of this issue to reflect the known deficiency, and I've assigned this issue to 5.2 so that others know that this has been addressed.

Thanks again, @philwebb, for `SimpleAnnotationMetadata` and (unwittingly?) fixing this issue!
