### ISSUE TITLE
Only one connection receive subscriber allowed On custom HandlerMethodArgumentResolver

### ISSUE THREAD

**Issue by ileler** [spring-projects/spring-framework#23449]
https://github.com/spring-projects/spring-framework/blob/28c5d7b586bac659bac2558264a928e1f5dd6b2c/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/InvocableHandlerMethod.java#L200
When you read the body of request in the `resolveArgument` method of `HandlerMethodArgumentResolver`, an error "`Only one connection receive subscriber allowed.`" occurs.
look at this: 
https://stackoverflow.com/questions/57427549/only-one-connection-receive-subscriber-allowed-on-custom-handlermethodargumentre

Do I think it is necessary to wrap a copy of `exchange` here in` line 200`? Each time the `resolveArgument` method is a separate copy, can you solve this problem?

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

From what [I can see](https://github.com/ileler/spring-web-json-param/tree/master/src/main/java/org/ileler/swjp), for Spring MVC you're reading the body once and caching it. WebFlux is no different, the body can only be read once unless cached.
