### ISSUE TITLE
Respect already set `content-length` header for HEAD request.

### ISSUE THREAD

**Issue by TYsewyn** [spring-projects/spring-framework#23484]
Currently when making a downstream request from Spring Cloud Gateway, the `content-length` HTTP header is being overwritten by `org.springframework.http.server.reactive.HttpHeadResponseDecorator`. Ideally this decorator should not kick in when the header was already set manually, or otherwise.
Also see https://github.com/spring-cloud/spring-cloud-gateway/issues/1210.

**Comment by rstoyanchev** [comment]
Come to think of it, we still need to wait for data buffers to be written in order to release them. The question is what should happen if there are data buffers and an existing `content-length` header? 

@TYsewyn I believe in your case there is no data to be written since you're simply passing through a response from the downstream which has a `content-length` but no data otherwise. So the change could be to respect an existing `content-length` if no content was written.

**Comment by TYsewyn** [comment]
Yep, I believe that was the use case of the issued ticket at SC Gateway. I think your proposed solution would be perfect. If the downstream service does send data then it would make sense to recalculate the content length since that's the content the gateway received.
