### ISSUE TITLE
Revisit EnableCaching versus EnableTransactionManagement default order

### ISSUE THREAD

**Issue by qixiaobo** [spring-projects/spring-framework#23527]
I use EnableTransactionManagement and EnableCaching at the same time.
I find them in the same aspect order. 

You may see

> Advice ordering
> What happens when multiple pieces of advice all want to run at the same join point? Spring AOP follows the same precedence rules as AspectJ to determine the order of advice execution. The highest precedence advice runs first "on the way in" (so given two pieces of before advice, the one with highest precedence runs first). "On the way out" from a join point, the highest precedence advice runs last (so given two pieces of after advice, the one with the highest precedence will run second).
> 
> When two pieces of advice defined in different aspects both need to run at the same join point, unless you specify otherwise the order of execution is undefined. You can control the order of execution by specifying precedence. This is done in the normal Spring way by either implementing the org.springframework.core.Ordered interface in the aspect class or annotating it with the Order annotation. Given two aspects, the aspect returning the lower value from Ordered.getValue() (or the annotation value) has the higher precedence.
> 
> When two pieces of advice defined in the same aspect both need to run at the same join point, the ordering is undefined (since there is no way to retrieve the declaration order via reflection for javac-compiled classes). Consider collapsing such advice methods into one advice method per join point in each aspect class, or refactor the pieces of advice into separate aspect classes - which can be ordered at the aspect level.

the same order is Ordered.LOWEST_PRECEDENCE
I think the cacheAspect may have a higher order than transactionAspect because we need not to make a request to database if the data is cached.
In my project, I can see lot of 
```sql
select @@session.tx_read_only
```
even the data is cached.

I will modify the EnableCaching with the order Ordered.LOWEST_PRECEDENCE-1

**Comment by qixiaobo** [comment]
Someone makes a reply？

**Comment by qixiaobo** [comment]
so sad

**Comment by jhoeller** [comment]
On review, it is not so clear what a default order of those aspects should be: Cache operations may also participate in transactions, e.g. in a JTA setup with distributed caching or with the "transactionAware" flag for JCache. Configuring your own order explicitly - as you are able to do already - seems fine here, provided that you known that your cache does not need to be transaction-aware.

For a scenario where you'd like to avoid database connections for "empty" transactions, consider configuring `LazyConnectionDataSourceProxy` in front of your target `DataSource`. This is generally highly recommendable since it also works with built-in caches in the persistence provider, e.g. in Hibernate, where you always operate within a transaction while often not having to access the database eventually.
