### ISSUE TITLE
Spring cache multiple level cache support 

### ISSUE THREAD

**Issue by abccbaandy** [spring-projects/spring-framework#23531]
**Affects:** 5.1.9

Does spring cache support multiple level cache?

I want a L1 cache like caffeine and a L2 cache like redis.

There is a `CompositeCacheManager`, but it seems not for this case.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by abccbaandy** [comment]
I think this will be an enhancements if spring not support it.

About stackoverflow, there is already a question.
https://stackoverflow.com/questions/53786000/l1-l2-caching-strategy-using-spring-cacheable
