### ISSUE TITLE
Provide access to non-standard status codes from ServerHttpResponse

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#23547]
In a similar vein to https://github.com/spring-projects/spring-framework/issues/22872, it would be useful to have access to the raw status code rather than `null` when dealing with a response with a status code that is not known to `HttpStatus`.

**Comment by jhoeller** [comment]
This is available in some form (managing locally set status code values outside of the enum range) on `AbstractServerHttpResponse` - would a downcast be sufficient for your purposes?

Since the `ServerHttpResponse` interface is more about modifying than introspecting the response, I'm rather reluctant to add further introspection methods to the interface.

**Comment by wilkinsona** [comment]
Yes, that works nicely. Thanks for the suggestion.
