### ISSUE TITLE
Can't remove header using HttpServletResponse

### ISSUE THREAD

**Issue by SzabKel** [spring-projects/spring-framework#23548]
[Please check out my reproduction of the issue here.](https://bitbucket.org/szabkel/emptyfileonexceptionrepro/src/master/src/main/java/com/emptyfileproblem/repro/TestResponseChange.java)

I ran into this problem, while I wanted to make an endpoint, which allows the users to download a File (browser pops up a File Save As window), but if there is an error during the preparing process, it should display an error message (default spring whitelabel error page would be fine). You can read more [here](https://stackoverflow.com/questions/57689005/spring-boot-exception-during-download-results-in-empty-file).

If I once set the header `Content-Disposition`, I can't remove it using the `HttpServletResponse`.

Example: 
```java
@RestController
@RequestMapping("api")
public class TestResponseChange {
    @Autowired
    ResourceLoader resourceLoader;

    @GetMapping("/download-change")
    public void download(HttpServletResponse response) throws SomeException {

        try (OutputStream out = response.getOutputStream()) {
            response.setContentType("application/x-download");
            response.setHeader("Content-Disposition", "attachment; filename=\"SomeFile.txt\"");

            if (1 == 1 / 1) {
                throw new Exception("Test");
            }

            var resource = resourceLoader.getResource("classpath:TestFileToRead.txt");
            try (var inputStream = new FileInputStream(resource.getFile())) {
                StreamUtils.copy(inputStream, out);
            }
        } catch (Exception e) {
            response.setContentType("text/plain");
            response.setHeader("Content-Disposition", null);
            throw new SomeException(e);
        }
    }

    @ExceptionHandler(SomeException.class)
    public ResponseEntity<String> handleException(SomeException ex) {
        System.out.println("Failed. " + ex.getMessage());
        return new ResponseEntity<>(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
    }
}
```

If I navigate my browser to the `api/download-change` url, the result will be an empty file download and a "logged" error.

**Comment by bclozel** [comment]
I've checked the repro case and even tested a different variant:

```java
@RestController
@RequestMapping("api")
public class TestDownload {
	@Autowired
	ResourceLoader resourceLoader;

	@GetMapping("/download")
	public ResponseEntity<StreamingResponseBody> download() {
		return ResponseEntity.ok()
				.contentType(MediaType.valueOf("application/x-download"))
				.header("Content-Disposition", "attachment; filename=\"SomeFile.txt\"")
				.body(outputStream -> {
					if (true) {
						throw new SomeException("Test");
					}
					var resource = resourceLoader.getResource("classpath:TestFileToRead.txt");
					try (var inputStream = new FileInputStream(resource.getFile())) {
						StreamUtils.copy(inputStream, outputStream);
					}
				});
	}

	@ExceptionHandler(SomeException.class)
	public ResponseEntity<String> handleJasperException(SomeException ex) {
		System.out.println("Salary Report generation failed. " + ex.getMessage());
		return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
				.body(ex.getMessage());
	}
}

```

What happens is:
1. the response headers are written to the servlet response before we're entering the `StreamingResponseBody` part
2. exception is thrown before the body is written
3. error handling happens and the `ResponseEntity` is properly processed (copying headers and body to the servlet response)
4. at that point, the headers already written to the servlet response aren't removed and they're still here in the final HTTP response

I'm not sure how Spring Framework can help here since:
* the Servlet response API does not offer a way to remove HTTP response headers
* we wouldn't know which headers we should remove since some of those could have been added by a Filter or any other part that's not involved with the controller handler

The best course of action here would be to try and add those response headers as late as possible in the process. Also, keep in mind that if an exception happens while writing to the response body the servlet response is committed and nothing can change the HTTP status or headers anymore.

**Comment by chri-ma-ri** [comment]
in my mind this is not a spring-framework issue and also depends on your server runtimes implementation of `HttpServletResponse`

as @bclozel mentioned, add/set response-headers and open ServletOutputStream as late as possible

in your particular case (`ServletOutputStream` opened, reponse-headers are set/added and the error occurs before writing bytes to `ServletOutputStream`) you could try to use `response.reset()` in your `catch`-block to get `@ExceptionHandler(...)` to work

**Comment by bclozel** [comment]
As suggested by @chri-ma-ri , calling `reset` might also help.
I'm closing this issue as I don't think we can do anything about it in Spring Framework.
