### ISSUE TITLE
Bean definition override leads to NPE due to inconsistent equality check

### ISSUE THREAD

**Issue by andrey-vasilyev** [spring-projects/spring-framework#23593]
Hi, I've recently tried to switch to spring 5.1.9. And my old code (based on spring 4.3.4) stopped working because of NPE during context refresh. I've created a minimal reproducible example https://gist.github.com/andrey-vasilyev/ad42b33c13ce850bfd7065ef35f95017

The issues (difference in behaviour) seems to be in `AbstractBeanDefinition.equals` method. Could you please take a look?

**Comment by jhoeller** [comment]
This turns out to be caused by an inconsistent equality check in `ConstructorArgumentValues` (for indexed argument mismatches) as well as `GenericBeanDefinition` (which misses a check for parent name equality). While the reported NPE effect may only manifest in recent versions, the underlying bugs are present in 4.3.x too and should get backported there as well.
