### ISSUE TITLE
Could not find key 'spring.liveBeansView.mbeanDomain' in any property source

### ISSUE THREAD

**Issue by Purva-Kaul** [spring-projects/spring-framework#23609]

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

---

Having pointed out our policy, here's a tip you might find useful.

> Could not find key 'spring.liveBeansView.mbeanDomain' in any property source

That is either a DEBUG or TRACE level logging statement that is issued when Spring cannot find a property named `spring.liveBeansView.mbeanDomain` in the `Environment`.

Unless you are explicitly trying to use Spring's `org.springframework.context.support.LiveBeansView` support, you can safely ignore this log statement.
