### ISSUE TITLE
ProxyTransactionManagementConfiguration is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by liaozan** [spring-projects/spring-framework#23600]
It seems that it was initialized too early
#### steps to reproduce this issue:
- download simple code from start.spring.io
- add the following dependencies: `spring-boot-starter-cache`,`spring-boot-starter-data-jpa`,`spring-boot-starter-web`
- add `@EnableCaching` to the startup class
- then run the application
***
Next, you will see the output on the console.
`Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)`

**Comment by sbrannen** [comment]
Which version of Spring Boot did you select when generating the project?

**Comment by liaozan** [comment]
2.1.8.RELEASE and 2.2.0.M5, both tried

**Comment by liaozan** [comment]
> Which version of Spring Boot did you select when generating the project?

https://github.com/liaozan/demo ，here is the smallest example that can be reproduced

**Comment by snicoll** [comment]
That sounds like a duplicate of https://github.com/spring-projects/spring-boot/issues/17561 where something in Spring Data might indeed lead to eager initialization. 

@mp911de and I had a quick look to it but Mark was hoping we would assist him at tracking down the problem so if we could do that it would be great. It's not very obvious if the problem is in framework or in the way Spring Data uses the context.

**Comment by liaozan** [comment]
tks, i got it
