### ISSUE TITLE
How can i upgrade my spring boot 2.1.8 based project to spring framework  5.2.0 RC2

### ISSUE THREAD

**Issue by nikkisingh111333** [spring-projects/spring-framework#23624]
How can i upgrade my spring boot 2.1.8 based project to spring framework  5.2.0 RC2? I WANT TO UPGRADE MY PROJECT FOR STARTED USING R2DBC TRANSACTION MANAGEMENT IN MY PROJECT. HOW CAN I DO THAT WITHOUT STARTING MY PROJECT FROM SCRATCH?

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
