### ISSUE TITLE
Fix RSocketRequester API for requests without payload

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#23649]
Current `RSocketRequester` makes it mandatory to use `RequestSpec#data` methods in order to reach `ResponseSpec` methods that allow to perform the exchange. This `RequestSpec` / `ResponseSpec` split seems unnecessary since  all `ResponseSpec` methods can be invoked directly for request without payload, which seems to be a perfectly valid use case.

This leads to code like `req.route("find.radar.{iata}", iata).data(Mono.empty()).retrieveMono(AirportLocation.class))`, and the issue is even more impacting in Coroutines world since `data()` does not accept `null`.

After discussion with @bclozel, our proposal is to merge `RequestSpec` and `ResponseSpec` in order to avoid this issue. Another hint that they should probably be merged is that `ResponseSpec` methods have side effects on the request itself.

About the name, maybe we could just use `RequestSpec`,  move `ResponseSpec` methods in it and remove `ResponseSpec`.

**Comment by bclozel** [comment]
I think this change aligns nicely with our infrastructure and RSocket in general, because:

1. unlike its counterpart in `WebClient`, here the `ResponseSpec` is not only about how to consume the response, but also about the type of request and RSocket communication pattern we'll use. `ResponseSpec` has side-effects on `RequestSpec`.
2. as @sdeleuze said, none of the `RequestSpec` methods are mandatory.

The alternative would be to have a `noData()` in the `RequestSpec`, but its only goal would be to express the absence of a `data()` call.

**Comment by sdeleuze** [comment]
I have worked on that, and here is my proposal: https://github.com/sdeleuze/spring-framework/commit/rsocketrequester-refactoring.

This commit makes it possible to send requests without without requiring to call `data(Mono.empty())`.

It clarifies the semantics by renaming `ResponseSpec` to `InteractionSpec` in order to leverage more directly `RSocket` vocabulary and make things more consistent now that `RequestSpec`
extends it.

It also improves the `Consumer` variant of metadata in order to prevent calling `data` in the callback (only `metadata` is now accessible).

Any thoughts @bclozel @rstoyanchev?
