### ISSUE TITLE
SseEmitter onError method does not get called on Payara 5

### ISSUE THREAD

**Issue by hsynff** [spring-projects/spring-framework#23668]
I'm trying below code on Spring MVC (5.1.8 version of dependencies) deployed on Payara 5 (Glassfish) :

```java
@GetMapping("/listen-sse")
public SseEmitter sseEmitter() {
        SseEmitter emitter = new SseEmitter(0L);
        emitter.onError(e -> System.out.println("OnError"));

        ExecutorService service = Executors.newCachedThreadPool();
        service.execute(() -> {
            while (true) {
                try {
                    Thread.sleep(2000);
                    emitter.send("Hello");
                } catch (IOException | InterruptedException e) {
                    System.out.println("Exception");
                    break;
                }
            }
        });

        service.shutdown();
        return emitter;
}
```
When the client disconnects I can only see "Exception" on console but not "OnError".
I've tried the same code with Spring boot (same dependency versions) and embed tomcat everything works as expected.

**Comment by hsynff** [comment]
I've tested the same war on Tomcat 8.5.42 and onError called

**Comment by rstoyanchev** [comment]
`SseEmitter#onError` is a callback connected to the Servlet container via an `AsyncListener#onError`. This is registered in [StandardServletAsyncWebRequest](https://github.com/spring-projects/spring-framework/blob/47a24ac3787414b4ed6652cba53755ba752136eb/spring-web/src/main/java/org/springframework/web/context/request/async/StandardServletAsyncWebRequest.java#L144-L147) and propagates through the `DeferredResult` in [ResponseBodyEmitter.Handler](https://github.com/spring-projects/spring-framework/blob/47a24ac3787414b4ed6652cba53755ba752136eb/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyEmitterReturnValueHandler.java#L220-L223). 

The Servlet container is supposed to notify of errors via `AsyncListener#onError` and in this case it isn't. It could simply be a bug in Glassfish. Or perhaps they intentionally do not notify because of the expectation you would have caught the exception, although that doesn't make sense since an `AsyncListener` may be completely independent from the code actually writing. So I suspect it is a bug and the fact that it works in Tomcat is another indication.

**Comment by deeDude** [comment]
This issue also happens with Jetty 9...

**Comment by rstoyanchev** [comment]
@deeDude, the Jetty 9.x version range spans nearly 7 years. Can you be more specific?

**Comment by deeDude** [comment]
> @deeDude, the Jetty 9.x version range spans nearly 7 years. Can you be more specific?

Sorry for my imprecision, the exact Jetty version is v9.4.22.v20191022, with spring boot v2.2.1
