### ISSUE TITLE
Allow dynamic ttl in @Cacheable

### ISSUE THREAD

**Issue by young891221** [spring-projects/spring-framework#23684]
Hitting this issue with Spring All versions:

Currently, `@Cacheable` only permmited cacheConfig TTL. I have a requirement to set TTL dynamically using the `@Cacheable` annotation.
Of course, it can be handled with a custom `RedisCacheWriter` or`CacheResolver`, but I think it can be useful to many users if a method such as `String dynamicTtl()` is supported for `@Cacheable`.

**Comment by snicoll** [comment]
> Currently, @Cacheable only permmited cacheConfig TTL

`@Cacheable`[does not have support for TTL by design](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#cache-specific-config) so it will definitely can't provide a dynamic TTL. Anything that's configuration related does not belong in this abstraction. 

Can you please clarify what you mean by TTL and why you think `@Cacheable` supports it?

**Comment by young891221** [comment]
Sorry, I haven't read the doc([does not have support for TTL by design](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#cache-specific-config)).
The TTL I said is synonymous with Redis's evict time.
In my opinion, one of the development requirements was the ability to dynamically specify an eviction time for the cache. I raised the issue, thinking that this same issue could happen to many other users.

**Comment by snicoll** [comment]
You can’t configure the evict time with cacheable either. This isn’t a design goal of the project to provide a configuration abstraction. Thanks anyway.
