### ISSUE TITLE
Spring Cache:How to set prefixKeysWith in RedisCacheConfiguration 

### ISSUE THREAD

**Issue by jianguo8661** [spring-projects/spring-framework#23687]
I want to change prefixKey in RedisCacheConfiguration with below code:
`@Component
public class RedisCacheConfigurationBeanPostProcessor implements BeanPostProcessor {
    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
        if (bean instanceof org.springframework.data.redis.cache.RedisCacheConfiguration) {
            ((RedisCacheConfiguration) bean).prefixKeysWith("#");
        }
        return bean;
    }
}` **but this not work!**

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also please note that `RedisCacheConfiguration` is not part of Spring Framework but Spring Data Redis.
