### ISSUE TITLE
i hava to ask the question that one class which is annotaed with @Configuration has a lot of methods that those have the same method name and were annotated with @Bean

### ISSUE THREAD

**Issue by 535431135** [spring-projects/spring-framework#23720]
the code is below:
    @Bean("test")
    @ConditionOnProperties(properties = "user.age")
    public InnerClass test() {
        return new InnerClass("1");
    }

    @Bean("test2")
    public InnerClass test(@Qualifier("test") InnerClass innerClass) {
        System.out.println(innerClass);
        return new InnerClass("2");
    }

Q:
If the @ConditionOnProperties is effective that the bean named as "test" will be passed,the Other Bean named "test2" can be added into the Bean Container?

the question is tested when i saw the source code from the spring framework,and the source code is below:
		// Do we need to mark the bean as skipped by its condition?
		if (this.conditionEvaluator.shouldSkip(metadata, ConfigurationPhase.REGISTER_BEAN)) {
			configClass.skippedBeanMethods.add(methodName);
			return;
		}
		if (configClass.skippedBeanMethods.contains(methodName)) {
			return;
		}
that is in the ConfigurationClassBeanDefinitionReader class file,the concrete position is from 186 line to 193 line.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by 535431135** [comment]
I think it is a genuine bug. Becaese I have tested

**Comment by snicoll** [comment]
It's not very obvious what you're asking I am afraid `@ConditionOnProperties` does not exist (at least not in our code base) and if you're referring in `@ConditionalOnProperty` it's part of Spring Boot. Rather than code snippet if you attach a zip (or a link to a github repo) that reproduces the problem you're describing we could take another look.

**Comment by 535431135** [comment]
the question is generally that when I added most of  overload methods being annotated with @Bean In the class file which is annotated with @Configuration.when I added one Condition's annotation. on one of the overload methods.if the method that be annotated with @Condition's annotation is skipped.the other overload method will not be add into Spring Bean Container.
