### ISSUE TITLE
I found a problem in the process of reading the source code, the configurationClasses member of the ConfigurationClassParser class, why not use Set here?

### ISSUE THREAD

**Issue by wycm** [spring-projects/spring-framework#23857]
I found a problem in the process of reading the source code: the `configurationClasses` member of the `ConfigurationClassParser` class.

Why not use `Set` here?

https://github.com/spring-projects/spring-framework/blob/5b6337b6a9c4b23720f92aee575df099a9972c64/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java#L133

**Comment by sbrannen** [comment]
A `Map` is needed here in order to look up an existing `ConfigurationClass`.

See the `processConfigurationClass(ConfigurationClass)` method for details.

https://github.com/spring-projects/spring-framework/blob/5b6337b6a9c4b23720f92aee575df099a9972c64/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java#L225-L240

**Comment by wycm** [comment]
I think this lookup doesn't make sense because the only key and value arguments that call the put method are the same object.[https://github.com/spring-projects/spring-framework/blob/5b6337b6a9c4b23720f92aee575df099a9972c64/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java#L249](url)

**Comment by sbrannen** [comment]
The lookup is necessary, and `Set` does not provide direct access to its elements (i.e., it has no `get(...)` method). Thus, using a `Set` is not an option.
