### ISSUE TITLE
How to get certificate in spring-webflux

### ISSUE THREAD

**Issue by xxxxpenny** [spring-projects/spring-framework#23853]
If use spring tomcat server, I can get client certificate by the code.
```java
X509Certificate[] certs = (X509Certificate[])HttpServletRequest.getAttribute("javax.servlet.request.X509Certificate");
```

Now, I use webflux netty-http-server, How to get client certificate?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
