### ISSUE TITLE
Get null result when using RefreshScope annotation with Kotlin

### ISSUE THREAD

**Issue by newry** [spring-projects/spring-framework#23854]
We found following Kotlin code will return null when we call it by http://localhost:8080/message, which should be 'Hello default'

@RestController
@RefreshScope
open class MessageRestController {

    @Value("\${message:Hello default}")
    @get:RequestMapping("/message")
    internal val message: String? = null
}
If we changed it to Java, it works well

used Spring version:
spring boot 2.1.6
spring-cloud-dependencies Greenwich.SR3

is this a know issue?

**Comment by mgmeiner** [comment]
I couldn't reproduce this. 
Tried it with a simple spring.boot 2.1.6, 2.1.9 and 2.2.0 app. RefreshScope also works fine. 
Maybe you could create a demo project to reproduce the issue?

Also I would not recommend to use a nullable `val` for this because _val_ should not change after initialization. If you want to "inject" the configuration-property like that I would make use of the [Kotlin Lateinit Property keyword](https://kotlinlang.org/docs/reference/properties.html#late-initialized-properties-and-variables) because the message property can never be null as you provide a default value. 

Example: 
`internal lateinit var message: String`

**Comment by newry** [comment]
Can you try following git:
https://github.com/newry/spring-examples

**Comment by newry** [comment]
I found the issue, the method need to be open, otherwise will not work, closing

**Comment by mgmeiner** [comment]
Consider using the  [kotlin compiler plugin forspring support](https://kotlinlang.org/docs/reference/compiler-plugins.html#spring-support).
It "opens" the required classes automatically.
