### ISSUE TITLE
Specify params of @PostMapping based on @RequestBody

### ISSUE THREAD

**Issue by Evertude** [spring-projects/spring-framework#23865]
As described in [this question](https://stackoverflow.com/questions/58522021/distinguish-spring-boot-postmapping-based-on-key-in-requestbody/58522430#58522430), I'd like to be able to use the params value of the PostMapping to distinguish between two endpoins based on existence of a key in the body.

```Java
@PostMapping(value = "/classes", params = {"specialKey"})
public ResponseEntity<Class> createClass(@Valid @RequestBody SpecialClass class) throws URISyntaxException {
    // do something special
}

@PostMapping("/classes")
public ResponseEntity<Class> createClass(@Valid @RequestBody Class class) throws URISyntaxException {
    // do something
}
```

**Comment by bclozel** [comment]
I believe this won't work with our current programming model.
We can only map requests using information that's available that's independent of the request body.

This approach would not work, for example, for formats that won't deserialize to `Map<String, Object>` types. Binary formats, such as Protobuf, won't work here. What should happen if both classes have that "param key"?
In case the client sends a request body without that "param key", we won't know if we should respond HTTP 404 as we couldn't map the request, or if we should go with an HTTP 400 because the body has the wrong format.
