### ISSUE TITLE
Support for limits on input stream processing in WebFlux codecs 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#23884]
While a proxy, or the underlying server, or a `WebFilter` can be used to enforce general limits on the size of server request input, it would be helpful for `Decoder` and `HttpMessageReader` implementations to expose configurable limits too, because codecs in WebFlux can parse asynchronously and pass one object one at a time to the application, as a stream. That means the overall request input stream may be infinite, and it's the input per streamed object that should be limited.

**Comment by rstoyanchev** [comment]
For an overview see ["Limits" section](https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/web/webflux.adoc#limits) in the reference documentation.

**Comment by scottjohnson** [comment]
I know this issue was closed in October, but I'm curious @rstoyanchev if you could explain what the downside of _not_ having a limit is? In other words prior to implementing the limit, what could go wrong if the size was very large and how would that manifest; such that adding a limit by default is an effective protection?

**Comment by rstoyanchev** [comment]
@scottjohnson there is [some explanation](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-limits) in the docs. It's about making it easy for applications to declare limits on input buffering. In the absence of such limits the application can run out of memory.
