### ISSUE TITLE
Different behavior when injecting Collection of beans from local @Configuration class vs. external @Configuration classes

### ISSUE THREAD

**Issue by aposcia** [spring-projects/spring-framework#23934]
Version: 5.2.1.RELEASE

Given the following configuration:

```java
@Configuration
public class BaseTestConfig {

    @Autowired
    private Collection<String> strings;

    @Bean
    public String stringA() {
        return "A";
    }

    @Bean
    public String stringB() {
        return "B";
    }


    @Bean
    public DemoClass demoBean() {
        System.out.println("Base config autowired strings: " + strings.size());
        return new DemoClass(strings);
    }

    class DemoClass {
        private final Collection<String> strings;

        public DemoClass(Collection<String> strings) {
            this.strings = strings;
        }

        public Collection<String> getStrings() {
            return strings;
        }
    }

}
```

When `demoBean` is instantiated, it prints: 

> Base config autowired strings: 2

If we add another config file with content:

```java
@Configuration
public class Extension1TestConfig {

    @Bean
    public String stringC() {
        return "C";
    }

}
```

when `demoBean` is instantiated, it prints: 

> Base config autowired strings: 1

We expect to have the 3 string beans injected into `demoBean` (2 beans of `BaseTestConfig` and 1 bean of `Extension1TestConfig`). However, as soon as another configuration file is declaring some String beans, the beans declared in `BaseTestConfig` are not injected anymore in the collection (strings) and only the beans of the other context(s) are injected.

**Comment by sbrannen** [comment]
When you say "are not injected anymore in the collection", do you mean that you experienced different behavior in a version of Spring Framework prior to 5.2.1?

**Comment by aposcia** [comment]
No, we actually tried with 5.1 as well and the behaviour is the same as with 5.2.1.

**Comment by sbrannen** [comment]
@aposcia, thanks for the feedback.

I have confirmed the described behavior against `master` (i.e., `5.2.x`), and I cannot yet explain why we are seeing that.

However, I do have a workaround for you.

Redeclare your `demoBean()` method as follows, allowing Spring to inject the collection directly into the method, and remove the autowired `Collection<String> strings` field from your `@Configuration` class.

```java
@Bean
DemoClass demoBean(Collection<String> strings) {
	return new DemoClass(strings);
}
```

Please let me know if that works for you.

**Comment by aposcia** [comment]
Thanks @sbrannen for the prompt answer.

We tried this possibility and I confirm that it is technically working for us. 

However, in our real life application, demoBean is used by many other beans in different configuration files. We want to explicitely reference baseTestConfig.demoBean() when injecting demoBean into other beans, and not call baseTestConfig.demoBean(strings) (which means that we would need to autowire the collection in each bean definition using demoBean).

**Comment by sbrannen** [comment]
@aposcia, thanks again for the feedback.

In the interim I have concluded that the root cause is that `org.springframework.beans.factory.support.DefaultListableBeanFactory.isSelfReference(String, String)` considers the string beans `"A"` and `"B"` to be _self references_ since they "point back to factory methods on the original bean".

I'll therefore discuss this further with @jhoeller in order to determine how we want to proceed.

**Comment by sbrannen** [comment]
In light of the above conclusion, I can now offer you an additional workaround.

If you ensure that none of the beans that should end up in the collection are declared in the same `@Configuration` class that is consuming those beans, it will also work.

For example, the following constellation will cause the test to pass.

```java
	@Configuration
	static class BaseTestConfig {

		@Autowired
		private Collection<String> strings;

		@Bean
		DemoBean demoBean() {
			return new DemoBean(this.strings);
		}
	}

	@Configuration
	static class Extension1TestConfig {

		@Bean
		String stringA() {
			return "A";
		}

		@Bean
		String stringB() {
			return "B";
		}
	}

	@Configuration
	static class Extension2TestConfig {

		@Bean
		String stringC() {
			return "C";
		}
	}
```

**Comment by aposcia** [comment]
Yes, we also experienced that. However, this is not what we would ultimately like to achieve (declare String beans in both the context where the collection is autowired and other contexts).

**Comment by sbrannen** [comment]
### Related Issues

- #13096
- #16794
- #19532

**Comment by sbrannen** [comment]
This is potentially a regression introduced in 4.3 in commit 4a0fa69ce469cae2e8c8a1a45f0b43f74a74481d.

**Comment by sbrannen** [comment]
If we switch from a `Collection` to a `List`, the test case I supplied passes against Spring Framework branch `3.2.x` but starts failing with branch `4.0.x`.

After further investigation, it turns out that this was actually a regression introduced in Spring Framework 4.1 RC2 and backported to 4.0.7 (see https://github.com/spring-projects/spring-framework/issues/16634#issuecomment-453415199 and commit https://github.com/spring-projects/spring-framework/commit/496492b2d8edb1d700c8c26ba0a4194f1880cb32#diff-94a3159735d9f8189b4b02707d4d4d73).

**Comment by jhoeller** [comment]
This is by design, even if several factors contribute to this in somewhat unexpected ways...

We generally consider *other* components as potential injection matches, only falling back to self references as a last resort in a separate pass. This is primarily designed for non-optional individual component references (before we fail, we'll rather inject a self reference, assuming that's the user's intent) but semantically also applies to multiple references such as in the collection case. Also, instance-based factory methods on the same instance count as self references as well, so injecting the outcome of such a factory method is the same case as injecting the configuration class instance itself.

So in your scenario, matching beans from another configuration class are always preferred. Only if no such beans are resolvable, we'll fall back to locally declared beans on the same configuration instance (in a separate self-reference pass). I totally see that this is unexpected in your particular scenario but it is at least a well-defined combination of effects.

Now, the main culprit in your scenario is the mix of injection point and factory methods on the same instance, involving a form of circular reference in terms of the instance lifecycle. Separating such injection points from the declaration points with an independent lifecycle - as suggested above - is highly recommended. If you'd nevertheless like to colocate them onto the same class, you may decouple their lifecycle by declaring the factory methods as `static`. This simply explicitly declares that your factory methods do not need the configuration instance state and therefore do not have access to the injected collection with the circular lifecycle problem.

Declaring the injection point as an argument on the factory method where you actually need it, as Sam suggested, is a fine solution as well, leading to lazy resolution for the construction of the affected bean - without any impact on the configuration instance lifecycle. Alternatively, if you'd like to avoid those extra arguments and nevertheless bypass the self reference algorithm, consider injecting a `ListableBeanFactory` into the configuration instance and programmatically call `getBeansOfType` on it within your factory method implementations... which always delivers the full result of currently available instances, including instances with problematic lifecycle relationships.

Hope that helps for a start. I've turned this into a documentation issue along those lines.

**Comment by aposcia** [comment]
Thanks for the detailled explanation and rapid support. For the time being, we will have in our use case to manually add to the set of autowired beans from external context, the bean defined locally.
