### ISSUE TITLE
Calling MethodParameter.isOptional() for Kotlin Continuation parameter fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#23991]
**Affects:** 5.2.1.RELEASE

Calling `MethodParameter.isOptional()` for a `kotlin.coroutines.Continuation` parameter of a `suspend fun` fails when introspecting a Coroutines method.

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.springframework.core.MethodParameter$KotlinDelegate.isOptional(MethodParameter.java:899)
	at org.springframework.core.MethodParameter.isOptional(MethodParameter.java:408)
```

The backing collection of `KParameter`s does not contain the parameter and therefore optionality checks fail.

**Comment by sdeleuze** [comment]
Could you share a little bit more about the context where this code path is reached? I am asking that because in current Coroutines support this kind of code path is not reached because we use upfront Kotlin reflection to identify the parameters that the user see, not the parameters at bytecode level that does not really make sense from a programming model perspective.

**Comment by mp911de** [comment]
Sure, we're introspecting in Spring Data `MethodParameter`s to determine whether they are nullable or not (optional vs. required). 

Here's some context of how it is used:

```
interface CoCrudRepository<T, ID> {
	suspend fun save(entity: T): T
}

Method method = CoCrudRepository.class.getDeclaredMethod(…);

for (int i = 0; i < method.getParameterCount(); i++) {

	MethodParameter parameter = new MethodParameter(method, i);
	parameter.isOptional();
}
```
