### ISSUE TITLE
Question about AnnotatedBeanDefinitionReader#doRegisterBean()

### ISSUE THREAD

**Issue by gnehcgnaw** [spring-projects/spring-framework#24021]
I found the following code will never execute, which is left for the subsequent expansion of Spring?

```java
if (qualifiers != null) {
	for (Class<? extends Annotation> qualifier : qualifiers) {
		if (Primary.class == qualifier) {
			abd.setPrimary(true);
		}
		else if (Lazy.class == qualifier) {
			abd.setLazyInit(true);
		}
		else {
		    abd.addQualifier(new AutowireCandidateQualifier(qualifier));
		}
	}
}
```

I am a beginner. Can you give me an explanation? 

Thank you.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

In any case, that method is invoked with a `null` value for `qualifiers` from other methods such as `org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(Class<?>, String)`.
