### ISSUE TITLE
SqlRowSet accessor methods should be marked @Nullable

### ISSUE THREAD

**Issue by turbanoff** [spring-projects/spring-framework#24042]
We use `org.springframework.jdbc.support.rowset.SqlRowSet` in our project to extract data from PostgreSQL.
Recently I found out that IntelliJ IDEA shows warning where it shouldn't be.
![image](https://user-images.githubusercontent.com/741251/69243130-6f257a00-0bb3-11ea-9def-cff779350091.png)
As I understand it's because IDEA thinks that `SqlRowSet.getString` always return non-`null` value. But it's not true. It's because of `@NonNullApi` annotation in https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/support/rowset/package-info.java

Need to mark all `SqlRowSet`s methods which can return `null` as `@Nullable` to avoid static analyzer false-positive warnings.

**Comment by sbrannen** [comment]
Good catch.

@turbanoff, would you like to submit a PR to address this?

**Comment by jhoeller** [comment]
Actually, let me take this opportunity to generally revisit our use of the JDBC API which unfortunately comes with "unclean" nullability, so the static analyzers don't perform strict validation against it. Otherwise we would have discovered the mismatch in `ResultSetWrappingSqlRowSet` right away.

So from that perspective, no need for a PR... I can take this from here and backport it to 5.1.x and 5.0.x as well.
