### ISSUE TITLE
URL suffix pattern issues

### ISSUE THREAD

**Issue by joshfix** [spring-projects/spring-framework#24041]
**Affects:**
2.2.1
---
I have some tests that test PUTting a resource to an endpoint. We support using path extensions to determine the content type of the request. The tests that do not include the file suffix in the path pass fine; the test that does include the suffix fails with a 406. The suffix is registered in ContentNegotationConfigurer and I've tried every combination of spring.mvc.pathmatch.use-suffix-pattern, spring.mvc.pathmatch.use-registered-suffix-pattern, spring.mvc.contentnegotiation.favor-path-extension, and spring.mvc.contentnegotiation.favor-parameter to no avail.

The request mapping in question accepts all values and produces html, xml, and json.

Debugging into the DispatcherServlet, I noticed in RequestMappingInfo.getMatchingCondition, the consumes condition properly matches, but the produces condition returns null. Stepping in further, I see the ContentNegotiationManager has 4 strategies, one of them being ServletPathExtensionContentNegotationStrategy. This class has a method resolveMediaTypeKey, which basically tries to look up the extension from registered media types. Because my file extension and media type are registered, it matches and returns the media type for that extension (which is not html, xml or json) and in turn, the ContentNegotationManager returns that value to the ProducesRequestCondition. At this point, the returned media type is compared to the declared produces values. Since the value being returned does not match any of the declared produces values from the controller, the condition fails.

This seems problematic to me. It seems like the behavior implies that if you PUT/POST/whatever a resource to a controller and it uses the file suffix to determine the content type of the request, it also attempts to force it as the return type when attempting to determine the handler mapping, which is not the case.

This was not an issue in Spring Boot 2.1.x. Curious if this is a legitimate issue or if there is something I'm missing.

**Comment by joshfix** [comment]
I created a small application that demonstrates the issue:

https://github.com/joshfix/suffix-demo

**Comment by bclozel** [comment]
That's strange - I've tested your repro project with versions as far back as Spring Boot 2.0.0 and the test is still failing. We've made the content-negotiation configuration change in spring-projects/spring-boot/issues/11105. Are you sure this behavior worked in Spring Boot 2.1.x? Maybe there's something else at play that I'm missing here?
I've also reproduced the same thing with Spring Boot 1.5.20.RELEASE, which makes this think this might have been the behavior all along.

Now about what you're describing - the suffix pattern matching was [initially implemented for browsers not sending the appropriate `Accept` request header](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#mvc-ann-requestmapping-suffix-pattern-match). In that case, since the header should not be considered, this content negotiation strategy is ordered before the one considering the HTTP headers.

`ContentNegotiationStrategies` [are designed for understanding what are the requested media types by the HTTP client](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#mvc-config-content-negotiation). The media type of the request body is set by the `Content-Type` request header only.

In your test, it seems we're failing with an HTTP 406 because the controller handler declares several media types as produced and they're not compatible with the `application/vnd.ogc.sld+xml` media type, which is the type requested by the client.

Could you update your sample to better reflect the problem you're seeing?

**Comment by joshfix** [comment]
So this may be a little difficult to follow, but my sample application is a direct representation of the code that has been working for some time.  There is a large and popular open source geospatial product called GeoServer.  The test that is failing can be seen here:

https://github.com/geoserver/geoserver/blob/master/src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java#L646-L664

and here is the actual controller:

https://github.com/geoserver/geoserver/blob/2.16.0/src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java#L454-L463

I'm not running the test directly from GeoServer.  My company has open source a Spring Boot version of GeoServer called "Stratus" that does quite a few little tricks to make GeoServer stateless and scalable.  We have re-implemented all of GeoServer's legacy code that writes data to the filesystem with classes that instead write everything to redis.  We extend from GeoServer's tests to mix in whatever redis-y stuff is necessary:

https://github.com/planetlabs/stratus/blob/master/src/stratus-application-tests/src/test/java/org/geoserver/rest/catalog/RedisStyleTest.java#L73

The test has always passed in the past and has only started failing as I simultaneously upgraded our project to the latest version of GeoServer (2.16.0) as well as Spring Boot 2.2.1.  I just went back to verify  this test passes in several previous versions and it does.  So all of this being said (sorry for being long winded, but I wanted to be thorough), I'm reading the documentation you linked and see this:

>  The file extension is then used to interpret the requested content type to use for the response

GeoServer originally used Restlet and only recently moved most of its REST endpoints to Spring MVC.  I'm thinking this was legacy behavior and they have hacked together changes to make it work with Spring MVC.  This endpoint is literally to "upload" a style file with the extension .sld, so their interpretation is that the extension in the path defines the content type of the request body, but the response is going to be XML or JSON stating if the transaction was successful.

Because all of this worked in previous versions, I thought it was a bug that it was using the registered media type to try to match the "produces" media type of a controller endpoint instead of only the "accepts", but this seems to be the correct and expected behavior, and it's GeoServer that is trying to do some funky stuff :)  

I believe this issue can be closed.  Thank you for taking the time to test my sample application and respond.

**Comment by rstoyanchev** [comment]
Indeed in the sample test, there is a produces condition that does not include "application/vnd.ogc.sld+xml" and that would not have ever matched in any Boot version. By contrast the referenced test does not have a produces condition so it can match to requests for any media type. If I remove the produces in the sample, the test also passes because the controller is allowed to return any format.
