### ISSUE TITLE
How to register/activate MappingJackson2HttpMessageConverter using Bean Definition DSL?

### ISSUE THREAD

**Issue by alxbbnk** [spring-projects/spring-framework#24053]
Hi!

I am using spring-webmvc + jackson databind + kotlin

I need to configure/activate **MappingJackson2HttpMessageConverter** for the media type "application/*+json"  in **GenericWebApplicationContext**  using  **Bean Definition DSL**.  

Unfortunately, I did't find any documentation for this.

Currently, I have found the following solution:

```
bean {
    RouterFunctionMapping().apply {
        setMessageConverters(listOf(
            MappingJackson2HttpMessageConverter(ref()),
            StringHttpMessageConverter()
        ))
        order = 1
   }
}
```

Is this correct or not?

Thanks for attention :)

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by rstoyanchev** [comment]
If you're using `@EnableWebMvc` then follow the [docs for message converters](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config-message-converters). If not then it should be a matter of just setting the the messageConverters proeprty of `RouterFunctionMapping`.
