### ISSUE TITLE
UriTemplate unconditionally percent-encodes literal part

### ISSUE THREAD

**Issue by bodewig** [spring-projects/spring-framework#24094]
**Affects:** 5.2.1 and earlier

When using `UriTemplate` with a properly percent-encoded literal part, the percent sign gets encoded a second time. For example

```java
new UriTemplate("https://example.org/foo%20and%20bar/{baz}").expand("xyzzy")
```

yields `https://example.org/foo%2520and%2520bar/xyzzy` rather than the expected `https://example.org/foo%20and%20bar/xyzzy`.

`UriTemplate`'s constructor uses `UriComponentsBuilder.build()` without any arguments. One option could be to provide a second constructor with a boolean `encoded` argument mirroring the one-arg version of `UriComponentsBuilder.build()`. If this sounds like a useful addition I can create a small PR.

**Comment by rstoyanchev** [comment]
`UriTemplate` is a thin wrapper around `UriComponentsBuilder` that exists for historic reasons, so why not bypass it altogether? That said your requirement can't be expressed with boolean flag because then `"{"` and `"}"` are invalid characters and `UriComponents` will flag them.

`UriBuilderFactory` provides another thin layer over `UriComponentsBuilder` with multiple [options for encoding](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/DefaultUriBuilderFactory.EncodingMode.html). It could be used like this for this use case:

```java
DefaultUriBuilderFactory factory = new DefaultUriBuilderFactory();
factory.setEncodingMode(EncodingMode.VALUES_ONLY);

URI url = factory.uriString("https://example.org/foo%20and%20bar/{baz}").build("xyzzy");
```

**Comment by rstoyanchev** [comment]
Closing but feel free to comment.

**Comment by bodewig** [comment]
Many thanks @rstoyanchev I agree this is the better approach.

Actually I've been using `UriTemplate` transitively via Spring HATEOAS - and @odrotbohm has already taken your advice and fixed things over there. I really appreciate both of you taking time for this.
