### ISSUE TITLE
How to aop method 'handleBinaryMessage' ?

### ISSUE THREAD

**Issue by lujiango** [spring-projects/spring-framework#24091]
i have a websocket application. How to aop method 'handleBinaryMessage' ?
```java
@Service
public class AsrHandler extends BinaryWebSocketHandler {
    @Override
    public void afterConnectionEstablished(WebSocketSession session)
        throws Exception {
    }
    @Override
    protected void **handleBinaryMessage**(WebSocketSession session, BinaryMessage message)
        throws Exception {
    }
    @Override
    public void afterConnectionClosed(WebSocketSession session, CloseStatus status)
        throws Exception {
    }
}

@Configuration
@EnableWebSocket
public class WebsocketEndPoint implements WebSocketConfigurer {
    @Autowired
    private AsrHandler asrProxyHandler;

    @Override
    public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
        registry.addHandler(asrProxyHandler, API_V1)
            .setAllowedOrigins("*")
            .addInterceptors(new HttpSessionHandshakeInterceptor());
    }
}
```

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
