### ISSUE TITLE
why spring use My custom annotations's value for the beanName

### ISSUE THREAD

**Issue by authorZhao** [spring-projects/spring-framework#24102]
```java
@Service
@TopicName(value="topic22")
public class TopicService implements TopicComsumerMsg {

    @Override
    public void omTopic(MqMsgDto mqMsgDto) {
        System.out.println("接收到了消息，我是topic22");
    }
}
```
```java

@Service
@TopicName(value="topic22")
public class TopicService2 implements TopicComsumerMsg {

    @Override
    public void omTopic(MqMsgDto mqMsgDto) {
        System.out.println("接收到了消息TopicService2，我是topic22");
    }
}
```

why spring use My custom annotations's value for the beanName,if I use
 name=“topic22” is right

**Comment by authorZhao** [comment]
my github project URL： https://github.com/authorZhao/mq-parent
is my demo for activeMq

**Comment by sbrannen** [comment]
> why spring use My custom annotations's value for the beanName,if I use name=“topic22” is right?

That's because your custom [`@TopicName`](https://github.com/authorZhao/mq-parent/blob/master/mq-interface/src/main/java/com/git/anno/TopicName.java) annotation is meta-annotated with `@Component` and declares an annotation attribute named `value` of type `String`. Such a `value` attribute will be used as the bean name (see [`AnnotationBeanNameGenerator`](https://docs.spring.io/spring/docs/5.2.1.RELEASE/javadoc-api/org/springframework/context/annotation/AnnotationBeanNameGenerator.html) for details).

If you do not want that to happen, you might consider removing the `@Component` declaration from `@TopicName` or changing the name of the `value` attribute in `@TopicName`.
