### ISSUE TITLE
Change value of Order.LOWEST_PRECEDENCE or make it configurable

### ISSUE THREAD

**Issue by zhengchb** [spring-projects/spring-framework#24101]
Whether you can change the Order of int LOWEST_PRECEDENCE = Integer. MAX_VALUE; Can provide overwriting LOWEST_PRECEDENCE after the sorting function

**Comment by sbrannen** [comment]
@zhengchb, I reworded the title of this issue.

Does that reflect your intention?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by zhengchb** [comment]
yes

**Comment by bclozel** [comment]
Many applications, Spring projects and libraries are relying on this value being a constant and have defined values of their own. Changing this is likely to break our support in many areas.

I think this issue is lacking context; we'd need to have a concrete use case and the problem we're trying to solve here. I'm closing this issue now. Feel free to reopen with a comment stating: the complete use case, what's been tried so far and why it didn't work, how you'd tackle the issues I've listed above.

Thanks!

**Comment by snicoll** [comment]
Can be related to #24844
