### ISSUE TITLE
Core Section of reference guide is wrongly formatted

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-framework#24138]
**Affects:** 5.2.2.RELEASE (haven't checked the new 5.1 release!)

The documentation appears to be garbled. The headers haven't been rendered properly. Text contains things like ==, === and ==== which should lead to headers and a proper index. The index however stops at 1.9.4, whereas the documentation continues. 

Appears that it was already fixed with #24132.

**Comment by rstoyanchev** [comment]
Yes this was fixed indeed. Thanks for the report.

**Comment by jnizet** [comment]
Is it really fixed? There are still formatting issues here for example: https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-java-bean-annotation. But maybe the fix hasn't been applied to the online documentation yet?

**Comment by sbrannen** [comment]
No, it does not appear to be fixed.

I'm reopening this since the latest build snapshots display improper headings.

https://docs.spring.io/spring/docs/5.2.2.BUILD-SNAPSHOT/spring-framework-reference/core.html#beans-java-bean-annotation

**Comment by sbrannen** [comment]
@jnizet It is fixed in the 5.2.3 snapshot: https://docs.spring.io/spring/docs/5.2.3.BUILD-SNAPSHOT/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers

**Comment by rstoyanchev** [comment]
Fixed but not released yet.

**Comment by izeye** [comment]
This seems to be able to be closed.

**Comment by kriegaex** [comment]
How can this be closed as fixed? The current version is 5.2.2 and the official documentation on the website is broken. Please publish a new documentation online, otherwise the manual for 5.2.2 will be broken forever.

**Comment by rstoyanchev** [comment]
@kriegaex, the same is true for all bugs fixed in 5.2.3. 

The reference documentation link always points to the "current" release, i.e. https://docs.spring.io/spring/docs/current/spring-framework-reference/, which at the moment still links to 5.2.2 but on Jan 14 will link to 5.2.3. At that point, I don't expect anyone to access 5.2.2 directly.

We could however consider having "current" link to the latest snapshot of the current branch. That would make documentation fixes available immediately.

**Comment by bclozel** [comment]
I've updated the `/current` and `/5.2.x` links in the meantime, so they point to the `5.2.3.BUILD-SNAPSHOT` docs for now. This is rather unusual, as we tend to avoid pointing to unreleased versions there, but this seems to annoy developers so we'll have that arrangement until our next release.

**Comment by kriegaex** [comment]
Thank you very much, that is a functioning workaround. But is it really a good idea to do it that way? 

* Actually until 5.2.1 (inclusive) everything was fine, only 5.2.2 is problematic. So you don't need to re-route all 5.2.x versions to the development snapshot.
* Often when I help people on StackOverflow concerning Spring AOP and AspectJ LTW, I point them to the documentation of their Spring specific version. So even in the future I might point them to 5.2.2, even when that version is not the most current one anymore. It would really be better to fix the documentation for that specific version instead of pointing to the latest development snapshot or to a future 5.2.3 documentation.

I was just thinking out loud. I do not want you to have too much extra effort, but this is my opinion.

**Comment by snicoll** [comment]
@kriegaex I don't think pointing people to an old maintenance release is necessary. I'd rather point them to the latest maintenance release in that line, so that they benefit from whatever we've fixed, i.e. typo, clarifications and formatting issues like this one.
