### ISSUE TITLE
Spring Cache does not support List key cache

### ISSUE THREAD

**Issue by shenjianeng** [spring-projects/spring-framework#24139]
I hava some ids to find users :

```java

List<User> users = ids.stream().map(id -> {
    return getUserById(id);
})
.collect(Collectors.toList());

@Cacheable(key = "#p0", unless = "#result == null")
public User getUserById(Long id) {
...
}

```

I can also use ：

```java

List<User> users = ids.stream().map(id -> {
    return getUserById(id);
})
.collect(Collectors.toList());

@Cacheable(key = "#ids.hash")
public Collection<User> getUsersByIds(Collection<Long> ids) {
...
}

```
but getUsersByIds(Collection<Long> ids) cache and getUserById(Long id) cache cannot be shared

why does spring cache not support ids cache？

I want them to share the cache

**Comment by shenjianeng** [comment]
```java
@Cacheable(key = "#ids.hash")
public Collection<User> getUsersByIds(Collection<Long> ids) {
...
}
```
RedisCache 
key: ids.hash
value: list<User>


invoke method：
```java
void updateUser(Long id)
```

I need clear RedisCache（key:ids.hash）

it is not graceful

**Comment by snicoll** [comment]
Thanks for the report. The cache abstraction has no notion of such state, if you return a `Collection`, that's effectively what you're asking to store in the cache. Nothing forces you to keep the same item type for a given cache either so that kind of assumptions is not a great candidate for such a high-level abstraction.

The discussion in #23221 is also relevant.

**Comment by ms100** [comment]
You can use [Cache As Multi](https://github.com/ms100/cache-as-multi)

**Comment by shenjianeng** [comment]
这是来自邮箱的自动回复邮件，我已收到邮件。-------------------------------------------------
