### ISSUE TITLE
ClassUtils  resolvePrimitiveClassName  will check name less than 8

### ISSUE THREAD

**Issue by gravin** [spring-projects/spring-framework#24192]
looks even like `Boolean.class.getName()` will have a length than 8,  it will miss the cache.

why not use the max length of keys of `primitiveTypeNameMap`?
	
```java
public static Class<?> resolvePrimitiveClassName(String name) {
		Class<?> result = null;
		// Most class names will be quite long, considering that they
		// SHOULD sit in a package, so a length check is worthwhile.
		if (name != null && name.length() <= 8) {
			// Could be a primitive - likely.
			result = primitiveTypeNameMap.get(name);
		}
		return result;
	}
```

**Comment by sbrannen** [comment]
Since this method accepts primitive type names as input, the longest possible supported input value `"boolean"` has a length equal to 7. Thus, `boolean` does not result in a cache miss.

You can verify this by executing the following which prints `boolean`.

```java
System.out.println(ClassUtils.resolvePrimitiveClassName("boolean"));
```

I am therefore closing this issue, and I will update the check to be `<= 7`.
