### ISSUE TITLE
SpringExtension stops other Extensions after it from working when Autowiring test method

### ISSUE THREAD

**Issue by nishantvas** [spring-projects/spring-framework#24199]
**Affects:** 2.2.1.RELEASE
---

When using `SpringExtension` with JUnit 5 for injecting beans to test methods via `ParameterResolver`, if the test method is annotated with `@Autowired` it Custom Annotations are not invoked by JUnit.

Not sure if this should be a Spring or JUnit issue.

Example 1: 

```java
/**
 * Order of ExtendsWith right to left
 **/
@SpringBootTest
@ExtendWith({Reset.class, SpringExtension.class})
class SpringTestBase {

           @Autowired
           void testWithAutoWiredAnnotation(AutoWirableClass var) {
           // ...
           }
}
```

Example 2:

```java
@SpringBootTest
@ExtendWith({Reset.class, SpringExtension.class})
class SpringTestBase {

           void testWithAutowiredVariable(@Autowired AutoWirableClass var) {
           // ...
           }
}
```

Custom Extension

```java
public class Reset implements BeforeEachCallback, AfterEachCallback {

  @Override
  public void beforeEach(ExtensionContext context) {
    reload();
}

  @Override
  public void afterEach(ExtensionContext context) {
    reload();
  }
}
```

With Example 1, `CustomExtension` fails to be called; with Example 2, it works perfectly.

Oddly, in both cases, `SpringExtension` does work and Autowires the beans properly, however, when the annotation is put on the test method instead of each variable, it doesn't work.

As I understand from the documentation, `ParameterResolver` only supports autowiring of constructors and then Parameters marked with `@Autowired` and doesn't check `@Autowired` to be present on the method, however Spring in its own process autowires the test method variables but somewhere interferes with JUnit's test context and stops further Extensions from being called.

**Comment by sbrannen** [comment]
Actually, neither of the supplied examples should work since the test method is not annotated with `org.junit.jupiter.api.Test`.

In any case, `@Autowired` should never be used _on_ a test method, because Spring will then consider it a "config method", in which case Spring will invoke the method directly to perform dependency injection (e.g., as if it were a _setter_ method). Then the testing framework (JUnit Jupiter in this case) would invoke the same method again as a _test_ method. So you certainly do no want that to happen.

Regarding your claim that Spring "interferes with JUnit's test context and stops further Extensions from being called", your examples do not demonstrate that. So, if you have witnessed that, please provide an example that demonstrates that.

In the interim I am going to close this issue, but please do report back here if you can confirm your claim regarding extension interference.

As a side note, `@SpringBootTest` is meta-annotated with `@ExtendWith(SpringExtension.class)` in Spring Boot 2.2. Thus there is no need to register the `SpringExtension` again, since the second attempt will be ignored.
