### ISSUE TITLE
Allow AcceptHeaderLocaleResolver to fail on unsupported locales

### ISSUE THREAD

**Issue by michael-o** [spring-projects/spring-framework#24225]
I have configured in 5.2.0.RELEASE:

```xml
	<beans:bean id="localeResolver" class="org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver">
		<beans:property name="defaultLocale" value="de" />
		<beans:property name="supportedLocales">
			<beans:list>
				<beans:value>cs</beans:value>
				<beans:value>de</beans:value>
				<beans:value>en</beans:value>
				<beans:value>es</beans:value>
				<beans:value>fr</beans:value>
				<beans:value>pt</beans:value>
				<beans:value>ru</beans:value>
			</beans:list>
		</beans:property>
	</beans:bean>
```

I would like the system to use the default locale if and only if the `Accept-Language` header has not been provided. In the case a user sends `Accept-Language: pl, da` I want the resolver to return 400 because neither Polish not Danish is supported.

**Comment by rstoyanchev** [comment]
`LocaleResolver` has no access to to the response and can't return a 400 by itself. The contract rules out returning `null` as well. Its purpose is literally to "resolve" the locale for the request, if possible matching to a supported one, or falling back on a fixed default, or otherwise resolving to the one from the request. 

It would have to be some other component that checks whether the resolved locale is supported or not. A `HandlerInterceptor` perhaps:

```java
public class LocaleValidatingInterceptor implements HandlerInterceptor {

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        LocaleResolver r = RequestContextUtils.getLocaleResolver(request);
        if (r instanceof AcceptHeaderLocaleResolver) {
            List<Locale> supported = ((AcceptHeaderLocaleResolver) r).getSupportedLocales();
            if (!supported.contains(LocaleContextHolder.getLocale())) {
                response.setStatus(400);
                return false;
            }
        }
        return true;
    }

}
```

Even if we made it configurable to force an exception, the resolver is used way before handler mappings and the usual handler exception handling would not apply.

**Comment by michael-o** [comment]
So you see no better way, but handle this either in the controller or in an controller advice? I don't want to replicate the code of `AcceptHeaderLocaleResolver`.

**Comment by rstoyanchev** [comment]
No I don't see any option whatsoever through the `LocaleResolver`. The suggested interceptor snippet above does not replicate the `LocaleResolver` logic.

**Comment by izeye** [comment]
Based on the "status: declined" label, this appears to be meant to be closed.

**Comment by snicoll** [comment]
Good catch!
