### ISSUE TITLE
External Filter

### ISSUE THREAD

**Issue by KishoreVenkatachalam123** [spring-projects/spring-framework#24255]
I need to add my custom Filter as a library for existing web applications without code changes in that application, kind of plug and play.

Extended myclass with OncePerRequestFilter and Overrided dofilterInternal with my changes, but failed to add this in existing application.

it works if I add below code @Bean
public RequestFilter getdeta(){ return new RequestFilter(); }

Is that possible to achieve it without adding the above code?

Thanks in Advance

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
