### ISSUE TITLE
Is this a wrong practice

### ISSUE THREAD

**Issue by chenshun00** [spring-projects/spring-framework#24271]
```java
@Controller
public class View implements InitializingBean {

    @GetMapping("log")
    public String log() {
        return "log";
    }

    @Override
    public void afterPropertiesSet() throws Exception {
        System.out.println("init");
    }
}
```

ths in advance :)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
