### ISSUE TITLE
org.springframework.web.server.WebFilter Not working , while we have spring-boot-starter-web on classpath

### ISSUE THREAD

**Issue by santhoshgs** [spring-projects/spring-framework#24313]
**Affects:** \<5.2.2>
Hi,

i have implemented custom webfilter for org.springframework.web.server.WebFilter , and i dont see incoming request being filtered when im having below 2 dependencies in my Project.
1) spring-boot-starter-web
2) spring-boot-starter-webflux

if i remove "spring-boot-starter-web" , every thing works just fine , but my project need has to have both the dependency for now , and i dont see any solution being given any where.

---

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by santhoshgs** [comment]
i dont see a solution from stackoverflow as well , should i assume we can never use webfilter while having below dependency in class path.
spring-boot-starter-web
spring-boot-starter-webflux

Below is the Link to stackoverflow:
https://stackoverflow.com/questions/59668246/reactive-webfilter-is-not-working-when-we-have-spring-boot-starter-web-dependenc

**Comment by snicoll** [comment]
@santhoshgs please review your stackoverflow question. It has been closed as a duplicate and [the accepted answer](https://stackoverflow.com/a/51378560/613628) provides all the details you need.
