### ISSUE TITLE
my project run fail in jar but success in local intellliJ,show exception has been injected into other beans...

### ISSUE THREAD

**Issue by kse-music** [spring-projects/spring-framework#24325]
**Affects:** spring-framwork 5.1.9.RELEASE

---

First,my project exist circle reference.But run in intellij  IDEA no problem.in jar run failed. I am very worried about it.

The exception is as follows:

> org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'attributeDateTimeDaoImpl': Bean with name 'attributeDateTimeDaoImpl' **has been injected into other beans** [attributeDateTimeServiceImpl] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesOfType' with the 'allowEagerInit' flag turned off, for example.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
