### ISSUE TITLE
In IDEA， could not find org.springframework.cache.annotation.EnableCachingIntegrationTests.DummyFooRepository

### ISSUE THREAD

**Issue by sluk3r** [spring-projects/spring-framework#24394]
Hi, I am new to Spring Framework compilation, and after I import Spring source code into IDEA, there are some errors. 

for example, 

![image](https://user-images.githubusercontent.com/6405801/72655805-08191b80-39d2-11ea-82b2-461297b31c3c.png)

as the above photo shows, IDEA could not find class org.springframework.cache.annotation.EnableCachingIntegrationTests.DummyFooRepository， and as you can see, the class is here. 

And I guess， there is something wrong in my IDEA config, but could not locate the wrong config. 

So, could you help me with that.

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Please, be sure to check [Build from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) wiki page and follow the link to import into IntelliJ. There are some peculiarities and limitations with IntelliJ so be sure to follow those steps closely.
