### ISSUE TITLE
top-level domain

### ISSUE THREAD

**Issue by Iamdreamlover** [spring-projects/spring-framework#24407]
Hi!
I use spring boot 2.2.2.RELEASE and spring webflux.
When I send POST Http request to my app by host name http://mobile-backend:8080/api/cat name, I saw what app got GET request to /app path
When I send request by ip address or without "-" in name it works fine.

How can I fix it? Thank you

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case, it seems that a proxy server (or the application itself) is rewriting requests.
