### ISSUE TITLE
How can we use Spring Cloud Sleuth with spring MVC project?

### ISSUE THREAD

**Issue by jitenvij1992** [spring-projects/spring-framework#24423]
I am trying to use spring cloud sleuth with spring web mvc project. We are sending the request from spring web mvc to another spring boot project. I need to have the traceID and spanId to display in the UI. How can we achieve this?

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by jitenvij1992** [comment]
Added in stack over flow: https://stackoverflow.com/questions/59891583/how-can-we-use-spring-cloud-sleuth-with-spring-mvc-project

**Comment by jitenvij1992** [comment]
Added in stackoverflow: https://stackoverflow.com/questions/59891583/how-can-we-use-spring-cloud-sleuth-with-spring-mvc-project
