### ISSUE TITLE
spring-aspects has a non-optional compile dependency on spring-orm

### ISSUE THREAD

**Issue by asibross** [spring-projects/spring-framework#24491]
Starting from version 5.2.0 `spring-orm` is no longer an optional dependency of spring-aspects.
https://search.maven.org/artifact/org.springframework/spring-aspects/5.2.0.RELEASE/jar

This causes the below conditional to match which will then try to auto configure a data source.
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration.java#L52

Was this intentional?

**Affects:** 5.2.x

---

**Comment by snicoll** [comment]
@asibross thanks for the report. This looks like a regression introduced by the Gradle build refactoring.

**Comment by bclozel** [comment]
Hey @larsgrefer, previously "spring-aspects" had an optional dependency on "spring-orm" (see [the POM in 5.1.13.RELEASE](https://search.maven.org/artifact/org.springframework/spring-aspects/5.1.13.RELEASE/jar) and now it seems we're publishing this module with a hard dependency on "spring-orm".

Do you know if we can change the "aspect" configuration so that it does not leak as a transitive dependency for that module? I know how to remove the node from our published POM, but that won't solve the issue once we're publishing Gradle metadata.

Thanks!

**Comment by larsgrefer** [comment]
@bclozel I'll have a look how I can improve this.

**Comment by larsgrefer** [comment]
@bclozel What exactly is the point of having `spring-orm` on the aspectpath of `spring-aspects` at all?

Neither `spring-orm` nor any of its transitive dependencies seem to contain aspects, which could be woven into `spring-aspects`.

I've just compiled `spring-aspects` locally once with `spring-orm` and once without `spring-orm` on the aspectpath. The output was the same.

**Comment by bclozel** [comment]
I've indeed checked the output of the build with and without that change and nothing changes.
I guess it might have been a detail that was overlooked and just ported over when we reorganized our build.

Thanks @larsgrefer for looking into this and sorry I've bothered you for a mistake on our part!
