### ISSUE TITLE
NullPointerException when no protocol is explicited on MockHttpServletRequestBuilder class

### ISSUE THREAD

**Issue by dFarras** [spring-projects/spring-framework#24556]
**Affects:**  spring-boot-starter-test 2.1.6.RELEASE

**Use Case:** When performing an spring integration test over a get controller we add an url as a String to MockHttpServletRequestBuilder to perform such action.

**Issue:** When we add that url String without the protocol (for instance: "localhost:port...") the request returns a NullPointerException.

**Code failing:** 
```java
MockHttpServletResponse response = 
    mockMvc.perform(MockMvcRequestBuilders.get("localhost:port/some domain/etc...")).andReturn().getResponse();
```

**Code working:**
```java
MockHttpServletResponse response = 
    mockMvc.perform(MockMvcRequestBuilders.get("http://localhost:port/some domain/etc...")).andReturn().getResponse();
```
Just to clarify the only difference is that the second url contains the http protcol explicitly declared

**Expectation:** 
Since http is the default protocol in many other frameworks I expect it to be inferred as url protocl if no other is defined explicitly.

**Cause:** 
Inside that `MockMvcRequestBuilders.get("uri")` method there is a call to a private constructor who converts that String into an actual URI
```java
MockHttpServletRequestBuilder(HttpMethod httpMethod, String url, Object... vars) {
	this(httpMethod.name(), UriComponentsBuilder.fromUriString(url).buildAndExpand(vars).encode().toUri());
}
```

But it does not work properly since this.utl.getRawPath() returns null which later causes updatePathRequestProperties to throw mentioned NullPointerException
![image](https://user-images.githubusercontent.com/28202081/74846333-9580c000-5330-11ea-8f97-694833356157.png)

Thanks in advance!

**Comment by rstoyanchev** [comment]
`MockMvcRequestBuilders` uses `UriComponentsBuilder.fromUriString`, which can't parse the given input correctly because "localhost:" looks like a scheme.

Switching to `UriComponentsBuilder.fromHttpUrl` provides a more helpful error:
```
java.lang.IllegalArgumentException: [localhost:8080/path] is not a valid HTTP URL
```

I don't we should go further and fill in the protocol since we don't know if that should be "http:" or "https:" and that could lead to surprises, and possibly even possible contradictions (e.g. "localhost:443").

**Comment by rstoyanchev** [comment]
Actually it looks like `fromUriString` is quite useful because it allows to provide a path only. We need to keep that so it comes down to, either provide a URI with a path only (i.e. no scheme, host, port), or otherwise a proper HTTP URL.

If you want the short syntax you could go with just path, skipping host and port. Any reason not to do that.
