### ISSUE TITLE
Response Body coming null in Code but coming proper using PostMan

### ISSUE THREAD

**Issue by BaljinderSingh007** [spring-projects/spring-framework#24592]
<org.springframework-version>4.3.20.RELEASE</org.springframework-version>

ResponseEntity<OtdsOauthToken> response = restTemplate.exchange(builder.toUriString(), HttpMethod.POST, entity, OtdsOauthToken.class);  // Getting response object body as null, header is coming and Status is 200
![response](https://user-images.githubusercontent.com/43573402/75266440-5a8ef880-5818-11ea-9b20-e64e5fdb4cbe.PNG)

**Comment by BaljinderSingh007** [comment]
![Untitled](https://user-images.githubusercontent.com/43573402/75424964-b916bc80-5967-11ea-8e8b-812107a64ae0.png)


I am getting no response body using restemplate.exchange

**Comment by 0x100** [comment]
Can you show the OtdsOauthToken class?

**Comment by 0x100** [comment]
I've answered you here: https://stackoverflow.com/questions/60429106/not-getting-response-body-from-resttemplate-exchange-while-getting-from-postman

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
