### ISSUE TITLE
Add Encoder and Decoder for ByteBuf

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-framework#24615]
Now it's not possible to output ByteBuf to browser with data from RSocket, gRPC or other Netty based RPC frameworks with Spring WebFlux, and you should convert ByteBuf to ByteBuffer.  Any consideration to support ByteBuf directly.   Maybe performance enhancement without convert, and API friendly. 

```
   @GetMapping(value = "/bytebuf", produces = {MediaType.APPLICATION_JSON_VALUE})
    public Mono<ByteBuf> byteBuf() {
          //data from RSocket payload
    }
```

**Comment by s-m-sufyian** [comment]
I am willing to work on this issue

**Comment by poutsma** [comment]
Not sure if a codecs is the proper place for this, as I am not sure what they would do in scenario's where `ByteBuf` is not available (i.e. WebFlux on Servlet). Also, there are workarounds:

For extracting a `ByteBuf`, you can easily cast to a NettyDataBuffer, and call [`getNativeBuffer()`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/buffer/NettyDataBuffer.html#getNativeBuffer--). To create a `DataBuffer` from a `ByteBuf`, use [wrap](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/buffer/NettyDataBufferFactory.html#wrap-io.netty.buffer.ByteBuf-).

**Comment by rstoyanchev** [comment]
Typically in a Spring application you with `WebClient` or `RSocketRequester` what you'll have is `DataBuffer` instead but if what you have is `ByteBuf` then we should be able to adapt. I can imagine `ByteBufEncoder` that simply with `NettyDataBufferFactory`, or otherwise copy to `ByteBuffer` and wrap, and releases the `ByteBuf`. A matching `Decoder` would make sense too and would be a simple pass-through.

Scheduling tentatively for 5.3 M1 but with a PR, we could probably include it sooner.

**Comment by encircled** [comment]
Looks like s-m-sufyian is not working on it so I took it :)

**Comment by rstoyanchev** [comment]
Superseded by #24866.
