### ISSUE TITLE
Spring JDBC Slice doesn't work

### ISSUE THREAD

**Issue by LaCoCa** [spring-projects/spring-framework#24662]
Hi,
One question before send the issue.
I am using @EnableJdbcRepositories with last vesrion of the dependencies:
https://docs.spring.io/spring-data/jdbc/docs/current/reference/html/#jdbc.repositories

Is it possible to use Slice<?> or Page<?> in CrudRepository ?

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Having said that, if you encounter an issue with Spring Data JDBC, please open it in the [dedicated JIRA issue tracker](https://jira.spring.io/projects/DATAJDBC/issues/DATAJDBC-499?filter=allopenissues).

/CC @odrotbohm

**Comment by LaCoCa** [comment]
Ok Thanks,
Clos
