### ISSUE TITLE
WebClient returns empty object instead of an empty Mono in 5.2 when statusHandler returns Mono.empty()

### ISSUE THREAD

**Issue by jmayday** [spring-projects/spring-framework#24736]
During Spring Boot 2.2 upgrade (from 2.1.x) we've noticed regression in tests using webclient. 

**Scenario**: Call an enpoint returning 404 NOT_FOUND (with **non-empty** response body)

**Expected**: webclient returns empty Mono instance

**spring-webflux >= 5.2.0**
**Actual**: webclient call returns an non-empty response but the wrapped object has nothing more than nulls inside - unit test fails. 

**spring-webflux == 5.1.14**
**Actual**: webclient call returns an empty response - unit test works fine. 

Here is a sample that reproduces the problem: https://github.com/jmayday/emptymono
Please have a look at this unit test (it uses Wiremock) - _shouldReturnEmptyObjectFor404WithResponseBody_

Unit test result:
```
java.lang.AssertionError: 
Expecting an empty Optional but was containing value: <MyEntity(id=null, name=null, owner=null)>.
```
Pay attention, that if we'll modify response body in wiremock mapping and replace body
```
{"error_code":404,"message":"Page not found"}
```
with empty body, then test will work. 

Is this a spring-webflux 5.2.x regression or I'm misusing it?

**Comment by rstoyanchev** [comment]
I believe this is due to https://github.com/spring-projects/spring-framework/commit/a9b3d95a14c316387f2b77328d6864b8e0a36721. As explained in the commit message (and Javadoc) an empty Mono effectively suppresses the error, and the `bodyToMono` tries to map the error JSON to the normal response Object, which results in null values.

I think the Javadoc could use some improvement. That aside, @poutsma what is your thought on the best way to achieve the effect of "no result", i.e. complete empty?

**Comment by poutsma** [comment]
I think you'd have to use an `ExchangeFilterFunction` to accomplish this. The `onStatus` handlers are designed to map to an exception; not to an alternative (empty) result.

As said in the commit message, returning an empty result prior to a9b3d95 (eg 5.1.14) will actually leak memory (i.e. the body), so it never "worked" correctly in the first place.

**Comment by rstoyanchev** [comment]
@jmayday see the updated to the Javadoc in the referenced commit above. I've clarified the various cases and provides suggestions for your case.

**Comment by jmayday** [comment]
Thank you.
