### ISSUE TITLE
 What is the use of resolvableDependencies collection

### ISSUE THREAD

**Issue by lyvee** [spring-projects/spring-framework#24797]
org.springframework.context.support.AbstractApplicationContext#prepareBeanFactory
```
beanFactory.registerResolvableDependency(BeanFactory.class, beanFactory);
beanFactory.registerResolvableDependency(ResourceLoader.class, this);
beanFactory.registerResolvableDependency(ApplicationEventPublisher.class, this);
beanFactory.registerResolvableDependency(ApplicationContext.class, this);
```
![image](https://user-images.githubusercontent.com/25558493/77720586-51659700-7023-11ea-9942-47a84f6163b2.png)

Why not register to the singletonObjects

beanFactory.registerSingleton(“name”,object);

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

In any case, I recommend reading the [Javadoc for `registerResolvableDependency()`](https://docs.spring.io/spring/docs/5.2.5.RELEASE/javadoc-api/org/springframework/beans/factory/config/ConfigurableListableBeanFactory.html#registerResolvableDependency-java.lang.Class-java.lang.Object-).
