### ISSUE TITLE
Recompile spring-web with Maven

### ISSUE THREAD

**Issue by kadimulam** [spring-projects/spring-framework#24806]
Is there a way we can download spring-web  source and compile with Maven? If yes, could you please let me know the steps?

**Comment by snicoll** [comment]
Our build is based on Gradle so, no, there isn't a way to compile `spring-web` with Maven without crafting your own build. It shouldn't be that complicated although if you're trying to reproduce what we officially build, I can only recommend you to use the official build rather than creating your own.

If you have more questions, please follow-up on Stackoverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
