### ISSUE TITLE
entityManager.createQuery() taking lot of time to build query and bind the parameters. Performance affected

### ISSUE THREAD

**Issue by githubsree** [spring-projects/spring-framework#24809]
Can you please help on this issue raised in stackoverflow:
https://stackoverflow.com/questions/60886012/entitymanager-createquery-taking-lot-of-time-to-build-query-and-bind-the-param

The org.hibernate.Criteria, fetches results in milliseconds, where "CriterialBuilder" takes a lot of time in:

CriteriaCompiler.compile
CriteriaQueryImpl$1.buildCompiledQuery
CriteriaCompiler$1$1.bind

Please help here.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
