### ISSUE TITLE
spring-beans:compileGroovy FAILED。 Spring5.1.x

### ISSUE THREAD

**Issue by ListenerSun** [spring-projects/spring-framework#24817]
who can help me？ When I compile Spring5.1.x use idea,always this error. 

```
D:\sqt\demo\spring-framework>gradlew :spring-oxm:compileTestJava

> Task :spring-beans:compileGroovy FAILED
D:\sqt\demo\spring-framework\spring-beans\src\main\java\org\springframework\beans\support\PropertyComparator.java:138: ??: ??????: PropertyComparator<CAP#1>?????Comparator<? super CAP#1>
                        source.sort(new PropertyComparator<>(sortDefinition));
                                    ^
  ??, CAP#1??????:
    CAP#1???????Object
?: ?????????; ??? -Xdiags:verbose ???????????
1 ???
startup failed:
Compilation failed; see the compiler error output for details.

1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-beans:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
12 actionable tasks: 1 executed, 11 up-to-date
```

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

If you need some assistance with the build, we recommend you first make sure that you follow the instructions outlined in [Building from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source).

**Comment by jyqjyq** [comment]
did u reslove thie question?
i have the same question with that
