### ISSUE TITLE
UriComponentsBuilder.addPath() needs behavior documented in regards to slashes

### ISSUE THREAD

**Issue by ctytgat** [spring-projects/spring-framework#25055]
Version: 5.2.5-RELEASE

We're using spring hateoas (webflux version) and noticed that our links have a missing slash between the context path and the controller `RequestMapping.path`.

Adding slashes to the `RequestMapping.path` is a workaround, but shouldn't be needed.

The method below seems to be the culprit. 

If `psBuilder == null` and `fpBuilder != null`, no slash is added.

```java
public void addPath(String path) {
	if (StringUtils.hasText(path)) {
		PathSegmentComponentBuilder psBuilder = getLastBuilder(PathSegmentComponentBuilder.class);
		FullPathComponentBuilder fpBuilder = getLastBuilder(FullPathComponentBuilder.class);
		if (psBuilder != null) {
			path = (path.startsWith("/") ? path : "/" + path);
		}
		if (fpBuilder == null) {
			fpBuilder = new FullPathComponentBuilder();
			this.builders.add(fpBuilder);
		}
		fpBuilder.append(path);
	}
}
```

**Comment by rstoyanchev** [comment]
This is intentional. The `path(String)` method operates on a full path as appending to the same string. See for example [this test](https://github.com/spring-projects/spring-framework/blob/a3c5625d4e1e2b5ca720b8e74797ee8bd30f54e4/spring-web/src/test/java/org/springframework/web/util/UriComponentsBuilderTests.java#L565-L572). Only when working with `pathSegment(String...)` do we fill in slashes if missing. 

At best we can improve the Javadoc on `path(String)`. This definitely needs to be specified so I'll schedule this for a change..
