### ISSUE TITLE
Custom HTTP Method on MockServerHttpRequest

### ISSUE THREAD

**Issue by GuyLewin** [spring-projects/spring-framework#25109]
In some cases we'd like to use `MockServerHttpRequest` with methods not in Spring's `HttpMethod` enum (for testing corner cases for example).
My scenario was wanting to use `MockServerHttpRequest` with the CONNECT method, which isn't in HttpMethod.
When `ServerHttpRequest` receives a request from Reactor Netty it can accept CONNECT as a string method even though it's not in the enum.
I believe we should also add a string-based method initialization to `MockServerHttpRequest`.

This was originally described in #24820 but I was asked to create a separate issue for this.
@rstoyanchev FYI

**Comment by sbrannen** [comment]
As pointed out by @eleftherias, the change associated with this issue is actually a breaking change for anyone that previously supplied `null` for the `HttpMethod`.

For example, the following used to be supported but now throws an `IllegalArgumentException`.

```java
 MockServerHttpRequest.method(null, "/").build();
```

In light of that, perhaps we should reopen this issue to again support `null` for the `HttpMethod`.

@rstoyanchev Thoughts?

----

See also: https://github.com/spring-projects/spring-security/issues/8592

**Comment by rstoyanchev** [comment]
My only concern is that Spring Security had no choice but to pass `null` since it was the only way to simulate a custom method. Aside from that there is no reason to pass `null`. My thought is to leave it the way it is but have a more helpful error message along the lines of "if you are passing `null` to simulate a custom method, please use ... instead". After all it's a test that's failing and it's easy to correct.

**Comment by sbrannen** [comment]
> My thought is to leave it the way it is but have a more helpful error message

Fair enough. Let's just hope there weren't many projects depending on the previous unintentional _support_ for `null`.

**Comment by midumitrescu** [comment]
Hello everybody, 

I played during the weekend with the idea of changing the HttpMethod to an interface and move the HttpMethod enum to HttpMethods. 

This introduces quite a few of necessary actions during an update to the newerst Spring version. 

You can check a comparison done under: https://github.com/midumitrescu/httpmethod-refactorings 

However, HTTP/1.1 and HTTP/2 both mention CONNECT as valid HTTP Method. 

Maybe one could consider simply adding the value to the enum? :)

**Comment by midumitrescu** [comment]
Now, about changing just *MockServerHttpRequest*.

I haven't considered changing MockServerHttpRequest to allow for 
```
MockServerHttpRequest.method("CUSTOM-HTTP-METHOD", "/")
```

The biggest issue I see is that 
```
MockServerHttpRequest extends AbstractServerHttpRequest
```
which brings from HttpRequest: 

```
	@Nullable
	default HttpMethod getMethod() {
		return HttpMethod.resolve(getMethodValue());
	}

	String getMethodValue();
```

It feels somehow weird to me that, for example, for  **CONNECT** or **CUSTOM-HTTP-METHOD**  
```
getMethodValue()
```
should return a valid String but 

```
getMethod()
```
should return **null**. 

One can write the code to work, but this feels anyways a bit weird.
