### ISSUE TITLE
Avoid need for default constructor in ContextAnnotationAutowireCandidateResolver subclasses

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#25131]
As reported [here](https://github.com/spring-projects/spring-boot/issues/16230), it seems that under certain circumstances, the `BeanFactory` expects `ContextAnnotationAutowireCandidateResolver`s to expose a default constructor which limits the ability to populate instances with configuration on construction.

**Comment by jhoeller** [comment]
This is coming from `DefaultListableBeanFactory.copyConfigurationFrom` for the special purpose of building internal copies of a given `BeanFactory` in certain scenarios. Replacing its `AutowireCandidateResolver` handling with a `Cloneable` arrangement instead of a hard `BeanUtils.instantiateClass` call seems to be a straightfoward and flexible enough solution here.
