### ISSUE TITLE
Cannot find the class under the target package

### ISSUE THREAD

**Issue by wukong-yu** [spring-projects/spring-framework#25237]
![Uploading image.png…](picture)
idea cannot show target package, so when i run test case, it turns some errors, cannot find org.springframework.aop.target.
how should i do

**Comment by wukong-yu** [comment]
waitting online

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
