### ISSUE TITLE
Build from source error

### ISSUE THREAD

**Issue by andresetevejob** [spring-projects/spring-framework#25245]
Hi everyone,
I have an error when,i want to build Spring framework from source.When i tap ./gradlew build in the terminal.I get this error : 
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-1.11-bin.zip

**Comment by sbrannen** [comment]
The `403` response is due to the fact that the URL uses HTTP instead of HTTPS.

Based on the Gradle wrapper version, I assume you are attempting to build an older version of Spring Framework 4.0.x or 4.1.x, in which case the latest configuration on those branches should download the Gradle wrapper using `https://services.gradle.org/distributions/gradle-1.12-all.zip`.

Thus, updating your clone of the branch should help solve the problem.

Otherwise, consider building a more recent version of the Spring Framework if you still have issues with 4.0.x and 4.1.x which are no longer supported.
