### ISSUE TITLE
XML request body cannot be deserialised by Spring web 5 with javax.xml.bind.annotation

### ISSUE THREAD

**Issue by quancheng-zhao** [spring-projects/spring-framework#25273]
Hello, when upgrading SpringBoot from 1.x to 2.x, Restful apis which consumes xml as request body  are broken because values are deserialised to null.

API is like: 

```java
@RequestMapping(
            method = POST,
            consumes = {APPLICATION_XML_VALUE, TEXT_XML_VALUE},
            produces = {APPLICATION_XML_VALUE, TEXT_XML_VALUE})
    Response postSomething(@ApiParam(name = "Request", value="A valid <Request /> xml query") @Valid @RequestBody **XmlRequest** xmlRequest);
```

`XmlRequest` used javax.xml.bind.annotation. Then I changed annotation to jackson-dataformat-xml, request body can be deserialised as before.

I don't find any report about javax xml problem. Does SpringBoot 2 have some limitation to use this package? Should XML deserialisation use jackson xml databinding? When I refactored the code, I find out jackson xml databing has less annotation and it works not well with polymorphic subtypes.

Thanks for your help.

**Comment by poutsma** [comment]
I believe this is by design, due to the support for Jackson XML (#16407) we introduced in 6665634675da1230339e9e5749f0693fd09a68ff. 

Effectively, this means that the Jackson XML mapper takes precedence over the JAXB converter. You can customize the order of the converters by overriding `extendMessageConverters` in your `WebMvcConfig`.
