### ISSUE TITLE
Revisit ScriptUtils and related classes in spring-r2dbc

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#25275]
Determine if common functionality for script parsing and execution can be extracted from `spring-jdbc` (package `org.springframework.jdbc.datasource.init`) and `spring-r2dbc` (package `org.springframework.r2dbc.connection.init`).

See related discussions in #25065.

**Comment by jhoeller** [comment]
Looking at this one more time, it's still not clear where to extract such pieces to. Even just extracting common exception classes seems like an unfortunate tradeoff since we'd have to put them into a SQL-specific (but not JDBC-specific) package which we don't have yet and don't want to introduce just for a few exception classes. Furthermore, we'd have to keep mirroring/deriving from those exception classes in JDBC for backwards compatibility purposes. Overall there is no real gain here, so a degree of duplication seems preferable over forced reuse (e.g. like some infrastructure in `spring-web` vs `spring-messaging`).
