### ISSUE TITLE
spel ,i can't get value when the expression is like '01'

### ISSUE THREAD

**Issue by sucls** [spring-projects/spring-framework#25299]
spring-expression-5.1.3.RELEASE

---
ExpressionParser parser = new SpelExpressionParser()
StandardEvaluationContext context = new StandardEvaluationContext();
Record record = new Record();
record.put("name","scl"); 
record.put("2","22"); 
record.put("03","33"); 
context.setRootObject(record);
parser.parseExpression("[a]").getValue(context);//11
parser.parseExpression("[2]").getValue(context);//22
parser.parseExpression("[03]").getValue(context);//null

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
