### ISSUE TITLE
MappingJackson2HttpMessageConverter might be too specific in its Charset support

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-framework#25322]
With this https://github.com/spring-projects/spring-framework/commit/eb0aae066c83ae0b7be280bd5c9e0679ed394a92#diff-ea14ba194c2adb7f8aa7f97a2ca5bcc7, spring web Jackson2 Converter introduced an enum set limiting UTF options. In a testing scenario we use "US-ASCII" which was working until now. Since 5.2.7, the controller will rejects requests, failing to decode.
Is that the intended behavior or should `ENCODINGS` map include US-ASCII as well ?

**Comment by poutsma** [comment]
Hey @smaldini, I think this has already been fixed as part of #25247. Can you please try a recent [5.2.8 snapshot](https://repo.spring.io/snapshot/org/springframework/spring-beans/5.2.8.BUILD-SNAPSHOT/) and see if that works as expected?

Though this issue is about **de**coding ASCII, it did remind me that we should also support ASCII for **en**coding as well, because it is essentially the same as UTF-8. So I will fix that.

**Comment by smaldini** [comment]
@poutsma good job ! We have confirmed it fixed it sorry for the noise :) Talk soon !

**Comment by poutsma** [comment]
Closing as duplicate of #25247.
