### ISSUE TITLE
Bean overriding for 'taskExecutor' alias is not detected

### ISSUE THREAD

**Issue by rgampa** [spring-projects/spring-framework#25430]
Earlier I was using 2.0.9.RELEASE, i have simply upgraded to 2.1.7.RELEASE. One of the bean couldn't be found or scanned by ComponentScan. 

```
***************************
APPLICATION FAILED TO START
***************************
Description:
Field taskExecutor in com.helper.Helper required a bean of type 'com.task.TaskExecutor' that could not be found.
The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
Action:
Consider defining a bean of type 'com.task.TaskExecutor' in your configuration.
```

In main class `@ComponentScan` is present and TaskExecutor is annotated with `@Component`.

I have tried moving up the main class, but didn't help still.

**Comment by saltyx** [comment]
I think this may be a bug. I check the ``ConfigurationClassBeanDefinitionReader#loadBeanDefinitionsForBeanMethod`` method.

```java
// Consider name and any aliases
List<String> names = new ArrayList<>(Arrays.asList(bean.getStringArray("name")));
String beanName = (!names.isEmpty() ? names.remove(0) : methodName);

// Register aliases even when overridden
for (String alias : names) {
  this.registry.registerAlias(beanName, alias);
}

// Has this effectively been overridden before (e.g. via XML)?
if (isOverriddenByExistingDefinition(beanMethod, beanName)) {
  ......
}

```

It uses the first item in the name array as the beanName, therefore, when checking whether the existing bean definition can be overridden, it is actually not checked whether the alias exists

In order to verify, I changed the name of the custom bean from TaskExecutor to ApplicationTaskExecutor. After executing it again, it reminded me that the name has been used. This is different from the previous bean not found error

When verifying whether the bean can be overridden, I think both beanName and its alias should be checked

**Comment by jhoeller** [comment]
This seems to be caused by a missing check for an alias overriding a bean definition of the same name in `DefaultListableBeanFactory`. Adding such a check makes the scenario fail with an `IllegalStateException` for me here, in case of `allowBeanDefinitionOverriding=false`.

I'll make sure to get this into 5.3 M2. Backporting is tough here since some applications may rely on an accidental override.
