### ISSUE TITLE
Feature: more flexible callbacks in spring-test

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-framework#25431]
What I miss in spring-test when I want to add a new feature is a way to communicate between extension components. If I'm using Spring Boot I want users to be able to just use `@SpringBootTest`, so the `ContextLoader` and the bootstrapper are fixed. I can add `TestExecutionListeners` and `ContextCustomizers` but they don't have a way to influence the way the `ContextLoader` works because they don't share any context.

See also https://github.com/spring-projects/spring-boot/issues/22405

**Comment by snicoll** [comment]
There hasn't been much traction for this and I am in the opinion that the TCF should have less callbacks rather than adding more of them (or, rather, consolidate them, rather than creating new ones). I am going to close this but if you have something concrete that you can showcase in a small project we can look at it and perhaps create a more focused issue.
