### ISSUE TITLE
Reporting wrong  SpelEvaluation EL1004E when an exception is happening in the method

### ISSUE THREAD

**Issue by ppjohnson** [spring-projects/spring-framework#25438]
Hi
When code is calling the JPA it is throwing a runtime exception due to transaction manager problem.
But Spring Integration is reporting as 
org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method processQuery(somepackage.ErrorMsgByErrorCodeQuery) cannot be found on type somepackage.QueryHandler .
This is wrong, it is not using the message from payload to report correct problem, so it is causing lot of confusion and taking too much time to isolate the problem.
Looking for a solution.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
