### ISSUE TITLE
MimeType.checkParameters() high processing time

### ISSUE THREAD

**Issue by arajitsamanta** [spring-projects/spring-framework#25479]
**Affects:** 
Spring Boot 2.0.1 RELEASE, Spring Framework 5.0.5 RELEASE

**Issue Description:** 
In a highly concurrent environment(Average 20K transaction per minute) it was observed that 100% of the processing time is being taken by `MimeType.checkParameters()`

Attached screenshot of the dynatrace 

Wondering if this is something related to #25043 / #24886. 

Any solution/suggestion would be helpful

 
---

**Comment by quaff** [comment]
Please try latest 5.2.8.RELEASE.

**Comment by bclozel** [comment]
I don't see a screenshot attached to your bug report. We've made significant performance improvements in the latest releases in this space.

Is the behavior you're seeing unusual? With which Spring Framework version this was behaving as expected?

I don't this this is related to the issues you're pointing to since the changes were introduced in Spring Framework 5.2 with #22340.

Maybe the media types used by your application (or sent by the clients) are a bit unusual and could explain this performance issue?

**Comment by arajitsamanta** [comment]
@bclozel  Please see below 

**Spring Version**
Spring Boot 2.0.1 RELEASE, Spring Framework 5.0.5 RELEASE


**Content Type Headers**
_Content Type:_ application/json
_Accept:_ text/html, image/gif,image/jpeg, *;q=.2, */* ; q=.2;

Dynatrace Screenshot
<img width="1298" alt="Spring Issue_Bug" src="https://user-images.githubusercontent.com/6784986/88681021-bd7e0780-d0b6-11ea-87cb-a18024ab6340.png">

**Comment by bclozel** [comment]
> Is the behavior you're seeing unusual? With which Spring Framework version this was behaving as expected?

Could you answer this question as well?
The call stack we're seeing here is not unusual. We've made performance improvements in recent versions about that, but I don't remember a change there around this version.

**Comment by arajitsamanta** [comment]
@bclozel 
We have been observing higher percentage(>50%) of contribution of that particular method call towards overall processing time. Lets say overall processing time is 1 sec for a single request. More than 50% being spent on that method invocation which seems to be very unusual.

Is that something expected with spring 5.0.5 version ?

**Comment by bclozel** [comment]
It all depends on the actual processing time of such requests - if it's really short, let's say a few milliseconds, then it might not be unexpected.

As I've said earlier, we've made significant improvements in recent versions in that area - improvements that we cannot backport in earlier versions for stability reasons. Without knowing where to look for, especially in which version this performance problem appeared, I cannot really make progress on this issue: I would just go down the path I've already worked on, which is caching the parsing of media types.

Ideally, changing the Spring Framework version (changing dependency version or going back into your project's history) and   and checking whether the problem is still there would help narrowing down the problem. Better, maybe you can reproduce this performance problem on a new sample project?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by arajitsamanta** [comment]
I tried to re-produce but not being able to. This issue can be closed for now.

**Comment by bclozel** [comment]
Thanks for checking!

**Comment by HaleLu** [comment]
I think I found out the truth. It's a bug in jdk.
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8137184

**Comment by bclozel** [comment]
@HaleLu it's been fixed and released with a bunch of JDK versions. Unless you're running an old JDK this shouldn't be a problem. See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8054446

**Comment by HaleLu** [comment]
@bclozel i know. I just want to explain why this is happening for @arajitsamanta
