### ISSUE TITLE
Upload a file, asynchronous processing will trigger Java.io.FileNotFoundException

### ISSUE THREAD

**Issue by lanicc** [spring-projects/spring-framework#25481]
upload a file, and and handle it like this, cause Java.io.FileNotFoundException.
tmp file will be cleaned after the request thread been processed.

![image](https://user-images.githubusercontent.com/48583080/88612351-9b3bb800-d0bd-11ea-96aa-dcb9db2016b8.png)
![image](https://user-images.githubusercontent.com/48583080/88612373-a7277a00-d0bd-11ea-9134-391119f0b194.png)

Exception is
`
java.io.FileNotFoundException: /private/var/folders/3f/r0vdjy7x6_gf8r65qztk2s280000gn/T/tomcat.8862437345990196241.8080/work/Tomcat/localhost/ROOT/upload_72649361_9318_475e_ac23_968976e74536_00000000.tmp (No such file or directory)
`

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by lanicc** [comment]
I think this is a bug. Another thread holds a reference to the uploaded file, but the real file is cleaned up by the request thread.

**Comment by hendisantika** [comment]
Is it solved? What's the solution?
I saw it's closed. But what's the solution?

I had same error when upload data.

Check this repository --> https://github.com/hendisantika/springboot-multithreading
