### ISSUE TITLE
Redis Reactive:Update Cache Fails

### ISSUE THREAD

**Issue by upen4a3** [spring-projects/spring-framework#25502]
Spring_boot_version = '2.3.1.RELEASE'

**what works** 

**Update Redis using Jedis** 
```
        val jedis = Jedis("localhost")
        println("Connection successful")
        println("Connection successful"+jedis.ping())
        jedis.set("cacheKey", cacheValue);
        println("Cache Value-"+jedis.get("cacheKey"))
```

**Get Using reactive redis Template--Successful**

`redisTemplate.opsForValue().get("cacheKey")`

**What Fails**

**Update cache using reactive redisTemplate**

`redisTemplate.opsForValue().set(cacheKey , cacheValue , Duration.ofSeconds(10s))`

**Get Using reactive redis Template--Failed**
`
redisTemplate.opsForValue().get("cacheKey")`

**Redis Configuration**

```
@Configuration
@ConditionalOnClass(
    ReactiveRedisTemplate::class,
    RedisConnectionFactory::class,
    LettuceConnectionFactory::class,
    ReactiveRedisConnectionFactory::class
)
open class RedisConfiguration
`{`

    @Bean
    open fun reactiveRedisConnectionFactory(): ReactiveRedisConnectionFactory {
        return LettuceConnectionFactory()
    }

    @Bean
    open fun reactiveRedisConnection(redisConnectionFactory: ReactiveRedisConnectionFactory): ReactiveRedisConnection
    {
        return redisConnectionFactory.reactiveConnection
    }

    @Bean
    open fun reactiveRedisTemplateString(@Qualifier("redisCache") connectionFactory: ReactiveRedisConnectionFactory?): ReactiveRedisTemplate<String,String> {
        return ReactiveRedisTemplate(
            connectionFactory,
            RedisSerializationContext.string()
        )
    }


}
```

Do i have to add any additional steps in order to update redis cache using redis reactive?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
