### ISSUE TITLE
DefaultMessageListenerContainer stops listening

### ISSUE THREAD

**Issue by xiangyang-gao** [spring-projects/spring-framework#25519]
<spring.version>5.0.8.RELEASE</spring.version>
erro：
All scheduled consumers have been paused, probably due to tasks having been rejected. Check your thread pool configuration! Manual recovery necessary through a start() call. 

Question: in what scenarios will this problem occur? How to solve it?

thank you

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
