### ISSUE TITLE
1 update query takes 3-4 minutes at DB2

### ISSUE THREAD

**Issue by muhammedOzbilici** [spring-projects/spring-framework#25595]
pom file looks like this; (spring boot version 2.1.8)

```
<dependency>
	<groupId>com.ibm.db2.jcc</groupId>
	<artifactId>db2jcc4</artifactId>
        <version>10.1</version>
</dependency>
<dependency>
       <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
</dependency>
```

and query is this, just one row

`jdbcTemplate.update("UPDATE myTable SET hashValue= ? WHERE TRIM(id) = ?", hashValue, id);`

So far, I tried to set `auto-commit=false` but nothing changed.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
