### ISSUE TITLE
Why PropertyValue needs to extends AttributeAccessor

### ISSUE THREAD

**Issue by yilianhuaixiao** [spring-projects/spring-framework#25607]
In spring-bean, PropertyValue now extends  AttributeAccessor, so it holds "attributes" in bean object.  But since PropertyValue represents an individual bean property, is it really  necessary to be like this?
PropertyValue extends AttributeAccessor  makes me confused.
Why not extends nothing only add a "source" field in PropertyValue?

**Comment by mdeinum** [comment]
[StackOverflow](https://stackoverflow.com/questions/tagged/spring) is the place to ask questions that way GitHub issues can remain for issues and enhancements. 

So please open a question there.

**Comment by yilianhuaixiao** [comment]
@mdeinum I am not sure if PropertyValue is bad desgined. So I want to get some feedback . If others think so too, maybe we can improve it.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
