### ISSUE TITLE
I create Bean Son which needs the Bean Father, and the bean father created on missingBean Enemy, the result is 

### ISSUE THREAD

**Issue by wy911149112** [spring-projects/spring-framework#25609]
there is no bean Father, but there is Bean Son, is this a bug?

```java
ConfigurableApplicationContext context = SpringApplication.run(SpringBeanApplication.class, args);
Son son = context.getBean(Son.class);
son.hello();
Father bean = context.getBean(Father.class);
bean.hello();


@Service
@ConditionalOnMissingBean(Enemy.class)
public class Father {
    public void hello() {
        System.out.println("father hello");
    }
}

@Service
public class Enemy {

}

@Service
@ConditionalOnBean(Father.class)
public class Son {
    public void hello() {
        System.out.println("son hello");
    }
}
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

As indicated in the [Javadoc of `@ConditionalOnMissingBean`](https://github.com/spring-projects/spring-boot/blob/9460d74e8ad8c247c3ad9a627ab35aa08df21152/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnMissingBean.java#L53-L56), such condition relies on the order in which the various components have been defined and you should only use those on auto-configuration.
