### ISSUE TITLE
Improve default `setNull` performance on PostgreSQL and MS SQL Server (e.g. for `NamedParameterJdbcTemplate` batch updates)

### ISSUE THREAD

**Issue by ricardoekm** [spring-projects/spring-framework#25679]
We've been investigating an issue where we had a 100x performance drop when switching from JdbcTemplate to NamedParameterJdbcTemplate in batch update operations.

We found out that the root cause is the handling of null values by StatementCreatorUtils:setNull, which in turn calls getParameterMetadata from the connection. It seems this issue a database call for every row to be inserted (call stack from profiler attached) which basically kills the performance gains of the batch insert.

We're using Postgres as back-end database. Spring JDBC 5.2.5.

Thanks.

<img width="1153" alt="namedparameterjdbctemplate_stack" src="https://user-images.githubusercontent.com/747894/92023631-631a3b80-ed33-11ea-8ef6-85f53f39a045.png">

**Comment by quaff** [comment]
Have you tried `-Dspring.jdbc.getParameterType.ignore=true`?

**Comment by quaff** [comment]
It seems `spring.jdbc.getParameterType.ignore` will not avoid `ps.getConnection().getMetaData()`, should spring need introducing a new `spring.jdbc.getMetaData.ignore`?

**Comment by quaff** [comment]
@jhoeller Could you explain why not simply call `ps.setObject(paramIndex, null)` ?

**Comment by jhoeller** [comment]
`ps.getConnection().getMetaData()` usually isn't expensive since it's cached in the connection pool. Just `getParameterMetaData()` may turn out to be expensive, and that's what `spring.jdbc.getParameterType.ignore=true` covers.

As for why not simply call `setObject`, it's about compatibility with certain drivers/databases. Quoting the `setObject` javadoc:

     *<b>Note:</b> Not all databases allow for a non-typed Null to be sent to
     * the backend. For maximum portability, the <code>setNull</code> or the
     * <code>setObject(int parameterIndex, Object x, int sqlType)</code>
     * method should be used
     * instead of <code>setObject(int parameterIndex, Object x)</code>.

**Comment by ricardoekm** [comment]
spring.jdbc.getParameterType.ignore=true did the trick, thanks!

**Comment by quaff** [comment]
@jhoeller I assume all modern databases allow non-typed Null, if it's true, `spring.jdbc.getParameterType.ignore` should be  `true` by default.

**Comment by ricardoekm** [comment]
Reasonable defaults, that's what life is about :)

**Comment by jhoeller** [comment]
We're happy to refine our default assumptions there. However, a few years ago, there were only a few databases supporting untyped `setObject(paramIndex, null)` calls, e.g. Microsoft's then-new SQL Server driver. For all others, a `setNull` call with some SQL type argument is needed.

I'd particularly like to learn about recent driver behavior with MySQL and PostgreSQL there. We effectively using `setNull(paramIndex, Types.NULL)` for the latter, like for other databases that we don't have explicit rules for. If this is known to work reliably, we can explictly opt into that for such well-known databases, not ever trying `getParameterType` for those then (independent from the `spring.jdbc.getParameterType.ignore` setting).

**Comment by jhoeller** [comment]
A StackOverflow answer about support for `setObject` vs `setNull` in common JDBC drivers (https://stackoverflow.com/a/10068111, dating back to 2016) and other articles suggest that MySQL does indeed reliably support untyped nulls, whereas PostgreSQL requires the specific SQL type to be set. I'll revise our default algorithm to take that into account, reopening this issue for it.

**Comment by ricardoekm** [comment]
Great to hear that you're revisiting this implementation.

Setting null with Types.NULL indeed works for PostgresSQL (JDBC) 42.2.12 and C3P0 0.9.5.5.

Adding a bit more information, here is the result of our performance test

### JdbcTemplate
Batch 1: 10925 records/sec.
Batch 2: 11189 records/sec.
Batch 3: 11170 records/sec.
Batch 4: 11140 records/sec.
Batch 5: 11179 records/sec.

Average: 11,120

### NamedJdbcTemplate default configuration
Batch 1: 312 records/sec.
Batch 2: 344 records/sec.
Batch 3: 348 records/sec.
Batch 4: 350 records/sec.
Batch 5: 357 records/sec.

Average: 342.2 records/sec.

### NamedJdbcTemplate with spring.jdbc.getParameterType.ignore=true

Batch 1: 10384 records/sec.
Batch 2: 10652 records/sec.
Batch 3: 10937 records/sec.
Batch 4: 10697 records/sec.
Batch 5: 10961 records/sec.

Average: 10,726 records/sec.

So in general, JdbcTemplate is a bit faster than NamedJdbcTemplate with spring.jdbc.getParameterType.ignore=true (around 4%), but in the same order of magnitude.

However, there's a huge performance drop by using NamedJdbcTemplate with the default configuration.

**Comment by quaff** [comment]
@jhoeller I'm wondering why `JdbcTemplate` not affected.

**Comment by quaff** [comment]
It seems like `JdbcTemplate` always use `TYPE_UNKNOWN` if type is not explicit, so there is some inconsistency with `NamedParameterJdbcTemplate`. 
https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-jdbc/src/main/java/org/springframework/jdbc/core/ArgumentPreparedStatementSetter.java#L69

**Comment by jhoeller** [comment]
Hmm `NamedParameterJdbcTemplate` should effectively also end up with `SqlTypeValue.UNKNOWN` by default... wondering where the performance difference actually comes from. Maybe it's some subtle interaction that I'm missing here.

**Comment by ricardoekm** [comment]
I've done some additional investigation to try to identify the difference between the NamedJdbcTemplate and JdbcTemplate when using *ignoreParameterType*.

It seems the issue is StatementCreatorUtils.setParameterInternal, but I was unable to track the cause (it seems something the method is doing itself, not something he's calling).

When using JdbcTemplate setting values take 6.9% of the time:
<img width="1148" alt="jdbcTemplate" src="https://user-images.githubusercontent.com/747894/93940789-80737180-fd03-11ea-8848-410f9eb7410f.png">

When using NamedJdbcTemplate it goes to 15.9% of the time:
<img width="1148" alt="namedJdbcTemplate" src="https://user-images.githubusercontent.com/747894/93940895-abf65c00-fd03-11ea-9331-5a85e2326300.png">

For additional info here goes the jProfiler snapshot:
[jProfilerSnapshot.zip](https://github.com/spring-projects/spring-framework/files/5264162/jProfilerSnapshot.zip)

**Comment by sabomichal** [comment]
Curious why this is still not fixed, having huge performance impact on many systems not even knowing. Is there anything what needs to be done yet?

**Comment by jhoeller** [comment]
The hard part here is identifying whether it is necessary to specify a concrete SQL type for a given JDBC driver. Most modern drivers take the given type into account and send corresponding prepared parameter information to the DBMS, so simply changing this to untyped by default might be accepted by the driver but influence the resulting execution plans. It is tough to make assumptions here as a caller without knowing the implementation specifics of the driver and the target database.

A quick re-check of several driver implementations leads me to the assumption that `getParameterMetaData` is actually a cheap enough operation in most drivers, including recent MySQL drivers and PGJDBC-NG... with a single exception: the classic PostgreSQL JDBC driver. Now we could hard-code a bypass there in `StatementCreatorUtils.setNull` based on `DatabaseMetaData.getDriverName().startsWith("PostgreSQL")`, never calling `getParameterMetaData()` by default then. However, even such a workaround is not ideal since we'd keep bypassing it even if a newer PostgreSQL driver version (identifying itself through the same driver name) chooses to implement `getParameterMetaData`  in a cached manner like most other drivers do. With such a reasonable implementation, we would prefer to specify null with a concrete SQL type again.

**Comment by jhoeller** [comment]
For the classic PostgresSQL JDBC driver, there is actually a GitHub issue for it: https://github.com/pgjdbc/pgjdbc/issues/621
Seems to have got stuck some time last year.
Can everyone interested in this from Spring's side here cast their vote over there please :-)

**Comment by davecramer** [comment]
@jhoeller can you point me to the concrete caching approach you are referring to?

**Comment by jhoeller** [comment]
@davecramer it looks like @vlsi was pretty much working in that direction with https://github.com/pgjdbc/pgjdbc/issues/621 already. I suppose a PreparedStatement-level cache would go a long way, a Connection-level cache would be even better.

All we really need is `getParameterMetaData()` turning into a cheap enough operation for repeated calls on the same `PreparedStatement`, with any necessary backend interaction only happening once and the resulting SQL type information then being immediately available for repeated parameter setting on the same statement.

On Spring's side, we just need that metadata for passing in a SQL type to a `PreparedStatement.setNull` call if we don't have more specific type information for a given parameter. If there is another way of sending typed nulls to the DBMS without introspecting `getParameterMetaData()`, we could support that on Spring's side as well. Generally speaking, we operate under the assumption that `setNull(..., Types.NULL)` is not good enough by default, and neither is `setObject(..., null)`.

**Comment by jhoeller** [comment]
@davecramer, reviewing other JDBC driver implementations in that respect, the key-based caching approach that @vlsi considered was probably more sophisticated than necessary. The common driver implementations seem to simply cache the `ParameterMetaData` object in the `PreparedStatement` instance after obtaining it. So no reactions to intermediate changes in the database schema or the like, and no reuse at the connection level either, just returning the existing metadata object for repeated calls on the same `PreparedStatement` instance.

**Comment by vlsi** [comment]
@jhoeller , thank you for the clarification. Let me see if I can implement the MVP.

**Comment by viniciusxyz** [comment]
I had performance problems in production due to the setNull using MSSQL with the official driver in the latest version available (12.4.1) and JDBCTemplate.update(), when adding the parameter `-Dspring.jdbc.getParameterType.ignore=true`, the time for preparing the query decreased drastically, giving a **70%** lower average execution time and reducing the amount of GC during some tests from **196** executions to just **17** which greatly improved CPU performance.

I would like to understand when the use of this parameter can actually be something negative and if there is any relationship between drivers where it causes problems, currently I use the official [mssql driver](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.4.1) and the [postgresql driver](https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.6.0) for some demands, is there any way that Do you recommend so that I can test these drivers? If possible, I would like to always set the value of `spring.jdbc.getParameterType.ignore` to `true` in some applications I have, but I'm unsure of what exactly might happen if I do that.

Thank you in advance if anyone can clarify these doubts, I don't understand in depth how the drivers work and so it's difficult for me to know exactly which scenarios are problematic with the mentioned parameter.

**Comment by viniciusxyz** [comment]
@jhoeller There is an extra point that I believe was not considered.

When an application uses two different types of datasources, for example mssql and oracle, jdbctemplate will always have non-ideal performance or erroneous behavior if IGNORE_GETPARAMETERTYPE_PROPERTY_NAME is set to true.

For these cases, it might be worth allowing the configuration of ignore_getParameterType via a property configured on the object instance instead of a static attribute that will necessarily be the same for all instances.

An example would be a CQRS application that for whatever reason has the command layer in mssql and the reading layer in oracle or vice versa

**Comment by viniciusxyz** [comment]
> @jhoeller There is an extra point that I believe was not considered.
> 
> When an application uses two different types of datasources, for example mssql and oracle, jdbctemplate will always have non-ideal performance or erroneous behavior if IGNORE_GETPARAMETERTYPE_PROPERTY_NAME is set to true.
> 
> For these cases, it might be worth allowing the configuration of ignore_getParameterType via a property configured on the object instance instead of a static attribute that will necessarily be the same for all instances.
> 
> An example would be a CQRS application that for whatever reason has the command layer in mssql and the reading layer in oracle or vice versa

@jhoeller I just noticed that your implementation went to the heart of the problem and added the code directly over setNull making the behavior ideal for the cases I talked about. I really appreciate the modification.
