### ISSUE TITLE
DispatcherServlet.doDispatch.cleanupMultipart

### ISSUE THREAD

**Issue by WwwJy** [spring-projects/spring-framework#25750]
I use【MultipartFile.transferTo(File dest)】method deal with my file uploaded by HTTP
When I return the HTTP request correctly , The file was deleted.
I found out that DispatcherServlet.doDispatch.cleanupMultipart did this.
Should I give up the multipartfile.transferto (File dest) method for this reason?

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
