### ISSUE TITLE
Why XmlBeanDefinitionReader does not define a private static Set to solve resourcesCurrentlyBeingLoaded reloading?

### ISSUE THREAD

**Issue by hzmpay** [spring-projects/spring-framework#25832]
**Affects:v5.2.x \<Spring Framework version>

---

ThreadLocal processing can only prevent the current thread from repeated loading. Why not use Set for processing, which can prevent multiple threads from repeated loading. Is this designed to load the latest XML resources under the scenario where the XML resources have been modified?

**Comment by jhoeller** [comment]
This is only really meant to detect cyclic import definitions within the current thread. Since there is usually a primary startup thread, it is sufficient to do this in a thread-local manner. Other threads may load the same resources at other times, potentially picking up updated files there, and getting the same thread-local cycle detection for their individual loading attempt.
