### ISSUE TITLE
ServerSentEventHttpMessageWriter should not write Flux<DataBuffer> without a content type hint

### ISSUE THREAD

**Issue by violetagg** [spring-projects/spring-framework#25908]
**Affects:** 5.2.9.RELEASE

---

According to the specification RFC https://tools.ietf.org/html/rfc7231#section-4.3.2

```
The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted.
```

This is the endpoint

```java
private final DataBufferFactory dataBufferFactory = new DefaultDataBufferFactory();

@GetMapping("/headers")
public ResponseEntity<Flux<DataBuffer>> testHeadersGET() {
	return ResponseEntity
			.ok()
			.body(Flux.defer(() -> {
				byte[] bytes = "variableLengthString".getBytes();
					 
				return Flux.just(dataBufferFactory.wrap(bytes));
			}));
}
```

With GET request these are the request/response headers

```
GET /headers HTTP/1.1
Host: localhost:8080
Accept: */*
```

```
HTTP/1.1 200 OK
transfer-encoding: chunked
Content-Type: text/event-stream
```

With HEAD request these are the request/response headers

```
GET /headers HTTP/1.1
Host: localhost:8080
Accept: */*
```

```
HTTP/1.1 200 OK
Content-Type: text/event-stream
Content-Length: 20
```

In the first case with GET, `transfer-encoding` is used, while in the case with HEAD it is `Content-Length: 20`. Why is that?

Also additional question why Spring Framework decides to return `Content-Type: text/event-stream` as it is not specified that this is SSE.

This is related to https://github.com/reactor/reactor-netty/issues/1333

**Comment by rstoyanchev** [comment]
Both `DataBufferEncoder` and `ServerSentHttpMessageWriter` indicate they can write the given `Flux<DataBuffer>` but the latter is wrong. The choice to write SSE should be based on something more explicit such as a media type hint (via `Accept` header or a `produces` condition) or a more explicit return type (i.e. `ServerSentEvent`). That is how Spring MVC works.

As a result "text/event-stream" is the chosen content type, but `DataBufferEncoder` is still first and willing to write for any media type. From there for HTTP HEAD the `HttpHeadResponseDecorator` counts the bytes and sets the content-length, while for HTTP GET the `EncoderHttpMessageWriter` skips aggregation because it recognizes `text/event-stream` as a streaming media type which leads to the difference in response headers.

**Comment by rstoyanchev** [comment]
I've [updated](https://github.com/spring-projects/spring-framework/commit/1d96f6a266553d1c5512fbd9de9e91d53390ecf1) `HttpHeadResponseDecorator` in 5.2.x to avoid adding `Content-Length` if there is an existing `Content-Length` and `Transfer-Encoding` header. 

I've [extended](https://github.com/spring-projects/spring-framework/commit/7e647ab1d831170b912ea29add4e79839535ec93) this further in 5.3 so that `Content-Length` is only calculated for a `Mono` since normally for a GET `HttpMessageWriter` implementations typically do not set a `Content-Length` for a `Flux`.
