### ISSUE TITLE
springmvc get request query string param wrap to a pojo

### ISSUE THREAD

**Issue by L1yp** [spring-projects/spring-framework#25971]
**Affects:** \springmvc latest
how to set the default value of the pojo property?
---

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by L1yp** [comment]
thanks, stackOverflow: [link](https://stackoverflow.com/questions/64533000/springmvc-get-request-query-string-param-wrap-to-a-pojo)
