### ISSUE TITLE
@EnableConfigurationProperties mark internal class happen exception

### ISSUE THREAD

**Issue by biuabiu** [spring-projects/spring-framework#26179]
spring 5.1.9-RELEASE
spring boot 2.1.7-RELEASE
when i has internal class to register ,i use @EnableConfigurationProperties marks on class A and B  ,at this time  has  happen exception; i remove the class A  annotation;at this time started successful;
the class B use @EnableConfigurationProperties registering  C,at this time B is also registered,the classB should b be registered at this time ?
But when I move the two internal classes to the same level as a, both class A and class B have to be @EnableConfigurationProperties  annotated to complete the startup

[TestConfiguration.txt](https://github.com/spring-projects/spring-framework/files/5615267/TestConfiguration.txt)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

FTR, this is the wrong issue tracker to report this as `@ConfigurationProperties` is a Spring Boot feature. Please review [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-enabling) and follow up on StackOverflow if necessary.
