### ISSUE TITLE
ServerHttpRequestDecorator's getBody is not invoked without @RequestBody

### ISSUE THREAD

**Issue by ryukato** [spring-projects/spring-framework#26249]
### Version
 - spring-boot-starter-webflux: 2.3.3.RELEASE
### What happened
We're using a class that extending `ServerHttpRequestDecorator` and is being used in a filter chain to do a sort of validation against body of a request. And the our custom decorator is being invoked in normal situation but if there is body of a request from a client to call a API that defined without `@RequestBody`, then the decorator is not invoked.

I guess the decorator have to be invoked if there is body of a request, even though there is no `@RequestBody` annotated.

Sorry a sort of short explanation but I will attach more if I found anything.

Thanks

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

My best guess is the request body isn't being consumed and/or there is no body. It's probably expected behavior.

**Comment by ryukato** [comment]
Thanks for response, Yes there was a fault with handling `DataBuffer` but we fixed it and everything is working fine.
Sorry for bothering you and thanks again.
