### ISSUE TITLE
Can we manage thread pool in webclient when sending a request?

### ISSUE THREAD

**Issue by bastayanfa** [spring-projects/spring-framework#26373]
Currently, I'm migrating RestTemplate to webClient.
In RestTemplate have coroutineDispatcher to manage thread pool of app.
```
val coroutineDispatcher = ThreadPoolExecutor(
        0,
        1,
        1L,
        TimeUnit.HOURS,
        LinkedBlockingQueue(),
)
        .asCoroutineDispatcher()
```
When I send an HTTP request, I found out that it's created all thread that my pc has.
But the app's requirement spec needs a config like the coroutineDispatcher above, and I cannot find a way to configure it on webClient.

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

As an additional comment, please refer to the documentation for [configuring options](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-reactor) on the level of the HTTP client in the Spring Framework reference and then check the docs for the HTTP client you are using. Conceptually this is no different than how it works with the `RestTemplate`.
