### ISSUE TITLE
@AuthenticationPrincipal resolves to null when spring security is also included

### ISSUE THREAD

**Issue by krm1312** [spring-projects/spring-framework#26380]
Followup to #26117.

When using boot 2.4.1 with managed spring and spring security dependencies @AuthenticationPrincipal is no longer bound.  Brief debugging appears to indicate that AuthenticationPrincipalArgumentResolver 'supports' the argument and resolves it to null before PrincipalMethodArgumentResolver has a chance to resolve it.  

Sample project:  https://github.com/krm1312/spring-auth-principal.

Toggle boot version in pom.xml to see difference.

**Comment by rstoyanchev** [comment]
Thanks for the sample. 

That looks like expected behavior to me. According to the Javadoc `@AuthenticationPrincipal`, it resolves `Authentication#getPrincipal()` which in this case is `org.springframework.security.core.userdetails.User` and that is not a `Principal`. It did work before because `Principal` was resolved earlier prior to 5.3 but in that case the annotation is ignored. So it seems like you need to remove the annotation and if you want to be resolved through the request.

**Comment by krm1312** [comment]
Thank you.  I can confirm removing the annotation fixes it in our real application as well.

Feel free to close if you want to keep the more strict behavior.
