### ISSUE TITLE
IllegalStateException for form content type and @RequestBody on reactive stack

### ISSUE THREAD

**Issue by huberchrigu** [spring-projects/spring-framework#26386]
A `@RestController` like

```
@RestController
 public class DemoController {
     @PostMapping
     public Map<String, Object> getAttributes(@RequestBody Body body, ServerWebExchange serverWebExchange) {
         return serverWebExchange.getAttribute(body.getAttribute());
     }
 }
```

is expected to handle requests with content type _application/json_. When the client request has a content type _x-www-form-urlencoded_, I would expect that the server returns _415 Unsupported Media Type_ or another client error.
Instead Spring throws _java.lang.IllegalStateException: In a WebFlux application, form data is accessed via ServerWebExchange.getFormData()._

A sample application with failing test can be found here: https://github.com/huberchrigu/spring-reactive-wrong-content-type

**Comment by rstoyanchev** [comment]
Technically it is possible to read the body via `FormHttpMessageReader` but we decided to prevent it as part of #22486 in order to avoid running into the issue of trying to consume the body twice, once via `ServerWebExchange#getFormData` (e.g. in a filter or other) and a second via `@RequestBody`. You're right though that 415 would be a better way to flag this since this effectively means that method doesn't support it.
