### ISSUE TITLE
AbstractBeanDefinition#equals handles propertyValues incorrectly

### ISSUE THREAD

**Issue by AnthonyYeracaris** [spring-projects/spring-framework#26433]
See line 1198: ObjectUtils.nullSafeEquals(this.propertyValues, that.propertyValues)
Look at AbstractBeanDefinition#getPropertyValues, line 891, which treats, in effect a propertyValues of null as equivalent to en empty MutablePropertyValues object (i.e., a side-effect of getPropertyValues is to create an empty MutablePropertyValues object when propertyValues is null).
Affects version 5.3.3

**Comment by jhoeller** [comment]
This turns out to be a regression from 4.3.x where there always were empty `MutablePropertyValues` and `ConstructorArgumentValues` instances in every `BeanDefinition`. In 5.x we optimized those to be lazily created but accidentally consider `BeanDefinition` instances now if they are not in the same field initialization state, even if nothing has been registered.

**Comment by AnthonyYeracaris** [comment]
BTW, and forgive me if it's too obvious, but don't forget the hashCode() implementation.
