### ISSUE TITLE
AbstractRoutingDataSource - Object instead of DataSource interface

### ISSUE THREAD

**Issue by Drezir** [spring-projects/spring-framework#26431]
Hi,
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.html#setTargetDataSources-java.util.Map-

it accepts Map<Object, Object> but why is the second type an Object? Should not it be an interface DataSource?
The method determineTargetDataSource map to this type anyway and cast exceptions may be throws if someone passes some other object.

Questions are:

1. Is it save to assign Map<Object, Object> to Map<Object, DataSource>
2. Why to accept argument with raw Object type rather then DataSource

**Comment by jhoeller** [comment]
There's a note on it in the javadoc: `The mapped value can either be a corresponding DataSource instance or a data source name String (to be resolved via a DataSourceLookup). ` So this intentionally abstracted, even beyond DataSource/String since subclasses may implement the `resolveSpecifiedDataSource` template method in a custom way.
