### ISSUE TITLE
In version 2.4.X @Mock HttpHeaders is not work

### ISSUE THREAD

**Issue by ERAGON-JCV** [spring-projects/spring-framework#26509]
In unit test with mockito and Junit 5 

with version Spring Boot 2.3.4 @Mock HttpHeaders works

![image](https://user-images.githubusercontent.com/50639030/106818523-66995200-6646-11eb-905e-a3c722120ecf.png)

![image](https://user-images.githubusercontent.com/50639030/106818448-4bc6dd80-6646-11eb-9bc3-6e9d22c6f5c1.png)

but in version 2.4.X this error appears, apparently Mock HttpHeaders is null or empty in this verification

![image](https://user-images.githubusercontent.com/50639030/106819034-37371500-6647-11eb-9bff-dc2e418d93c8.png)

![image](https://user-images.githubusercontent.com/50639030/106818702-a6603980-6646-11eb-92d3-29f92edfe4e8.png)

with version Spring Boot 2.3.4 this verification was like this and it worked

![image](https://user-images.githubusercontent.com/50639030/106819493-e247ce80-6647-11eb-9108-fc2e432181a1.png)

please fix it in new versions, thank you very much.

**Comment by sbrannen** [comment]
@ERAGON-JCV, why are you mocking `HttpHeaders`?

Why not simply use a new instance of `HttpHeaders`?

For example, if you remove the `@Mock private HttpHeaders headers;` declaration in `ClientServiceTest` and then add the following line to your `init()` method ...

```java
ReflectionTestUtils.setField(clientService, "headers", new HttpHeaders());
```

... then your test passes with a real, legitimate instance of `HttpHeaders`.

Of course, we discourage the use of `@Autowired` fields in production classes, since that makes it harder to test components. Introducing constructors or setter methods that accept the `HttpHeaders` and `urlMonetaryFee` would alleviate the need to use `ReflectionTestUtils` for setting those private fields.

**Comment by sbrannen** [comment]
**Team Decision**: The Spring Framework team does its best to ensure stability in public APIs across releases; however, that does not apply to internal implementation details. Mocking a concrete type such as `HttpHeaders` can lead to a mock that relies on the internal implementation (which is not part of the public API), and the behavior of such a mock can therefore be incompatible with changes to internal implementation details across releases. In light of that, I am closing this issue.

https://github.com/spring-projects/spring-framework/issues/26509#issuecomment-776616369 provides a viable solution by using a real instance of `HttpHeaders`.

Aside from that, having an `@Autowired HttpHeaders` dependency in a Spring-managed component seems questionable. Typically a new instance of `HttpHeaders` would be created for each request submitted via the `RestTemplate`. If a single, preconfigured instance of `HttpHeaders` is desirable, one would typically create one local to its usage and not define one as a singleton bean in the `ApplicationContext`. Thus, you may wish to reconsider your use of a shared `HttpHeaders` bean in your application.
