### ISSUE TITLE
Scheduled class ScheduledTaskRegistrar to implement the InitializingBean interface

### ISSUE THREAD

**Issue by MentosL** [spring-projects/spring-framework#26516]
I have a question：

Why does ScheduledTaskRegistrar implement Interface InitializingBean？

afterPropertiesSet methods of class ScheduledTaskRegistrar are not in the Spring bean life cycle,Instead, it uses event listening

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by MentosL** [comment]
Good thank you
