### ISSUE TITLE
BeanUtils does not copy properties with generics from a Proxy since 5.3.0

### ISSUE THREAD

**Issue by rreitmann** [spring-projects/spring-framework#26531]
After upgrading from spring boot 2.3.8 to 2.4.2 our following test case fails:
[CopyPropertiesTest](https://github.com/dzhw/metadatamanagement/blob/development/src/test/java/eu/dzhw/fdz/metadatamanagement/searchmanagement/service/CopyPropertiesTest.java) 

Basically it loads a spring data projection from MongoDB and tries to copy all of its properties with Spring's `BeanUtils.copyProperties` into another bean. For some reason "collection"-properties are not copied anymore after the upgrade.

**Comment by sbrannen** [comment]
I have confirmed that this is a regression beginning with Spring Framework 5.3.0 due to #24281 as suggested by @mbhave.

My initial analysis is that the type information is lost when using `ResolvableType.forMethodReturnType(...)` for the `getOrderLineItems()` method in the proxy for the `OrderProjection` (note that Spring Data creates a proxy that implements the `OrderProjection` interface). Thus, we are effectively now comparing `List<?>` to `List<String>`, deciding that is a mismatch, and skipping the `orderLineItems` property.

**Comment by sbrannen** [comment]
This has been fixed in `master` and will be available in the upcoming 5.3.4 snapshot.

Feel free to give it a try and let us know if you run into any issues.

**Comment by rreitmann** [comment]
Thanks for the quick fix, I will wait until it is part of a spring boot release.
