### ISSUE TITLE
After Spring upgrade from 5.2.x to 5.3.x - No mapping for GET /

### ISSUE THREAD

**Issue by hth** [spring-projects/spring-framework#26563]
After upgrading the same project stops working. Fails to load and the log shows `Message=No mapping for GET /`

Please let me know what all details would be required to investigate it. I have a sample project available to showcase this error message.

**Comment by bclozel** [comment]
There's not much we can do with so little information.
Could you please give us the link to your sample or attach it as a zip file here?

Thanks!

**Comment by hth** [comment]
Sample project location: [https://github.com/hth/sampler](https://github.com/hth/sampler)

It is a one page application. Web Output below. 

Hello 28-03-2018
Parsed Date: Wed Mar 28 00:00:00 PDT 2018

Supported Spring Version: springVersion=5.2.12.RELEASE
Once modified to 5.3.4, error message on console `Message=No mapping for GET /`

**Comment by rstoyanchev** [comment]
Thanks for the sample. The war doesn't build correctly (it contains only classes and libs). I see the web.xml has `<welcome-file>open/home.htm</welcome-file>`. However suffix patterns are no longer enabled by default as mentioned in the [upgrade notes](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#spring-mvc) and the [reference docs](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-requestmapping-suffix-pattern-match). You can try changing it to `<welcome-file>open/home</welcome-file>` or otherwise re-enable suffix pattern matching.

**Comment by hth** [comment]
I have fixed the war issue and checked in. It seems the reference you provided solved my issue. Please mark this as closed. Apologies on missing out on upgrade notes. Thanks again for your help! Good day.
