### ISSUE TITLE
servlert-api-2.5 jar包下的javax.servlet下缺少类

### ISSUE THREAD

**Issue by 1403786495** [spring-projects/spring-framework#26573]
**Affects:** \<Spring Framework version>

---

![屏幕截图 2021-02-20 102122](https://user-images.githubusercontent.com/62466008/108580264-bd509c80-7365-11eb-96fe-d28ac0e8b158.png)

在idea上下了源代码就显示DispatcherType类显红，

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
