### ISSUE TITLE
How to monitor `org.springframework.cache.interceptor.AbstractCacheInvoker#doEvict`?

### ISSUE THREAD

**Issue by dongfangding** [spring-projects/spring-framework#26653]
Sorry to disturb you.

I wanna monitor `org.springframework.cache.interceptor.AbstractCacheInvoker#doEvict` and handle some extra logic in it, and then I see it in the code` org.springframework.cache.interceptor.CacheInterceptor `.

 I try to customize the overlay behavior, just like[https://github.com/spring-projects/spring-framework/issues/22641](https://github.com/spring-projects/spring-framework/issues/22641).

`org.springframework.cache.annotation.ProxyCachingConfiguration`，
It seems that this registered class is designed to not allow custom interceptor extensions.

Please help, do I have any other way now?

**Comment by snicoll** [comment]
That sounds a question we'd prefer you to ask on StackOverflow (please review [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss)).

If you decide to ask on StackOverflow, please describe your use case rather than what you think is the right way of implementing it. `doEvict` ultimately call the underlying `Cache` so a `CacheResolver` that returns a custom cache of yours would be enough to run additional logic when eviction occurs.
