### ISSUE TITLE
WebFlux annotation Controller Mono empty unified response processing

### ISSUE THREAD

**Issue by liuzhongkai** [spring-projects/spring-framework#26669]
When the Mono processing result is empty, add a unified response result.
A single Mono can use ****IfEmpty to implement this logic.
Api of function can use HandlerFilterFunction.
I now use annotation @RequestMapping, how should I implement it, and add a unified response result.
Thank you for your time!

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
