### ISSUE TITLE
Add PrematureCloseException to WebFlux HttpWebHandlerAdapter

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#26771]
Spring Boot has had a PR raised to add `PrematureCloseException` to our `AbstractErrorWebExceptionHandler` (see https://github.com/spring-projects/spring-boot/pull/25886). Since these values are copied from `HttpWebHandlerAdapter` I want to raise the same issue for consideration in Framework before we merge the PR.

**Comment by rstoyanchev** [comment]
> `reactor.netty.http.client.PrematureCloseException` is equivalent for `org.apache.catalina.connector.ClientAbortException` and should be treat similar

@michaldo, Reactor Netty has a `ClientAbortException` which is raised when the server response is aborted because the remote client went away. We do treat that as "disconnected client". The `PrematureCloseException` exception on the other hand is raised when a client loses its connection to a server which implies the server could not handle the request because it the remote service it was talking to went away. This is not the same scenario and we cannot suppress it.

**Comment by michaldo** [comment]
Thanks for clarification,
I encountered the exception logged on cloud gateway and I must wrongly understand where is the problem - on downstream or on upstream

**Comment by rstoyanchev** [comment]
Ok no problem
