### ISSUE TITLE
HandlerMappingIntrospector does not work with PathPattern backed HandlerMappings

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#26814]
Discovered whilst working on https://github.com/spring-projects/spring-boot/issues/24645. Running [`CorsSampleActuatorApplicationTests.preflightRequestToEndpointShouldReturnOk` from this branch](https://github.com/philwebb/spring-boot/tree/gh-24645) should replicate the problem.

This issue is a quite subtle and hard to replicate. I've found it to cause problems for `CorsFilter` as well as `MvcRequestMatcher` in Spring Security. It appears that `HandlerMappingIntrospector` can fail to find mappings if they are configured with a `PathPattern`.

In `AbstractHandlerMapping.initLookupPath` there's the following branch:

```java
if (usesPathPatterns()) {
	request.removeAttribute(UrlPathHelper.PATH_ATTRIBUTE);
	RequestPath requestPath = ServletRequestPathUtils.getParsedRequestPath(request);
	String lookupPath = requestPath.pathWithinApplication().value();
	return UrlPathHelper.defaultInstance.removeSemicolonContent(lookupPath);
}
else {
	return getUrlPathHelper().resolveAndCacheLookupPath(request);
}
```

This means that `ServletRequestPathUtils.getParsedRequestPath(request)` is called when a `PathPattern` is set. That code will fail if `request.getAttribute(PATH_ATTRIBUTE)` is `null`.

Usually `HandlerMappers` are only called from the `DispatcherServlet` which has the following logic:

```
RequestPath previousRequestPath = null;
if (this.parseRequestPath) {
	previousRequestPath = (RequestPath) request.getAttribute(ServletRequestPathUtils.PATH_ATTRIBUTE);
	ServletRequestPathUtils.parseAndCache(request);
}
```

The problem is that `HandlerMappingIntrospector` is designed to be called from a `Filter` which means that it can be executed before the `DisatcherServlet` runs.

**Comment by rstoyanchev** [comment]
It looks like the [original intent was](https://github.com/spring-projects/spring-framework/blob/5d297c6387b9e6c62dcb7e6ec3c5d04aad85310d/spring-webmvc/src/test/java/org/springframework/web/servlet/handler/HandlerMappingIntrospectorTests.java#L131-L134) that Spring Security might configure `ServletRequestPathFilter` in its filter chain. However, when the [solution was refined](https://github.com/spring-projects/spring-security/issues/8691#issuecomment-654218610) so that its Spring Security can remain unaware of the kind of patterns used, the `HandlerMappingIntrospector` was never updated. I will fix that.

I'm not sure what the issue is for `CorsFilter`, I presume that is a variation of the same issue when Spring Security calls `HandlerMappingIntrospector#getCorsConfiguration`?

**Comment by philwebb** [comment]
Yes, it's [this line](https://github.com/spring-projects/spring-framework/blob/5d297c6387b9e6c62dcb7e6ec3c5d04aad85310d/spring-web/src/main/java/org/springframework/web/filter/CorsFilter.java#L86) when `configSource` is a `HandlerMappingIntrospector`. The `CorsConfiguration` is never returned because [this line](https://github.com/spring-projects/spring-framework/blob/5d297c6387b9e6c62dcb7e6ec3c5d04aad85310d/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/HandlerMappingIntrospector.java#L167) catches and swallows [this exception](https://github.com/spring-projects/spring-framework/blob/5d297c6387b9e6c62dcb7e6ec3c5d04aad85310d/spring-web/src/main/java/org/springframework/web/util/ServletRequestPathUtils.java#L77).

**Comment by rstoyanchev** [comment]
Okay thanks for confirming.
