### ISSUE TITLE
Add optional path parameter to @Controller

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-framework#26872]
I type `@RequestMapping` and `@Controller` before almost all my Controllers.

```java
@RequestMapping("/clients")
@Controller
class ClientsController {
}
```

If you introduce a `path` attribute in `@Controller`,  this can be reduced to:

```java
@Controller(path="/clients")
class ClientsController {
}
```

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
Hi @hansdesmet,

Thanks for creating your first Spring Framework issue!

Regarding your proposal, we would not want to introduce a `path` attribute in `@Controller` since controller classes are not required to declare a class-level `@RequestMapping`.

However, you can make use of a custom _composed annotation_ that will help you achieve your goal.

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Controller
@RequestMapping
public @interface MappedController {

	@AliasFor(annotation = Controller.class)
	String value() default "";

	@AliasFor(annotation = RequestMapping.class)
	String path();
}
```

You can then use that composed annotation as follows.

```java
@MappedController(path = "/clients")
class ClientsController {
    // ...
}
```

In light of that, I am closing this issue.

**Comment by rstoyanchev** [comment]
Note also `@Controller` isn't defined as a Web controller and doesn't have to. It is also supported for STOMP or RSocket messaging in which case a `path` attribute wouldn't fit well.
