### ISSUE TITLE
Upgrade to Gradle 7.2

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-framework#26870]
Here is tasks I can remember
- [x] upgrade gradle wrapper
- [x] replace removed configration `compile` `runtime` `testCompile` `testRuntime`
- [x] use convention plugin to [organize build logic for subprojects](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html)

**Comment by bclozel** [comment]
I've got a draft commit for this, fixing quite a few things in our build. The `dokka` plugin version we're using is not compatible with Gradle 7 and after checking with the team, [we should probably wait for the 1.5.0 version](https://github.com/Kotlin/dokka/milestone/22).

I'm moving this back to the backlog and marking it as blocked in the meantime.

**Comment by sbrannen** [comment]
In the meantime, [Gradle 7.1](https://docs.gradle.org/7.1/release-notes.html) has been released.

**Comment by bclozel** [comment]
I've got a [draft commit for this issue here](https://github.com/bclozel/spring-framework/tree/gh-26870).

The build runs fine but the dokka generation takes 10+min on my laptop and the result is quite large (almost 40MB). I'm wondering if I've messed up the configuration or if there's a way to limit the scope here so that the plugin has less things to consider. [The new version of the plugin simplifies our setup quite a bit](https://kotlin.github.io/dokka/1.5.0/user_guide/gradle/usage/#multi-module-projects).

@sdeleuze Could you have a look here?

You can locally trigger the generation with: `./gradlew dokkaHtmlMultiModule --no-scan --info`.

**Comment by quaff** [comment]
1. The Report.destination property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the outputLocation property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:destination for more details.

2. The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.

**Comment by sbrannen** [comment]
Thanks, @quaff.

We've noticed those warnings as well.

Reopening to address those two warnings.

I'll address the first one for `spring-test`.

**Comment by snicoll** [comment]
@sbrannen can we please update the title of this issue as it no longer reflects the original intention.
