### ISSUE TITLE
Spring CLI cannot find main class after installing

### ISSUE THREAD

**Issue by RshStone** [spring-projects/spring-framework#26971]
Hi. I'm new to learn spring. And I learn it with the document on spring.io, which is [the url](https://docs.spring.io/spring-boot/docs/2.5.1-SNAPSHOT/reference/html/getting-started.html#getting-started).
I read part `3.2.1. Manual Installation ` and met a problem.
I have JDK 1.8, and apache-maven 3.8.1 on Windows 10 Home, 20H2. I download the spring framework spring-2.5.0 and spring-2.5.1-SNAPSHOT. I try both of them.
I met some problems with the environment system variables set. I follow the guide but with problems `C:\Users\ASUS>spring
Error: Could not find or load main class org.spring framework.boot.loader.JarLauncher`.
I try to search for information about this problem but little satisfying result. My problem is similar to the question on StackOverflow [Spring CLI cannot find main class after installing](https://stackoverflow.com/questions/59905353/spring-cli-cannot-find-main-class-after-installing/67680336#67680336)
I edit `Path` with `%SPRING_HOME%\bin` on `System Variables`.
![image](https://user-images.githubusercontent.com/62530115/119424837-d0925000-bd38-11eb-85b2-019d9669cd38.png)
I also set the Variable `SPRING_HOME` and the Value the path of bin `D:\Downloads\spring-2.5.0\bin`.
![image](https://user-images.githubusercontent.com/62530115/119425000-28c95200-bd39-11eb-8aa2-cd6e33e2438b.png)
Thank you!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
