### ISSUE TITLE
How to generate bytecode file of proxy class

### ISSUE THREAD

**Issue by huifer** [spring-projects/spring-framework#26972]
How to generate a proxy class to a folder in spring

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

Regarding proxies created by Spring using CGLIB, the core Spring Framework does not provide any mechanism for exporting the generated bytecode to a file.
