### ISSUE TITLE
How can i send zip file content to body of webclient

### ISSUE THREAD

**Issue by ShubhaKV** [spring-projects/spring-framework#27134]
Hi,

I need to send the content of zip to post method.
Here byte[] is the binary file i uploaded in postman

public String publishZipFile(byte[] data) {

    System.out.println(data.length);

	String channelResp =null;
			webClientBuilder
			.build()
			.post()
			.uri("/appCatalogs/teamsApps")
			.headers(httpsHeader -> httpsHeader.addAll(headerMap))
			.syncBody(data)
			.retrieve()
			.bodyToMono(byte[].class)
			.block();
	
	
	return  channelResp;
	
}
Anything wrong am doing here.
Pls help me how i can send zip file content to body of webclient

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
