### ISSUE TITLE
webflux  send http get request garbled

### ISSUE THREAD

**Issue by ai-chips** [spring-projects/spring-framework#27137]
When I use webflux to send requests , If the request contains Chinese without URL encoding, it will be garbled.
eg: 
     client  curl  info    :  "curl http://localhost:8689/api/search/v1?query=北京&appkey=ABCD456F653E15B424C39FBCF9F7F081"
     Server error info  :  "org.springframework.http.server.reactive.ReactorHttpHandlerAdapter - Invalid URL for incoming request: Illegal character in query at index 43: http://localhost:8689/api/search/v1?query=åäº¬&appkey=ABCD456F653E15B424C39FBCF9F7F081"

How can I solve this problem?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

You can also have a look at [the URI building / encoding section in our reference documentation](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-uri-building).
