### ISSUE TITLE
How to set DefaultListableBeanFactory#allowEagerClassLoading property

### ISSUE THREAD

**Issue by yaoyuandota** [spring-projects/spring-framework#27178]
hello, i want to know how to set DefaultListableBeanFactory#allowEagerClassLoading value. I user spring + springmvc. I know have a public method "setAllowEagerClassLoading", but i do not know where to use it

**Comment by sbrannen** [comment]
How does your application create its `ApplicationContext`?

In any case, you would need to extend the `ApplicationContext` you are using and override the `org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory()` method in order to invoke `setAllowEagerClassLoading(boolean)` on the `DefaultListableBeanFactory`.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
