### ISSUE TITLE
Use flux to response garbled code

### ISSUE THREAD

**Issue by Dogs-toeight** [spring-projects/spring-framework#27244]
Version about spring-boot 2.5.1.
Do I have a problem learning how to use webFlux: 
I use Flux.fromStream() to get datas, datas garbled.
I try to set produces = "text/event-stream;charset=UTF-8", but useless.
My code on this pictures:
![image](https://user-images.githubusercontent.com/33596244/128288885-c9c785ef-3917-407c-b344-bf0c96d5a7e7.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Dogs-toeight** [comment]
> Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Ok, Thanks.

**Comment by rong-jw** [comment]
The problem here is that Spring uses the to convert the into the http response body. This converter defaults to the charset, even though is required by specification when you use StringHttpMessageConverterFlux<String>ISO-8859-1UTF-8produces = "text/event-stream"
in org/springframework/http/converter/StringHttpMessageConverter.java:51

     ...
     public static final Charset DEFAULT_CHARSET = StandardCharsets.ISO_8859_1;
     ...


You can do this:

@Configuration
 public class WebConfig implements WebMvcConfigurer {

   @Override
   public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
       converters.stream()
               .filter(converter -> converter instanceof StringHttpMessageConverter)
               .forEach(converter -> 
                    ((StringHttpMessageConverter) converter)
                         .setDefaultCharset(StandardCharsets.UTF_8));
   }
 }

**Comment by bclozel** [comment]
@rong-zhi-yi I believe this different. This issue was about using Server Sent Events with WebFlux, whereas your question is about Server Sent Events with Spring MVC. I don't think you necessarily need to change the default charset of all converters. When using the `SseEmitter` with MVC, you should be able to tell which media type to use when writing a "data" event. If you tell SSE to write a `String` as `text/plain;charset=UTF-8`, the String converter should encode the String events accordingly.

If this does not work for you, please create a new issue with a minimal sample application that reproduces the problem.
