### ISSUE TITLE
Link Multiplexing Problem After Reconnection

### ISSUE THREAD

**Issue by omercelikceng** [spring-projects/spring-framework#27255]
I am using;
* RabbitMQ Websocket with Spring Integration for backend; (spring-boot-starter-parent : 2.3.0.RELEASE, spring-cloud-dependencies : Hoxton.SR5)
* **"react-stomp 5.1.0"** at frontend

I am trying to make it work. I installed RabbitMQ cluster with 3 instances. 

My issue is : If I close one of the instance in the cluster, my websocket connections get multiplexed. 

What's the point I am missing if exists? Can anyone help me?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by omercelikceng** [comment]
Ok I will try to understand the problem. Thank you so much. If I have more information, I'll inform you.
