### ISSUE TITLE
Upgrade to AspectJ 1.9.8

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#27416]
This is the first version that officially supports JDK17 source and target compatibility level (see eclipse/org.aspectj#79).

Right now, we've downgraded the language level to 1.8 in aspectj Gradle tasks. Closing this issue would involve reverting the changes to the `compileAspectj` and `compileTestAspectj` tasks in `spring-aspects.gradle`.

**Comment by jhoeller** [comment]
We're tracking the AspectJ 1.9.8 RCs in #27537 (for 6.0 M1), so I'm repurposing this ticket for AspectJ 1.9.8 GA (in 6.0 M2).

**Comment by sbrannen** [comment]
Related Issue:

- #27935

**Comment by philjoseph** [comment]
Hello AspectJ team, so is the GA for version 1.9.8, that will be the first GA for Java 17, currently depending on the optimization @sbrannen mentioned 25 days ago ?

**Comment by kriegaex** [comment]
No @philjoseph, that optimisation is already merged. Actually, we had stable versions for 1.9.8 - currently RC3 - for a long time and could have declared any of them final. Actually, I wanted to celebrate my committer status for AspectJ by cutting the release, even though technically it is not necessary, because I can already deploy to Maven Central ob behalf of the organisation. I just cannot directly commit and always have to trigger Andy Clement to merge my PRs for every little commit. Because internal Eclipse processes are rather Byzyntine, I still do not have committer status for AspectJ proper (only for AJDT), so I simply did not "push the release button". Sorry to have no more exciting (feature-wise) or better justified excuse for you. Maybe I should just deploy a release. For further oprimisations (Andy fixed a few minor bugs since 1.9.8.RC3), there is always the next release. But if you simply want to use Java 17, just use RC3.

**Comment by kriegaex** [comment]
Release 1.9.8 is out, see also https://github.com/eclipse/org.aspectj/pull/121 and the message I sent to the AspectJ users mailing list. Quote:

> Dear AspectJ users,
> 
> we have just released 1.9.8 (yes, finally). It is [available on Maven Central](https://repo1.maven.org/maven2/org/aspectj/aspectjtools/1.9.8/) already. The AspectJ installer can be found on [Aspectj.dev](https://aspectj.dev/maven/org/aspectj/installer/1.9.8/).
> 
> For more information, please read the [release notes](https://htmlpreview.github.io/?https://github.com/kriegaex/org.aspectj/blob/4b9d86acd096e5ee9e108ff0a450c420c880b6ea/docs/dist/doc/README-198.html).
> 
> See [AspectJ GitHub issue #95](https://github.com/eclipse/org.aspectj/issues/95) for more information and for an example project showing how to upgrade to the latest AspectJ version when using [dev.aspectj:aspectj-maven-plugin:1.13.1](https://github.com/dev-aspectj/aspectj-maven-plugin).
> 
> Enjoy AspectJ!
> 
> The AspectJ team

**Comment by snicoll** [comment]
FTR we've decided to backport this to `5.3.x` as well, see #28060
