### ISSUE TITLE
Drop RPC-style remoting: Hessian, HTTP Invoker, JMS Invoker, JAX-WS

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#27422]
Since most of our RPC-style remoting support has been officially and/or effectively deprecated for several years, let's remove it for 6.0 M1 right away (which also reduces subpackage overload in several modules a bit).

**Comment by knoobie** [comment]
@jhoeller Are there any recommended strategies documented by Spring how to get JAX-WS working with the latest Spring Framework / Boot again? Especially removal of `ignoreResourceType("javax.xml.ws.WebServiceContext");` breaks integration with CXF 4.0 by default if `WebServiceContext`is injected as `@Resource` with no clear migration path how to overcome this.

**Comment by snicoll** [comment]
As stated above, it's been deprecated for several years and now removed so we can't recommend anything about those.

**Comment by knoobie** [comment]
@snicoll Thanks for your comment! I'm aware of the deprecating and removal of RPC-style remoting (I'm totally find with that). I just came across this commit because it also removed JAX-WS "Integration" which I think is not deprecated and still heavily used. For example from the CXF 4 / Jakarta 9+ Migration, there is this open issue that lead me to this change: https://issues.apache.org/jira/browse/CXF-8666

My current workaround is to customize the `CommonAnnotationBeanPostProcessor`and re-introduce the deleted line. 

```java
@Configuration
public class WorkaroundForCxfConfig {

  @Autowired
  private CommonAnnotationBeanPostProcessor processor;

  @PostConstruct
  public void initialize() {
    processor.ignoreResourceType("jakarta.xml.ws.WebServiceContext");
  }
}
```

**Comment by Osmanbell** [comment]
yes
