### ISSUE TITLE
Upgrade to AspectJ 1.9.8 for official Java 17 support

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#27537]
## Overview

AspectJ 1.9.8 RC1 was [released](https://github.com/eclipse/org.aspectj/issues/79#issuecomment-938499393) today, so we'll start testing against that and upgrade to 1.9.8 GA once it's been released.

## Resources

- preliminary [release notes](https://htmlpreview.github.io/?https://github.com/eclipse/org.aspectj/blob/29b024efe4cb4db803103aa099d60b9bc85bac6c/docs/dist/doc/README-198.html)

## Deliverables

- Upgrade to AspectJ 1.9.8 GA
- Add note to reference manual regarding changes to LTW support (see AspectJ 1.9.8 release notes for details)

**Comment by kriegaex** [comment]
Thanks for adopting the new AspectJ version so quickly. I am looking forward your feedback. Not knowing what the minimum Java version is in your build system and also for native AspectJ LTW, please note the following caveat:

The Eclipse Java Compiler (ECJ) 3.2.7 supporting Java 17 now needs JDK 11+ as a build environment, because Eclipse migrated the code base to Java 11. Because the AspectJ Compiler (AJC) contained in `aspectjtools` is an ECJ fork, using a Java-17-enabled AJC version (1.9.8.RC1 and higher) means that you need to run your build on JDK 11+. You can still compile to goals as low as Java 1.3, don't worry. It is only about the build environment. I am not sure if you even use AJC or depend on the AspectJ Tools library anywhere, please check.

As for LTW, I just verified that for now, the class files contained in the smaller `aspectjweaver` agent library still do not contain Java 11 class files, i.e. LTW should still work on JDK 8 systems.

**Comment by sbrannen** [comment]
> Thanks for adopting the new AspectJ version so quickly. I am looking forward to your feedback. 

You're welcome. We're glad to help integration test with the RC before the GA release.

Our build is working fine with the changes in fa3a2dc98142d397c8394e93d79749f345c149a7.

> Not knowing what the minimum Java version is in your build system, please note the following caveat:

For Spring Framework 6.0 (`main`), Java 17 is the baseline for the build and any applications using Spring 6.0.

**Comment by jhoeller** [comment]
I'm about to close this issue with an upgrade to AspectJ 1.9.8 RC3 (for 6.0 M1). We can track the AspectJ 1.9.8 upgrade in #27416 then.
