### ISSUE TITLE
Autowiring a bean of type Map will inject different values for 2 identical JUnit tests

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-framework#27542]
**Affects:** `5.3.10` with Java `11`

I know that Spring Framework has a special relationship in regards to injecting Maps. I have a JUnit test where I am encountering a strange injection behavior, though.

See JUnit test case: https://github.com/ghillert/spring-di-with-maps/blob/main/src/test/java/com/hillert/spring/maps/AutowiredMapInjectionTests.java

I am declaring a single bean of type `Map<String, Object>` (used by 2 tests) that gets injected using `@Autowired` and  `@Qualifier("myMapBean")` annotations. Both tests use the same autowired dependency of the map but the injected value of  the dependency is different. The second test should see the injected bean, as does the first test, NOT the value of the underlying map. Thus, when I change the execution order of the tests, they will both fail. Is this somehow expected behavior or possibly an issue?

**Comment by SpiReCZ** [comment]
I have found something that may be related or it is a separate bug regarding DI of Maps. I would surely like it to be fixed.

Spring: `5.3.18` (Spring Boot: `2.6.6`)
TestNG: `7.5`
Java: `11`

[Spring 5 + XML context + TestNG = wrong type injected: ServiceA3XmlTest.java](https://github.com/SpiReCZ/spring5-map-di-testng/blob/main/src/test/java/test/autowiremap/test/ServiceA3XmlTest.java)

`factoryGroupsA_fails` test fails because wrong type is injected. This happens in combination of using:
- XML context definition
- TestNG (... extends AbstractTestNGSpringContextTests)

In our Application we use bare Spring 5. Only thing that is different in the example test demo is that it uses Spring Boot (we don't in this case). 

Expected type: `Map<String, Map<String, MyServiceFactory>>`
Injected type: `Map<String, Map<String, Map<String, MyServiceFactory>>>`

ServiceA3XmlTest.java:
```java
package test.autowiremap.test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;
import test.autowiremap.service.MyServiceFactory;

import java.util.Map;

@Test
@ContextConfiguration(locations = {"classpath:context.xml"})
public class ServiceA3XmlTest extends AbstractTestNGSpringContextTests {
    @Autowired
    @Qualifier("xmlFactoryMap")
    private Map<String, Map<String, MyServiceFactory>> factoryGroupsXml;
    @Autowired
    @Qualifier("xmlFactoryMap")
    private Object factoryGroupsXmlObject;

    @Test
    public void factoryGroupsA_fails() {
        // Throws NullPointerException due to different data type
        MyServiceFactory myServiceFactory = factoryGroupsXml.get("xmlGroup").get("xmlFactory");
        System.out.println(myServiceFactory);
    }

    @Test
    public void factoryGroupsA_working() {
        var factoryGroupsXmlObject = (Map<String, Map<String, MyServiceFactory>>) this.factoryGroupsXmlObject;
        MyServiceFactory myServiceFactory = factoryGroupsXmlObject.get("xmlGroup").get("xmlFactory");
        System.out.println(myServiceFactory);
    }
}
```

**Comment by snicoll** [comment]
It's odd but I can't reproduce it with a recent JDK. Sorry this got overlooked.

**Comment by SpiReCZ** [comment]
@snicoll Might be worth checking the linked issue.
