### ISSUE TITLE
Bean scope "websocket" not available using rsocket messaging

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-framework#27631]
I'm trying to port an app to rsocket over websocket messaging because the kind of interaction required should be ideal for this very promising standard.

The problem is that I'm unable to define a bean with a scoped property of websocket like I usually do with STOMP.
The error I get is:
> java.lang.IllegalStateException: No Scope registered for scope name 'websocket'

Since there is no "rsocket" scope I wonder how could I correctly use beans like when using websockets/stomp.

**Comment by mrcljx** [comment]
Related: #28235

**Comment by jhoeller** [comment]
As with #28235: Since there is no technical interaction between the core container `Scope` mechanism and the reactive pipelines in RSocket endpoints, we are not able to provide direct support for an equivalent `Scope`. Any such scoped attributes will have to be programmatically added to the reactive pipeline in the endpoints instead. If there is anything we can do to make such a programmatic arrangement more convenient, feel free to create a separate issue for it.
