### ISSUE TITLE
When using HandshakeInterceptor with ServerHttpAsyncRequestControl, Jetty10RequestUpgradeStrategy throws exception due to null servletContext

### ISSUE THREAD

**Issue by ajr3-gen** [spring-projects/spring-framework#27653]
We are upgrading our project from Jetty v9 to v10 and have encountered a problem with the new spring-boot Jetty implementation.

Our WebSocketController includes a custom HandshakeInterceptor.  In the beforeHandshake() method, we use this line:
```
        ServerHttpAsyncRequestControl requestControl = request.getAsyncRequestControl(response);
        requestControl.start();
```
so that we can authorize the request before completing it.  We do that authorization in a separate thread and then call DefaultHandshakeHandler to complete the handshake:
```
        handshakeHandler.doHandshake(request, response, wsHandler, attributes);
        requestControl.complete();
```
while the beforeHandshake method exits on the main thread.

This worked fine with Jetty v9 (which is implemented in spring-boot via the class `org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy`).  However, with Jetty v10 (which uses a new class: `org.springframework.web.socket.server.jetty.Jetty10RequestUpgradeStrategy`), there is a NullPointerException.  This is because Jetty10RequestUpgradeStrategy uses reflection to invoke `JettyWebSocketServerContainer getContainer(ServletContext servletContext)` which tries to resolve an attribute from the request's servletContext -- **but servletContext has now been cleared out** as we have exited the beforeHandshake() method on the main thread.

I confirmed this by adding a Thread.sleep() to our beforeHandshake() method to delay it from returning for a couple of seconds, and this allowed the thread with DefaultHandshakeHandler to complete.  Without this delay, we catch this error and the handshake does not complete:
`    org.springframework.web.socket.server.HandshakeFailureException: Failed to upgrade; nested exception is java.lang.NullPointerException`

Versions used:
spring.boot = 2.5.6
jetty.version = 10.0.6
spring.framework = 5.3.12

**Comment by ajr3-gen** [comment]
Has anyone had a chance to look into this issue yet?  Our upgrade to Jetty v10 is on hold waiting for this.  Thanks.

**Comment by ajr3-gen** [comment]
@snicoll  @rstoyanchev  Can I please get someone to look at this?  We're going to have to upgrade to Jetty v10 eventually, and I'd like to get this blocking issue resolved before it becomes urgent.  Thanks.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ajr3-gen** [comment]
Thanks for getting back to me.  I'm afraid I'm having some trouble seeing the solution, though.  One of your suggestions is to block for the authentication, but I don't want to do that because it defeats the point of being asynchronous.  You also suggested a redirect, but (a) we don't want to change the behavior our clients are expecting, and (b) websocket clients aren't guaranteed to honor redirects (according to this: https://stackoverflow.com/questions/46962881/is-it-possible-to-seamlessly-redirect-websockets).

That leaves the third option, of dispatching to the same URL through the Servlet API.  I tried that, but it just caused a loop that exhausted memory, so either it doesn't work or I am not following what you had in mind.  Maybe you could expand on that?

I will say that `ServerHttpAsyncRequestControl` seemed like the right thing to use here, based on its brief description in the API Javadoc:  "A control that can put the processing of an HTTP request in asynchronous mode during which the response remains open until explicitly closed."  That's what we're doing here, and it _did_ work with Jetty9.

**Comment by rstoyanchev** [comment]
The Java/Jakarta EE WebSocket API did not make it possible to initiate a WebSocket handshake at runtime and we've had to find ways to do it on each container. The way we did it on Jetty 9 made it possible to do what you want to do. However, the Jetty WebSocket API in Jetty changed significantly from 9 to 10, and we had to change too, even request an API change to enable what we needed to do, see https://github.com/eclipse/jetty.project/issues/5866. Now we're using the only API that we can and the upgrade requires access to the `ServletContext`. You can [see the same](https://github.com/spring-projects/spring-framework/blob/50973f73c70723198752d6ded3ad6af2c05b5674/spring-websocket/src/main/java/org/springframework/web/socket/server/jetty/JettyRequestUpgradeStrategy.java#L66-L100) in the `main` branch which compiles against Jetty 10 and hence does not need reflection. It is the same there, i.e. this is not related to the use of reflection.

I'm afraid I don't know what else we can do about this. It's the only mechanism we have to use, and I don't know what your application does with WebSocket (STOMP, raw WebSocket, etc) to be able to suggest other changes like using WebFlux or otherwise dropping on a lower level.

**Comment by ajr3-gen** [comment]
Thanks for the feedback.  I guess we'll have to try to figure something else out.  I may have more questions as we work at it, but for now it seems clear that the current logic won't work with Jetty 10.

**Comment by rstoyanchev** [comment]
Okay, I'm closing for now, but feel free to add comments if needed.
