### ISSUE TITLE
@RequestBody inject field failed when the field name conform to a form like 'aType'

### ISSUE THREAD

**Issue by CPJIE** [spring-projects/spring-framework#27693]
Here is a example:

```java
// AController.java
@PostMapping
public String add(@RequestBody @Validated Form form) {
        ...
}
```

```java
// Form.java
@Data
public class Form {
    private String aType;
    private String bAbc;
    private Integer cDef;
}
```

request:
```json
{
  "aType":"123",
  "bAbc":"abc",
  "cDef":1
}
```
![0](https://user-images.githubusercontent.com/59378056/142170402-feea0df3-4614-4ba6-97c8-9b1b111bf475.png)

All of the field in object 'from' will be null.

**Comment by xixingya** [comment]
because jackson default use legacyManglePropertyName this logic is 

After removing set, the first letter set lowercase,

After the second letter is lowercase, compare it with the lowercase of the second letter. If it is all lowercase, then directly connect it and return,

If the second letter is capitalized, use the lowercase case, connect it, and look for the next letter until you find a lowercase letter.

you can use @JsonProperty("aType") fix it, or use gson etc.

**Comment by napoleon-he** [comment]
spring allows you to customize HttpMessageConverters and replace the default configuration of the framework

**Comment by CPJIE** [comment]
> because jackson default use legacyManglePropertyName this logic is
> 
> After removing set, the first letter set lowercase,
> 
> After the second letter is lowercase, compare it with the lowercase of the second letter. If it is all lowercase, then directly connect it and return,
> 
> If the second letter is capitalized, use the lowercase case, connect it, and look for the next letter until you find a lowercase letter.
> 
> you can use @JsonProperty("aType") fix it, or use gson etc.

ok,thanks

**Comment by CPJIE** [comment]
> spring allows you to customize HttpMessageConverters and replace the default configuration of the framework

ok,thanks
