### ISSUE TITLE
charset=UTF-8 appended to application/x-www-form-urlencoded 

### ISSUE THREAD

**Issue by DaveDunne** [spring-projects/spring-framework#27737]
Hey everyone,
So for a top tier telco comnpany I am trying to integrate and set CONTENT_TYPE in my request .. in many ways however server rejects as 

application/x-www-form-urlencoded;charset=UTF-8 

is sent instead of

application/x-www-form-urlencoded which is all that is accepted ( I have confirmed this with another Java program ) 

i.e. webflux

  .header(HttpHeaders.CONTENT_TYPE, "application/x-www-form-urlencoded")
                    . contentType(MediaType.APPLICATION_FORM_URLENCODED)

etc. I have tried coding around this. Can you tell me if there is a workaround as I need one urgently 

org/springframework/spring-webflux/5.3.9/spring-webflux-5.3.9.jar
org/springframework/spring-web/5.3.9/spring-web-5.3.9.jar
org/springframework/spring-core/5.3.9/spring-core-5.3.9.jar
org/springframework/spring-web/5.3.9/spring-web-5.3.9.jar!/org/springframework/http/codec/FormHttpMessageWriter.class

	protected MediaType getMediaType(@Nullable MediaType mediaType) {
		if (mediaType == null) {
			return DEFAULT_FORM_DATA_MEDIA_TYPE;
		}
		else if (mediaType.getCharset() == null) {
			return new MediaType(mediaType, getDefaultCharset());
		}
		else {
			return mediaType;
		}
	}

Can you tell me if there is a workaround?

Dave

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
