### ISSUE TITLE
A Question about default tag parsing

### ISSUE THREAD

**Issue by mingwang01** [spring-projects/spring-framework#27940]
**Affects:** 5.2.8

```java
package org.springframework.beans.factory.xml;
	@Nullable
	public BeanDefinitionHolder parseBeanDefinitionElement(Element ele) {
		return parseBeanDefinitionElement(ele, null);
	}
```

This `BeanDefinition` parameter is always `null`, and it is impossible to find the case that this parameter is not empty, then whether this parameter is a meaningless judgment.

**Comment by mingwang01** [comment]
This BeanDefinition parameter is always null, and it is impossible to find the case that this parameter is not empty, then whether this parameter is a meaningless judgment

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

In any case, `org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseBeanDefinitionElement(Element, BeanDefinition)` is not always invoked with `null` for the containing `BeanDefinition`.
