### ISSUE TITLE
spring MVC params issues

### ISSUE THREAD

**Issue by shootday** [spring-projects/spring-framework#28034]
When spring MVC receives a string type parameter in the controller's method, the requested URL and form data have this parameter at the same time, and the back-end will merge the parameters received

![image](https://user-images.githubusercontent.com/39784893/153531581-b41e9425-ce10-4ce0-9c78-3d8c11d7bb47.png)
![image](https://user-images.githubusercontent.com/39784893/153531608-c92d5e40-a4d9-41ca-8cb2-9755ffa00d5c.png)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
