### ISSUE TITLE
Upgrade to AspectJ 1.9.8

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#28060]

**Comment by snicoll** [comment]
Given that AspectJ requires Java 11 at build-time, I am going to stick with `1.9.7` for now. If we decide to upgrade in the `5.3.x` line, we'll have either to use Java11 to build the project or use the toolchain (which only exists on `main`.

**Comment by kriegaex** [comment]
> Given that AspectJ requires Java 11 at build-time, I am going to stick with `1.9.7` for now.

Yes, this is true for compile-time weaving, because the AspectJ compiler is a fork of the Eclipse Java compiler, which was upgraded to 11 too. So we could not to avoid to have a couple hundred Java 11 class files in AJC's belly, even though we tried to lobby against moving from 8 to 11. AJC can still generate Java 8 files, though, and LTW with `aspectjweaver` also still works on Java 8. I wish it was different, but I think the build-time requirement is the lesser evil and feasible. It is not a limitation for end users who still need Java 8 compatibility when running Spring. I hope for you that the toolchain thing or the Java 11 upgrade for the build system is not going to be much of an effort or serious limitation for you and your team.
