### ISSUE TITLE
Use exception type information instead of pattern matching for transaction rollback rules

### ISSUE THREAD

**Issue by hduyyg** [spring-projects/spring-framework#28098]
Source code in question：

```java
private int getDepth(Class<?> exceptionClass, int depth) {
	if (exceptionClass.getName().contains(this.exceptionName)) {
		// Found it!
		return depth;
	}
	// If we've gone as far as we can go and haven't found it...
	if (exceptionClass == Throwable.class) {
		return -1;
	}
	return getDepth(exceptionClass.getSuperclass(), depth + 1);
}
```

test code:

```java
public class CustomException extends Exception {
}

public class CustomExceptionX extends Exception {
}

@Override
@Transactional(rollbackFor = CustomException.class)
public void testTransaction() throws Exception {
    taskMapper.softDeleteById(1, "test");
    if (1 == 1) {
        throw new CustomExceptionX();
    }
}
```

**Comment by sbrannen** [comment]
This is by design and was originally implemented using `contains()` for use in XML configuration files where users often specified the _simple name_ of a custom exception type instead of the _fully qualified class name_.

You can see examples of this in the [reference docs](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-declarative-rolling-back).

```xml


<tx:advice id="txAdvice" transaction-manager="txManager">
  <tx:attributes>
    <tx:method name="get*" read-only="true" rollback-for="NoProductInStockException"/>
    <tx:method name="*"/>
  </tx:attributes>
</tx:advice>
```

With your proposal to use `equals()` instead of `contains()`, configuration like that would no longer work since `NoProductInStockException` would only ever be equal to the fully qualified class name if the `NoProductInStockException` was declared as a top-level class in the _default_ package -- which is rather unlikely.

Please take note of the [Javadoc for `RollbackRuleAttribute`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/interceptor/RollbackRuleAttribute.html#RollbackRuleAttribute-java.lang.String-) as well:

> **NB**: Consider carefully how specific the pattern is, and whether to include package information (which is not mandatory). For example, "Exception" will match nearly anything, and will probably hide other rules. "java.lang.Exception" would be correct if "Exception" was meant to define a rule for all checked exceptions. With more unusual exception names such as "BaseBusinessException" there's no need to use a fully package-qualified name.

Similar documentation exists for the `rollbackForClassName` attribute in `@Transactional`.

**Comment by sbrannen** [comment]
I retract my previous statement. The Javadoc for the `RollbackRuleAttribute(Class)` constructor is correct.

However, the documentation for rollback rules can be improved to warn that unintentional matches may arise if the name of a thrown exception _contains_ the name of a registered exception type.

I am therefore repurposing this issue to improve the documentation.

**Comment by sbrannen** [comment]
> I think this rollback rule is fallible and needs more precise matching rules。

I agree with you. I've raised #28125 to improve the documentation for `5.3.x`.

And we'll use _this_ issue to improve the behavior in `6.0`.

Specifically:

- If an _exception pattern_ is supplied as a `String` -- for example, in XML configuration or via `@Transactional(rollbackForClassName = "example.CustomException")` -- the existing `contains()` logic will continue to be used.
- If a concrete _exception type_ is supplied as a `Class` reference -- for example, via `@Transactional(rollbackFor = example.CustomException.class)` -- new logic will be implemented which honors the supplied type information, thereby avoiding an unintentional match against `example.CustomException2` when `example.CustomException` (without the `2)` was supplied as the exception type.
