### ISSUE TITLE
spring @Transactional annotation lose efficacy

### ISSUE THREAD

**Issue by zhao190775705** [spring-projects/spring-framework#28128]
## spring version ？
4.3.13RELEASE
## question ？
A service is not TransactionInterceptor  intercepted，cause transactional to fail，all configurations are correct under the same circumstances ，some transactional will take effect
## solution？
`

 @Autowired
 MaterialService materialService;
`
materialService the method inside have question， all add  private  succeed

What kind of question is that？
Looking forward to your reply

**Comment by snicoll** [comment]
Sorry but I don't understand the report and that looks like a question. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
