### ISSUE TITLE
Strict input validation for REST APIs

### ISSUE THREAD

**Issue by donnd-t** [spring-projects/spring-framework#28159]
**Affects:** \5.3.13

---

When I define an API like this:
```java
@RestController
public class MyController {

  @GetMapping
  Me me() {
    ...
  }
  
}
```

I would like to receive an HTTP 400 Bad Request response when passing a parameter e.g. /me?you=notme

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
