### ISSUE TITLE
How could @Caching version be bound to JPA entity version(optimistic lock)?

### ISSUE THREAD

**Issue by nianxiaoyi** [spring-projects/spring-framework#28177]
I use spring @Version for optimistic lock, and I use @Caching to cache the jpa entity. the version in database was auto incremented when the transaction was committed, but the version in cache was not incremented. How could I keep them consistent whenever the transaction is committed or rollback?

**Comment by snicoll** [comment]
I assume you meant `@Cacheable`. The cache abstraction is a straightforward arrangement where objects returned from the method is called. The optimistic locking is the least of your problem here as it would store the whole graph and not a single entity and that will lead to serve you outdated data.

There is a [warning in the doc](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-strategies) about this.

You should use the second level cache of your JPA provider for this. If you have more questions, please follow-up on StackOverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
