### ISSUE TITLE
CustomEditorConfigurer中维护的Map并没有对应关系

### ISSUE THREAD

**Issue by ImUglyZ** [spring-projects/spring-framework#28186]
在使用XMl文件的方式注入属性编辑器的过程中，使用<map><entry key=? value =属性编辑器></map>，我发现map的键和值并不是一一对应的关系，于是找到CustomEditorConfigurer类发现CustomEditorConfigurer中维护的Map并没有对应关系，这个问题意味着，我只需要注入值（属性编辑器）就可以使用

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
