### ISSUE TITLE
Spring Webflux returns Chinese garbled characters on ios

### ISSUE THREAD

**Issue by kukume** [spring-projects/spring-framework#28203]
Spring Webflux returns json with a default response header of Content-Type of application/json, which is fine on browsers such as chrome, but messes up on ios.
On ios when the response header Content-Type returns application/json;charset=UTF-8 there is no problem on ios.
So, can I change the Content-Type of the response header to application/json;charset=UTF-8 on ios?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
