### ISSUE TITLE
while uploading file getting error Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'. 

### ISSUE THREAD

**Issue by emmadavis16** [spring-projects/spring-framework#28239]
i have enabled csrf and send token 
`<input type="hidden" name="${_csrf.parameterName}"value="${_csrf.token}"/>` and still its not working and i have send csrf token from onceperfilter too still it is getting null
```
                CsrfToken token = (CsrfToken) request.getAttribute("_csrf");
	        response.setHeader("X-CSRF-HEADER", token.getHeaderName());
	        response.setHeader("X-CSRF-PARAM", token.getParameterName());
	        response.setHeader("X-CSRF-TOKEN", token.getToken());
```
Any leads will be appreciated 
Thanks in advance

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
