### ISSUE TITLE
Restrict access to property paths on Class references 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#28261]

**Comment by artem-smotrakov** [comment]
Hi @rstoyanchev Does this [address](https://github.com/spring-projects/spring-framework/commit/002546b3e4b8d791ea6acccb81eb3168f51abb15) the recent [vulnerability](https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement) in Spring Framework?

Is Spring Framework 3.x vulnerable? I see the code is quite [similar](https://github.com/spring-projects/spring-framework/blob/v3.2.17.RELEASE/spring-beans/src/main/java/org/springframework/beans/CachedIntrospectionResults.java#L306).

**Comment by dicer** [comment]
@artem-smotrakov  See https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

**Comment by artem-smotrakov** [comment]
Hi @dicer My question is exactly about this announcement :) I am looking for a commit that fixe this issue.

**Comment by artem-smotrakov** [comment]
Hi @jhoeller All valid points, absolutely agree that it would be better to move to 5.3.x

If I understand correctly, this commit fixes the [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965). I'd appreciate if someone for the Spring team confirmed that. Thanks!

https://github.com/spring-projects/spring-framework/commit/002546b3e4b8d791ea6acccb81eb3168f51abb15

**Comment by skydreamerr** [comment]
@bclozel we started to get Exception after upgrade
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'beanClassLoader' of bean class [org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceProxyFactoryBean]: Bean property 'beanClassLoader' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at 
	
	The property has type ClassLoader

**Comment by marcelstoer** [comment]
> Hi @jhoeller All valid points, absolutely agree that it would be better to move to 5.3.x
> 
> If I understand correctly, this commit fixes the [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965). I'd appreciate if someone for the Spring team confirmed that. Thanks!
> 
> [002546b](https://github.com/spring-projects/spring-framework/commit/002546b3e4b8d791ea6acccb81eb3168f51abb15)

I fully agree. I find it irritating that the issues here have no reference to the actual commit (or the other way around). That way you have to dig through the commit history and hope the commit message is the same as or similar enough to the issue title.

I did as you did and arrived at the same commit 👍

**Comment by bclozel** [comment]
@skydreamerr please create a new issue for this.

**Comment by jhoeller** [comment]
@skydreamerr Why is that "beanClassLoader" property being populated through declarative configuration? `setBeanClassLoader` is a programmatic callback that the container itself calls via `BeanClassLoaderAware`, it's not meant to be populated explicitly. Please double-check the property configuration for that bean; maybe that explicit setting can simply be removed so that the container can perform its standard callback?

**Comment by rstoyanchev** [comment]
@marcelstoer normally commits are linked to issues. This was not a normal case.

**Comment by marcelstoer** [comment]
> @marcelstoer normally commits are linked to issues. This was not a normal case.

I understand and appreciate this. Maybe just edit this issue (+ #28262) and add something like "Fixed by 002546b3e4b8d791ea6acccb81eb3168f51abb15"?

**Comment by copernico** [comment]
> Hi @dicer My question is exactly about this announcement :) I am looking for a commit that fixe this issue.

Here you find the commits for both affected release series: https://github.com/SAP/project-kb/blob/vulnerability-data/statements/CVE-2022-22965/statement.yaml

**Comment by kennymacleod** [comment]
> @skydreamerr Why is that "beanClassLoader" property being populated through declarative configuration? `setBeanClassLoader` is a programmatic callback that the container itself calls via `BeanClassLoaderAware`, it's not meant to be populated explicitly. Please double-check the property configuration for that bean; maybe that explicit setting can simply be removed so that the container can perform its standard callback?

`BeanClassLoaderAware` is being used by the Felix OSGi framework, so I can see they may have a legitimate use for `BeanClassLoaderAware`. In this particular case, the fix for the CVE seems to be breaking pre-existing and valid functionality.

**Comment by bclozel** [comment]
@kennymacleod please follow up on the dedicated issue here #28269, or create a new one if you believe your case is different.
What Juergen is merely pointing out here, is that the core container will honor this contract and that property configuration is not needed for this property.

**Comment by jhoeller** [comment]
@kennymacleod I'm sure it's a valid use case for `BeanClassLoaderAware` itself but that container callback is meant to only be called by the container itself, not specified via declarative user configuration. That's the part I'd like to understand, there is either double configuration here - or accidental overriding since the container will perform its standard `setBeanClassLoaderAware` call even when user configuration was passed into the same property before. Let's find out whether this is accidental for that specific OSGi setup scenario and whether it even had the intended effect before.

That said, as per my recent comment on #28269, we are aware that this is technically a regression for isolated declarative configuration cases, as a side effect of a defensive security measure. If there are common scenarios where this regression remains unresolvable, we might specifically enable certain ClassLoader configuration scenarios again in a follow-up Spring Framework release.

**Comment by Enerccio** [comment]
Are you sure that only Java 9+ is affected. By current attack vector, sure, but couldn't there be another one?

**Comment by jhoeller** [comment]
To the best of our understanding, from a Spring perspective, this is indeed a Java 9+ only attack vector. It's essentially revisiting an old Class property attack vector that we closed for Java 6-8 many years ago, not having had any follow-ups in the meantime, now reopened at this late point for the unnoticed Java 9+ introduction of `Class.getModule().getClassLoader()`.

That said, our new defensiveness checks in Spring's property descriptors cover any access to ClassLoader properties, on any JDK versions. We do recommend an upgrade to the latest framework version for defensiveness against unknown attack vectors, even on JDK 8, it is just not a necessary step to take for the present CVE with its Java 9+ attack vector.

Last but not least, since the present issue is about access to public facilities on Tomcat's ClassLoader implementation, we also strongly recommend an upgrade to the just-released Tomcat patches, in particular for attack vectors outside of Spring.

**Comment by grubeninspekteur** [comment]
The current fix restricts access to class properties ending in "Name". While this closes the present time vulnerability, there is a small, but nonzero probability a future Java version introduces another dangerous property whose name just happens to end in "Name". Shouldn't we restrict access further, either by whitelisting the exact names of all known safe Java 17 properties, or limiting to those with a String return type?

**Comment by bclozel** [comment]
@grubeninspekteur as you can imagine, this has been a stressful week for the Spring community. Discussing publicly the effectiveness of the fix and potential security issues is not the responsible way to share your concerns.

Please use the dedicated channels for that: https://spring.io/security-policy

**Comment by jhoeller** [comment]
@grubeninspekteur Point taken, we might slightly revise the check to refer to the String return value as well, not least of it all for clarity of the code. This won't make a difference in terms of the current effectiveness on all existing versions of Java, and I don't think it would be responsible for any future Java version to ever introduce a non-String property on Class ending with "Name", but we'll take that code revision into consideration along with the #28269 revision that we'll do for 5.3.19 this week.

That said, generally speaking, we should not be discussing the effectiveness of security measures here on GitHub indeed. In all other respects, feedback on code improvements is always welcome.

**Comment by grubeninspekteur** [comment]
@bclozel Of course, the workload caused by the irresponsible disclosure of the vulnerability last week must have been immense and as Spring users we are grateful for your quick actions. I understand your policy of not discussing these matters publicly and have removed my comment.

**Comment by JKAK47** [comment]
你好，已收到你的邮件！我尽快回复。
