### ISSUE TITLE
Unable to disable decoding Path Parameter in RestController

### ISSUE THREAD

**Issue by taoj-action** [spring-projects/spring-framework#28371]
Using Spring-Boot 2.3.12, we followed the solution on https://github.com/spring-projects/spring-framework/issues/20211 and add 

`server.undertow.decode-url: false`

to disable request decoding. The request mapping is:

`/foo/{id}/bar/{value}`

After the following GET request, the request reach to REST controller.

`GET /foo/83115320/bar/test+%2B-%2F%3A%3D_`

We would expect the value inside the controller is kept as-is due to disabled decoding:
`test+%2B-%2F%3A%3D_`

However, we actually get something like the following which has been decoded:
`test++-/:=_`

I debugged into the code and the decoding happens around org.springframework.web.method.annotation:
`	Object arg = resolveName(resolvedName.toString(), nestedParameter, webRequest);`

the request URI inside webRequest has not changed.

**Comment by taojwmware** [comment]
When running a unit test using @WebMvcTest(), the value is not decoded. Auto-decode only happens when running the application.

**Comment by quaff** [comment]
Spring Boot use `tomcat`  by default, please ensure you are using `undertow`.

**Comment by taojwmware** [comment]
Yes, we are using undertow.
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-undertow'
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
```

**Comment by taojwmware** [comment]
I found a workaround by customizing the UrlPathHelper. 
```
    @Override
    public void configurePathMatch(PathMatchConfigurer configurer) {
        UrlPathHelper urlPathHelper = new UrlPathHelper() {
            @Override
            public Map<String, String> decodePathVariables(HttpServletRequest request, Map<String, String> vars) {
                return vars;
            }
        };
        urlPathHelper.setUrlDecode(false);
        configurer.setUrlPathHelper(urlPathHelper);
    }
```
Although it is ideal, it works. I Hope the Spring community can come out with a better solution! Thanks!

**Comment by rstoyanchev** [comment]
This is by design, for all types of controller method parameters, to be passed in decoded form. You can re-encode it with [UriUtils](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/util/UriUtils) if it's in a small number of places. Alternatively, you could also extend [PathVariableMethodArgumentResolver](https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/PathVariableMethodArgumentResolver.java) to support a custom annotation such as `@EncodedPathVariable`. You can override the `resolveName` method to re-encode the value.
