### ISSUE TITLE
Move class Operation into package org.springframework.expression.spel.ast, class SpringVersion into package org.springframework.lang.

### ISSUE THREAD

**Issue by ysyim** [spring-projects/spring-framework#28378]
Hi, @snicoll  @poutsma 

**_Issue Description_**

Package **_org.springframework.expression_**, **_org.springframework.core_** are a promiscuous package, and groups together miscellaneous functionalities that might be useful to different subsystems. The package structure violates the “high cohesion and low coupling” design rules. I found that Class **_Operation_**, **_SpringVersion_** is not used by classes in their package. The project has grown larger, leading to becoming increasingly hard to maintain. During the development process, one groups together classes (that often co-change) with similar responsibilities in one package to facilitate maintenance, which prevents a change that causes other packages to be modified. For example, if one modifies package **_org.springframework.expression_** (i.e., package rename), resulting in multiple classes of package **_org.springframework.expression.spel.ast_** to be changed.

Location: The source file can be found at path File  spring-expression/src/main/java/org/springframework/expression/Operation.java
spring-core/src/main/java/org/springframework/core/SpringVersion.java

**Refactoring suggestions**

I suggest to move class **_Operation_** into package **_org.springframework.expression.spel.ast_**, class **_SpringVersion_** into package **_org.springframework.lang_**.

<img width="400" alt="springframework-Operation-java" src="https://user-images.githubusercontent.com/104186731/165103966-2217234a-a4e7-43a8-a2b9-490f5f2e11e3.png">
<img width="420" alt="springframework-SpringVersion-java" src="https://user-images.githubusercontent.com/104186731/165103984-4f9c5c40-7e8e-47f2-bb06-66630e38077c.png">

**Comment by poutsma** [comment]
We strive to maintain backwards compatibility in Spring Framework, even between major release. And because of the migration to Jakarta artefacts in the upcoming version 6.0, we do have more options with regard to refactoring than we typically do.

But moving `Operation` and `SpringVersion` to a different package is still going to upset people dependant on those types. With so many projects dependant on Spring, we can only make breaking changes like that with a very good reason. I don't think the violation of a coupling rule is a good enough reason.
