### ISSUE TITLE
Add Throwable functional interfaces

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#28417]
Within the framework and portfolio projects we often need to deal with checked exceptions inside the body of a `Function`, `Supplier`, `Consumer`, etc. This usually involves writing `try`/`catch` blocks inside the body. Since exception handling is usually also handled by the framework, it would be nice if we could offer `Throwing...` versions of common functional interfaces that do the wrapping for us.

**Comment by quaff** [comment]
Please consider throwing generic exception like this
```java
@FunctionalInterface
public interface CheckedFunction<T, R, E extends Throwable> {

	R apply(T t) throws E;

}
```

**Comment by sbrannen** [comment]
@quaff, can you please expound on your proposal with a rationale for needing the generic type declaration for the exception?

**Comment by sbrannen** [comment]
> it would be nice if we could offer `Throwing...` versions of common functional interfaces that do the wrapping for us.

I agree: such types can be very useful.

I also agree with the `Throwing*` naming convention. Though I noticed you've introduced `Throwable*` types in your commit.

I think we should go with `Throwing*`. For example, `ThrowableSupplier` implies that the supplier supplies a `Throwable`, like a `StringSupplier` would supply a `String`. 

Furthermore, the `Supplier` itself is not "throwable" since it does not implement `Throwable`.

What we're really talking about is a "supplier that is capable of throwing a checked exception", but we cannot convert that to a type name because it's simply too long: `CheckedExceptionThrowingSupplier`. If we go with `ThrowingSupplier`, that's succinct and in line with the naming convention used in several other open source projects -- for example, Spring Data, JUnit, AssertJ, Kotlin internals, some JDK internals, [etc.](https://www.google.com/search?q=%22ThrowingSupplier%22).

**Comment by quaff** [comment]
> @quaff, can you please expound on your proposal with a rationale for needing the generic type declaration for the exception?

@sbrannen  For example we can throw Throwable inside lambda
```java
@Aspect
public class Instrumentation {

	@Around("execution(* *.*(..))")
	public Object timing(ProceedingJoinPoint pjp) throws Throwable {
		return Tracing.execute(pjp, ProceedingJoinPoint::proceed);
	}
}
```
```java
public class Tracing {
	public static <T, R> R execute(T input, CheckedFunction<T, R, Throwable> function) throws Throwable {
		// create new span
		try {
			return function.apply(input);
		} finally {
			// finish span
		}
	}
}

```

**Comment by quaff** [comment]
> some JDK internals

Many projects use `Checked*`, for example `vavr` `elasticsearch`
