### ISSUE TITLE
Remove obsolete SpEL expression grammar file

### ISSUE THREAD

**Issue by superdc** [spring-projects/spring-framework#28425]
Can you provide a SpEL expression grammar file for antlr4 as known as `SpringExpression.g4`?

**Comment by superdc** [comment]
@sbrannen need help

**Comment by sbrannen** [comment]
I am not aware of any formal grammar file for SpEL.

@aclement, please correct me if I'm wrong about that.

**Comment by sbrannen** [comment]
Reopening to allow @snicoll to elaborate on where `SpringExpressions.g` came from.

**Comment by sbrannen** [comment]
As explained in commit da112a7ea82fee786a309f24baeda57d15478ff7:

> The antlr-based SpEL expression grammar file (`SpringExpressions.g`) was introduced during initial development and prototyping of the Spring Expression language; however, it was quickly abandoned in favor of a handcrafted implementation. Consequently, it has become obsolete over time and has never been actively maintained.

Since the grammar file is not used with the Spring Framework itself, the team has no plans to maintain it or release a new version compatible with later versions of antlr.

In light of that, I have repurposed this issue to remove the obsolete SpEL expression grammar file.

**Comment by superdc** [comment]
> As explained in commit [da112a7](https://github.com/spring-projects/spring-framework/commit/da112a7ea82fee786a309f24baeda57d15478ff7):
> 
> > The antlr-based SpEL expression grammar file (`SpringExpressions.g`) was introduced during initial development and prototyping of the Spring Expression language; however, it was quickly abandoned in favor of a handcrafted implementation. Consequently, it has become obsolete over time and has never been actively maintained.
> 
> Since the grammar file is not used with the Spring Framework itself, the team has no plans to maintain it or release a new version compatible with later versions of antlr.
> 
> In light of that, I have repurposed this issue to remove the obsolete SpEL expression grammar file.

So now SpEL is not antlr-based，right？parser and lexer are produced handcraft?

**Comment by sbrannen** [comment]
> @sbrannen So now SpEL is not antlr-based，right？parser and lexer are produced by handcraft?

That's correct. 

Take a look at `org.springframework.expression.spel.standard.InternalSpelExpressionParser` and the types in the `org.springframework.expression.spel.ast` package for details.

**Comment by superdc** [comment]
> > @sbrannen So now SpEL is not antlr-based，right？parser and lexer are produced by handcraft?
> 
> That's correct.
> 
> Take a look at `org.springframework.expression.spel.standard.InternalSpelExpressionParser` and the types in the `org.springframework.expression.spel.ast` package for details.

@sbrannen  Can I know the reasons why SpEL turns into not antlr-based？We want to parse SpEL in frontend and construct our custom ast tree. One method is used antlr4 to generate parser, lexer and visitor，but now this method looks impractical.

**Comment by sbrannen** [comment]
> Can I know the reasons why SpEL turns into not antlr-based?

I was not the original developer of the Spring Expression language, but as far as I understand, using antlr turned out to be too cumbersome. Thus, the original developer, @aclement, decided it would be easier to handcraft the support.

**Comment by deanmaster** [comment]
hello @sbrannen we have intention to build tooling support for projects to expresison their own needs in more friendly and controllable way. 

1. Using antlr4 would help a lot since it can support code completion from many platforms.
2. If you don't use it any suggestion for testing a dedicate expression if it's working ? from unit test point of view.

Thanks a lot,
Tuan Do

**Comment by sbrannen** [comment]
> If you don't use it any suggestion for testing a dedicate expression if it's working ? from unit test point of view.

You can use the tests in our test suite for inspiration -- for example, any of the tests in [`src/test/java`](https://github.com/spring-projects/spring-framework/tree/main/spring-expression/src/test/java/org/springframework/expression/spel) in the `spring-expression` project, in particular [`EvaluationTests`](https://github.com/spring-projects/spring-framework/blob/main/spring-expression/src/test/java/org/springframework/expression/spel/EvaluationTests.java).

**Comment by deanmaster** [comment]
hello @sbrannen ,

Currently i'm implementation an autocompletion for SpEl in our project. Do you know how can I "extracted" from existing code? Or I have to manually create the grammar on my own ? Because everything in the package org.springframework.expression are basically java form which can't convert to any syntax which can be used to return as autocompletion suggestion.

Any suggestions are really helpful for me.

Thanks,
Tuan Do

**Comment by sbrannen** [comment]
Hi @deanmaster,

> Do you know how can I "extracted" from existing code?

I doubt there is any way to _extract_ the grammar automatically from the code, since the lexing and parsing is now handwritten.

The classes you'll need to look at are `Tokenizer`, `TokenKind`, and `InternalSpelExpressionParser` in the `org.springframework.expression.spel.standard` package.

Those classes sometimes refer to the original antlr grammar in comments.

> Or I have to manually create the grammar on my own ?

Yes, I think you'll basically have to create your own grammar from scratch, but you can probably use the [original antlr grammar](https://github.com/spring-projects/spring-framework/blob/3.2.x/spring-expression/src/main/java/org/springframework/expression/spel/generated/SpringExpressions.g) as a starting point.

**Comment by jakeboone02** [comment]
@deanmaster I was curious if you've made any significant progress with your antlr4 grammar. I'd be willing to pitch in if you want help; I have a use case in my [`react-querybuilder`](/react-querybuilder/react-querybuilder) project where I'm currently using `spel2js` but would like to move to a static grammar file.

**Comment by deanmaster** [comment]
@jakeboone02 i'm able to convert the grammar file to latest v4 ANTLR but obviously it does not reflects newest "java syntax" with current version of SpEl. We are pending this topic for now. In the future when i'm able to complete the grammarfile I can share it here
