### ISSUE TITLE
Refine CachedIntrospectionResults property introspection

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#28445]

**Comment by tcrass** [comment]
Hi,

we used to access a read-only property the type of which happened to implement AutoCloseable like this...

        BeanWrapper sourceBeanWrapper = PropertyAccessorFactory.forBeanPropertyAccess(source);
        TypeDescriptor sourceTypeDescriptor = sourceBeanWrapper.getPropertyTypeDescriptor(sourcePropertyName);

...but after switching to a newer Spring version we realized that this is apparently no longer possible due the isInvalidReadOnlyPropertyType() method introduced in 83186b68 -- sourceTypeDescriptor turns out to be null.

 Any work-arounds...?

Cheers, Torsten
