### ISSUE TITLE
hello   您对spring的生命周期怎么看

### ISSUE THREAD

**Issue by sakura-maple** [spring-projects/spring-framework#28471]
面试经常被问spring的生命周期 我很苦恼，能不能简单说下

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by sakura-maple** [comment]
thanks  i love spring framework,I want to learn the source code of the framework

then.  I want to write another spring framework，I look forward to future cooperation。
