### ISSUE TITLE
The problem that field must be all capitalized when use Constants

### ISSUE THREAD

**Issue by wrj15034011352** [spring-projects/spring-framework#28483]
If I use the construction method of Constants, the key in the fieldcache attribute is the attribute name and is not capitalized, but when I use the asxxxx method, the parameter code will be capitalized, resulting in no corresponding value
![image](https://user-images.githubusercontent.com/38170277/169243636-c8c8dacf-9412-4bec-bd4f-a0abde907008.png)
![image](https://user-images.githubusercontent.com/38170277/169243746-8d92d0c4-461e-480b-9154-bfc2385a5692.png)
Why not capitalize when put？
Although the Java specification constants should be all capitalized, this is not mandatory. It is better if they are also capitalized when put！

**Comment by jhoeller** [comment]
Capitalizing on put could have side effects when the same constant is declared with different casing (since fields are case-sensitive). Instead, we could leniently find fields with the provided casing in `asObject`, but even that would create an inconsistency with `getNames` and related methods.

Since `Constants` is not considered a general utility but rather a Spring-style adapter for classic Java constants used in several framework classes, we'll rather leave it as-is. For custom purposes, it is straightforward enough to create a similar adapter of your own, inspired by Spring's `Constants` class.
