### ISSUE TITLE
Getting Internal Error 500 response in Spring 5 when url contains semicolon. It was working fine with Spring 3. Any clue please?

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28513]
**Affects:** \<Spring Framework version>

---

**Comment by snicoll** [comment]
We can't give you support based on the information that you've shared and giving you a clue is probably going to lead to a lot of back and forth. Rather, please take the time to build a small sample we can run ourselves (zip or GitHub repo) using a supported version of the Spring Framework that reproduces the problem. Based on that, we can investigate and help you.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Nidhi-Tanwar14** [comment]
Thank you your response. I am making a rest call with url:- /rest/IMS/getIdentityMappings/roleId/PSI43771294;assetRole. This is giving me error please

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by bclozel** [comment]
As explained in this issue and the other similar ones you've created, this issue tracker is not for questions. Feel free to add a link to your StackOverflow question.

**Comment by Nidhi-Tanwar14** [comment]
Solved the issue by adding the below snippet to security-config.xml. This will allow semicolon and percentage character in the url.


    <property name="allowSemicolon" value="true"/>
    <property name="allowUrlEncodedPercent" value="true"/>
