### ISSUE TITLE
Api for Group Video call using webRTC

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28566]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Nidhi-Tanwar14** [comment]
Thank you for your response, but I did check on stack overflow and I have not found any solution there. I was asking if we can have any api to have group video call just as we have for peer to peer call please.

**Comment by bclozel** [comment]
As explained in this issue and the other similar ones you've created, this issue tracker is not for questions. Feel free to add a link to your StackOverflow question.

**Comment by Nidhi-Tanwar14** [comment]
With due respect, as per the guidelines, making a new feature request is good way to contribute. So I thought of requesting on this platform to request for the api for advanced features on webRTC please.

Thank you so much for being patient and responding

**Comment by Nidhi-Tanwar14** [comment]
Actually, I am working on a spring project to create a video call using webRTC, so wondering if we can have these advance features please.

**Comment by bclozel** [comment]
Thank you, but we are not investing in this field right now. Spring Framework should help you design such a solution, but not provide it out of the box.

**Comment by Nidhi-Tanwar14** [comment]
ok, thank you
