### ISSUE TITLE
webrtc call gets disconnected on unintentionally closing the browser without warning

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-framework#28568]
**Affects:** \<Spring Framework version>

---

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Nidhi-Tanwar14** [comment]
Thank you for your response, but I did check on stack overflow and I have not found any solution there. I was hoping can we have an enhancement here to warn the user if he closes the browser please?

**Comment by bclozel** [comment]
As explained in this issue and the other similar ones you've created, this issue tracker is not for questions. Feel free to add a link to your StackOverflow question.

**Comment by Nidhi-Tanwar14** [comment]
With due respect, I was trying to request for a new feature here please. As per the guidelines, we can do that on this platform.

Thank you for being patient, kindly correct me if I am wrong

**Comment by Nidhi-Tanwar14** [comment]
Actually, I am working on a spring project to create a video call using webRTC, so wondering if we can have these advance features please.

**Comment by bclozel** [comment]
Thank you, but we are not investing in this field right now. Spring Framework should help you design such a solution, but not provide it out of the box.

**Comment by Nidhi-Tanwar14** [comment]
ok, thank you
