### ISSUE TITLE
Provide a way to request a WebSession without creating one

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-framework#28575]
Provide a way to request a session without creating one. Please see https://github.com/spring-projects/spring-framework/issues/26958 for details

Note that this is intended to track the change mentioned in https://github.com/spring-projects/spring-framework/issues/26958#issuecomment-856986682

> We can explore a more optimal, longer term solution for 6.0, such as new methods on WebSession and ServerWebExchange or perhaps a non-blocking id generator if that's even feasible.

**Comment by poutsma** [comment]
@rwinch We were wondering if there is still a use case for this issue, after the resolution of #26958? Note that in WebFlux, sessions work a bit differently that in a Servlet environment: the  `WebSession` might be created, but it is not stored until the session is started.

**Comment by rstoyanchev** [comment]
See also the [Javadoc on WebSession#isStarted](https://github.com/spring-projects/spring-framework/blob/3d8455b257bdf903259676a04329fad28676c970/spring-web/src/main/java/org/springframework/web/server/WebSession.java#L96-L102), which protects the call to `save()` in `DefaultWebSessionManager`, so that generally a session is not created unless explicitly started or if session attributes were added.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
