### ISSUE TITLE
About register "BeanPostProcessor" use"BeanFactoryPostProcessor"

### ISSUE THREAD

**Issue by livk-cloud** [spring-projects/spring-framework#28592]
> When I use "BeanFactoryPostProcessor" to register "BeanPostProcessor" and at the same time use AutoConfiguration to wire up my defined "BeanFactoryPostProcessor", I found that my "BeanPostProcessor" execution order is after "@PostConstruct", I am curious why, and please what is good way to deal with

> The key code is as follows
> JDK17\SpringBoot3.0.0-M3
```java
@RequiredArgsConstructor
public class MapstructFactory implements BeanPostProcessor {

	private final MapstructRegistry registry;

	@Override
	public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
		if (bean instanceof Converter) {
			registry.addConverter((Converter<?, ?>) bean);
		}
		return BeanPostProcessor.super.postProcessBeforeInitialization(bean, beanName);
	}

}
```
```java
@RequiredArgsConstructor
public class MapstructFactoryRegister implements BeanFactoryPostProcessor {

	private final MapstructRegistry registry;

	@Override
	public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
		 beanFactory.addBeanPostProcessor(new MapstructFactory(registry));
	}

}
```

```java
@AutoConfiguration
public class MapstructAutoConfiguration {

	@Bean
	public MapstructFactoryRegister mapstructFactoryRegister(MapstructRegistry registry) {
		return new MapstructFactoryRegister(registry);
	}
}
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
