### ISSUE TITLE
I have some questions to ask how to solve

### ISSUE THREAD

**Issue by zhangsai123** [spring-projects/spring-framework#28657]
Some  problems  in  CoroutinesUtils.Class

'await(kotlin.coroutines.Continuation<? super T>)' in 'kotlinx.coroutines.Deferred' cannot be applied to '(kotlin.coroutines.Continuation<capture<? super T>>)'

'awaitSingleOrNull(reactor.core.publisher.Mono<T>, kotlin.coroutines.Continuation<? super T>)' in 'kotlinx.coroutines.reactor.MonoKt' cannot be applied to '(reactor.core.publisher.Mono<T>, kotlin.coroutines.Continuation<capture<? super T>>)'

'callSuspend(kotlin.reflect.KCallable<? extends R>, java.lang.Object[], kotlin.coroutines.Continuation<? super R>)' in 'kotlin.reflect.full.KCallables' cannot be applied to '(kotlin.reflect.KFunction<capture<?>>, java.lang.Object[], kotlin.coroutines.Continuation<capture<? super T>>)'

'callSuspend(kotlin.reflect.KCallable<? extends R>, java.lang.Object[], kotlin.coroutines.Continuation<? super R>)' in 'kotlin.reflect.full.KCallables' cannot be applied to '(kotlin.reflect.KFunction<capture<?>>, java.lang.Object[], kotlin.coroutines.Continuation<capture<? super T>>)'

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
