### ISSUE TITLE
Add prefix or suffix to the GET,PUT,POST,DELETE mappings in controller at method level using custom annotation

### ISSUE THREAD

**Issue by pawank0411** [spring-projects/spring-framework#28706]
I am trying to add a prefix or suffix in the controller at the method level on top of GET, POST, PUT, DELETE mappings.

Controller class

    @RestController
    @RequestMapping("/something")
    public class SomeController {
    @PutMapping("/some/path/")
    public ResponseEntity<ApiResponse<String>> someMethod() {
    ....
    }
    ...
    }
So, basically, the above request URL should be something like : **http://localhost:8080/something/some/path/**

Now, I just want to add some prefix or suffix whatever is feasible to the request URL which will be something like : **http://localhost:8080/read/something/some/path/** or **http://localhost:8080/something/some/path/read/** the extra "/read" which needs to be added to the request URL as a prefix or suffix. I can do this directly by adding this to the PutMapping value, but I want to decorate it somewhat using annotation like **@Read**

So, the updated Controller class will be like 

    @RestController
    @RequestMapping("/something")
    public class SomeController {
    @Read
    @PutMapping("/some/path/")
    public ResponseEntity<ApiResponse<String>> someMethod() {
    ....
    }
    ...
    }
and the same way updated request URL will be like : **http://localhost:8080/read/something/some/path/**

I am unable to find a better way to do this. Till now I have only achieved adding a class-level prefix using custom annotation.

Can anyone please help with the above requirement.?
Thank you !!

I am also curious to know whether is achievable or not even?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
