### ISSUE TITLE
Missing documentation for `spring.spel.ignore` and `spring.xml.ignore`

### ISSUE THREAD

**Issue by joca-bt** [spring-projects/spring-framework#28726]
Properties `spring.spel.ignore` (https://github.com/spring-projects/spring-framework/issues/25153) and `spring.xml.ignore` (https://github.com/spring-projects/spring-framework/issues/25151) are not documented. Other similar properties are documented in the appendix https://docs.spring.io/spring-framework/docs/current/reference/html/appendix.html so I think it would make sense to add these there as well.

**Comment by sbrannen** [comment]
This omission is intentional. These two specific properties are not considered "supported", and the table in the appendix "lists all currently supported Spring properties".

However, since these unsupported properties have existed for a while and are used in conjunction with applications running within a native image, the team will revisit this topic.

**Comment by sdeleuze** [comment]
Let's maybe decide what we do on Spring Framework 6 timeframe for those, the ideal outcome would be to remove those flags, removing the need for documentation.

**Comment by adrianbob** [comment]
Hey,
I'm new to open source contributing. Please let me know if it would be ok to open a PR for this issue for removing those properties. Thanks!

**Comment by sbrannen** [comment]
Hi @adrianbob,

Thanks for the offer.

Please note, however, that this is an issue that will be decided within the core team.

In light of that, a PR for removal would not be appropriate at this time.

**Comment by sbrannen** [comment]
Superseded by:

- #29277
