### ISSUE TITLE
`HibernateTransactionManager` compatibility with Hibernate 6.0/6.1

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#28813]
We [already fixed](https://github.com/spring-projects/spring-framework/issues/28007) references to API removed in Hibernate 6 for `HibernateJpaVendorAdapter` but apparently `HibernateTransactionManager` also refers to the [very same API](https://github.com/spring-projects/spring-framework/blob/0b5c5dbc313fcd61abdf8e0f3b68a6a8fbbc0f98/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTransactionManager.java#L565).

**Comment by jhoeller** [comment]
To be clear, `HibernateTransactionManager` is part of our legacy `orm.hibernate5` package and should be replaced with `JpaTransactionManager` plus `HibernateJpaDialect` / `HibernateJpaVendorAdapter` with `LocalContainerEntityManagerFactoryBean` since we officially only support Hibernate 6.x via JPA.

That said, it turns out that we can make `HibernateTransactionManager` compatible with Hibernate 6.0/6.1 with a few minor tweaks where we're calling Hibernate 5.6's internal connection handling mechanisms instead of the public API (the latter is gone in Hibernate 6.0 but the internal coordinator SPI is still the same). We won't be able to guarantee compatibility with Hibernate 6.x going forward, but for a start this allows usage of `LocalSessionFactoryBean` and `HibernateTransactionManager` for transitionary purposes when upgrading from Hibernate 5.6 to 6.0/6.1.
