### ISSUE TITLE
Stream Closed appears when uploading files using MultipartFile

### ISSUE THREAD

**Issue by Mr-YW** [spring-projects/spring-framework#28932]
In order to read the body twice, we rewrite the `HttpServletRequestWrapper`, and wrap the original request through the `Filter`. Although we packing the original Request, upload files, `StandardMultipartHttpServletRequest` call or use the original Request, not after we packing, We rewrite `HttpServletRequestWrapper` `getInputStream` method is not called, the original flow has been closed, result in an error

At present, our solution is to call the `getParameter` method of request once in the wrapped `Filter` to solve this problem

[StreamClosed.zip](https://github.com/spring-projects/spring-framework/files/9267541/StreamClosed.zip)

**Comment by rstoyanchev** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
