### ISSUE TITLE
Spring-oxm with JDK11

### ISSUE THREAD

**Issue by navyakrishna92** [spring-projects/spring-framework#28992]
Hi Team,

We want to use spring-oxm with JDK11, we're facing issue while we migrating from JDK8 to JDK11 w.r.t Jaxb2Marshaller and StaxEventItemReader.

Kindly let us know when we can expect new release or is there any workaround to handle this ?

**Comment by snicoll** [comment]
@navyakrishna92 you haven't described what issue you're facing so I don't know what you're expecting us to do.

**Comment by navyakrishna92** [comment]
As we know, Java EE modules, including the JAXB packages javax.xml.* is completely removed in jdk11, Oracle submitted the Java EE to Eclipse Foundation and repackaged javax.xml.* to jakarta.xml.* since version 3.0.
When we're migrating to jdk11, our implementation expecting us to use  jakarta.xml.* but spring-oxm version 6 is not yet released and using  javax.xml.*. Example: 
JAXBContext context = JAXBContext.newInstance(FormBCTrnsmtSubmissionDtlType.class); // using import jakarta.xml.bind.JAXBContext;
Unmarshaller unmarshaller = context.createUnmarshaller(); // using import jakarta.xml.bind.Unmarshaller;
StaxEventItemReader<JAXBElement<ABDObject>> itemReader = new StaxEventItemReader<>();
itemReader.setUnmarshaller(unmarshaller); // compiler error is thrown here to use required 
org.springframework.oxm.Unmarshaller and i can't use "Jaxb2Marshaller" because inside it uses  javax.xml.* package

**Comment by snicoll** [comment]
> When we're migrating to jdk11, our implementation expecting us to use jakarta.xml.* but spring-oxm version 6 is not yet released and using javax.xml.

You don't have to use the `jakarta` namespace because you upgraded to Java 11. There are a lot of questions around this on StackOverflow, for example [this one](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception). If you add JAXB to your classpath (now that it's removed from the JDK) you'll be able to use the same code unchanged.

Going forward, please ask questions on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.
