### ISSUE TITLE
spring Security + rsocket @MessageExceptionHandler  

### ISSUE THREAD

**Issue by itmagus** [spring-projects/spring-framework#29040]
https://github.com/spring-projects/spring-framework/issues/26636

ControllerAdviceBean.findAnnotatedBeans(context).forEach(controllerAdviceBean ->
        rsocketMessageHandler.registerAdviceBean(new MessagingAdviceBeanWrapper(controllerAdviceBean));

@ControllerAdvice
public class MessageControllerAdvice {
    @MessageExceptionHandler(Exception.class)
    public Mono<Response> handleException(Exception e) {
    }
}

Controller exceptions can be caught globally

Unable to catch exception spring Security AccessDeniedException
//org.springframework.security.authorization.ReactiveAuthorizationManager
default Mono<Void> verify(Mono<Authentication> authentication, T object) {
		// @formatter:off
		return check(authentication, object)
				.filter(AuthorizationDecision::isGranted)
				.switchIfEmpty(Mono.defer(() -> Mono.error(new AccessDeniedException("Access Denied"))))
				.flatMap((decision) -> Mono.empty());
		// @formatter:on
	}

What is the normal way to handle global exceptions?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
