### ISSUE TITLE
Add proxy hints for org.hibernate.SessionFactory & org.hibernate.Session

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-framework#29138]
The following hints are required to run jpa with hibernate.

```json
{
  "interfaces": [
    "org.hibernate.SessionFactory",
    "org.springframework.orm.jpa.EntityManagerFactoryInfo"
  ]
},
{
  "interfaces": [
    "org.hibernate.Session",
    "org.springframework.orm.jpa.EntityManagerProxy"
  ]
}
```

See: [spring-aot-smoke-tests#113](https://github.com/spring-projects/spring-aot-smoke-tests/pull/113/files#diff-7ef71cf1c606f367db61256ab78fcda4d1ae5acc1b54ad93439c97fcf25a274f)

**Comment by sdeleuze** [comment]
@snicoll @jhoeller Do they seem relevant proxy hints we can't infer and that we should configure?

**Comment by jhoeller** [comment]
The combination of `SessionFactory` and `EntityManagerProxy` seems odd, is that really necessary in that combination?

The other two are obviously the EMF/EM proxies that we create in our JPA setup arrangement. For the EMF proxy, we might able to infer it from a narrowed `AbstractEntityManagerFactoryBean.getObjectType()` implementation. For the EM proxies, I'm not quite sure where to infer those since we typically create those on demand (i.e. not as beans).

**Comment by christophstrobl** [comment]
@jhoeller good catch - thanks - my bad, yes we can do without that one. I'll update the description

**Comment by sdeleuze** [comment]
Ok let's configure hints for those for M6 since that's the last JPA blocker, I will create a follow-up issue for RC1 to see if we can infer them.
