### ISSUE TITLE
DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl is unable to resolve root url in native image

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-framework#29137]
Bootstrapping the `DefaultPersistenceUnitManager` fails in native image being unable to resolve the root url. Replacing `determineDefaultPersistenceUnitRootUrl` via a substitution that returns `null` allowed to initialize the `PersistenceUnitManager`.  

See: [pring-aot-smoke-tests#113](https://github.com/spring-projects/spring-aot-smoke-tests/pull/113/files#diff-3f810a09badaf6852c87168c71c77aa4871afec6e8a526ed5c512c0e600156f6)

**Comment by jhoeller** [comment]
I guess it would also help to call `setDefaultPersistenceUnitRootLocation(null)` since the implementation already has that escape hatch? We should make the default implementation more defensive though, there is no need to fail hard, at least not with the `ORIGINAL_DEFAULT_PERSISTENCE_UNIT_ROOT_LOCATION` as input . Could be as straightforward as just logging the "Unable to resolve persistence unit root URL" message and returning `null` instead of throwing a `PersistenceException` there, potentially with an `if` check to only leniently return in case of `defaultPersistenceUnitRootLocation == ORIGINAL_DEFAULT_PERSISTENCE_UNIT_ROOT_LOCATION`.
