### ISSUE TITLE
NestedExceptionUtils为什么是抽象类，而且是必须的

### ISSUE THREAD

**Issue by dengWeiChang** [spring-projects/spring-framework#29191]
5.3.x版本，we can't share a base class among different exception types ？ 
在NestedRuntimeException中实现NestedExceptionUtils的逻辑有什么不妥之处吗

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
