### ISSUE TITLE
Support `@RSocketExchange` for annotated responders

### ISSUE THREAD

**Issue by CoderYellow** [spring-projects/spring-framework#29240]
It's better to addopt unifed annotation contract for both server and client side. And I think the [RSocket Interface annotation ](https://docs.spring.io/spring-framework/docs/6.0.0-M6/reference/html/web-reactive.html#rsocket-interface)  is more powerful and meaningful

**Comment by rstoyanchev** [comment]
We can enhance [Annotated Responders](https://docs.spring.io/spring-framework/docs/6.0.0-M6/reference/html/web-reactive.html#rsocket-annot-responders) to support `@RSocketExchange` instead of `@MessageMapping`, which would allow using the same interface to make and to handle requests. 

The semantics overlap to a large degree. These are the differences I see: 

- Metadata Object, followed by `MimeType` -- supported for `@RSocketExchange` but not for `@MessageMapping`; we can add arguments resolvers to support it
- `RSocketRequester` argument -- this is a responder-only concept, and therefore not applicable with `@RSocketExchange`
- Synchronous return type -- for `@MessageMapping` we assume non-blocking handling (no I/O essentially), while for requests with `@RSocketExchange` it is a way to block for the result; we can proactively switch threads when such methods are used for handling with `@RSocketExchange`

**Comment by CoderYellow** [comment]
yes, something like MVC annotation, it's better have rescoket team to make a common standard like JAX-RS annotation, so that other framework can implement it too

**Comment by OlgaMaciaszek** [comment]
We are going to experiment with this for `6.1`.
