### ISSUE TITLE
LinkedCaseInsensitiveMap::getOrDefault throw NullPointerException

### ISSUE THREAD

**Issue by SortfGrowingup** [spring-projects/spring-framework#29265]
Hello, @poutsma 
I current use version is org.springframework:spring-core:5.3.8

When I used JdbcTemplate::queryForList(sql) found that,
LinkedCaseInsensitiveMap::getOrDefault throw NullPointerException，
This is obviously not the expected value OrDefault.
<img width="1512" alt="WeChat0ac08d2ab6eead3f082434db1039d370" src="https://user-images.githubusercontent.com/40589041/194113150-e433885e-b2c1-4d21-819a-c37768a4cfba.png">

**Comment by bclozel** [comment]
It's not clear whether you're reporting an issue for `JdbcTemplate`, `LinkedCaseInsensitiveMap` or an issue with your auto-configuration setup. Could you share a minimal application that demonstrates the issue?
If the problem is about `LinkedCaseInsensitiveMap`, a simple code snippet explaining the behavior you'd expect and what you're seeing instead would be enough.

Screen captures are hard to work with - in this case we have no clue about the `schema` variable, its state or where it comes from.

**Comment by SortfGrowingup** [comment]
Sorry, I misunderstood the meaning of the api itself...
Thanks for @mdeinum explanation. 
As you said, The ```map#key``` exists, because the wrong api is used, resulting in the ```getOrDefault#toString 
```
