### ISSUE TITLE
Spring boot with embodied Netty Http 2 server does not provide any option to ignore http2 request without response

### ISSUE THREAD

**Issue by iyappan** [spring-projects/spring-framework#29298]
### Requirement:
Our application runs on Springboot with embedded Netty server(enabled http2). And it exposes services via Rest Apis.
On Rest Api call, we have a scenario where we wanted to ignore the http2 request without sending any response.
### Expected behavior
 Netty server need to expose a API or any other visible provision to ignore a request without sending a response. 
### Actual behavior
 Not able to find any solution for this expectation
### Steps to reproduce
 Not able to find any solution for this expectation
### Environment
springBootVersion= 2.6.7
Reactor version(s) used: reactor-netty-http : 1.0.16
JVM version (java -version): 17.0.1

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

When asking this question on StackOverflow, please add the relevant information:

* what do you mean by no response? What would you like the HTTP client to get?
* How is HTTP/2 relevant here? Does it mean that it should send a response for HTTP 1.1?
* How is this specific to Netty? Are you dealing with the Reactor Netty API directly or Spring WebFlux?

Thanks,
