### ISSUE TITLE
Add AOT support for `@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)`

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#29335]
@snicoll @jhoeller It looks like this is not supported by AOT transformations:
```
@StepScope
@Bean
public ItemReaderListener reader() {
   ...
}
```

This is the equivalent of:
```
@Scope(value = "step", proxyMode = ScopedProxyMode.TARGET_CLASS)
@Bean
public ItemReaderListener reader() {
   ...
}
```
Since we don't have hints for CGLIB proxies, we are kind of blocked currently for [this kind of Batch IO use case](https://github.com/spring-projects/spring-aot-smoke-tests/pull/116). See also the [original Spring Native issue](https://github.com/spring-projects-experimental/spring-native/issues/459) where this use case was supported.

**Comment by jhoeller** [comment]
Scoped proxy detection seems to be broken at the moment due to an explicit bypass in the BeanFactory implementation, always determining the type of the target bean instead. Removing that bypass makes the proxy discoverable through `ScopedProxyFactoryBean.getObjectType()` as part of our regular `preDetermineBeanTypes` algorithm, for CGLIB proxies as well as JDK proxies (auto-inferring the runtime hint for the latter).

The remaining question is why that (old) type determination bypass was needed in the first place. I'll revise this towards not being necessary for scoped proxies anymore at least, in time for the RC2 release.

**Comment by jhoeller** [comment]
This should work now, with CGLIB proxy classes captured as well as runtime hints registered for both types of scoped proxies (no explicit hints necessary for either anymore).

**Comment by snicoll** [comment]
Supporting a proxy at that level means that AOT exposes it and any container lifecycle callback is invoked on it. Looking at the AOT contribution for the scoped proxy, it's a bit odd as it's exposing the underlying type from the instance supplier. I bet this was done to make sure that type resolution works but I am not entirely sure it is still relevant.

**Comment by snicoll** [comment]
This should now be fixed with https://github.com/spring-projects/spring-framework/commit/affccba8f1beccdb5910e4a0e909701d33255db5
