### ISSUE TITLE
Parent Conditionals are ignored on component scanning

### ISSUE THREAD

**Issue by levitin** [spring-projects/spring-framework#29372]
Imagine you have the following configuration and the associated properties:

<details>
<summary>MyConfiguration.java</summary>

```java
@Configuration
@EnableConfigurationProperties(MyProperties.class)
public class MyConfiguration {

  @Configuration
  @ConditionalOnProperty(value = "my.enabled", havingValue = "true")
  static class MyEnabledConfiguration {

    @Configuration
    @ConditionalOnProperty(value = "my.version", havingValue = "v1")
    static class MyEnabledFirstConfiguration {
      @Bean
      public MyClient firstClient() {
        return new FirstClient();
      }
    }

    @Configuration
    @ConditionalOnProperty(value = "my.version", havingValue = "v2", matchIfMissing = true)
    static class MyEnabledSecondConfiguration {
      @Bean
      public MyClient secondClient() {
        return new SecondClient();
      }

    }
  }

  @Configuration
  @ConditionalOnProperty(value = "my.enabled", havingValue = "false", matchIfMissing = true)
  static class MyDisabledConfiguration {

    @Bean
    public MyClient thirdClient() {
      return new ThirdClient();
    }
  }
```
</details>

<details>
<summary>MyProperties.java</summary>

```java
@Getter
@Setter
@Validated
@ConfigurationProperties(prefix = "my")
public class MyProperties {

  private boolean enabled;

  private Version version = Version.V1;

  public enum Version {
    V1,
    V2
  }
}
```

</details>

In following case I expect the only single bean of type `ThirdClient`

```yaml
my:
  enabled: false
  version: v1
```

And it actually works fine, if you write your test as following: 

```java 
@SpringBootTest(classes = MyConfiguration.class)
class MySpringBootTest {

    @Autowired
    private ApplicationContext context;

    @Test
    void contextLoads() {
        assertThat(context.getBeansOfType(MyClient.class).size()).isEqualTo(1);
        assertThat(context.getBean(MyClient.class)).isInstanceOf(ThirdClient.class);
    }
}
```

However if you are using component scan, the parent conditional is ignored.

```diff
+ @SpringBootTest
- @SpringBootTest(classes = MyConfiguration.class)
class MySpringBootTest {
    ...
}
```

In this case you get the following two beans instead of expected single one as in example above. 
* FirstClient
* ThirdClient

**Comment by jhoeller** [comment]
As mentioned on #30750, the classpath scan finds the nested classes directly rather than through their containing class. As a consequence, it processes them in the order that it found them in the classpath. Through declaring those nested classes as non-static, classpath scanning does not consider them as independent anymore, so they will actually be processed through their containing class then - with the order for nested classes respected there. You can achieve the same effect by removing the @Configuration stereotype from the nested classes so that classpath scanning does not identify them anymore; this works with static classes as well since they will only be found through their containing class then.
