### ISSUE TITLE
SpringBoot java SimpleJdbcCall  simply does not work with ORACLE  ...  Needs to be fixed 

### ISSUE THREAD

**Issue by sidhartha11** [spring-projects/spring-framework#29440]
I have been trying to create a automatic way vender agnostic way of calling  simple jdbc call. It works for SYBASE, SQL SERVER , MYSQL .....   BUT ....
Oracle is a BIG NO GO.  IT IS TOTALLY BROKEN WITHIN SPRING FRAMEWORK. I continually get the same error over and over no mattter what I do ... 
-----------------------------
The stored proc in question works perfectly in SQL Developer ( oracle ) ...  But refuses to work when called from SimpeJdbccall.  Note that it works for all the other database venders I am testing agaiinst.   Someone from Spring needs to step forth fix it  ... or at least tell the developer community THAT IT IS BROKE so that we can stop wasting days trying to figure it out.  
-------------- 
Can someone show proof  that  SimpleJdbcCall ever  works for ORACLE ????

**Comment by sidhartha11** [comment]
I forgot to mention:  The error is that standard oracle message that is meaningless:
PLS-00306: wrong number or types of arguments in call to 'BLAHBLAH' 
ORA-06550:  line 1, column 7    (  which is totally sillly because it does not point to anything )

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

> PLS-00306: wrong number or types of arguments in call to 'BLAHBLAH'
> ORA-06550: line 1, column 7 ( which is totally sillly because it does not point to anything )

I suggest that you [take some time crafting an actual sample that reproduces the problem](https://stackoverflow.com/help/minimal-reproducible-example) before reaching out to StackOverflow. Many community members run this use case in production and numerous tests are being checked as well.
