### ISSUE TITLE
Code listing callouts are displayed incorrectly in core-beans.adoc

### ISSUE THREAD

**Issue by tehnodev** [spring-projects/spring-framework#29457]
There is no bubles in java example [Fine-tuning Annotation-based Autowiring with Qualifiers](https://docs.spring.io/spring-framework/docs/6.0.0-RC4/reference/html/core.html#beans-autowired-annotation-qualifiers)
<img width="381" alt="image" src="https://user-images.githubusercontent.com/43758487/200921613-ecf62aa6-8268-4776-9abc-06cd2e017c85.png">

Same thing with second example.

In the third example with xml is opposite situation, bubbles present in example, but there is no description under example
<img width="410" alt="image" src="https://user-images.githubusercontent.com/43758487/200922427-035a3619-fb34-4f05-83b0-ba90e27540d4.png">

**Comment by sbrannen** [comment]
Hi @tehnodev,

Congratulations on raising your first issue for the Spring Framework! 👍 

This turns out to be the same underlying issue raised in #29505 which will later be automatically handled by the fix for https://github.com/spring-io/spring-asciidoctor-backends/issues/68.

However, I'll go ahead and address the issues in `core-beans.adoc` since I don't know when we'll be able to upgrade to [spring-asciidoctor-backends](https://github.com/spring-io/spring-asciidoctor-backends) 0.0.4.
