### ISSUE TITLE
Remove LocalVariableTableParameterNameDiscoverer

### ISSUE THREAD

**Issue by jhoeller** [spring-projects/spring-framework#29559]
Following up on #29531, we intend to remove `LocalVariableTableParameterNameDiscoverer` completely in 6.1. It is entirely superseded by `StandardReflectionParameterNameDiscoverer` and only serves an outdated fallback after the latter in `DefaultParameterNameDiscoverer` still. Since it performs blocking class file parsing and does not work in a native image, it has no remaining role anymore.

For the transition period up until then, as per #29531, it logs a warning for every successful resolution attempt - that is, where `StandardReflectionParameterNameDiscoverer` did not find names retained through `-parameters` compilation before.

**Comment by kriegaex** [comment]
@jhoeller, are you aware of the fact that JDKs < 19 suffer from [OpenJDK PR 4265](https://github.com/openjdk/jdk17u-dev/pull/4265), which effectively means that `MethodParameters` info is stripped out of classes compiled with `-parameters` when subjected to instrumentation using **retransformation**?

Many Java agents used with Spring applications apply retransformation. This change makes them all fail since Spring 6.1, because `LocalVariableTableParameterNameDiscoverer` was removed. As current Spring versions are still supposed to support Java 17, I suggest you consult with the rest of the Spring dev team to decide if it might make sense to bring back that class, because at least the parameter name info in the constant pool survives retransformation. I would not remove this helpful feature in any Spring version still supporting Java versions < 19.

Otherwise, all Java agents can do is to check for the JRE version and skip retransformation altogether in such cases. Not only does this add if-else runtime version check boilerplate to all those agents, but it also degrades their effectiveness, skipping features which used to work fine until Spring 6.0, but now yielding exceptions since 6.1. One such example is DataDog (see PR https://github.com/DataDog/dd-trace-java/pull/10521), but there must be many more.

**Comment by bclozel** [comment]
Thanks for the heads up @kriegaex , this change was shipped a while ago and this is the first time we are getting this feedback. It's a hard problem to investigate, so I'm not sure how developers managed to solve that if they encountered it.

We have just [updated our wiki section with this](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.1-Release-Notes#parameter-name-retention) to raise awareness. In the meantime, Java got quite a few upgrades and the JDK backport fix seems to be seriously considered for maintenance updates.

Given the timeline, I don't think we'll bring the `LocalVariableTableParameterNameDiscoverer` back. The earliest would be the 6.2.x generation - [its OSS support ends in a few months](https://spring.io/projects/spring-framework#support) so tradeoffs are not in favor of changing the behavior now. We can always reconsider if we get more feedback, including from customers and commercially supported versions.

**Comment by kriegaex** [comment]
It was shipped a while ago, alright. But in most commercial environments, people do not jump to new versions right after GA. That can take years, depending on rules and available resources in dev and ops. I.e., many customers are still ahead of hitting the problem.

As you can see in the DataDog issue, this started happening to the customer in question just recently, and it was very difficult to diagnose, because Spring kept telling him to compile with `-parameters`, which he already did. The fact that the issue occurred sporadically, because it was bound to dynamic instrumentation on a case-by-case basis (exception replay, debug sessions conducted by other people), did not make it any easier to pinpoint.

I am somewhat disheartened to hear your thoughts about timelines and OSS support. My recommendation still would be to bring it back into 6.1 and all others after that to ensure an unbroken line of availability for `LocalVariableTableParameterNameDiscoverer` (albeit with interruptions in some 6.1+ releases). I know, it might be a PITA to maintain the class, but I think it would be in the category of defensive programming and not unnecessarily breaking java agent usage for existing Spring applications which just happen to upgrade, because either they want some new features, fixes - or follow upgrading recommendations due to ending OSS support for their older versions, ironically.

Edit: I do wish to thank you for adding a warning to the 6.1 release notes, though. 🙂

**Comment by kriegaex** [comment]
As I just mentioned mentioned in https://github.com/DataDog/dd-trace-java/pull/10521#issuecomment-5042188710:

FYI, yesterday OpenJDK 17.0.20 was released. It contains the backport fix for JDK-8240908. As soon as they are available, you can download JDK binaries for re-test from several sources, e.g.

* https://adoptium.net/de/temurin/releases?version=17
* https://www.azul.com/downloads/?version=java-17-lts&package=jdk#zulu
* https://developers.redhat.com/products/openjdk/download
* https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-17

At the time of writing this, Azul Zulu 17.0.20 is already available, and I was able to successfully test the fix locally. Adoptium and Redhat downloads are still on 17.0.19.

I.e., now there is an option for Spring to use method parameter names successfully on JDK 17.
