### ISSUE TITLE
Space in integer request parameter neither triggers the default value nor generates a 400

### ISSUE THREAD

**Issue by oscarfh** [spring-projects/spring-framework#29550]
**Affects:** spring-web 5.3.22

### Expectation

Given an endpoint with an `Integer` parameter named `limit` with a default value of `10`, when a user makes a request with `limit=%20` then the system should either return a `400 - Bad Request` or have the default value applied.

### Actual

Given an endpoint with an `Integer` parameter named `limit` with a default value of `10`,  when a user makes a request with `limit=%20` then the system accepts the request and the limit variable has a `null` value.

This happens because when checking for the default value, Spring will not trim the string, so `" "` will be a value and will not trigger the default value.

But when binding the value to the variable, [this line](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/propertyeditors/CustomNumberEditor.java#L105) will resolve to `true` (because `allowEmpty` is set to `true` and `!StringUtils.hasText(" ")` resolves to `true`), so `null` will be set (instead of generating an exception).

I have no idea how to fix it, because this does not seem to be a bug in the code, but a mismatch of expectations.

### Steps to reproduce

1. Clone the reproducer https://github.com/oscarfh/spring-reproducer
2. Start the application
3. Call in your terminal: `curl "http://localhost:8080/endpoint?limit=`
   - "50" will be returned, this is the default value set for the limit endpoint, meaning that the default value was applied.
4. Call `curl "http://localhost:8080/endpoint?limit=a"`
   - Note that a 400 is returned, meaning that limit does not support string values.
5. Call `curl "http://localhost:8080/endpoint?limit=%20"`
   - Notice how "null" is returned, meaning that the `limit` variable was assigned the `null` value.

This is unexpected because, due to the fact that this variable is an integer with a default value. You either expect it to be the integer supplied by the user or the default value. You do not expect it to be null. This null will then very likely cause a null pointer exception in your code.

**Comment by rstoyanchev** [comment]
Thanks for the analysis and sample.

There was a similar case in #23939, but where the request parameter is required and becomes `null` after conversion. We added handling for it in 5.3 to recognize that as a missing value. 

I think this here is a variation of the same case, but with an optional parameter and default value. The initial decisions around default/missing value are confounded due to the presence of an empty string, but conversion results in `null`, and the default value could be applied instead of leaving it as `null`.

I think backwards compatibility concerns are very similar. We cannot apply it in a maintenance release, and this would have to be a potential 6.1 target. What do you think @jhoeller?

In the mean time you can customize the behavior of `CustomPropertyEditor` with an `@InitBinder` method either in the controller or in an `@ControllerAdvice`:
```java
@InitBinder
void initBinder(WebDataBinder binder) {
	binder.registerCustomEditor(Number.class, new CustomNumberEditor(Number.class, false));
}
```

**Comment by RemusRD** [comment]
Hey can I work on this one? :)

**Comment by rstoyanchev** [comment]
@RemusRD this one is not labelled with `"status: ideal-for-contribution"`.

**Comment by Nheyll** [comment]
@rstoyanchev 

> this one is not labelled with "status: ideal-for-contribution".

None of the issues are labelled with "status: ideal-for-contribution". 
There were 3 issues with this label since 2020 : 
https://github.com/spring-projects/spring-framework/labels/status%3A%20ideal-for-contribution
