### ISSUE TITLE
Unrendered asciidoc headings in reference documentation

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-framework#29569]
See for example https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-websocket

It contains

```
= Introduction to WebSocket
```

which is not rendered as a heading.

**Comment by sbrannen** [comment]
This is due to the use of `{chapter}` in the IDs.

`websocket-intro.adoc` attempts to use dynamic IDs such as `[[{chapter}.websocket-intro]]`; whereas, `web-uris.adoc` uses dynamic IDs such as `[id={chapter}.web-uricomponents]`.

The latter works.

I noticed the difference previously while working on a different issue and wondered if it was problematic, but I forgot to follow up on that. Now we know!
