### ISSUE TITLE
Improve options to expose MessageSource formatted errors for a ProblemDetail response

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-framework#29574]
Currently it is not that easy to get access to the injected `MessageSource` when extending the `ResponseEntityExceptionHandler`. It is in a `private` field and there is no getter for it. It would be handy if there would be an `protected getMessageSource` so that when subclassing getting the `MessageSource` is easier. 

For now it is possible to workaround it by implementing `MessageSourceAware` as well and store the reference in the `@ControllerAdvice` and calling the super method. But it is far from ideal. 

Affects: Spring 6.0.x

**Comment by rstoyanchev** [comment]
Makes sense, I'll go ahead and add a getter.

Are you calling `ErrorResponse.builder(..).build()` and then `updateAndGetBody` to resolve "detail" and "title" message codes? We could add an overloaded `build(MessageSource, Locale)` to shorten that a bit as a follow-up improvement on #29462.

**Comment by mdeinum** [comment]
```java
@Override
protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex,																															HttpHeaders headers, HttpStatusCode status,WebRequest request) {
	var problemDetail = createProblemDetail(ex, status, "Validation errors", null, null, request);
	var errors = ex.getFieldErrors().stream()
					.collect(
						Collectors.toMap(FieldError::getField, FieldError::getDefaultMessage));
		problemDetail.setProperty("errors", errors);
	return createResponseEntity(problemDetail, headers, status, request);
}
```

Is what I currently have. I also would like to use the `MessageSource` to resolve the locale specific erorr message for the `FieldError`. As that itself is a `MessageSourceResolvable` one could simply pass it to the `MessageSource. So I'm actually calling the methods provided from the `ResponseEntityExceptionHandler`.

I thought of using the `ErrorResponse.builder` but as I needed to call `updateAndGetBody` that let me down the path getting the `MessageSource` myself. 

It is a sample from the Spring 6 Recipes book and I now wonder what the best practice would be?

**Comment by rstoyanchev** [comment]
Thanks for the extra detail.

`MethodArgumentNotValidException` already contains a `ProblemDetail`, so you can just change it, e.g. `ex.getBody().setProperty(..)`. It also [exposes "detail" message arguments](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-rest-exceptions-i18n) with the lists of global errors at `{0}` and the list of field errors at `{1}`. So, if that works for you, you can include those in the "detail"  by adding a message for this exception.

There are also utility methods in `MethodArgumentNotValidException` to turn errors into a list of strings with a `MessageSource`. Their main purpose is to share the code with `WebExchangeBindException` but you could use them for this too:

```java
protected ResponseEntity<Object> handleMethodArgumentNotValid(
		MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {

	var errors = MethodArgumentNotValidException.errorsToStringList(
			ex.getFieldErrors(), getMessageSource(), LocaleContextHolder.getLocale());

	ex.getBody().setProperty("errors", errors);

	return handleExceptionInternal(ex, null, headers, status, request);
}
```

It makes me wonder if we should expose similar, instance methods on `MethodArgumentNotValidException`, one for global and one for local fields, just taking a `MessageSource` and a `Locale`. This would support creating an "errors" property, rather than including the errors in the "detail" message.

**Comment by mdeinum** [comment]
Thanks for the hint on the helper methods on the `MethodArgumentNotValidException` and the reminder that it itself is a `ErrorResponse`, I should have looked at the javadoc for those. This code looks cleaner then what I had, will update my sample for the book. 

I do like the idea of an `errors` property.

**Comment by rstoyanchev** [comment]
Okay, thanks. I'll experiment with that.

**Comment by rstoyanchev** [comment]
The above snippet can now be written using an instance method:

```java
protected ResponseEntity<Object> handleMethodArgumentNotValid(
		MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {

	Map<ObjectError, String> errorMessages =
			ex.resolveErrorMessages(getMessageSource(), LocaleContextHolder.getLocale());

	ex.getBody().setProperty("errors", errorMessages.values());

	return handleExceptionInternal(ex, null, headers, status, request);
}
```
