### ISSUE TITLE
Plain `request`-scoped bean with `@Lazy` fails in a native image (due to missing detection of CGLIB lazy resolution proxies)

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-framework#29584]
Hi - I noticed what I think is a regression on the GraalVM/AOT handling of scoped beans 

This issue (errantly put in the spring boot tracker and closed) has the details of a reproducible example. 

https://github.com/spring-projects/spring-boot/issues/33366

**Comment by jhoeller** [comment]
Hey Josh, this is a variant of #29309 where we obviously fail to register the reflection hints for CGLIB proxy classes. As pointed out there by Ollie and Christoph, you can register those hints manually for the time being.

We detect CGLIB proxy classes by top-level bean inspection in `GenericApplicationContext.preDetermineBeanTypes`. Any internal exposure of CGLIB proxies is captured in terms of the generated classes (since that is a CGLIB-internal hook) but not visible for proxy hint registration (which happens at bean introspection level). The capture of generated classes is wider than proxy classes (also includes fast-class helpers etc), and only actual proxy classes need reflection hints on top. Our current runtime hint registration aims to be minimal there, avoiding unnecessary hints. We can possibly make this more lenient.

So for such scenarios, it would be good to understand why `GenericApplicationContext.preDetermineBeanTypes` is not able to see the affected CGLIB proxy classes and therefore not registering the corresponding runtime hints. Any analysis/debugging in that direction would be very helpful. From a quick glance, I wonder whether it has to do with the non-public visibility of `RequestContext`?

**Comment by jhoeller** [comment]
Alternatively, declaring the `ContextHttpController` constructor with an `ObjectProvider<RequestContext>` constructor instead should also work. I would generally recommend avoiding proxies for lazy-resolution purposes since this can always be replaced with a lightweight `ObjectProvider` arrangement. Or in this case, with a full-scale scoped proxy bean which is more efficient as well (since it is not on-demand per constructor but rather shared application-wide).

**Comment by jhoeller** [comment]
An update after some analysis: It seems that we do indeed have a gap in our attempts to pre-resolve lazy resolution proxies for AOT where we currently detect and register JDK proxies but not CGLIB proxies in some scenarios. I'll make this consistent for 6.0.3, closing that specific gap and therefore widening the scenarios that we can discover upfront.

This should also make the above scenario work as far as I can see. However, all the recommendations above stand nevertheless since it is generally a good idea to reduce unnecessary proxy requirements or make them exposed at the bean level at least.

**Comment by joshlong** [comment]
I've made the changes you suggested, and this works. Thanks! 

The only oddity is that it did work with the regular (non target-proxy) on the JRE. Each new request sees a new value for the `uuid`.
