### ISSUE TITLE
HTTP interface client does not call FormHttpMessageWriter when writing form data

### ISSUE THREAD

**Issue by li0180** [spring-projects/spring-framework#29615]
We are in the process of migrating to Spring 6 and are trying to leverage the new HTTP interface for WebClient. We have a CustomCodec to add form fields to every outbound request (see screenshot). However, it seems to us that this behavior is not working when wrapped with the new HTTP interface.
![image](https://user-images.githubusercontent.com/5499005/204843433-29a415d0-f0dc-4ef2-bc31-14ad17256921.png)

Here is a demo project that reproduces this issue: https://github.com/matthenry87/http-interface-form-fields-codec-bug

If you run the tests in the project, you can see the test that uses WebClient alone works as intended and the test that uses InterfaceClient does not.
![image](https://user-images.githubusercontent.com/5499005/204845491-a0d61a60-ad0f-4327-a7db-3f5bf18f0f6a.png)

Additionally, we are also curious about whether we are setting up our MultiValueMap correctly. Spring Docs says we can pass one string value. Does it support passing multiple if they are annotated with @RequestParam?
![image](https://user-images.githubusercontent.com/5499005/204846730-b9aff95a-31e6-4fee-a29d-f2e686ec86cb.png)

We are using Spring 6 and Spring Boot 3.

**Comment by rstoyanchev** [comment]
Thanks for the demo project!

`HttpRequestValues` serializes form data, and sets the body to a `byte[]`, and that's why `FormHttpMessageWriter` doesn't get involved. There is no reason to do it this way, however, and we could just as well set the body to a `MultiValueMap` instead, and let the configured codecs serialize it. 

> we are also curious about whether we are setting up our MultiValueMap correctly. Spring Docs says we can pass one string value. Does it support passing multiple if they are annotated with @RequestParam?

Yes it does and your sample is fine the way it is. Both the Javadoc for `@RequestParam` and the [reference docs](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#rest-http-interface) mention that you can pass a `MultiValueMap`. Are you looking at another place where this is not documented correctly?

**Comment by rstoyanchev** [comment]
Yes, you can.

**Comment by matthenry87** [comment]
@rstoyanchev Hello,

Would this not be considered a bug? Would we not expect that we would get the same behavior as a stand-alone WebClient when wrapping it in the ServiceProxy?

**Comment by matthenry87** [comment]
Ah, nevermind I see the commit :)
