### ISSUE TITLE
The last modified timestamps of files in spring-core JAR are incorrect

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#29633]
The last modified time of ``spring-core-5.3.24.jar`` file is incorrect, It can't be ``1980/2/1``, but the last modified time of ``spring-context`` is correct, It seems to have something to do with kotlin. Because ``kotlin-stdlib-jdk7-1.6.21.jar``, ``kotlin-stdlib-jdk8-1.6.21.jar``, ``kotlin-stdlib-common-1.6.21.jar`` are also wrong last modified time

![image](https://user-images.githubusercontent.com/13413715/205455047-6ca462e8-cd04-4d19-a1ea-d0d288a0c2c0.png)

**Comment by sbrannen** [comment]
Thanks for reporting this @brucelwl.

This applies to files within the `spring-core` JAR for 6.0.x as well.

**Comment by bclozel** [comment]
It looks like it was intentional. Maybe we should apply this for all Spring modules? See 50a0094a47bc

**Comment by sdeleuze** [comment]
My commit reverts the changes done via 50a0094a47bc25539ccca4cb184af53f44aff3f0 in order to ensure consistency across modules (those changes were specific to spring-core).

Reproducible builds are likely desirable, but it is a complex topic (see gradle/gradle#14819) that needs to be addressed portfolio wide, with a better control than what Gradle currently allows (for example to allow using EPOCH instead of the current 1980 date).

Basic tests did not show an obvious impact on testing avoidance with modern Gradle versions.
