### ISSUE TITLE
`@JsonDeserialize(builder = ...)` does not work in GraalVM native image

### ISSUE THREAD

**Issue by dilipdhankecha2530** [spring-projects/spring-framework#29646]
## Overview

We update our spring boot version to 3.0.0 and build native image with below mentioned grallvm version.

```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```

While call the API which use Jackson-databind annotation then it will return with an error.

## Related Issues

- #29426
- #29386

**Comment by bclozel** [comment]
As part of this issue, we should consider whether we want to introduce specific AOT rules for Jackson. Since there are many features and variants in Jackson, I'm not sure we should invest in that area.

**Comment by bclozel** [comment]
We could expand the scope of our `@RegisterReflectionForBinding` and use it to process method parameters and return types of controller methods.

This means supporting various features like:

* `@JsonNaming` strategies
* `@JsonDeserialize`, `@JsonSerialize`
* `@JsonGetter`, `@JsonSetter` `@JsonValue`
* `@JsonCreator`
* Detecting `@JsonSubTypes` types if only the interface type is detected through AOT processing

We could also refine the binding algorithm to include/ignore `@JsonIgnoreProperties`, `@JsonIgnore` and `@JsonIgnoreType`, `@JsonAutoDetect` annotated elements.

All of that should also support custom annotations with `@JacksonAnnotationsInside`.
Note that all of those features can be turned off by a Jackson configuration flag through the `MapperFeature`, which is not accessible during the AOT phase.

With that in mind, I'm not in favor of implementing Jackson-specific behavior, but keep using our general "reflection for binding" that matches a lot of cases already. I think this should be handled in a GraalVM `Feature` or better, through a build-time mechanism provided by the Jackson project itself: keeping up with all the changes in Jackson is an important maintenance burden in this space.

**Comment by mhalbritter** [comment]
> keeping up with all the changes in Jackson is an important maintenance burden in this space.

I agree on not implementing Jackson-specific behavior.

**Comment by sdeleuze** [comment]
On one side I understand our reluctance related to the maintenance burden especially given the various annotations we would have to support, on another side:
 - We need to be consistent. Why would we support JPA `@Converter` and `@Convert` annotation like we do in `PersistenceManagedTypesBeanRegistrationAotProcessor` and not Jackson similar use case?
 - Spring is already in charge of providing hints for classes serialized by Jackson via the knowledge it has of related classes via for example Spring MVC/WebFlux programming model or `RegisterReflectionForBinding`, conceptually this is similar.
- The end user will have to go threw the pain of multiple native build failure which is not ideal
- Jackson is probably the most popular dependency we support

Since `BindingReflectionHintsRegistrar` already has some logic related to the handing of `@JacksonAnnotation`, my proposal would be simply to refine that logic to add invoke hints on declared constructors for class attribute of annotations annotated with `@JacksonAnnotation`. Looks like a small change, rather maintainable which translate as a big improvement for native users. Any thoughts?

**Comment by sbrannen** [comment]
> Since `BindingReflectionHintsRegistrar` already has some logic related to the handing of `@JacksonAnnotation`, my proposal would be simply to refine that logic to add invoke hints on declared constructors for class attribute of annotations annotated with `@JacksonAnnotation`. Looks like a small change, rather maintainable which translate as a big improvement for native users. Any thoughts?

I agree that not doing anything additional for Jackson use cases will put a large burden on our users. If the Jackson team some day introduces a GraalVM `Feature` (or similar), that would of course be great, but who knows if that day will ever come.

So, if we can make a big improvement with such a small change like you've proposed Sebastien, I am in favor of that.

**Comment by sdeleuze** [comment]
After discussing with @bclozel and @jhoeller, let's give it a try. If the implementation is more involved than expected, we may reconsider implementing this.
