### ISSUE TITLE
why PersistenceExceptionTranslationInterceptor only concern RuntimeException?

### ISSUE THREAD

**Issue by aximo** [spring-projects/spring-framework#29724]
Hi, anybody give some idea  why PersistenceExceptionTranslationInterceptor only concern RuntimeException?

as some driver will give the exception such as `org.postgresql.util.PSQLException` or `java.sql.SQLException`

we want to convert these exception to others and can not be handled at here via PersistenceExceptionTranslator

it is a design cursoriness or a special consideration?

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by aximo** [comment]
ok, i post it at https://stackoverflow.com/questions/74884586/why-persistenceexceptiontranslationinterceptor-only-concern-runtimeexception

there also 
https://stackoverflow.com/questions/7125837/why-does-transaction-roll-back-on-runtimeexception-but-not-sqlexception
https://stackoverflow.com/questions/12712742/why-isnt-spring-rolling-back-on-runtimeexception

i will close this issue
