### ISSUE TITLE
Compatibility with Hibernate ORM 6.2

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#29736]
I've just tried to run a build of Spring Data JPA on [Hibernate 6.2 CR1](https://in.relation.to/2022/12/22/orm-62-cr1/). It apparently [changes a couple of default settings](https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html#enhancement), which now cause `SpringPersistenceUnitInfo.addTransformer(…)` being called, which blows up with an `IllegalStateException` if no `LoadTimeWeaver` is set.

I am not certain how we want to handle this, but as it looks like the current default bootstrap settings will either have to handle that call more leniently or we will have to change our default settings. Unfortunately, the tickets linked to from the migration guide indicate that the flags are deprecated for removal without replacement.

The comments in `EntityManagerFactoryBuilderImpl` seem to indicate that they only assume the call to `….addTransformer(…)` to have an effect in EE environments anyway. I could get this working with a local copy of `SpringPersistenceUnitInfo` tweaked to drop the invocation if no load time weaver was specified instead of throwing the exception. SD JPA builds fine then.

**Comment by jhoeller** [comment]
Following that advice, `SpringPersistenceUnitInfo` just logs a warning in case of no `LoadTimeWeaver` setup now, leniently ignoring the given transformer in such a case.

If anything else can be addressed for Hibernate ORM 6.2 RC1 or a follow-up RC, there's still a chance for the 6.0.4 release. Otherwise we'll address any remainders in 6.0.5.
