### ISSUE TITLE
Support method validation for an interface only proxy like an HTTP interface client

### ISSUE THREAD

**Issue by DanielLiu1123** [spring-projects/spring-framework#29782]
I want to validate the params on client side, it works fine when using `spring-cloud-openfeign`, but it doesn't work when using `HttpExchange`. 
```java
@Validated
public interface EchoClient {
    @GetExchange("/echo")
    String echo(@RequestParam("message") @NotNull String message);
}
```

**Comment by sbrannen** [comment]
Where does that `@Validate` annotation come from?

Do you perhaps mean Spring's `@org.springframework.validation.annotation.Validated`?

If so, have you registered an `org.springframework.validation.beanvalidation.MethodValidationPostProcessor` bean?

**Comment by DanielLiu1123** [comment]
> Do you perhaps mean Spring's `@org.springframework.validation.annotation.Validated`?

yep~

> If so, have you registered an `org.springframework.validation.beanvalidation.MethodValidationPostProcessor` bean?

I have `spring-boot-starter-validation` on classpath, so there is a `MethodValidationPostProcessor` bean.

I've looked into the proxy bean, there are two advisors, I think the second one is used to method validation, but it doesn't work.
<img width="756" alt="image" src="https://user-images.githubusercontent.com/62151295/211205844-225ac973-5fb3-48f7-8042-b67026e89914.png">

**Comment by sbrannen** [comment]
Thanks for the feedback. We'll look into it.

**Comment by rstoyanchev** [comment]
The proxy advisors are not in the right order indeed. The one for `@HttpExchange` doesn't delegate, and should go last, but is always added first. I was able to use an `AdvisedSupportListener` that updates the order whenever there is an advice change.

Now `MethodValidationInterceptor` is getting called but raises an ISE with "Target must not be null". From what I can see it needs the target in order 1) get the `@Validated` from the class to check for validation groups, and 2) for invoking bean validation. 

So it looks like method validation via `@Validated` doesn't work for interface-only proxies, unless I'm missing something, but I'm wondering if it can be made to work? Perhaps by passing the type-level `@Validated` into the the interceptor so it doesn't have to look it up. As for Hibernate Validator, it asserts that the target isn't null but I'm not sure if it needs much else from the target, or would passing the proxy itself work. /cc @jhoeller 

It's also interesting that it works with spring-cloud-openfeign. @DanielLiu1123, do you get an actual `ConstraintViolation` with spring-cloud-openfeign since in the given example you would also get an IAE from the `HttpServiceProxyFactory` code for such a required `@RequestParameter`.

**Comment by DanielLiu1123** [comment]
I personally think the ability to support `@Validated` on interface (feign, httpExchange) is a very useful feature. It can unify client-side and server-side constraints (server-side implements the interface).

**Comment by rstoyanchev** [comment]
This has been addressed by improving Spring AOP support for interface-only proxies where there is no target class, and in which case the last AOP advisor does the actual work and should always remain last in the order. So this change should help not only method validation, but also any other AOP advice applied to an HTTP interface client.
