### ISSUE TITLE
Introduce `HttpServiceProxyFactory#createClient` Kotlin extension

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#29942]
To allow `createClient<TestHttpService>()` syntax instead of `createClient(TestHttpService::class.java)`.

**Comment by srydberg** [comment]
@sdeleuze I get the below error, and this change seems to break java modules since you are exporting a package already included in spring-web from the spring-webflux module. Is this tracked or do we have a workaround?

`...module-info.java:1: error: module com.module-a reads package org.springframework.web.service.invoker from both spring.webflux and spring.web
module com.module-a {
^`

**Comment by sbrannen** [comment]
@srydberg, that appears to have been oversight.

Would you mind creating a new ticket to track this?

**Comment by sdeleuze** [comment]
I have created #30042 related issue since I was about to push the fix, so no need to create it. Thanks for catching this.

**Comment by srydberg** [comment]
Thanks alot 🙇🏻‍♂️
