### ISSUE TITLE
WebClient now requires scheme

### ISSUE THREAD

**Issue by gm2552** [spring-projects/spring-framework#30053]
**Affects:**  SpringBoot 3.0.3/Spring Framework 6.0.5

I have multiple WebClient instances that uses a target's name without a scheme.  Ex:

```
var client = WebClient.builder().baseUrl("service1").build();
		
client.get().retrieve().bodyToMono(String.class)...
```
With SpringBoot 3.0.2 and below (including all current version of SpringBoot 2.x including 2.7.9), the above code will
resolve `service1` to a DNS name and execute the `GET` request and expected.  

As I upgrade to SpringBoot 3.0.3, the above code will now throw an exception with the following error:

```
Caused by: java.lang.IllegalArgumentException: URI is not absolute: service1
``` 

It appears the framework is expecting the target name to now include a scheme prefix such as `http://` or `https://`.
Is this behavior an intended change or a bug?

**Comment by rstoyanchev** [comment]
This is due to dd3dc2d0 from #29954. It looks like Reactor Netty's the [HttpClient is less strict](https://github.com/reactor/reactor-netty/blob/abb9ccba83887c693b65ae8d798c16524ddf8b17/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFinalizer.java#L65-L84) when the URI is provided as a String, and fills in some defaults in `UriEndpointFactory`.

We can check if the URI is absolute, and if not, fall back on `uri.toString()` as it was before 6.0.5.

**Comment by breun** [comment]
Using Spring Framework 6.0.11 throws `org.springframework.web.reactive.function.client.WebClientRequestException: Host is not specified` for this code, which is kind of surprising for a URI which _only_ contains a hostname.
