### ISSUE TITLE
Exception is thrown in AsyncTaskExecutor, and the result is returned twice

### ISSUE THREAD

**Issue by babyblue94520** [spring-projects/spring-framework#30181]
**Affects:** \<5.3.23>

---

I customized AsyncTaskExecutor to throw RejectedExecutionException when the queue is full, but I got twice the error message.

[demo](https://github.com/babyblue94520/async-request-example)

**Comment by sbrannen** [comment]
Hi @babyblue94520,

Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

As a side note, you should avoid changing the state of your `CustomAsyncTaskExecutor` bean within your `TestController`. `CustomAsyncTaskExecutor` is registered as a shared _singleton_ bean. Consequently, its configuration should not be changed at runtime.

**Comment by babyblue94520** [comment]
I spent some time writing this example to fully reproduce the problem,
Changing __CustomAsyncTaskExecutor__ configuration on the fly is for the scenarios mentioned in [README.md](https://github.com/babyblue94520/async-request-example/blob/master/README.md).

The current tracking result is that when __DispatcherServlet__ processes async request, if the task throws an exception before entering AsyncExecutor, the data status in __asyncManager__ is not processed normally, causing the request to enter __DispatcherServlet__ again.
