### ISSUE TITLE
is  Spring-framework-6 support JPMS?

### ISSUE THREAD

**Issue by cdtuql** [spring-projects/spring-framework#30276]
when I develop a SpringBoot 3 Application ,It tell me the information "Field productRepository in com.tuql.sbmtest.services.ProductService required a bean of type 'com.tuql.sbmtest.repositories.ProductRepository' that could not be found." ,I use the jpa

**Comment by cdtuql** [comment]
Can you tell me what to do

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
