### ISSUE TITLE
How to upload multipart files without a temporary directory

### ISSUE THREAD

**Issue by pcgeng** [spring-projects/spring-framework#30284]
We are using `MultipartFile` to do the file upload in spring boot, but if we upload a large file (>5GB) through it, the uploaded file will be written to a temporary directory first and then copied to a specific directory (whcih is specified in our code) on disk. Actually we want to monitor the upload progress, but for the first step (upload to a temporary directory) we cannot monitor the progress of this part, so how can we upload files directly to the specific directory without first uploading to a temporary directory? Is there any configuration for doing this?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
