### ISSUE TITLE
Which spring core version is compatible with springboot version2.6.6 and which is not any vulnerability

### ISSUE THREAD

**Issue by surjitkv** [spring-projects/spring-framework#30346]
Hi any one,can pls confirm which spring core version is supported  by springboot version 2.6.6 which is not any vulnerability

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
