### ISSUE TITLE
Reject null and empty SpEL expressions

### ISSUE THREAD

**Issue by ryan-c-wicks** [spring-projects/spring-framework#30371]
We have upgraded from Spring Framework 5.2.23 to 5.2.24 and seems now we are getting some NullPointerExceptions.  Looking in the stack traces we find that issues are in:
spring-framework-5.2.24.RELEASE\spring-expression\src\main\java\org\springframework\expression\spel\standard\InternalSpelExpressionParser.java

With 5.2.24 there is now a 'checkExpressionLength(expressionString);' which calls:

```
	private void checkExpressionLength(String string) {
		if (string.length() > MAX_EXPRESSION_LENGTH) {
			throw new SpelEvaluationException(SpelMessage.MAX_EXPRESSION_LENGTH_EXCEEDED, MAX_EXPRESSION_LENGTH);
		}
	}
```

 if 'string' is null then string.length throws NullPointerException - Is this the intended behaviou of checkExpressionLength or is this a bug?

**Comment by quaff** [comment]
Why `string` is null?

**Comment by sbrannen** [comment]
The `expressionString` should never be `null`. If it is `null`, that is a user error.

`org.springframework.expression.ExpressionParser.parseExpression(String)` and related methods accepting the `expressionString` do not specify it as `@Nullable`.

Interestingly enough, prior to #30325, the following test passed.

```java
	@Test
	void nullExpression() {
		ExpressionParser parser = new SpelExpressionParser();
		String expression = null;
		Expression expr = parser.parseExpression(expression);
		Object result = expr.getValue();
		assertThat(result).isNull();
	}
```

However, that was not by design. Rather, that was by accident.

Supplying a `null` expression internally resulted in an expression created by concatenating `null` with `"\0"` in the constructor for `org.springframework.expression.spel.standard.Tokenizer.`. Thus, supplying `null` as the expression was effectively equivalent to supply `"null"` as the expression.

We currently do not have any planned releases for 5.2.x. Thus if you are encountering this issue with Spring Framework 5.2.x, please ensure that you do not supply a `null` reference as the expression string to parse.

For Spring Framework 5.3.x and 6.x, I think we should introduce an explicit `Assert.notNull(...)` check for the user-supplied expression string.

**Comment by sbrannen** [comment]
In light of the above, I am repurposing this ticket to fail early if `null` or an _empty_ string is provided as the SpEL expression to parse.
