### ISSUE TITLE
Retry template buffer capacity

### ISSUE THREAD

**Issue by vinay120** [spring-projects/spring-framework#30412]
We recently replaced retryTemplate with WebClient but got the DataBufferLimit exception: Exceeded limit on max bytes to buffer: 262144. what is the buffer limit for the retry template? I couldn't find that value anywhere. it's definitely more than 262144, as post revert, it's working fine.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
