### ISSUE TITLE
Refine allocations for improved memory profile when creating a large amount of proxy instances

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#30499]
`JdkDynamicAopProxy` allocates a lot of objects in `findDefinedEqualsAndHashCodeMethods` and in the constructor via `AopProxyUtils.completeProxiedInterfaces` (object arrays, collection instances) to compute whether the interfaces implement hashCode/equals methods. 

This effect gets visible when creating several thousand (100000s) proxy instances. It would be neat to either have a built-in cache for these values or to be able to override these features so Spring Data could supply values from its caches.

Recorded allocations:

<img width="1658" alt="Allocations ProxyFactory" src="https://github.com/spring-projects/spring-framework/assets/1035015/337154dd-ee1b-4ee6-b33d-1290ee1f8b54">

Right now, this isn't possible because the methods are `private` or being called within the constructor. Also, the implementation of `invoke` uses several package-private fields of `ProxyConfig` and other protected components.

We found this aspect while debugging a more significant memory issue via https://github.com/spring-projects/spring-data-commons/issues/2831

**Comment by jhoeller** [comment]
I've introduced a `ProxiedInterfacesCache` object that we cache in the `AdvisedSupport` instance along with the existing method cache there. `JdkDynamicAopProxy` detects that existing metadata cache for repeated creation of a particular proxy.

It is important to create such repeated proxies from the same `AdvisedSupport` (`ProxyFactory`) instance, otherwise the cached metadata won't be preserved. This is true for existing AOP cache arrangements as well, so generally recommendable.
