### ISSUE TITLE
Support for AOT processing with GraalVM tracing agent is not consistent

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#30511]
## Overview

In Spring Framework 6.0.9, we made changes to the _Spring TestContext Framework_ (TCF) to allow AOT processing with the GraalVM tracing agent and Native Build Tools.

Specifically, we introduced a `TestAotDetector` utility that is specific to the TCF. This detector considers the current runtime to be in "AOT runtime mode" if the `spring.aot.enabled` Spring property is set to `true` or the GraalVM `org.graalvm.nativeimage.imagecode` JVM system property is set to any non-empty value other than `agent`.

Since Spring Boot's testing support uses `AotDetector.useGeneratedArtifacts()` in various places, the Boot team should investigate whether Spring Boot Test should migrate from `AotDetector` to `TestAotDetector`.

## Related Issues

- https://github.com/spring-projects/spring-framework/issues/30281

**Comment by mhalbritter** [comment]
> The agent should detect the codepath used on native to generate the most accurate hints, so I don't think we should change NativeDetector behavior.

I'm not sure I agree to that line of reasoning. IMHO the `NativeDetector` should return `true` if running a native image and `AotDetector` should return `true` if running in AOT mode (which is always the case in native image)

When running my integration tests while not using AOT mode with the agent attached, I would assume that it will generate hints for all dynamic behavior and that both `NativeDetector` and `AotDetector` return `false`.

If I want to generate hints with the agent for the AOT code path, then I would need to run the tests in AOT mode, too.

What's the idea behind `NativeDetector` or `AotDetector` return `true` when running with an attached agent? Better developer experience because users can run integration tests and only get hints for the AOT codepath out of the box?

**Comment by sdeleuze** [comment]
`NativeDetector` is on purpose pretty unopinionated and flexible, as soon as `org.graalvm.nativeimage.imagecode` is set it returns `true`, which means the app runs using one of the flavors of native image. In practice, it is set to [`buildtime` or `runtime` by `native-image` compiler](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java), or to [`agent` by various tools](https://github.com/oracle/graal/issues/2395#issuecomment-1253553254) that need to emulate native code path on the JVM.

This behavior looks correct to me as for some use cases, it is important to exercise the native code path on the JVM. The goal is not just to have more optimal hints, the goal is also to not break when running the app on native with tracing agent generated hints due to missing hints.

**Comment by snicoll** [comment]
> This behavior looks correct to me as for some use cases, it is important to exercise the native code path on the JVM

Yes, but to be consistent with that statement, said  code should run with AOT optimizations and it obviously can't. It looks wrong to me to require the native specific code path to run, while the most important bit, the one that avoids a bunch of code paths thanks to AOT, doesn't run. `NativeDetector` is obviously very generic on purpose but having it enabled while AOT is not (in the form of optimization, or execution) feels wrong to me.
