### ISSUE TITLE
Update Javadoc and reference doc for WebMvcConfigurer to mention Boot's HttpMessageConverters

### ISSUE THREAD

**Issue by joca-bt** [spring-projects/spring-framework#30538]
The documentation for [`configureMessageConverters`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurer.html#configureMessageConverters(java.util.List)) states:

> Note use of this method turns off default converter registration. Alternatively, use [extendMessageConverters(java.util.List)](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurer.html#extendMessageConverters(java.util.List)) to modify that default list of converters.

This does not seem to be the case. My expectation from the documentation is that if I defined this override, my application will just use the converters I register manually there. However, if I inspect the list it contains the default converters. I can clear the list but the behaviour doesn't seem to match the documentation.

I have attached a simple application that shows the issue ([test.zip](https://github.com/spring-projects/spring-framework/files/11554358/test.zip)).

**Comment by rstoyanchev** [comment]
`configureMessageConverters` works as documented if used on its own. However, in a Boot application, the `WebMvcAutoConfiguration` adds message converters through its `HttpMessageConverters` mechanism, which by default includes any `HttpMessageConverter` beans, and default converters. So the way to customize this in a Boot application is [through HttpMessageConverters](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.message-converters), or use the `extendMessageConverters` which lets you customize the resulting list at the end.

I'll update the Javadoc to at least mention this, but aside from that it's expected behavior.

For future reference, please provide a Maven or Gradle configured sample. You can use https://start.spring.io/.

**Comment by joca-bt** [comment]
If I add a bean like

```
@Bean
public HttpMessageConverters httpMessageConverters() {
    return new HttpMessageConverters(...);
}
```

What is happening is that I am overriding the beans provided by Spring Boot (`StringHttpMessageConverter` and `MappingJackson2HttpMessageConverter` in my case) however the 6 default ones from Spring will still be there.

Is there maybe another bean to override everything?

The doc mentions

> Any HttpMessageConverter bean that is present in the context is added to the list of converters. You can also override default converters in the same way.

but it is not clear which bean should be overridden.
