### ISSUE TITLE
SpringBeanContainer not called with Hibernate ORM 6.2

### ISSUE THREAD

**Issue by vaclavsvejcar** [spring-projects/spring-framework#30545]
Hello,

did something related to `ApplicationContextAware` behaviour change between Spring Boot 3.0.6 and 3.1.0? I have custom Hibernate `IdentifierGenerator` that also implements `ApplicationContextAware` because it's POJO to access the spring context:

```java
import org.hibernate.HibernateException;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.id.IdentifierGenerator;
import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@NonNullApi
public class SnowflakeIdentifierGenerator implements IdentifierGenerator, ApplicationContextAware {

    private ApplicationContext applicationContext;

    @Override
    public Object generate(SharedSessionContractImplementor sharedSessionContractImplementor, Object o) throws HibernateException {
        return applicationContext.getBean(SnowflakeIdGenerator.class).nextId();  // NPE happens here
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }
}
```

This works fine with Spring Boot 3.0.6, but after upgrading to 3.1.0, the `ApplicationContext` is always `null`.

**Comment by wilkinsona** [comment]
Just to hopefully reduce any potential confusion, as I understand it `hibernate.cdi.extensions=true` is only needed for Hibernate to load extensions through `SpringBeanContainer`. Without this setting, converters and listeners were still loaded from `SpringBeanContainer`.

**Comment by 1dEraNCeSIv0** [comment]
For anyone else stumbling upon this, wondering why their extensions are not loaded via the `SpringBeanContainer` despite setting `hibernate.cdi.extensions=true`:

The implementation of [HHH-16069](https://hibernate.atlassian.net/browse/HHH-16069) has a bug, as reported in [HHH-16935](https://hibernate.atlassian.net/browse/HHH-16935), affecting Hibernate since version 6.2 and hence Spring Boot since version 3.1. At the time of writing there's no fix on Hibernate's side yet, as far as I could find anyway.

The result of this bug is that when building an entity manager via the `EntityManagerFactoryBuilder` the flag will actually be inverted before applying, Hibernate's `MetadataBuilderImpl.disallowExtensionsInCdi` returns `true` if  `hibernate.cdi.extensions=true` whereas it should return `false`.

I cannot tell if `hibernate.cdi.extensions=true` works correctly for use cases outside of this one.

**Comment by quaff** [comment]
@1dEraNCeSIv0 I've created https://github.com/hibernate/hibernate-orm/pull/7049.

**Comment by quaff** [comment]
> @1dEraNCeSIv0 I've created [hibernate/hibernate-orm#7049](https://github.com/hibernate/hibernate-orm/pull/7049).

It's merged into main branch by commit https://github.com/hibernate/hibernate-orm/commit/f309a88552ef8ccd9f47fe4214641ece151e472c, and not backported to 6.2.x and 6.3.x yet.
