### ISSUE TITLE
How to disable chunked transfer when using declarative http interface upload files?

### ISSUE THREAD

**Issue by yazinnnn** [spring-projects/spring-framework#30553]
related issue #20468 

is there any way to disable chunked transfer or calculate encoded part's content-length when using declare http interface ?

e.g.

```kotlin
@HttpExchange("/V1.0")
interface Client {

    @PostExchange("upload")
    fun postFile(
      @RequestPart file: Resource, 
      //@RequestHeader("Content-Length") contentLength: Int
    ): Mono<String>

}
```

how can i set the correct header?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
