### ISSUE TITLE
Log a warning when `commons-logging` is in the classpath

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#30575]
As mentioned in the [reference documentation](https://docs.spring.io/spring-framework/reference/core/spring-jcl.html#page-title), `spring-jcl` provides its own Commons Logging bridge, with classes like `org.apache.commons.logging.LogFactory`.

When `commons-logging:commons-logging` dependency is in the classpath (either included directly or transitively via dependency like `com.opencsv:opencsv` for example), it leads to dulicated classpath entries on the JVM and broken native compilation due to a build-time initialization error (see oracle/graal#6711 related issue).

This issue intends to introduce a warning when both `spring-jcl` and `commons-logging` are found in the classpath, to hint about excluding such `commons-logging` dependency.

**Comment by vpavic** [comment]
I can try with removing `spring-jcl` indeed, thanks for the suggestion.

> The log statement is rather friendly in its wording already, any suggestion for what we could do better there?

The wording itself is fine, but if someone decides (or has to) live with this, the fact that warning is written directly to stdout is a bit inconvenient, especially if your infra expects log entries of a certain structure (for example, JSON).

Additionally, after picking up the upgrade I originally had this logged multiple times - due to having `commons-logging` pulled-in both transitively and as the aforementioned shaded copy.

It's a bit unfortunate that this requires so much fiddling (if the solution really is to exclude `spring-jcl`) having in mind the component that logs this warning was (to my understanding from reading https://github.com/spring-projects/spring-framework/issues/21127) introduced exactly to allow `spring-jcl` and `commons-logging` to coexist.
