### ISSUE TITLE
Please suggest as solution to disable hostname verification in spring-cloud-gateway when ssl enabled?

### ISSUE THREAD

**Issue by sreeraksha** [spring-projects/spring-framework#30582]
Hi Team,

Request you to please suggest how I can disable hostname verification while using Spring cloud gateway which runs on embedded Netty server.

Thank you!

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
