### ISSUE TITLE
Excuse me, why is there no release version of the kit in jfrog

### ISSUE THREAD

**Issue by dmcisgood** [spring-projects/spring-framework#30674]
spring-release-5.3.9-dist.zip can be found in jfrog before, but it suddenly disappeared this time. May I ask why and where else can I find this tool package

**Comment by bclozel** [comment]
I think this is due to [the repo.spring.io permission changes](https://status.spring.io/incidents/rl38k61jk6hr).

We have never published those resources on maven central. Maybe we can somewhat make that available in some other way. Right now, SNAPSHOT versions are still available on the snapshot repository [here](https://repo.spring.io/ui/native/snapshot/org/springframework/spring/) and [here](https://repo.spring.io/ui/native/snapshot/org/springframework/framework-docs/). They don't seem very popular these days and this is the first request we are getting for a very long time. 

May I ask what's the main use case for downloading this on your side?

**Comment by quaff** [comment]
> I think this is due to [the repo.spring.io permission changes](https://status.spring.io/incidents/rl38k61jk6hr).
> 
> We have never published those resources on maven central. Maybe we can somewhat make that available in some other way. Right now, SNAPSHOT versions are still available on the snapshot repository [here](https://repo.spring.io/ui/native/snapshot/org/springframework/spring/) and [here](https://repo.spring.io/ui/native/snapshot/org/springframework/framework-docs/). They don't seem very popular these days and this is the first request we are getting for a very long time.
> 
> May I ask what's the main use case for downloading this on your side?

I used to download this for legacy application which manage dependencies manually.

**Comment by dmcisgood** [comment]
To demonstrate the basic use of spring to students, introduce dependencies manually and then through maven. So I need to download this kit to get spring dependencies

I had version 5.3.9 of the toolkit and tried to download the updated version and found that it was no longer available on jfrog.

Now I know about the situation, and I don't have to ask for the latest version, thank you

**Comment by bclozel** [comment]
Yeah distributing all dependencies as a zip is a bit outdated these days as we assume developers should download artifacts from maven central now. I'm closing this issue as a result.

**Comment by rtummuru** [comment]
May be good for students who want to learn. Helps to setup eclipse env easily. May be its good to have archived jars for easy download.

**Comment by sbrannen** [comment]
> May be good for students who want to learn. Helps to setup eclipse env easily. May be its good to have archived jars for easy download.

I don't think that's a good way for students to learn Spring.

I would recommend telling students to use https://start.spring.io to download a complete Spring Boot app that they can import into Eclipse IDE, IntelliJ IDEA, etc.
