### ISSUE TITLE
Investigate running tests for all supported Jetty versions

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#30700]
We could use https://github.com/spring-gradle-plugins/compatibility-test-plugin to run automated tests on Jetty 12. Right now, it's manual.

**Comment by jhoeller** [comment]
While I can see the compatibility test plugin being useful for our purposes, this 6.1 issue specifically seems to be superseded by the general Jetty 12 upgrade that we do for 6.1 RC1 now: https://github.com/spring-projects/spring-framework/issues/30698 - along with the Jetty clients, WebFlux server will be requiring Jetty 12 as well. Just regular Servlet-based deployments will remain naturally compatible with Jetty 11 since they have no Jetty-specific code at all but that's not really worth a specific test setup.
