### ISSUE TITLE
Align KeyValues of Scheduled-annotated observability with OpenTelemetry conventions

### ISSUE THREAD

**Issue by arik-dig** [spring-projects/spring-framework#30721]
following comment https://github.com/spring-projects/spring-framework/issues/29883#issuecomment-1591896876 it seems that provided tag entries are `method.name` and `target.type`
so first I think that target.type is missing the package name so the type would would be fully qualified name.
second, in order to be compatible with OpenTelemetry maybe you should consider use the standard [Semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#source-code-attributes) 
so `method.name` would become `code.function`
and `target.type` would become `code.namespace` (including the package name of course)

**Comment by jonatan-ivanov** [comment]
Let me try to add a few details.

As far as I know @arik-dig's use case is trying to connect spans to code. Basically spans that were emitted because `@Scheduled` is now instrumented, I guess in order to do this the fully qualified class name is needed.

As far as I know the linked semantic conventions are not stable so I think it worth considering if it makes more sense than the current one but I would definitely not make the change only the sake of being compatible with it since OTel semantic conventions are subject to change, we can be compatible today but that might change tomorrow.

**Comment by bclozel** [comment]
Using the full class name makes sense. Using `code.function` and `code.namespace` as KeyValues sounds reasonable although quite generic. I'll consider this with this issue.
