### ISSUE TITLE
The `HttpServiceProxyFactory` allows for the customization of request metadata generation

### ISSUE THREAD

**Issue by DanielLiu1123** [spring-projects/spring-framework#30733]
The current `HttpServiceProxyFactory` only supports handling annotations based on `@HttpExchange`. However, in certain scenarios, users may need to generate HTTP request based on custom annotations. For example, some `Spring Cloud OpenFeign` users prefer or have already been accustomed to using annotations based on `@RequestMapping`, or some may want to generate HTTP request based on `jakarta.ws.rs-api` annotations.

If the framework allows users to determine the logic for generating request metadata instead of being "hardcoded" within the framework, it would greatly enhance its extensibility.

**Comment by rstoyanchev** [comment]
In general nothing against flexibility, but specifically for `@RequestMapping` annotations, those were designed for server side use and their semantics are not neutral to client vs server use. Mapping with URL patterns vs declaring a concrete URL is just one example, but there are many others.

We created `@HttpExchange` annotations specifically for this reason. The method signature is largely compatible with `@RequestMapping` in terms of supported annotations and method arguments, but far from the same. The former is a subset of the latter, as it is focused on declaring a concrete request rather than on mapping requests to a server handler. 

Theoretically, given that `@HttpExchange` is neutral to client vs server, and so it could be supported it on the server side as an alternative to `@RequestMapping`. You would just need to accept working with a more limited range of options for the method signature. The other way around, however, supporting `@RequestMapping` for client side use, is not something we are going to do. It's what Spring Cloud Feign did and caused many issues.

Keep in mind also that the annotation and its attributes is just one side. The other is support for specific types of arguments and annotations. In that sense, you can't really only customize the annotation. You also need to support its semantics, including argument types and annotations. In other words it wouldn't be that simple to support `jakarta.ws.rs-api` annotations.

Is it just what you are accustomed or something, or is there some other reason for this?

**Comment by DanielLiu1123** [comment]
Thank you for your response.

Firstly, I understand that `@RequestMapping` is specifically designed for server-side implementation, and it has numerous attributes that are not suitable for the client-side. However, my intention is not to support `@RequestMapping` as a client-side implementation, but rather to provide the capability to support other annotations.

Currently, `HttpServiceProxyFactory` supports custom parameter resolution by implementing `HttpServiceArgumentResolver`. Therefore, in theory, I can support all method parameter types and method parameter annotations within the `jakarta.ws.rs-api` annotations (although I am aware that it would require a significant amount of work to support them). At the very least, I can achieve this because Spring provides such an extension interface.

However, the question remains: how can I customize the request method and URL? (I understand that the URI and HttpMethod in method parameters can fulfill this functionality.) The answer is that there is currently no way to do so, as Spring does not provide an interface for extending this capability. Therefore, we are limited to using annotations based on `@HttpExchange`.

My main point is that providing an extension interface like `HttpRequestValuesResolver` would not have any negative consequences. Its functionality would be similar to that of `HttpServiceArgumentResolver`. Spring already provides default implementations internally to handle method parameter annotations, such as `@RequestBody` and `@RequestParam`. Similarly, within the framework, an internal implementation could be introduced to support annotations based on `@HttpExchange` (possibly named `HttpExchangeHttpRequestValuesResolver`).

**Comment by rstoyanchev** [comment]
@DanielLiu1123, providing flexibility isn't always a net positive. Sometimes it's important to understand the exact use case in order to shape the solution and understand where it belongs, and the constraints and limitations are.

For example, you agree that server mapping support is useful, and if that's what you're actually after, then that's what we can focus our efforts on instead, and solve the problem in a way that is more broadly useful, and perhaps meets even more requirements.

Having an example of very concrete requirements is what would help the most to advance this issue.

**Comment by rstoyanchev** [comment]
Thanks for elaborating, that's very helpful. We'll consider what we can do.

**Comment by rstoyanchev** [comment]
I've created #30913 to support server handling with `@HttpExchange`. We are targeting 6.1 M4 already for that.

For the extension point in `HttpServiceProxyFactory`, we don't want to make this a permanent feature what is meant to be a short term solution. The method annotation used is connected with the method signature in terms of its semantics, and supported inputs and outputs. I see how it helps you to achieve your goal, but it doesn't make sense broadly since `@RequestMapping` methods support many more arguments when used on the server side.

If your goal is to switch your existing applications to use the HTTP interface client, replacing `@RequestMapping` with `@HttpExchange` should be the easy part. How well it works from there is the bigger question, but that's unrelated to which method annotation is used. On the server side you can extend `RequestMappingHandlerMapping` and override `getMappingForMethod` to populate the `RequestMappingInfo` from `@HttpExchange`. That should be really straight forward and it's what we are going to do for 6.1.
