### ISSUE TITLE
websocket blocked when  spring mvc cors with websocket

### ISSUE THREAD

**Issue by cjdxhjj** [spring-projects/spring-framework#30804]
**Affects:** \<Spring Framework version>
6.0.10
---

my websocket config is
![image](https://github.com/spring-projects/spring-framework/assets/5616997/d46c200c-fedb-4d02-9781-68b012436984)
my webmvc cors config is 
![image](https://github.com/spring-projects/spring-framework/assets/5616997/9997098a-4056-4520-a1ad-5f4c7acba84a)
when i use sockjs it fire an error
![image](https://github.com/spring-projects/spring-framework/assets/5616997/23e36a34-5ba8-4993-b804-b23d58fdb9d8)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
