### ISSUE TITLE
@Request body doesn't attach fields like iNN kPP

### ISSUE THREAD

**Issue by dennis-systems** [spring-projects/spring-framework#30877]
Using spring v. 3.0

Request body object looks like this:

{
  "name" : "test", 
  "iNN" : "12313"

}

Object model contains two fields 
name
iNN

when I do @RequestBody Object
I got name filled out and iNN not filled out.
if  I change name to inn this will work.

From my point of view it's a bug.

Please assist

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

We have tests that validate this behavior, so this is probably an issue in your application. Please create a new StackOverflow question and provide as much information as possible: Spring Boot version, the Controller class as well as the class being bound. A complete, minimal sample application is probably required.
