### ISSUE TITLE
Documentation: Fix CSS Rendering Issue

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-framework#30880]
The left navigation bar exhibits some CSS issues and overflows the page footer when the page is scrolled all the way down.

<img width="975" alt="image" src="https://github.com/spring-projects/spring-framework/assets/685363/8804dfaf-8259-413a-a945-33f18a80756f">

**Affects:** `6.0.10`

**Comment by reillylm** [comment]
Looking at the Inspector, seems like this happens when `nav.nav-menu` is longer than `div.nav-panel-menu`:

<img width="400" alt="antora1" src="https://github.com/spring-projects/spring-framework/assets/16691386/e1df95b3-b2a0-4d9b-8329-4ef6fc6e2a41">

In other Antora docs pages (like the [docs for Antora itself](https://docs.antora.org/antora/latest/navigation/)), the CSS looks a bit different, with `overflow-y: scroll` specified for the `.nav-panel-menu`, making the navigation sidebar scrollable:

<img width="400" alt="antora2" src="https://github.com/spring-projects/spring-framework/assets/16691386/32ceb029-e25a-4867-8979-43565334bc1d">

The Antora website itself uses their "[Antora Default UI Bundle](https://gitlab.com/antora/antora-ui-default)" (where the `scroll` rule [lives here](https://gitlab.com/antora/antora-ui-default/-/blob/d5febc2637f0812c4122d856891e9ecae3129962/src/css/nav.css#L68)); however, we have a custom Antora UI bundle, [spring-io/antora-ui-spring](https://github.com/spring-io/antora-ui-spring), where the `visible` rule is specified here:

https://github.com/spring-io/antora-ui-spring/blob/68a05e905c45b7d80fcc01459833856774efdade/src/css/nav.css#L33-L36

Looks like we switched from `scroll` to `visible` as part of this recent change: spring-io/antora-ui-spring@ba66d86.

I wonder if we need to open an issue over in `antora-ui-spring`?

**Comment by bclozel** [comment]
Thanks @reillylm for the detailed analysis - closing this issue in favor of https://github.com/spring-io/antora-ui-spring/issues/110

**Comment by rwinch** [comment]
@bclozel FYI the [0.3.3](https://github.com/spring-io/antora-ui-spring/milestone/5?closed=1) release fixes this and I've sent a PR https://github.com/spring-projects/spring-framework/pull/30911
