### ISSUE TITLE
starter-web does not report full nested errors when thrown in request handlers

### ISSUE THREAD

**Issue by j4m350n** [spring-projects/spring-framework#31035]
Hello,

I'd like Spring boot to log the entire exception thrown in request handlers, not just the root cause.

![image](https://github.com/spring-projects/spring-boot/assets/125522276/19726fce-164c-46ea-8654-5ca6bc01561f)

Whereas the nested exception is the following:

![image](https://github.com/spring-projects/spring-boot/assets/125522276/8a5de93f-10f5-4193-941f-b14aaa219f97)

**Comment by bclozel** [comment]
The log statement you have shared is from Tomcat. What makes you think this is a problem in Spring Framework?

**Comment by j4m350n** [comment]
A wild guess. Using `@ControllerAdvice` seem to solve the issue, but is it possible to change some setting to log the entire throwable?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case adding a ControllerAdvice makes the exception handled by Spring MVC. Please ask a question for this on StackOverflow.
