### ISSUE TITLE
Stop publishing distribution zip artifact

### ISSUE THREAD

**Issue by bsmoyers** [spring-projects/spring-framework#31049]
**Affects:**  5.3.26, 5.3.* releases

---

It seems that packages like https://repo.spring.io/ui/native/release/org/springframework/spring/5.3.26/spring-5.3.26-dist.zip are not in maven central, but are also blocked from download on repo.spring.io now - due to the login requirement. Is there a work around for this?

**Comment by bclozel** [comment]
This is due to the [permission changes on repo.spring.io](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023). I guess we made available a full distribution zip at the time to allow for various build setups. I'm not sure this is relevant these days.

Can you share why you need those zips that is not covered by the other artifacts? We might consider dropping those entirely from our build; even the reference documentation is now published out of band now.

**Comment by bclozel** [comment]
These days, most projects and libraries publish docs and JavaDocs online but do not ship "distribution zips". Like I said above, our distribution zip is mostly irrelevant now.

We just discussed that as a team and we have decided to apply the following changes on the main and 6.0.x branches:

* not create/publish the dist.zip anymore
* stop including the antora docs in the docs.zip, as docs are now published by a different process. We will keep publishing this zip file with the aggregated javadoc and kdocs. Those are automatically republished to docs.spring.io from this zip
* leave the publication of the schema.zip, even though we don't modify those anymore

This should speed up our build and make contributions easier. We can consider a different arrangement if a large enough group in the community requests specific artifacts to be made public.

I'm changing this issue to a task and will backport the changes.

**Comment by GrafDiffusore** [comment]
@bclozel Hi

>     * stop including the antora docs in the docs.zip, as docs are now published by a different process. We will keep publishing this zip file with the aggregated javadoc and kdocs. Those are automatically republished to docs.spring.io from this zip

Is it still possible to download zipped docs from anywhere, as it was before? You know, I like my docs available _locally_

**Comment by bclozel** [comment]
@GrafDiffusore unfortunately no, we don't build a set of docs per version anymore, this is a separate build that merges several versions together for better cross-linking and navigation.

The new system has better SEO, internal search engine, navigation, etc. I understand the downside here but so far the tradeoff is in favor of this new system.

We could work on publishing single version docs as an archive but we would need to spend time dedicating a build task for it and find a place to host that (repo.spring.io cannot host it anymore and IMO maven central is not a proper place for that).

We can reconsider this but so far the demand is quite low and it's not our priority. In the meantime you can clone this repository and build the docs locally.

**Comment by GrafDiffusore** [comment]
> @GrafDiffusore unfortunately no, we don't build a set of docs per version anymore, this is a separate build that merges several versions together for better cross-linking and navigation.
...

Hi
I just did docs build from sources, great it's an option still.
Thanks for quick and sensible reply.

**Comment by Kieaer** [comment]
Where can i get spring 3.x version release dist zip?
I'm maintaining a many project from over 10 years ago, it project not using maven or gradle, apache, etc so must be zip archive
But all official zip download method is dead, no unofficial mirrors, tomcat need to java 8, but spring 3.2.0 ~ 3.2.8 ASM doesn't support java 8

upgrade spring version isn't possible because code too large over 50k lines and too many modules.

**Comment by bclozel** [comment]
Spring Framework 3.2.x has been out of support for years now. We cannot provide unlimited support and downloads for all versions. Jars should still be on maven central and docs are still online: https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/
