### ISSUE TITLE
6.0.11版本，请求接口时警告：Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection

### ISSUE THREAD

**Issue by dengchufeng** [spring-projects/spring-framework#31094]
【版本】
你们好，版本如下，springframework：6.0.11，springboot：3.0.9

【问题】
项目启动，并且请求接口时，将会报出警告：Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: com.zy.base.controller.NwlBaseController

【示例】
1、接口和版本
![image](https://github.com/spring-projects/spring-framework/assets/142789289/4826be9c-7e06-4bd1-b2d2-c11e09ea874a)
2、当项目启动之后，请求接口时，会进入到“LocalVariableTableParameterNameDiscoverer”类的“inspectClass”方法，从而抛出警告
![image](https://github.com/spring-projects/spring-framework/assets/142789289/01bcc93c-4e6a-434d-acd3-505f3dc5824b)

**Comment by bclozel** [comment]
See #29531 as for why you're getting this log warning and see #29559 as this strategy has been removed from the next minor version.
Please compile your Java sources with the common Java 8+ `-parameters` flag for parameter name retention (instead of relying on the `-debug` compiler flag) in order to be compatible with `StandardReflectionParameterNameDiscoverer`.

**Comment by dengchufeng** [comment]
> See #29531 as for why you're getting this log warning and see #29559 as this strategy has been removed from the next minor version. Please compile your Java sources with the common Java 8+ `-parameters` flag for parameter name retention (instead of relying on the `-debug` compiler flag) in order to be compatible with `StandardReflectionParameterNameDiscoverer`.

原来是这样，Thank you！
