### ISSUE TITLE
`framework-api:javadoc` Gradle task outputs lots of warnings

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#31173]
Since the introduction of the `framework-api`, Javadoc generation results in lots of warnings like the following.

```
> Task :framework-api:javadoc
/source/spring-framework/spring-aop/src/main/java/org/aopalliance/intercept/MethodInterceptor.java:19: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/source/spring-framework/spring-aop/src/main/java/org/aopalliance/intercept/MethodInterceptor.java:20: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
                       ^
/source/spring-framework/spring-aop/src/main/java/org/springframework/aop/framework/CoroutinesUtils.java:19: error: package kotlin.coroutines does not exist
import kotlin.coroutines.Continuation;
                        ^
/source/spring-framework/spring-aop/src/main/java/org/springframework/aop/framework/CoroutinesUtils.java:20: error: package kotlinx.coroutines.reactive does not exist
import kotlinx.coroutines.reactive.ReactiveFlowKt;
```

```
warning: unknown enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status not found
```

We should see if we can clean up (avoid) those warnings in the Gradle build.

**Comment by f22520779** [comment]
Hello, when I was using intellij to develop, I found most of the annotations in spring-framework/spring-core/src/main/java/org/springframework/lang, and then the import declaration showed an exception. When I checked the source code of github branch 6.1, It still uses javax.annotation instead of jakarta.annotation.
Can the relevant prompts be ignored or does the problem need to be fixed?
View-source-jar
![image](https://github.com/user-attachments/assets/3eb08ba9-6457-4f1a-a9d8-0d6f31039b1d)
Error prompted
![image](https://github.com/user-attachments/assets/995d343c-4533-4ec0-bf54-b124f534852c)

**Comment by sbrannen** [comment]
Hi @f22520779,

Please refrain from commenting on issues that were closed almost 11 months, especially when the two topics are unrelated.

If you think you have discovered a problem, you should create a new GitHub issue.

Regarding your question, as stated in the JavaDoc (which is included in your screenshot), those nullability annotations leverage JSR-305 which uses annotations in the `javax.annotation` package and its subpackages.

If your IDE cannot resolve `javax.annotation.meta.TypeQualifierDefault`, that means you don't have the JSR-305 JAR on your classpath.
