### ISSUE TITLE
spring boot 3.1.14 completable future appends additional object to response

### ISSUE THREAD

**Issue by eldor9797** [spring-projects/spring-framework#31521]
Hi, team.

In Spring Boot 3.1.14 
Java 17
Gradle 
Windows OS   
I wrote API using ComletableFuture. while fetching data from Controller, we get back as response the following json in a single response
 `{
    "id": "993b47c0-7322-4a8d-ae79-73db7def776d",
    "result": {
        "object": [
            {
                "type": "BANNER",
                "data": [
                    {
                        "id": 2,
                        "title"
                    }
                ]
            }
        ]
    }
}{
    "code": -999999,
    "message": "Type definition error: [simple type, class uz.company.dtos.clients.banner.BannerTitle]",
    "data": null
}`
![photo_2023-10-30_14-37-29](https://github.com/spring-projects/spring-framework/assets/74771471/7f1b8132-645c-4f15-98dc-90c7a12530c5)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by eldor9797** [comment]
what do you mean stackoverflow? the json in the response is broken even tho no exception were raised, look at he the response in pic

**Comment by bclozel** [comment]
Sorry, but JSON snippets and screenshots do not qualify as a bug report. I can only assume that an error happens during serialization and that you're getting some response body and the error response mixed together (see https://github.com/spring-projects/spring-framework/issues/31511#issuecomment-1782474240).

As for why you're getting that serialization error in the first place, I'd suggest creating a well-written question to StackOverflow that helps people to reproduce the problem you're having.
