### ISSUE TITLE
Too many CacheEvaluationContext instances

### ISSUE THREAD

**Issue by liudaac** [spring-projects/spring-framework#31580]
Recently, I discovered a phenomenon where there is a large amount of CacheEvaluationContext instances in the jmap histo from my Spring Boot 2.7.15 application. When I examined the creation points in the source code, I found that the creation of this instance is triggered by three methods in CacheOperationContext: canPutToCache, generateKey, and isConditionPassing. The triggering conditions for these methods are StringUtils.hasText(unless), StringUtils.hasText(this.metadata.operation.getKey()), and StringUtils.hasText(this.metadata.operation.getCondition()) respectively. How should I optimize to reduce the number of CacheEvaluationContext instances?

**Comment by snicoll** [comment]
@liudaac you have described a situation but didn't explain how it was a problem. `CacheEvaluationContext` is a support for SpEL expression handling and shouldn't be costly. We don't keep references to those so they will be garbage collected when the JVM decides it should. Without any description of a concrete problem this issue is not actionable and looks more like a question. 

If you meat to ask a question, please use StackOverlfow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.

**Comment by snicoll** [comment]
In the meantime, we've found something trying to fix an unrelated issue that goes in the direction of the report, see #31617 for more details.

**Comment by liudaac** [comment]
Thank you very much for your attention. We hope the bug can be fixed as soon as possible.
