### ISSUE TITLE
Remove `.mailmap` file

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#31740]
The [`.mailmap`](https://github.com/spring-projects/spring-framework/blob/main/.mailmap) file currently references `@vmware.com` email addresses for core committers.

We will need to update that to reflect `@broadcom.com` email addresses as well, once we switch email addresses used in Git commits to `@broadcom.com` email addresses.

**Comment by snicoll** [comment]
FTR this file misses a number of core committers.

**Comment by sdeleuze** [comment]
I think we should decide to either remove that file or to fill it to make it extensive.

If possible, preference for the former since we will probably miss some contributors email addresses and since that make our emails an easy target for spams and prevents to use [Github no-reply address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses).
