### ISSUE TITLE
Reactive Spring Boot / WebFlux application: where to find default netty resolver configuration?

### ISSUE THREAD

**Issue by mayrstefan** [spring-projects/spring-framework#31927]
We are currently moving some reactive Spring Boot application to Microsoft Azure (Container Apps). Since moving those applications to the Azure network we see sporadic DNS resolution issues and opened https://github.com/netty/netty/issues/13660 to find the reason for that.

One [comment](https://github.com/netty/netty/issues/13660#issuecomment-1872394088) suggested to enable TCP fallback for DNS resolution. Now I'm trying to find out where to find the default configuration for the resolver (spring, reactor?) and if this has enabled the TCP fallback or not. Can anyone point the location where this is set up?

Thank you

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
