### ISSUE TITLE
Not clear how to inject custom ObjectMapper for @SpringBootTest(SomeController.class)

### ISSUE THREAD

**Issue by kpupkov-ppa** [spring-projects/spring-framework#31935]
**Affects:** \3.1.5

I am using custom configuration for an ObjectMapper like that:
`@Configuration
public class JsonConfiguration implements WebMvcConfigurer {

    @Autowired
    private ObjectMapper objectMapper;

    @Override
    public void extendMessageConverters (List<HttpMessageConverter<?>> converters) {
        converters.stream()
                .filter(x -> x instanceof MappingJackson2HttpMessageConverter)
                .forEach(x -> ((MappingJackson2HttpMessageConverter) x).setObjectMapper(objectMapper));
    }
}`

It is working OK in app, but I can't inject the same configuration to my JUnits. Is @SpringBootTest(Controller.class) possible to inject custom ObjectMapper or extendMessageConverter?

Please provide more details or workaround.

**Comment by sdeleuze** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
