### ISSUE TITLE
The problem of inserting data into the message body through BodyInserters during verification and other processing of uploaded files using webflux

### ISSUE THREAD

**Issue by Zwenzo** [spring-projects/spring-framework#31972]
![1704686530205](https://github.com/spring-projects/spring-framework/assets/86212399/83b878cc-54c2-4f58-8b52-b5fbf3595329)
![1704686556729](https://github.com/spring-projects/spring-framework/assets/86212399/22d17313-af0c-42d0-8ffd-ee119edef46b)

**Comment by Zwenzo** [comment]
![1704686657943](https://github.com/spring-projects/spring-framework/assets/86212399/49ff5d20-1c1a-482e-937d-d0dd8b394088)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
