### ISSUE TITLE
Spring Boot Memory Size Increase

### ISSUE THREAD

**Issue by hassibnkhoury** [spring-projects/spring-framework#31999]
Dear Support Team,
Would you please help us about the memory performance issue 
We have a small project using spring boot application and we wanna got an issue related to memory size
while on running my service on docker desktop the memory size increase after a many hours or during the load testing from Jmeter.
We don't know what is the problem if it is related to spring  boot version or JDK version or dockerfile or something else cz our code is small and easy

and kindly note that the bellow info needed to understand my issue :

Spring Boot V 3.2.1
JDK 19

One API : send a request with document size around 1MB
Jmeter Report : Load testing for more than 1000 requests per 3 minutes.

MAT(Memory Analyzer Tool )
![image](https://github.com/spring-projects/spring-framework/assets/123631914/1e5b6081-fbdc-43ac-903f-184e16fce16a)

Memory Usage on Docker and JVM on Visual VM:
![image](https://github.com/spring-projects/spring-framework/assets/123631914/f63d4e82-5f7d-484b-baab-11827280e4fd)

Docker File :
FROM openjdk:19-alpine
WORKDIR /usr/app
COPY /target/*.jar app.jar 
EXPOSE 8090 8091
# Set JVM options
ENTRYPOINT ["java", \
	"-XX:+UseG1GC","-Xms16m","-Xmx256m","-Xss256k","-XX:MaxRAM=1024m","-XX:MinHeapFreeRatio=5"\
	,"-XX:MaxHeapFreeRatio=10","-XX:+TieredCompilation","-XX:TieredStopAtLevel=1","-XX:GCTimeRatio=4"\
	,"-XX:AdaptiveSizePolicyWeight=20","-XX:MaxMetaspaceSize=320m","-XX:MetaspaceSize=42m"\
	,"-XX:InitialRAMPercentage=75.0","-XX:MaxRAMPercentage=75.0","-XX:MinRAMPercentage=75.0"\
	,"-XX:+UnlockExperimentalVMOptions","-XX:-ShrinkHeapInSteps"\
	,"-Dspring.profiles.active=local"\
	,"-Dcom.sun.management.jmxremote=true"\
	,"-Dcom.sun.management.jmxremote.port=8091"\
	,"-Dcom.sun.management.jmxremote.local.only=false"\
	,"-Dcom.sun.management.jmxremote.authenticate=false"\
	,"-Dcom.sun.management.jmxremote.ssl=false"\
	,"-Dcom.sun.management.jmxremote.rmi.port=8091"\
	,"-Djava.rmi.server.hostname=localhost"\
	,"-jar","app.jar"]
	
pom.xml :
	
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.1</version>
		<relativePath/> 
	</parent>
	<groupId>com.qrdn.common</groupId>
	<artifactId>qrcodejwt</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>qrcode</name>
	<description>Demo project for Spring Boot</description>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>  
        		
		 <dependency>
	      <groupId>org.springframework.boot</groupId>
	      <artifactId>spring-boot-starter-validation</artifactId>
	    </dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.16</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>4.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.qrdn.common</groupId>
			<artifactId>service-discovery</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.qrdn.common</groupId>
			<artifactId>interceptor</artifactId>
			<version>1.0.0</version>
			<exclusions>
				<exclusion>
					<artifactId>jwt-verifier</artifactId>
					<groupId>com.qrdn.common</groupId>
				</exclusion>
				<exclusion>
					<artifactId>data-storage</artifactId>
					<groupId>com.qrdn.common</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.qrdn.common</groupId>
			<artifactId>jwt-verifier</artifactId>
			<version>1.0.8</version>
		</dependency> 
		<dependency>
			<groupId>com.qrdn.common</groupId>
			<artifactId>mnp-pdf</artifactId>
			<version>1.0.0</version> 
		</dependency>  

	    <dependency>  
			<groupId>com.qrdn.common</groupId>
			<artifactId>data-storage</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.qrdn.common</groupId>
			<artifactId>db-connect</artifactId>
			<version>1.0.0</version>
		</dependency> 
		<dependency>
			<groupId>com.qrdn.common</groupId>
			<artifactId>kafka-producer-log</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency> 
			<groupId>com.qrdn.common</groupId>
			<artifactId>qr-code</artifactId>
			<version>1.0.0</version>
		</dependency>
		
	
		
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by bclozel** [comment]
As discussed in https://github.com/spring-projects/spring-framework/issues/25619, there is no indication that there is a memory leak in Spring. Your screen captures show that the memory usage is not growing infinitely so I don't understand how you can infer a memory leak.

Please investigate with your application. We can reopen this issue if it turns out you can shows that there is a leak in Spring Framework.

**Comment by hassibnkhoury** [comment]
and take MOT report inconsideration while you can see they have leak issue related to 2 classes :
org.springframework.beans.factory.support.DefaultListableBeanFactory
org.springframework.boot.loader.launch.LaunchedClassLoader

**Comment by bclozel** [comment]
This points to a bean in your application leaking memory. Can you see which bean in the context is increasing the memory?

**Comment by hassibnkhoury** [comment]
How can i see which bean in the context is increasing the memory if I am using spring boot?
only I wanna create these annotation :
@Service for each service needed to put data on DB using hibernate
 @Autowired to create singleton class from service
@Configuration to configure main info

**Comment by bclozel** [comment]
Sorry but we can't justify spending time helping you to investigate an application problem. You can drill down in your memory profiling tool to better understand where the problem comes from.

**Comment by hassibnkhoury** [comment]
thanks a lot
you can close this isue

**Comment by SimoneGiusso** [comment]
Hello @bclozel,

I'm encountering problems with `DefaultSingletonBeanRegistry` as well. 

I found that our request scoped bean (name by spring as `scopedTarget.myName`). created under `@Configuraiton` annotation has 800k dependencies in `DefaultSingletonBeanRegistry#dependenciesForBeanMap`. On the other side in `DefaultSingletonBeanRegistry#dependentBeanMap` there are 800k entries. These 800k are jdk.proxy3.$Proxy as this is their name.

I'm not really sure how it is possible that this bean as so many bean dependencies. It seems that this data are not freed after GC runs. I found it odds because this bean has only 5 properties:

```java
    @Bean
    @Scope(value = SCOPE_REQUEST, proxyMode = TARGET_CLASS)
    Consumer consumer(HttpServletRequest request) {
        return new RequestConsumer(request, uuid);
    }

    static class RequestConsumer implements Consumer {

        private static final String
        private static final String

        private final HttpServletRequest;
        private final MyCustomObject;
        private final UUID;
        
    }
```
    
Where myCustom contains some strings and UUID. 

Are there any suggestions?

**Comment by bclozel** [comment]
@SimoneGiusso not on the top of my head. If you manage to reproduce the problem with a minimal sample, please create a new issue and we'll have a look.

**Comment by SimoneGiusso** [comment]
> @SimoneGiusso not on the top of my head. If you manage to reproduce the problem with a minimal sample, please create a new issue and we'll have a look.

Just as a note (see also my message above) for others reading the conversation. We have encounter a leak which is really similar to what is explained [here](https://github.com/spring-projects/spring-framework/issues/13814#issuecomment-453366042). The problem is present with `Spring Boot 2.7.18` but not with `Spring 3` apparently.

Enabling this logging:

```
logging:
  level:
    org.springframework.beans: DEBUG
```

Will confirm that, every time a request is made, the following is logged:

> Autowiring by type from bean name 'scopedTarget. consumer' via factory method to bean named 'jdk.proxy2.$Proxy439@36c72b3c'

The cause of the leak seems apparently odd. The usage of `ApplicationEventPublisher` at some point of the code (not in consumer) triggers the leak and the leak is anyway happening before the usage of `ApplicationEventPublisher`. We noticed that commenting the line that uses `ApplicationEventPublisher` doesn't trigger the leak. I know it sounds odd.

Our workaround was modifying the code above:

```java
    @Bean
    @Scope(value = SCOPE_REQUEST, proxyMode = TARGET_CLASS)
    Consumer consumer() { // Here the change
        return new RequestConsumer(((ServletRequestAttributes)RequestContextHolder.getRequestAttributes()).getRequest(), uuid);
    }

    static class RequestConsumer implements Consumer {

        private static final String
        private static final String

        private final HttpServletRequest;
        private final MyCustomObject;
        private final UUID;
        
    }
```

So that the `HttpServletRequest` is not autowired everytime a request is made with a different name. Causing:

```java
/** Map between dependent bean names: bean name to Set of dependent bean names. */
private final Map<String, Set<String>> dependentBeanMap = new ConcurrentHashMap<>(64);

/** Map between depending bean names: bean name to Set of bean names for the bean's dependencies. */
private final Map<String, Set<String>> dependenciesForBeanMap = new ConcurrentHashMap<>(64);
```

in `DefaultSingletonBeanRegistry` to grow indefinitely.
