### ISSUE TITLE
Spring API Docs not built for versions 6.1.1, 6.1.2 and 6.1.3

### ISSUE THREAD

**Issue by Kapeli** [spring-projects/spring-framework#32013]
Spring API Docs are not available for versions 6.1.1, 6.1.2 and 6.1.3 at https://repo.spring.io/ui/native/libs-snapshot-local/org/springframework/framework-docs/

**Comment by bclozel** [comment]
They're still published on our docs website:

* https://docs.spring.io/spring-framework/docs/6.1.3-SNAPSHOT/javadoc-api/
* https://docs.spring.io/spring-framework/docs/6.1.3/javadoc-api/

I guess you're asking because of Dash? In this case, javadocs have been relocated here: https://repo.spring.io/ui/native/libs-snapshot-local/org/springframework/framework-api/

Let me know how this works for you.

**Comment by Kapeli** [comment]
Yes. Thank you!

**Comment by bclozel** [comment]
Cool. Let us know if something's missing.
