### ISSUE TITLE
Support binary streams with `JdbcClient`

### ISSUE THREAD

**Issue by dopsun** [spring-projects/spring-framework#32161]
In Postgres database, there is a column type `bytea`.  According to [Storing Binary Data](https://jdbc.postgresql.org/documentation/binary-data/), here is the code to write files to `bytea` column with `PreparedStatement`:

``` java
File file = new File("myimage.gif");
try (FileInputStream fis = new FileInputStream(file);
        PreparedStatement ps = conn.prepareStatement("INSERT INTO images VALUES (?, ?)"); ) {
    ps.setString(1, file.getName());
    ps.setBinaryStream(2, fis, (int) file.length());  // <-- setBinaryStream needed here
    ps.executeUpdate();
}
```

For the current version of `JdbcClient` (6.1.1), `StatementSpec.param()` does not support `InputStream`. I have tried to open up underlying code and cannot find places where doing stream related code.

Missing this feature, will prevent `JdbcClient` to be used  when `bytea` column exists.

**Comment by dopsun** [comment]
I only tried using `SqlLobValue` with default `LobHandler`. Below is what it looks like:

``` java
InputStream inputStream = new FileInputStream(file);
SqlLobValue lobValue = new SqlLobValue(inputStream, (int) file.length());

this.jdbcClient.sql(sql)
    .param("data", lobValue)
    .update();
```
It throws exception with text "SqlLobValue only supports SQL types BLOB and CLOB".

**Comment by quaff** [comment]
It should be supported at `JdbcOperations` not `JdbcClient` level, @dopsun Could you confirm that is not supported by `JdbcTemplate` currently?

**Comment by dopsun** [comment]
Thanks @quaff I just did the same change in my code and got the same exception as yours.

For time being, I have changed my code to use `PreparedStatement`.

**Comment by quaff** [comment]
@dopsun I've fixed this by https://github.com/spring-projects/spring-framework/pull/32163, please patch `StatementCreatorUtils` to your project to verify.

**Comment by dopsun** [comment]
Great @quaff 

I tried to get source and apply patch locally, build `spring-jdbc` and replace my local maven jar. It reports same exception.

Read your patch, it seems like there is a special condition:
``` java
"Oracle".equals(ps.getConnection().getMetaData().getDatabaseProductName())
```

So, I tried to print out mine:
``` java
String databaseProductName = this.dataSource.getConnection().getMetaData().getDatabaseProductName();
System.out.println(databaseProductName);
```

It produces `PostgreSQL`. I guess this could be the reason?

_This is my first time to build this repository from source and patch, please correct me if I'm missing anything_

**Comment by dopsun** [comment]
Great @quaff

I tried with your new patch and build locally. It works for my case with `JdbcClient`.

_This is my first time to build this repository from source and test locally, seems like IDE local cache causes my initial false errors (hence I deleted my previous comment with error report). Restarted IDE with a clean start, your patch works for me._

**Comment by quaff** [comment]
> Great @quaff
> 
> I tried with your new patch and build locally. It works for my case with `JdbcClient`.
> 
> _This is my first time to build this repository from source and test locally, seems like IDE local cache causes my initial false errors (hence I deleted my previous comment with error report). Restarted IDE with a clean start, your patch works for me._

You can try the trick that paste changed files to your project src directory to override classes in jars.

**Comment by jhoeller** [comment]
@dopsun as mentioned, for a BLOB type, we got `SqlLobValue`... but that is indeed restricted to BLOB handling, not covering direct byte array types as with Postgres here. For the Postgres `bytea` type, you could implement a custom `SqlTypeValue` where you call `setBinaryStream` or `setBytes` in your `setTypeValue` implementation, and pass that as an argument into `JdbcClient`. That's probably the best you can do with existing Spring versions.

The plain handling of an InputStream argument in `StatementCreatorUtils` (as in the PR) might work for simple scenarios, as long as the caller makes sure to close the InputStream afterwards, e.g. when the InputStream never reaches the PreparedStatement. However, we generally do not intend to support such plain "hot" streams as arguments. Also, JDBC drivers usually insist on knowing the length of the stream upfront in order to allocate accordingly, so a plain InputStream object won't be sufficient.

We intend to address the file use case with support for special value types, e.g. `Resource` handles such as `FileSystemResource`, that lazily retrieve the `InputStream` and also provide the content length upfront. Alternatively, we may also support `byte[]` arguments directly. I'm going to turn this issue into a corresponding enhancement request for 6.1.4.

For that reason, I'm going to close the PR. Thanks for your efforts there in any case, @quaff!

**Comment by jhoeller** [comment]
For the above, you could simply declare `InputStreamValue implements SqlTypeValue`. No need to extend from ´SqlLobValue` there, you could rather implement the same callback interface that `SqlLobValue` implements as well.

As for standard value types, it looks we will introduce a pair of `SqlBinaryValue` and `SqlCharacterValue` classes, similar to `SqlLobValue` in design but delegating to the corresponding `PreparedStatement` methods for any target SQL type.

As a side note, a parameter of type `byte[]` might work as-is already (without the need for a custom value type) since most database drivers explicitly handle that when passed into `PreparedStatement.setObject` (which Spring's `StatementCreatorUtils` uses by default). We can make this more explicit through dedicated `setBytes` support for a given byte array in `StatementCreatorUtils` but that's just for consistent behavior across databases.
