### ISSUE TITLE
[Feature Request] Packaging POM option via New > Spring Starter Project

### ISSUE THREAD

**Issue by rodneyazev** [spring-projects/spring-framework#32220]
There is no packaging POM option via New > Spring Starter Project.

Spring Starter Project (No Pom): 

![spring-starter-project-no-pom-option](https://github.com/spring-projects/spring-framework/assets/40548312/9130e031-2a38-4405-ae9b-f372d3bbe797)

Maven Project (Pom):

![spring-pom-via-maven-project](https://github.com/spring-projects/spring-framework/assets/40548312/b1dc4217-ea23-4458-80a0-4bc1c2ced4db)

We need to convert Spring Starter Project to pom adding POM packaging tag (Any possibility to let us choose it by the main Project menu creation?) :

![spring-pom-feature-only-converting-it-manually](https://github.com/spring-projects/spring-framework/assets/40548312/45d699b7-a5ff-4579-8573-2689d1710e56)

**Comment by snicoll** [comment]
@rodneyazev this issue tracker is for the core spring framework. The UI you're showing is a client for start.spring.io and it has a [dedicated issue tracker](https://github.com/spring-io/start.spring.io/). If you insist you can raise an issue there but I don't think we will add support for a `pom` type in that UI as it would be too awkward. The example you're using is a bit contrived as creating an empty Java project with Maven has a valid point of only creating a POM so that you can craft the rest of project. However, a Spring Boot project is "ready to use" and comes with resources and an application class.

**Comment by rodneyazev** [comment]
It's like I said in the previous message, people who don't know the IDE, for example, will have difficulties. For example, I know on my own what I should configure to have a functional microservice environment, but if you look about it, not just about it, you realize that not everything found on the internet works as it should. Experienced people can evaluate and correct it on their own.

These are trivial things that some IDEs like Intellij helps making the lives of those just starting out easier. But it's fine. Thank you anyway.
