### ISSUE TITLE
Reactive connection handling on Tomcat 

### ISSUE THREAD

**Issue by mschweyen** [spring-projects/spring-framework#32249]
We observed a problem with the connection handling when using Webflux on Tomcat. 
Connections remain open in CLOSE_WAIT status on the server site when the client closes the connection.
This may lead to a situation where the server is not reachable if there are so many client connections that the server reaches its limit. 

There is no problem when using Netty. Here is a small example ([webflux-problem.zip](https://github.com/spring-projects/spring-framework/files/14250019/webflux-problem.zip)) demonstrating that the same tests succeed on Netty and fails on Tomcat.

The problem may have a similar origin as Issue #30393.

**Comment by rstoyanchev** [comment]
@mschweyen you mention using WebFlux on Tomcat, but tomcat-demo in the example has `spring-boot-starter-web`, i.e. Spring MVC and Tomcat. Can you clarify on that please? Also, is the behavior related to a specific version or upgrade?

**Comment by mschweyen** [comment]
Is there anything I can do to support you with the analysis?

**Comment by rstoyanchev** [comment]
@mschweyen I've had a look at the sample. 

I'm not sure what `option(ChannelOption.SO_LINGER, 0)` achieves. I see no difference with and without it. Basically, `blockFirst()` requests 1 and cancels the inbound stream, and Reactor Netty to close the connection. If I switching to `blockLast()`, it hangs for 10 seconds until the client response timeout, so again the option doesn't seems to achieve anything that I can see.

For a single run, with the spring-mvc-demo, I see one streamed, after which Tomcat triggers a timeout notification, which we handle with an ASYNC dispatch, and the request completes. I don't know why a timeout, and not an error for the closed connection, but we handle both similarly. For the webflux-tomcat-demo, the handling is a bit different (no ASYNC dispatch), but the sequence of events is the same.

For the long test with 30000 requests, each request streams its one event, after which the client closes and performs the next request. On the server side, however, there are no timeout notifications, and as the controller stream is infinite, nothing further happens. This is both with the Spring MVC and the WebFlux demos. After the configured 10 second client response timeout, there is a flood of timeout notifications on the server side that are handled as expected. 

This is probably expected behavior due to Servlet containers not providing notifications for closed connections, see https://github.com/jakartaee/servlet/issues/44, so the only way to find out if there is a network issue is to keep writing (e.g. heartbeats) which eventually fails as the socket is not usable. For example, changing to:

```java
@PostMapping(value = "/api/pdp/decide", produces = MediaType.TEXT_EVENT_STREAM_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
public Flux<ServerSentEvent<String>> decide(
        @Valid @RequestBody Object input) {

    return Flux.merge(
            Flux.interval(Duration.ofSeconds(5))
                    .map(aLong -> ServerSentEvent.<String>builder().comment("heartbeat").build()),
            Flux.create((FluxSink<String> fluxSink) -> fluxSink.next(PERMIT))
                    .map(decision -> ServerSentEvent.<String>builder().data(decision).build()));
}
```

I start to see "Broken pipe" `IOException`s and the test runs to completion.

It is however a little surprising that even when Servlet non-blocking I/O is used as with WebFlux, the behavior is the same. It might also be worth investigating why Tomcat can notify of the time out on a single request immediately while for many requests, it doesn't notice any of them until the server is closed. It might be possible to improve something. /cc @markt-asf.

**Comment by mschweyen** [comment]
@rstoyanchev the option SO_LINGER=0 is set to avoid that the socket is held in TIME_WAIT state on the client site. Depending on the host config it can runs out of available sockets during load tests. The same can be reproduced with one server and multiple client hosts. 

-----------

Here some additional information about our usecase:
In our usecase the client is sending a request (subscription) to the server and the server answers with an indefinite flow of answers to the client. The Answers are sent over the Flux implemented as server-sent-events connection. Now it depends on the client how long the subsription persists. In this demo the client takes one single response (blockFirst). 

The usecase is about a solution for stream based access control where a client sends an AuthroizationSubscription and the server is answering with a flow of AuthrizationDecisions. Now it's on the client to apply the decision. The Decision changes over time depending on the date, time, rule changes or any other exteral infromation. Actually we can not use netty because we are using Vaadin as Web UI.

-----------

Geat, thanks a lot for this solution. I understand that the heartbeat may be a way to ensure that tomcat detects a dead client. I will have a try now with our application and I'm confident that it solves the problem.

May be a good idea to find a gerneric solution for tomcat as this can easily lead to problems or even be used for DOS attacs.

**Comment by rstoyanchev** [comment]
Thanks for the extra context. I can't speak for Tomcat, but the above referenced Servlet issue is probably where something needs to change first, but I could be wrong.

**Comment by ugurberkecan** [comment]
Hi, even though we have a heartbeat, some connections don't close when we have too many subscriptions at the same time. What should I do?
