### ISSUE TITLE
Spring Boot 3.2.2: Migration Lowagie Pdf to Itextpdf 

### ISSUE THREAD

**Issue by yasin-herken** [spring-projects/spring-framework#32268]
In web-mvc module, the dependency uses `com.lowagie.text.Document` and we need to use `com.itextpdf.text.Document`.
If this is a bug or needs to be changed, I am volunteer to change.

**Comment by jhoeller** [comment]
I'm afraid that newer versions of iText are licensed under the AGPL, not allowing us to compile against it since it would force us to declare all of Spring as AGPL as well. Our common dependencies are mostly licensed under Apache/BSD, with some under LGPL.

From that perspective, feel free to take Spring's `AbstractPdfView` as a copy-and-paste template for a custom `View` class in your project, compiling it against newer versions of iText there, provided that you comply with the current iText licensing rules.
