### ISSUE TITLE
Implement refresh support in Environment

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-framework#32293]
If I change a property/YAML value in a local configuration file, I want the `Environment` object to be able to read from the file again (i.e refresh its values).

Online research mentions using Spring Cloud Config, Spring Boot actuator, etc, which are all really cumbersome to adopt for such a simple thing.

Any plans to enhance `Environment`?

For example:

- `environment.refresh()` to refresh all its configuration values
- `environment.getProperty("myKey", true)` to refresh a specific key --  `true` means refresh; default can be `false`.

**Comment by sbrannen** [comment]
Thanks for the proposal, @hannah23280.

> * `environment.refresh()` to refresh all its configuration values

This would not provide any benefit, since properties are _pulled_ from the `Environment` (via `getProperty(...)`) instead of the `Environment` _pushing_ properties to consumers.

> * `environment.getProperty("myKey", true)` to refresh a specific key --  `true` means refresh; default can be `false`.

Similar to the above, a `boolean refresh` flag would not provide any benefit since a `getProperty(...)` invocation already queries underlying `PropertySource` implementations for the "current" value.

Thus, in order to achieve your goal of refreshing the value of a given property, the `PropertySource` responsible for that property would need to perform its own refresh/reload for the underlying source of the properties.

For example, instead of using a `PropertiesPropertySource`, you could implement your own custom `PropertySource` which always retrieves properties from a `.properties` file in the filesystem or classpath instead of caching those properties in a `java.util.Properties` object.

In light of that, I am closing this issue.
