### ISSUE TITLE
ContentCachingResponseWrapper no longer honors Content-Type and Content-Length

### ISSUE THREAD

**Issue by yikuo123** [spring-projects/spring-framework#32317]
As of Spring Framework 6.1.4, `ContentCachingResponseWrapper` returns `null` for `Content-Type` and `Content-Length` via `getHeader("Content-Type")`, `getContentType()`, etc.

**Comment by amuttsch** [comment]
We have the problem that our rest controller, which sits behind a `ShallowEtagHeaderFilter`, does not return the `Content-Type` header anymore. I guess this is also related to this change.

**Comment by jhoeller** [comment]
Do you specifically see a difference for programmatic calls on the `HttpServletResponse` there? Where do the header values (that you expect to see there) come from, are they being set programmatically elsewhere (outside of `ContentCachingResponseWrapper`)?

**Comment by tjalling-ran** [comment]
spring-framework 5.3.32 may also be affected. 

After upgrading to it (because of [CVE-2024-22243](https://spring.io/security/cve-2024-22243)), we no longer had content type headers in responses. So I downgraded back to 5.3.29. (luckily, we don't think we have any endpoints that are vulnerable to the CVE)

**Comment by amuttsch** [comment]
@jhoeller We set then through the `@GetMapping(produces = [MediaType.APPLICATION_JSON_VALUE])` annotation. We return a `ResponseEntity.ok()` and also tried to set the content type using `.contentType(MediaType.APPLICATION_JSON_VALUE)`, which did not work either.

**Comment by sbrannen** [comment]
Thanks for all of the feedback!

We're looking into a fix.

**Comment by sbrannen** [comment]
Current work on this issue can be viewed in the following feature branch.

https://github.com/spring-projects/spring-framework/compare/main...sbrannen:spring-framework:issues/gh-32317-ContentCachingResponseWrapper-and-preset-headers

**Comment by sbrannen** [comment]
I've pushed a potential fix to `6.1.x` and `main` (see commit 5680d2063744380583bdc58fca0a17ac382beaa4).

@yikuo123, @amuttsch, @tjalling-ran, and anybody else interested in helping out...

We would be grateful if you could try out one of the upcoming `6.1.5-SNAPSHOT` builds and let us know if the proposed fix addresses the regressions you've encountered!

If you confirm the fix works, we'll then backport to `6.0.x` and `5.3.x`.

Cheers,

Sam

----

p.s. you can find information on accessing snapshot builds [here](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Artifacts#snapshots).

**Comment by tjallingran** [comment]
i> @yikuo123, @amuttsch, @tjalling-ran, and anybody else interested in helping out...
> 
> We would be grateful if you could try out one of the upcoming `6.1.5-SNAPSHOT` builds and let us know if the proposed fix addresses the regressions you've encountered!
> 
> If you confirm the fix works, we'll then backport to 6.0.x and 5.3.x.

That was fast! 🚀 
Appreciatie the clear analysis / explanation in 5680d20

I'd be happy to try out a 5.3.x backport build if/when testers are desired for that. Unfortunately, we don't have any 6+ project that I can test with.

**Comment by sbrannen** [comment]
> That was fast! 🚀 

😎 

> Appreciate the clear analysis / explanation in [5680d20](https://github.com/spring-projects/spring-framework/commit/5680d2063744380583bdc58fca0a17ac382beaa4)

You're welcome, and glad you found it useful.

> I'd be happy to try out a 5.3.x backport build if/when testers are desired for that. Unfortunately, we don't have any 6+ project that I can test with.

Thanks for offering.

We'll let you know as soon as we've backported anything to 5.3.x.

**Comment by sbrannen** [comment]
**Update:** In be45481d701581efb69a990116d190a3879d0d1e, I fixed an additional minor issue with `getHeaderNames()` and introduced extensive tests to verify the expected behavior for all recent changes in `ContentCachingResponseWrapper`.

**Comment by sbrannen** [comment]
@yikuo123, @amuttsch, @tjalling-ran, and anybody else interested in helping out...

The proposed fix is now available in `6.1.5-SNAPSHOT` builds and will be available in upcoming `6.0.18-SNAPSHOT` and `5.3.33-SNAPSHOT` builds.

As mentioned in https://github.com/spring-projects/spring-framework/issues/32317#issuecomment-1962732906, we'd be grateful if you can test against the snapshots and report back here to let us know if the fixes work for you.

Thanks!

Sam


----

p.s. In the interim, we are leaving this issue "open" until we receive confirmations that the fixes work.

**Comment by tjalling-ran** [comment]
@sbrannen I tried the 5.3.33-SNAPSHOT build screenshotted below. It still has the issue - that is, there is no ContentType header in the response of the GET-request I tested with, whereas the same request on 5.3.29 does result in a response with the expected ContentType.

![image](https://github.com/spring-projects/spring-framework/assets/81741733/3912685b-58c6-46e8-bb8c-f34e0ae960bb)

(screenshot of https://repo.spring.io/ui/native/snapshot/org/springframework/spring-framework-bom/5.3.33-SNAPSHOT/)

According to the decompilation in IntelliJ, the snapshot build already has the fix, if I'm not mistaken:

![image](https://github.com/spring-projects/spring-framework/assets/81741733/4670946b-4946-4c8d-90fb-05f9e2f1626f)

**Comment by tjalling-ran** [comment]
I may have found the issue. I'm not familiar enough with the code to be confident that I didn't miss anything or make a wrong assumption somewhere.

`ConditionalContentCachingResponseWrapper.setContentType()` now sets its own ContentType instead of that of the wrapped Response.

As long as `ConditionalContentCachingResponseWrapper.copyBodyToResponse()` does indeed do copying, this is not a problem. However, when `ConditionalContentCachingResponseWrapper.content.size()` is `0`, no copying is done.

So then the question is: how can `ConditionalContentCachingResponseWrapper.content.size()` be `0`? The answer is that `ConditionalContentCachingResponseWrapper.getOutputStream()` only returns its own output stream if content caching is enabled. If content caching is disabled, it will delegate to the wrapped response's output stream. Thus, `ConditionalContentCachingResponseWrapper` will not have any content.

It will _not_ delegate to the wrapped response's `setContentType()`, however. So now we have a situation where the content is stored in the wrapped response, but the content type is stored in the wrapper.

And because a wrapper without content doesn't copy any of its own properties to the wrapped response, the wrapped response's content type (and possibly other properties) will remain `null`.

**Comment by amuttsch** [comment]
> @yikuo123, @amuttsch, @tjalling-ran, and anybody else interested in helping out...
> 
> The proposed fix is now available in `6.1.5-SNAPSHOT` builds and will be available in upcoming `6.0.18-SNAPSHOT` and `5.3.33-SNAPSHOT` builds.
> 
> As mentioned in [#32317 (comment)](https://github.com/spring-projects/spring-framework/issues/32317#issuecomment-1962732906), we'd be grateful if you can test against the snapshots and report back here to let us know if the fixes work for you.
> 
> Thanks!
> 
> Sam
> 
> p.s. In the interim, we are leaving this issue "open" until we receive confirmations that the fixes work.

I tried the 6.1.5-SNAPSHOT but it did not work, the `Content-Type` header is still missing. To rule out any configuration error on my side: I added the repository

```
repositories {
  maven { url = uri("https://repo.spring.io/snapshot") }
}
```

and overwrote the version using `ext["spring-framework.version"] = "6.1.5-SNAPSHOT"`. At least IntelliJ shows me that the `ShallowEtagHeaderFilter` was loaded from `spring-web-6.1.5-SNAPSHOT` and I synced, cleared and rebuild my gradle project.

**Comment by amuttsch** [comment]
I created a reproducible setup here: https://github.com/amuttsch/spring-boot-etag-content-header

**Comment by sbrannen** [comment]
Hi everybody,

Thanks a lot for all of the prompt feedback!

In the end, we decided to revert the `Content-Type` caching in `ContentCachingResponseWrapper`.

So, hopefully that will address all remaining issues. 🤞 

See cca440eb8e46c14d19df22df837ed4b90dd38673 for details.

The latest fix is now available in `6.1.5-SNAPSHOT` builds.

So, if you're using `6.1.x`, please try out the snapshot and let us know if the latest fix addresses the regressions you've encountered.

Once the fix is confirmed by a number of you, we'll then backport to `6.0.x` and `5.3.x`.

Cheers,

Sam

**Comment by amuttsch** [comment]
Thanks for the quick response. My demo code works now, I can check my production code tomorrow. But I think it will most likely work too.

**Comment by sbrannen** [comment]
> Thanks for the quick response. 

You're very welcome.

> My demo code works now, 

Awesome! Thanks for testing that with lightning fast speed and reporting back. 🚀 

> I can check my production code tomorrow. But I think it will most likely work too.

That would be much appreciated.

Thanks

**Comment by amuttsch** [comment]
> > I can check my production code tomorrow. But I think it will most likely work too.
> 
> That would be much appreciated.

My production code works as well 👍

**Comment by sbrannen** [comment]
@amuttsch and @resmo, thanks for confirming that the latest snapshots work! 👍 

I'll likely backport to `6.0.x` and `5.3.x` tomorrow.

**Comment by sbrannen** [comment]
The fix has now been backported to `6.0.x` and `5.3.x` and will be available in upcoming `6.0.18-SNAPSHOT` and `5.3.33-SNAPSHOT` builds.

If you can test your applications against those snapshots and report back here, that would be great.

Thanks,

Sam

**Comment by tjalling-ran** [comment]
I can confirm that the issue is fixed in today's `5.3.33-SNAPSHOT` build :sunglasses: 

Thank you for the prompt fix @sbrannen.

**Comment by sbrannen** [comment]
Glad to hear it, @tjalling-ran!

And thanks for letting us know.

**Comment by pperalta** [comment]
Just tested with `5.3.33-SNAPSHOT`, works for us too!

**Comment by sbrannen** [comment]
Thanks for letting us know it works for you with the 5.3.33 snapshots, @pperalta!
