### ISSUE TITLE
Generics Inject

### ISSUE THREAD

**Issue by itzpm** [spring-projects/spring-framework#32406]
Hello I have a problem in my project:

```java
// this is parent interface
public interface ParentComponent<T extends TestParent> {
    void test(T test);
}
```

```java
// impl 1
@Component
public class SonComponent1 implements ParentComponent<TestSon1> {
    @Override
    public void test(TestSon1 test) {
        System.out.println(test);
    }
}
```

```java
// impl 2
@Component
public class SonComponent2 implements ParentComponent<TestSon2> {
    @Override
    public void test(TestSon2 test) {
        System.out.println(test);
    }
}
```

```java
// parent class
public class TestParent {
}
```

```java
// son1
public class TestSon1 extends TestParent {
}
```

```java
// son2
public class TestSon2 extends TestParent {
}
```

I want inject like this. What should I do?

```java
@Autowired
private List<ParentComponent<TestParent>> parentComponents;
```

I don't want to use like below.

```java
@Autowired
ParentComponent<TestSon2> son2;

@Autowired
ParentComponent<TestSon1> son1;
```

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

The above is our standard policy for such questions.

In any case, the following is the solution to your issue.

```java
@Autowired
private List<ParentComponent<? extends TestParent>> parentComponents;
```
