### ISSUE TITLE
Feature defined by org.springframework.aot.graalvm.ConstantFieldFeature unexpectedly failed with a(n) java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by dnestoro** [spring-projects/spring-framework#32444]
While trying to run [GraalVM Reachability Meatdata](https://github.com/oracle/graalvm-reachability-metadata) tests with the `latest-ea` version (from [oracle-graalvm-ea-builds](https://github.com/graalvm/oracle-graalvm-ea-builds)), test `org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.0.M1` failed with the following error ([see this](https://github.com/oracle/graalvm-reachability-metadata/actions/runs/8280140253/job/22656050371#step:7:199)):
``` 
Error: Feature defined by org.springframework.aot.graalvm.ConstantFieldFeature unexpectedly failed with a(n) java.lang.NoSuchMethodError.
Please report this problem to the authors of org.springframework.aot.graalvm.ConstantFieldFeature.
```

cc: @mhalbritter

**Comment by fniephaus** [comment]
It turns out the test is using `spring-core-6.0.0-M6` which included a `ConstantFieldFeature` accessing Native Image internals: 

https://github.com/spring-projects/spring-framework/blob/877a3d362b6e619a09eb48a8588857b3f75b09a5/spring-core/graalvm/src/main/java/org/springframework/aot/graalvm/ConstantFieldFeature.java#L19-L20

Updating to 6.0.x should fix this, will check...

**Comment by dnestoro** [comment]
Resolved on Reachability Metadata side with [this pull request](https://github.com/oracle/graalvm-reachability-metadata/pull/465) that switched `testImplementation` from version `6.0.0-M6` (that contained `ConstantFieldFeature`) to `6.0.0` (which doesn't contain `ConstantFieldFeature`)
