### ISSUE TITLE
IllegalArgumentException / SpelEvaluationException even after compiling with -parameters

### ISSUE THREAD

**Issue by Sarthak-Kulkarni** [spring-projects/spring-framework#32533]
**Affects:** \<Spring Framework version>

---

I have a parent project with pluginManagement. I have added the -parameters in the parent project as follows:

![image](https://github.com/spring-projects/spring-framework/assets/35108485/7616f07c-cda3-47b2-86d2-26e5b403d361)

In the child projects I still see these errors. 
I even tried with adding the -parameters option in child projects. Even after that the errors persist. 
I am completely stuck with upgrade to Spring 6.1. Everything works fine with Spring 6.0.x but upgrading to Spring 6.1 is becoming painful.
Can someone please help?

**Comment by snicoll** [comment]
>  Can someone please help?

Unfortunately, it looks like you're asking for help on how to use Maven and that's the wrong place to do so. We don't really know what doesn't work since all you shared is a screenshot of some plugin configuration. If you can produce a small sample that reproduces your problem we can definitely have a look. For follow-up questions, please head to StackOverflow.
