### ISSUE TITLE
@RequestBody decorator is crashing on Json.Parse for null types - null types are from Google Firebase response stream.

### ISSUE THREAD

**Issue by smartbenapple** [spring-projects/spring-framework#32545]
The @RequestBody Json.Parse() routine, errors out when running into null types for a Json value.

Example:
{"username":"John","username":"Cindy","username":null,"username":""}

The Google Firebase response object can return objects that include 'null' for the value type side.  The 'null' values are not wrapped in quotes.  This causes a crash in the @RequestBody Json.Parse() iteration.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case the request body annotation merely get the request body and tries to map it to the requested type. You should configure your JSON library to handle null values as you would expect.
