### ISSUE TITLE
Make `MvcResultAssert.getResponse()` public

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-framework#32643]
`MockMvc` allows returning the response that one defined expectations on as a subsequent operation, which allows writing assertions like this:

```java
return mvc.perform(get("/").accept(…))
  .andExpect(status().isOk())
  .andReturn().getResponse();
```

I would appreciate it if we could return the response of an operation from a `MvcResultAssert`, too.

**Comment by snicoll** [comment]
Shouldn’t you use `satisfies` for this?

**Comment by odrotbohm** [comment]
I need to return the result from a method.

**Comment by snicoll** [comment]
Ok. An assert object is not meant to expose anything. You can assign the result of perform and get the response from there. Would that work?

**Comment by odrotbohm** [comment]
Yes, that works and is what I do as a workaround. I assume that other trying to migrate their existing assertion pipelines will run into this as well. 

Furthermore, `getResponse()` is already present, but protected. So I wonder why it should be fine to call that method on the object returned from `….andExpect(…)` but not the assertion object.

**Comment by snicoll** [comment]
It doesn’t matter that the method already exists. As I’ve tried to explain, we’re following what AssertJ does and they don’t expose their internal state with a getter like that (and they have them protected just because the hierarchy needs access to it). 

Mixing AssetJ with returning an element of the result and not willing to assign the result doesn’t look like a common case to me. But perhaps I am missing something.

**Comment by odrotbohm** [comment]
> We’re following what AssertJ does and they don’t expose their internal state with a getter like that (and they have them protected just because the hierarchy needs access to it).

Well, we're *extending* AssertJ. Which naturally means *adding stuff* to the thing that's extended, isn't it? So, AsserJ not doing something we do is by definition, isn't it? Furthermore, that internal state already *is* exposed on `MvcResultAssert`. There's nothing to be hidden, really. What do we gain from asking developers to write boilerplate code in this particular case?

> Mixing AssertJ with returning an element of the result and not willing to assign the result doesn’t look like a common case to me. 

Not willing sounds stubborn. I just think it would be nice to return the result of such an operation immediately, without having to capture some state initially solely to obtain the thing I want to return from it later. It's already possible on `MockMvc`: define the request, chain expectations, return an aspect of the result. I don't see how anything in AssertJ is deeming that problematic non-idiomatic.

Using the response of a request is pretty common, as soon as you move beyond one-line examples and have test methods that execute slightly more complex testing flows that span multiple requests. Find [an example](https://github.com/odrotbohm/spring-restbucks/blob/854013ff32f76ca26e017678ffbb7bdd6478e589/server/src/test/java/org/springsource/restbucks/payment/web/PaymentProcessIntegrationTest.java#L93-L104) of that in Spring RESTBucks.

**Comment by snicoll** [comment]
> Well, we're extending AssertJ. Which naturally means adding stuff to the thing that's extended, isn't it?

Yes, just like any custom `Assert`, including the ones provided by AssertJ itself. The point I was trying to make is that we want the user experience to be natural and consistent with other `Assert` classes. And an Assert either returns `SELF` or a more dedicated assert instance based on an extracting function of some kind. It usually doesn't have a termination method that returns `actual` or some state of `actual`.

> Furthermore, that internal state already is exposed on AssertableMvcResult

Again, that doesn't matter. And to be clear, I am not denying the use case here, just that it has to be fixed by making a method public, because it "is already present". I've already noticed a use case with async request where you want to first make a request and then get the response to trigger another `perform`. Your sample takes that to the next level with chain of processing that each take the previous response and contribute the one used by the next. I wonder if we shouldn't make that use case first class by providing a dedicated method. We'd need to hack a bit more to see how we'd name that though.

WDYT?

**Comment by odrotbohm** [comment]
In the end, I, personally, am more concerned about our users' ability to write boilerplate-free code. IMO, what is or is not deemed idiomatic should be of lower priority. Especially, as in this case, the absence of a certain style of method is equated with being non-idiomatic, which, I think, is not the same thing. But I've already argued that in a multitude of ways.

Find the translation of the Hamcrest-based definition of matchers to the AssertJ ones in Spring RESTBucks [here](https://github.com/odrotbohm/spring-restbucks/commit/6e547dbaab11118fe53f7ef4929086e1a33dedff#diff-613516c62ae1f72693ab21c3039c31af860e910e7426ba9e33b513ce6131d665). Note how, on [multiple](https://github.com/odrotbohm/spring-restbucks/commit/6e547dbaab11118fe53f7ef4929086e1a33dedff#diff-613516c62ae1f72693ab21c3039c31af860e910e7426ba9e33b513ce6131d665L36-R40) [occasions](https://github.com/odrotbohm/spring-restbucks/commit/6e547dbaab11118fe53f7ef4929086e1a33dedff#diff-0e0fc064bfc25ef5eb1adf3824138f2804efdc40c5069f957a9c8de13a2a01e6L128-R134) (more [here](https://github.com/odrotbohm/spring-restbucks/commit/6e547dbaab11118fe53f7ef4929086e1a33dedff#diff-0e0fc064bfc25ef5eb1adf3824138f2804efdc40c5069f957a9c8de13a2a01e6L128-R134) and [here](https://github.com/odrotbohm/spring-restbucks/commit/6e547dbaab11118fe53f7ef4929086e1a33dedff#diff-0e0fc064bfc25ef5eb1adf3824138f2804efdc40c5069f957a9c8de13a2a01e6L128-R134)), this causes what could have been expressed in a single, fluent statement now has to be broken up into multiple expressions.
