### ISSUE TITLE
HttpComponentsClientHttpRequestFactory does not set Content-Length: 0

### ISSUE THREAD

**Issue by tholinka** [spring-projects/spring-framework#32678]
**Affects:** 6.1.6

I have an API that requires sending a `Content-Length: 0` when the body is null/empty.

When we previously upgraded to Spring Boot 3 / Spring 6, we changed our `RestTemplate` to use `new BufferingClientHttpRequestFactory(new HttpComponentsClientHttpRequestFactory())` as the request factory in order to ensure that a `Content-Length` was set.

This worked on 6.1.5, but on upgrading to 6.1.6 we are no longer sending the `Content-Length` header.

---

Stepping through the code with a debugger, this changed in 019ce4418cd57391ed61c7fb6812bbd527db35e6 / gh-32612. https://github.com/spring-projects/spring-framework/blob/019ce4418cd57391ed61c7fb6812bbd527db35e6/spring-web/src/main/java/org/springframework/http/client/BufferingClientHttpRequestWrapper.java#L58

I can force the old behavior if I do the following, which leads me to believe it is that commit (effectively, I'm trying to just skip over the new `if`):
- Set a breakpoint at line 58 and at line 59 of `BufferingClientHttpRequestWrapper` 
- (on line 58 breakpoint) in the evaluation expression window run `bufferedOutput = new byte[1];`
- Continue to line 59 breakpoint
- (on line 59 breakpoint) in the evaluation expression window run `bufferedOutput = new byte[0];`

Doing this then causes the `Content-Length: 0` header to be sent as expected.

---

I tried also manually setting `Content-Length: 0` as a header, but `HttpComponentsClientHttpRequest` does not allow that, as is explicitly ignores `Content-Length` as a header. https://github.com/spring-projects/spring-framework/blob/019ce4418cd57391ed61c7fb6812bbd527db35e6/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L110

---

This still works as expected (`Content-Length: 0` is set) when using `SimpleClientHttpRequestFactory`, so for now I can work around this by using `new BufferingClientHttpRequestFactory(new SimpleClientHttpRequestFactory())` instead. However, I would prefer to use `HttpComponentsClientHttpRequestFactory` instead of `Simple` if possible.

**Comment by tholinka** [comment]
Looking into it some more, in `org.apache.hc.core5.http.protocol.RequestContent.process()` there is a null check for if entity is null. With the previous version, this is empty, but with the change in the `BufferingClientHttpRequestWrapper` it is now null.

This is because of this check: https://github.com/spring-projects/spring-framework/blob/019ce4418cd57391ed61c7fb6812bbd527db35e6/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L91.

In 6.1.5, this check would be true when using `BufferingClientHttpRequestFactory` (body would be empty, but not null). However, in 6.1.6 because of https://github.com/spring-projects/spring-framework/commit/019ce4418cd57391ed61c7fb6812bbd527db35e6 it is now null, so the entity is null.

**Comment by tholinka** [comment]
Sadly this isn't changeable from my team. We're trying to call an external API that is very resistant to change, and they've always required sending `Content-Length` as a header.

e.g. this curl works:
```
$ curl --location --request POST 'https://example.com/endpoint' --header 'Authorization: TOKEN' --header 'Content-Length: 0'
# good response
```
and so does this one:
```
$ curl --location --request POST 'https://example.com/endpoint' --header 'Authorization: TOKEN' --data-raw ''
# good response
```
but this one does not:
```
$ curl --location --request POST 'https://example.com/endpoint' --header 'Authorization: TOKEN'
# replies with "Content-Length is missing"
```

**Comment by tholinka** [comment]
We're trying to call in our code with the following currently
```java
HttpEntity<Object> entity = new HttpEntity<>("", headers);
ResponseEntity<Response> response = restTemplate.exchange(url), HttpMethod.POST, entity, Response.class);
```
I could understand not sending `Content-Length: 0` if the body is null, but we're explicitly trying to send an empty body, because we do want the `Content-Length` header.

**Comment by poutsma** [comment]
This seems related to, or perhaps even in contradiction of, #32650.

**Comment by poutsma** [comment]
I think this is mainly due to `HttpComponentsClientHttpRequestFactory` (i.e. Apache HttpClient) which does not send a `Content-Length: 0` by default. Switching to the JDK `HttpClient` by using `new BufferingClientHttpRequestFactory(new JdkClientHttpRequestFactory())` did show a `Content-Length: 0` header for me.

Let us know if switching the client request factory works for you, @tholinka.

**Comment by tholinka** [comment]
I don't think this is contradicted by #32650, for instance, in https://github.com/spring-projects/spring-framework/issues/32650#issuecomment-2061190826 @nhmarujo lays out almost exactly the same as what I would expect.

in #32650, the conclusion seems (and it seems to me that it works this way with `SimpleClientHttpRequestFactory` and `JdkClientHttpRequestFactory`):
- does NOT set header:
  - null
- DOES set header:
  - empty (but not null, e.g. `""`)
  - explicitly set
  - non-empty (body has an actual value)

Whereas currently with `BufferingClientHttpRequestFactory` + `HttpComponentsClientHttpRequestFactory`, this is what currently happens from my testing:
- does NOT set header:
  - null
  - empty (but not null, e.g. `""`)
  - explicitly set (this value is completely ignored, because httpclient5 throws when `Content-Length` is set, unless the override config value is set)
- DOES set header:
  - non-empty (body has an actual value)

**Comment by jbretsch** [comment]
I, too, suffer from this regression because a legacy system which is called by a service I’m helping to maintain requires `Content-Length: 0` for empty POST requests.

I think, for empty POST/PUT/PATCH requests, the Content-Length header _should_ be set to 0. This is supported by the [HTTP RFC#9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length). It says:

> A user agent SHOULD send Content-Length in a request when the method defines a meaning for enclosed content and it is not sending Transfer-Encoding. For example, a user agent normally sends Content-Length in a POST request even when the value is 0 (indicating empty content). A user agent SHOULD NOT send a Content-Length header field when the request message does not contain content and the method semantics do not anticipate such data.

Note that, „when the method defines a meaning for enclosed content“ in the first sentence refers to e.g. POST/PUT/PATCH requests. And „the method semantics do not anticipate such data“ in the last sentence refers to e.g. GET requests.

**Comment by nhmarujo** [comment]
@jbretsch note however that what you just posted speaks in favour of https://github.com/spring-projects/spring-framework/issues/32650 , https://github.com/spring-projects/spring-framework/commit/b3a45670f9b8b193a34c022b63cc2b587feae6ef
> A user agent SHOULD NOT send a Content-Length header field when the request message does not contain content and the method semantics do not anticipate such data.

**Comment by jbretsch** [comment]
> @jbretsch note however that what you just posted speaks in favour of #32650 , [b3a4567](https://github.com/spring-projects/spring-framework/commit/b3a45670f9b8b193a34c022b63cc2b587feae6ef)
> 
> > A user agent SHOULD NOT send a Content-Length header field when the request message does not contain content and the method semantics do not anticipate such data.

No, it does not. That is because with "the method semantics do not anticipate such data" they mean e.g. GET requests which normally have no body. POST/PUT/PATCH requests fall under "when the method defines a meaning for enclosed content". When the RFC speaks about "method", it does not speak about different resources and their specific semantics given by the implementing service. It speaks about HTTP methods, i.e. HTTP verbs.

**Comment by nhmarujo** [comment]
So say I have 2 POSTS with no content, one with Content-Type set and the other not. Are they the same to you?

**Comment by jbretsch** [comment]
> So say I have 2 POSTS with no content, but one with `Content-Type` set and the other not. Are they the same to you?

I see nothing in [section 8.3 Content-Type](https://www.rfc-editor.org/rfc/rfc9110.html#name-content-type) that suggests that those two requests should have different semantics. I would also still maintain the claim that from the perspective of the HTTP RFC, there is no difference between a POST request with an empty body and POST request with an absent body. Do you see where the HTTP RFC makes a distinction between empty and absent body?

**Comment by nhmarujo** [comment]
I think this comment on stackoverflow does shed some light with some RFC quotes https://stackoverflow.com/a/78182957 Let me know your thoughts 🙂

**Comment by jbretsch** [comment]
> I think this comment on stackoverflow does shed some light with some RFC quotes https://stackoverflow.com/a/78182957 Let me know your thoughts 🙂

The argument in <https://stackoverflow.com/a/78182957> assumes that a client is free to choose whether to include the `Content-Length` header or not in POST requests. One can argue that this is indeed true because only SHOULD instead of MUST is used in "A user agent SHOULD send Content-Length in a request when the method defines a meaning for enclosed content and it is not sending Transfer-Encoding." even if one believes that _all_ POST requests are meant with "the method defines a meaning for enclosed content".

I'm not convinced that it would be a good idea to actually implement a POST resource which behaves differently for absent and empty requests. But I'm fine with settling on: The HTTP RFC allows that.

The question remains how Spring should behave. I agree with <https://github.com/spring-projects/spring-framework/issues/32678#issuecomment-2067090473> which expects a `Content-Length: 0` header being present for:
```java
HttpEntity<Object> entity = new HttpEntity<>("", headers);
ResponseEntity<Response> response = restTemplate.exchange(url, HttpMethod.POST, entity, Response.class);
```

I think, it would be pragmatic to restore this behavior while simultaneously allowing people to differentiate between absent and empty request bodies by having Spring exclude the `Content-Length` header for:
```java
HttpEntity<Object> entity = new HttpEntity<>(null, headers);
ResponseEntity<Response> response = restTemplate.exchange(url, HttpMethod.POST, entity, Response.class);
```

**Comment by nhmarujo** [comment]
Yes, that is the suggestion I was trying to make - to avoid the second one from having the `Content-Length`.

**Comment by bclozel** [comment]
I had another look and tested the following code snippet with various combinations of request factories and checking the "Content-Length" header value received by the server:

```java
ResponseEntity<String> response = restClient.post().uri("http://localhost:8080/test").retrieve().toEntity(String.class);
```

## Spring Framework 6.1.5

We can see two inconsistencies, one with `HttpComponentsClientHttpRequestFactory` and another one with `SimpleClientHttpRequestFactory`.

| Client Factory                                                             | Content-Length value |
|----------------------------------------------------------------------------|----------------------|
| HttpComponentsClientHttpRequestFactory                                     | null                 |
| BufferingClientHttpRequestFactory + HttpComponentsClientHttpRequestFactory | 0                    |
| JdkClientHttpRequestFactory                                                | 0                    |
| BufferingClientHttpRequestFactory + JdkClientHttpRequestFactory            | 0                    |
| JettyClientHttpRequestFactory                                              | 0                    |
| BufferingClientHttpRequestFactory + JettyClientHttpRequestFactory          | 0                    |
| SimpleClientHttpRequestFactory                                             | null                 |
| BufferingClientHttpRequestFactory + SimpleClientHttpRequestFactory         | 0                    |

## Spring Framework 6.1.6

The `HttpComponentsClientHttpRequestFactory` inconsistency is fixed, but the `SimpleClientHttpRequestFactory` one remains.

| Client Factory                                                             | Content-Length value |
|----------------------------------------------------------------------------|----------------------|
| HttpComponentsClientHttpRequestFactory                                     | null                 |
| BufferingClientHttpRequestFactory + HttpComponentsClientHttpRequestFactory | null                    |
| JdkClientHttpRequestFactory                                                | 0                    |
| BufferingClientHttpRequestFactory + JdkClientHttpRequestFactory            | 0                    |
| JettyClientHttpRequestFactory                                              | 0                    |
| BufferingClientHttpRequestFactory + JettyClientHttpRequestFactory          | 0                    |
| SimpleClientHttpRequestFactory                                             | null                 |
| BufferingClientHttpRequestFactory + SimpleClientHttpRequestFactory         | 0                    |

I have tested a patch in `AbstractBufferingClientHttpRequest` that fixes the last one.

## Empty vs missing request body

I think the use case for `BufferingClientHttpRequestFactory` is to buffer the request and response body contents to allow for repeated writes. It should be as much transparent as possible for any other use case. Here, it seems that some of you are using this to work around a server behavior with missing/empty request bodies and the "Content-Length" header.

Several contracts in Spring Framework do not make that difference, for example the `ClientHttpRequestInterceptor` should always receive a non-null `byte[] body` when intercepting requests. My opinion is that we should not interfere with the libraries here, and instead the `BufferingClientHttpRequestFactory` should be as transparent as possible. If a particular behavior is required, then this should guide the choice of client library.

`org.springframework.http.client.HttpComponentsClientHttpRequest.addHeaders` will not write Content-Length headers to the actual request and will delegate that to the library itself. Maybe we should relax that in the case of the "0" value? This would allow a much more robust mechanism for applications with a custom interceptor:

```java
class ContentLengthInterceptor implements ClientHttpRequestInterceptor {

	@Override
	public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {
		if (body.length == 0) {
			request.getHeaders().setContentLength(0);
		}
		return execution.execute(request, body);
	}
}
```

**Comment by bclozel** [comment]
We have discussed this as a team and we think that the issue might not be in the `BufferingClientHttpRequestFactory`, but a bug in our implementation of the HttpComponents client. [In the `HttpComponentsClientHttpRequest`](https://github.com/spring-projects/spring-framework/blob/e0ac000415aa95b06767f472e902429ccb76ab61/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L91), we should probably set a [`NullEntity`](https://hc.apache.org/httpcomponents-core-5.2.x/current/httpcore5/apidocs/org/apache/hc/core5/http/io/entity/NullEntity.html) instead of skipping it entirely. This should result in setting the "Content-Length" header and align the behavior with other clients.

FYI we just reopened #32650 and we might revert the change there.
