### ISSUE TITLE
 12/5000 How do I set the URL to ignore case

### ISSUE THREAD

**Issue by LoveC521** [spring-projects/spring-framework#32684]
![image](https://github.com/spring-projects/spring-framework/assets/115055658/5edc185a-4278-4931-96ac-d2f25c77a2d1)
It didn't work

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
