### ISSUE TITLE
non-blocking call delayed accasionally.

### ISSUE THREAD

**Issue by kxying-kk** [spring-projects/spring-framework#32779]
we have two microservices. ms1 calls ms2. ms2 calls 3rd party service.
we use non-blocking (webclient.subscribe()) in ms1 when calling ms2 because the front end does not need to wait for the backend to finish all the process in ms2. however, occasionally we saw the actual call to MS2 did not happen until half an hour later. This is significant delay. we understand that it is asynchronous and expect some reasonable delay in MS2. can anybody explain this behavior? thanks.

we are using springboot 3.0.10

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
