### ISSUE TITLE
Do HttpExchange interfaces support exponential backoff and fallbacks?

### ISSUE THREAD

**Issue by UditMishraMoodys** [spring-projects/spring-framework#33084]
We were using OpenFeign in our project and it worked well. We have exponential retries configured and we also have fallbacks and fallback factories defined.

Recently, we stumbled upon [Spring Cloud OpenFeign doc](https://docs.spring.io/spring-cloud-openfeign/reference/) page which says that this is now feature complete and suggest migrating over to [Spring Interface Clients](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-http-interface) instead.

I read the documentation of Spring Interface Clients but it does not clearly explain about -

1. Fallbacks
2. How can we achieve exponential retries

**Comment by bclozel** [comment]
I have discussed this with @OlgaMaciaszek and she will provide some feedback here. We'll then decide what to do about this issue.

**Comment by OlgaMaciaszek** [comment]
Will get back on this here today or tomorrow.

**Comment by OlgaMaciaszek** [comment]
Thanks @UditMishraMoodys. In order to make it work OOTB, additional integration with Spring Cloud CircuitBreaker will be needed that has not been implemented yet. This is something that will need to be addressed in Spring Cloud, since it'll require access to SC CircuitBreaker dependencies. I have created an issue for it in Spring Cloud Circuit Breaker: https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/186.

**Comment by bclozel** [comment]
Thanks Olga for the analysis. I'm closing this issue for now as superseded by the Circuit Breaker one. We can reopen this issue if something needs to be done in Framework to support this case.

**Comment by agebhar1** [comment]
Hi @UditMishraMoodys, you can use Spring Retry w/ HttpExchange see [HttpExchangeTest.kt](https://github.com/agebhar1/snippets/blob/main/spring-boot/src/test/kotlin/io/github/agebhar1/snippets/HttpExchangeTest.kt) if the client is a Spring Bean.
