### ISSUE TITLE
Questions about Spring Circular Dependency.

### ISSUE THREAD

**Issue by TengWangCoder** [spring-projects/spring-framework#33209]
1. Why is Spring's circular dependency intermittent?
2. Why doesn't Spring reorder the reading of Jar files based on their FileName (I noticed that local loading does reorder them)?

Supplement: I understand that the intermittent nature might be related to the loading order of Beans. Spring reads beans from jar files, and Maven does not guarantee the order of files in the jar. Could this be causing Spring to read them in an unordered manner?

**Comment by TengWangCoder** [comment]
I'm not sure if Maven does not guarantee the order of files in the jar; this is just my guess.

**Comment by simonbasle** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
