### ISSUE TITLE
Why is TransactionManager an empty interface

### ISSUE THREAD

**Issue by luohongtu** [spring-projects/spring-framework#33254]
1. Why is TransactionManager an empty interface.
2. Why hasn't the PlatformTransactionManager open transaction abstraction method.

**Comment by luohongtu** [comment]
Can you share the design idea?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case, `TransactionManager` is a marker interface. You can research this topic independently.

**Comment by luohongtu** [comment]
Thank you very much.
