### ISSUE TITLE
Will there be a recursion error? ReflectionUtils.invokeJdbcMethod()

### ISSUE THREAD

**Issue by Asamiyaa** [spring-projects/spring-framework#33283]
org.springframework.util.ReflectionUtils.invokeJdbcMethod(Method method, @Nullable Object target)

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In addition, please note that there is no `invokeJdbcMethod(...)` method in  
`org.springframework.util.ReflectionUtils`.
