### ISSUE TITLE
Offer a way for MockitoTestExecutionListener to enable strict stubbing

### ISSUE THREAD

**Issue by jschmied** [spring-projects/spring-framework#33318]
Running tests with `SpringRunner` does not report unused stubs like `MockitoJUnitRunner` does.

In `MockitoTestExecutionListener.initMocks` it should use

```java
Mockito.mockitoSession()
  .initMocks(this)
  .strictness(Strictness.STRICT_STUBS)
  .startMocking();
```

to enable strict mocking.

**Comment by simonbasle** [comment]
I think we can use 6.2 as an opportunity to change Spring-Framework's newly introduced `@MockitoBean` default to the strict style, with an additional class-level annotation that can be used to switch to a lenient style.

I was not able to find a way to account for the `@MockSettings` annotation since it does `@ExtendWith(MockitoExtension.class)`, but the usage pattern would be pretty similar:

```java
@SpringJUnitConfig(Config.class)
@MockitoBeanSettings(Strictness.LENIENT)
public class MyIntegrationTests {
	@Test
	public void unusedStubbingNotReported() {
		var list = Mockito.mock(List.class);
		Mockito.when(list.get(Mockito.anyInt())).thenReturn(new Object());
	}
}
```

**Comment by sbrannen** [comment]
> I was not able to find a way to account for the `@MockitoSettings` annotation since it is meta-annotated with `@ExtendWith(MockitoExtension.class)`, 

It's indeed unfortunate that `@MockitoSettings` auto-registers the `MockitoExtension`, but then again... `@MockitoSettings` resides in the `mockito-junit-jupiter` module. So it's somewhat expected.

> but the usage pattern would be pretty similar:

Yes, your proposal looks good. 👍

**Comment by simonbasle** [comment]
Unfortunately, we had to backtrack on this in [6.2.0-RC2](https://github.com/spring-projects/spring-framework/issues/33692) due to various blocking issues with `MockitoSession` and `MockitoExtension` integration in a `SpringExtension`-enabled test suite. We'll reach out to the Mockito team to explore possible improvements in the Spring Framework 7 timeframe.

**Comment by sbrannen** [comment]
> Is there an issue that tracks the re-introduction of strict stubbing as the default behavior?

There wasn't one, but there is now. 😉 

- #34419
