### ISSUE TITLE
@AliasFor 'schemaClass' not meta-present in @Schema

### ISSUE THREAD

**Issue by bmt810818** [spring-projects/spring-framework#33335]
BACKGROUND:
I am creating a shared Swagger documentation template to be used everywhere, and I am trying to configure an annotation like this:
@DefaultDocs(value = "summary content of API", schemaClass = nameClass.class)

Here: https://github.com/bmt810818/issue/blob/main/%40AliasFor.md

I have read most articles about @AliasFor, but I haven't found a similar case.
"Any answer is helpful to me. Thank you for viewing this post"

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

Having said that, the error message explains the issue.

See the `Explicit alias for attribute in meta-annotation` description in the Javadoc for `@AliasFor`.

See also the [Spring Annotation Programming Model](https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model) documentation.
