### ISSUE TITLE
cannot call setTransactionAttributeSources

### ISSUE THREAD

**Issue by HelloDhero** [spring-projects/spring-framework#33576]
I want to create multiple `TransactionAttributeSources`. What should I do? 
I found that the use of  `CompositeTranscriptAttributeSource` is not supported in `ProxyTransactionManagementConfiguration`

**Comment by simonbasle** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
