### ISSUE TITLE
Proxy bean can't get the property

### ISSUE THREAD

**Issue by huabro** [spring-projects/spring-framework#33583]
I defined a bean configuration class:

```java
@Configuration
public class CoreAppBeanConfiguration {
    @Bean
    @Scope(value = WebApplicationContext.SCOPE_REQUEST, proxyMode = ScopedProxyMode.TARGET_CLASS)
    public CoreAppContext getCoreAppContext() {
        CoreAppContext context = new CoreAppContext();
        return context;
    }
}
```

Then I defined a filter to initialize the `CoreAppContext`:

```java
@Provider
@Component
public class TestHandler implements ContainerRequestFilter, ContainerResponseFilter {
    @Autowired
    private CoreAppContext coreAppContext;

    @Override
    public void filter(ContainerRequestContext containerRequestContext) throws IOException {
        coreAppContext.id="1";
        coreAppContext.name="test";
        RequestContextHolder.currentRequestAttributes().setAttribute("coreAppContext", coreAppContext, RequestAttributes.SCOPE_REQUEST);
    }
}
```

Finally I defined a resource class to get the `CoreAppContext` value:

```java
@Path("/test")
public class TestResource {

    @GET
    @Path("/get")
    public String get() {
        CoreAppContext coreAppContext= (CoreAppContext) RequestContextHolder.getRequestAttributes().getAttribute("coreAppContext", 0);
        String result = coreAppContext.getIdName();
        return result;
    }
}
```

As you can see in the below picture, I got the null value.
![proxy_issue1](https://github.com/user-attachments/assets/6523adee-14a3-4ac4-90b1-1fa29c38e047)
![proxy_issue2](https://github.com/user-attachments/assets/be6f37fe-77b0-46a6-a9cf-ac299017d781)
![proxy_issue3](https://github.com/user-attachments/assets/29603f17-624f-4690-8042-07b9147f4271)

**Comment by huabro** [comment]
Could you please help check if it is a bug or not?

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
