### ISSUE TITLE
Make `DynamicPropertyRegistrarBeanInitializer` public

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#33593]
## Overview

**Affects:** 6.2

Following up on [this comment](https://github.com/spring-projects/spring-framework/issues/33501#issuecomment-2348538458), we have [prototyped](https://github.com/wilkinsona/spring-boot/tree/gh-41996) a change to Spring Boot that is a step towards replacing its support for injecting a `DynamicPropertyRegistry` with support for `DynamicPropertyRegistrar` beans instead.

As explained in the comment in #33501, additional support for `DynamicPropertyRegistrar` is needed for [dynamic property registration when using Testcontainers at development time](https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.testcontainers.at-development-time.dynamic-properties). In tests, it isn't needed as the test context framework already enables the support through its context customizer.

The prototype of the changes to Boot currently uses reflection when [defining a `DynamicPropertyRegistrarBeanInitializer` bean](https://github.com/wilkinsona/spring-boot/blob/b53a83acce5541c50329c1f44b2e03e9edf60b4f/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/properties/TestcontainersPropertySourceAutoConfiguration.java#L61-L71) as the initializer is package-private. This has helped to verify the approach but isn't something that we'd want to ship. 

Can Framework 6.2 please provide an SPI for enabling `DynamicPropertyRegistrar` support outside of the test context framework, or perhaps just make `DynamicPropertyRegistrarBeanInitializer` public so that we don't need to use reflection?

## Related Issues

- #33501

**Comment by sbrannen** [comment]
Thanks for raising the issue, @wilkinsona.

> Following up on [this comment](https://github.com/spring-projects/spring-framework/issues/33501#issuecomment-2348538458), 

I apologize: I somehow missed that comment.

> we have [prototyped](https://github.com/wilkinsona/spring-boot/tree/gh-41996?rgh-link-date=2024-09-25T13%3A17%3A04Z) a change to Spring Boot that is a step towards replacing its support for injecting a `DynamicPropertyRegistry` with support for `DynamicPropertyRegistrar` beans instead.

That would of course be great if Spring Boot can benefit from the new `DynamicPropertyRegistrar` support.

> Can Framework 6.2 please provide an SPI for enabling `DynamicPropertyRegistrar` support outside of the test context framework, or perhaps just make `DynamicPropertyRegistrarBeanInitializer` public so that we don't need to use reflection?

In Spring Framework, we don't have any support for "dynamic properties" other than in the `spring-test` module. In other words, dynamic properties are very test-centric from a Framework perspective. In light of that, we don't have any plans to enable `DynamicPropertyRegistrar` support outside of the test context framework.

However, I think it should be fine to make `DynamicPropertyRegistrarBeanInitializer` public.

Shall I go ahead and make that change this week so that you can try it out with 6.2 snapshots?

**Comment by sbrannen** [comment]
`DynamicPropertyRegistrarBeanInitializer` is now `public` on `main`.

Feel free to try it out in upcoming 6.2 snapshots.

**Comment by wilkinsona** [comment]
I've updated the [prototype](https://github.com/wilkinsona/spring-boot/tree/gh-41996) and it looks good to me. Thanks!

**Comment by sbrannen** [comment]
Great! Glad to hear that.
