### ISSUE TITLE
MultiValueMap<String, String> couldn't get the parameters.

### ISSUE THREAD

**Issue by charlesChou321** [spring-projects/spring-framework#33695]
In my Spring Boot project, I want to transmit data through application/x-www-form-urlencoded. I used @RequestParam(defaultValue = "token") MultiValueMap<String, String> values to receive parameters, but I couldn't get the parameters. Debugging showed that the size was 0.
![123](https://github.com/user-attachments/assets/5f6f207e-6f5c-4799-afbd-810c71befba6)
![2](https://github.com/user-attachments/assets/36170f94-875a-4f7d-bbdf-9f5987c4ab58)
![3](https://github.com/user-attachments/assets/c802e314-02e3-4fef-8e86-e0e6a01e3374)

**Comment by varunu28** [comment]
@charlesChou321 Shouldn't the request be taking `RequestBody` instead of `RequestParam` if you are setting the params in body through Postman?

**Comment by varunu28** [comment]
I was able to get the params successfully but I had to set it in the url request param. Here is what my request looks like(I have a GET request instead of POST)
```
curl -G "http://localhost:8080/" --data-urlencode "param1=value1" --data-urlencode "param2=value2"
```

**Comment by livk-cloud** [comment]
Perhaps you can remove **@RequestParam(defaultValue = "token")** and simply use **MultiValueMap<String, String>** to receive the parameters.

**Comment by livk-cloud** [comment]
You should debug this class: **org.springframework.web.method.annotation.RequestParamMapMethodArgumentResolver**

**Comment by sdeleuze** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
