### ISSUE TITLE
How i can send/receive ping/pong for detect disconnection with spring webflux websockets ?

### ISSUE THREAD

**Issue by rullyalves** [spring-projects/spring-framework#33759]
I'm using spring webflux and I would like to know how I can detect pings/pongs and if the library has any configuration for this

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
