### ISSUE TITLE
RestClient exchange methods are not nullable 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-framework#33779]
The retrieve workflow, a shortcut for `exchange`, can end with null, but exchange itself is not declared as `Nullable`. There is no reason why an response cannot be exchanged for a null value.

**Comment by Donghh0221** [comment]
@rstoyanchev , Hi, I have some question abount this patch.

Currently, in a Kotlin environment, whenever we use the exchange method of RestClient, we have to perform a null check on the result due to the addition of @Nullable to its method signature.

Could you please share whether it is absolutely necessary to mark this method as @Nullable? Or, if there are alternative approaches to reduce the null-checking overhead in Kotlin, we would be grateful for your guidance. In most HTTP call scenarios, we expect the result to be non-null, and our team is experiencing an increase in unnecessary boilerplate code due to this change. We would also like to know if there are any plans or solutions being considered for future improvements.

In my opinion, it might be a good idea to add an additional non-nullable method in `RestClientExtensions.kt.`

**Comment by sdeleuze** [comment]
@Donghh0221 I introduced a `requiredExchange` extension via #34692.

**Comment by Donghh0221** [comment]
@sdeleuze Thanks! It will helpful for kotlin users!

**Comment by sdeleuze** [comment]
Notice we changed it to an `echangeForRequiredValue` method useful for both Java and Kotlin developers.
