### ISSUE TITLE
Why does updating the same data affect the number of rows by 1

### ISSUE THREAD

**Issue by tss3023coding** [spring-projects/spring-framework#33838]
When I update the same data, the number of affected rows is 1. The following is the code:
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/6252ed0a-e836-4553-a787-caff97caf79f">
When I logged in through MySQL client and executed the same update statement, the number of affected lines was 0, as shown in the following figure:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/82a67dc1-09fe-4f09-ae04-cb425fc2138b">
Has anyone encountered the same problem, unsure if it is a bug.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
