### ISSUE TITLE
NoResourceFoundException: No static resource 

### ISSUE THREAD

**Issue by githuailoveyou** [spring-projects/spring-framework#33880]
curl --location --request GET '10.65.10.160:8070/job/?Action=GetJobList&AccountId=180000000'
ERROR Tips:
2024-11-13 20:23:50.164 [TID: N/A] DEBUG 24733 --- [http-nio-8070-exec-5] o.s.w.s.DispatcherServlet               :120 : {} "ERROR" dispatch for GET "/error?Action=GetJobList&AccountId=180000000", parameters={Action:[GetJobList], AccountId:[180000000]}
![image](https://github.com/user-attachments/assets/2f83762f-12b8-4f2f-9409-fd10e69de2b2)

curl --location --request GET '10.65.10.160:8070/job?Action=GetJobList&AccountId=180000000'
Tips:
You can get the results

A problem occurred during the upgrade of spring 5.2.4 -> 6.1.4

spring-boot 2.2.5 -> 3.2.3 
![image](https://github.com/user-attachments/assets/ba52dfff-92d3-459f-8391-bf875d4c5781)
![image](https://github.com/user-attachments/assets/3541857b-fde4-447e-80a6-b63675078409)
help me brother

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
