### ISSUE TITLE
spring-jms decryp amqp packets

### ISSUE THREAD

**Issue by himachida** [spring-projects/spring-framework#34035]
I'm using spring-cloud-azure-sample-servicebus-jms-queue, that uses spring-jms.

The sample is here:
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue

Is there any way to see decrypted amqp packets?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
