### ISSUE TITLE
Support escaping prefix and separator in property placeholders [SPR-4953]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#9628]
**[Chris Lee](https://jira.spring.io/secure/ViewProfile.jspa?name=chrislee)** opened **[SPR-4953](https://jira.spring.io/browse/SPR-4953?redirect=false)** and commented

There is presently no way to inject a placeholder expression (`${...}`) that won't be picked up by `PropertyPlaceholderConfigurer`. Ideally we should be able to inject a string that contains `${...}` for later use in its target bean without involvement from `PropertyPlaceholderConfigurer`.

Perhaps a simple escape mechanism using the conventional backslash, such as `"The current value is \\${...}"` would suffice.

---

**Affects:** 2.5.4, 2.5.5

11 votes, 5 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by mar1ged** [comment]
I really would welcome a "fix" for this. 

In my app I externalized config into application.yml, this configuration contains `${var}` entries which I later on fill in using `PropertyPlaceholderHelper` in my own code.
When I have `${var}` in my application.yml the app does not load because the value of `var` will be filled in later and depends on user input.

I worked around this issue by putting `@{var}` into the yaml file and replacing `@` with `$` at runtime. But this is not very elegant because I have to do something like this:

	@Value("${my.app.var}")
	private String var;

	public String getVar() {
		return fixed(var);
	}

	private String fixed(String in) {
		return in.replace('@', '$');
	}

**Comment by sbrannen** [comment]
Interestingly enough, core support for ignoring nested properties appears to have been in place since Spring Framework 3.2 via the `ConfigurablePropertyResolver.setIgnoreUnresolvableNestedPlaceholders(boolean)` flag.

However, `PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(ConfigurableListableBeanFactory)` instantiates a `PropertySourcesPropertyResolver` (which is a subtype of `ConfigurablePropertyResolver`) without providing the option to set any flags in the property resolver.

@jhoeller, what do you think about providing a mechanism for configuring the `PropertySourcesPropertyResolver` used by `PropertySourcesPlaceholderConfigurer`?

**Comment by libinglong** [comment]
it's amazing the issue lasts for more than ten years.

**Comment by unrec** [comment]
Will it be fixed at all?

**Comment by honza-zidek** [comment]
@jhoeller, @rstoyanchev, @sbrannen, @sdeleuze, @bclozel, @poutsma, @snicoll, @izeye - any idea if this may be fixed? :)

**Comment by honza-zidek** [comment]
Any progress? Any comment? :)

**Comment by sbrannen** [comment]
The team currently plans to look into escaping support in the 6.0.x timeline.

**Comment by sebastianhaberey** [comment]
+1 for escaping!

**Comment by honza-zidek** [comment]
Hey team, any progress here?

**Comment by snicoll** [comment]
@honza-zidek did you take the time to look at the PR link right above your comment? If not, you can see we're working on it: https://github.com/spring-projects/spring-framework/pull/30671

**Comment by honza-zidek** [comment]
@snicoll Thanks, I haven't noticed. I am happy that the team reacted to the issues after 15 years - better late than never :)

**Comment by snicoll** [comment]
I realize that you're probably frustrated, but sarcasm such as this isn't helpful.
